Add filesystem layout to installation docs
pulp/pulpcore pull request #1007
Opened 2020-11-05 11:42 UTC by mdellweg

fixes #7750
https://pulp.plan.io/issues/7705

2020-11-05 13:31 UTC, fao89 approved these changes

2020-11-05 13:31 UTC, fao89 commented on docs/installation/instructions.rst
> +=============================== ==========================================================================================================
this is pretty handy!

2020-11-24 19:22 UTC, bmbouter commented on docs/installation/instructions.rst
> +.. _filesystem-layout:
Can we move this out of the installation area. I'm concerned that we're making a doc that's already too long, even longer. What about a new sub-section in [the "Architecture and Deploying" area](https://docs.pulpproject.org/pulpcore/components.html)?

2020-11-24 19:23 UTC, bmbouter commented on docs/installation/instructions.rst
> +`/var/lib/pulp/assets`          Staticly served assets like stylesheets, javascript and html; needed for the browsable api
```suggestion
`/var/lib/pulp/assets`          Statically served assets like stylesheets, javascript and html; needed for the browsable api
```

2020-11-24 19:24 UTC, bmbouter commented on docs/installation/instructions.rst
> +`/etc/pulp/settings.py`         Pulp's configuration file; see :ref:`configuration`
Can we indicate this is optional? It would be good to identify that env vars are another way to configure it perhaps when we link to the other section.

2020-11-24 19:25 UTC, bmbouter requested changes
Requested a few small changes. Overall I think this is really, really great.

2020-11-25 09:11 UTC, mdellweg commented on docs/installation/instructions.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
I don't know. I took the paths and description from the ticket.

2020-11-25 09:18 UTC, mdellweg commented on docs/installation/instructions.rst
> +`/etc/pulp/settings.py`         Pulp's configuration file; see :ref:`configuration`
In the configuration part, we describe the "By Environment Variables" configuration.
So i will add that it's optional.

2020-12-08 19:21 UTC, bmbouter approved these changes
I think this is great. Thank you.

2020-12-08 19:30 UTC, goosemania commented on docs/components.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
@mdellweg, do you have a default installation?
I've only seen `/var/lib/pulp/artifact/` and never `media/`.

2020-12-08 19:36 UTC, goosemania commented on docs/components.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
I see your reply, I've already asked.
And I checked the foreman post there https://github.com/theforeman/puppet-pulpcore#installation-layout

I think we should document pulp typical paths and not what foreman does.
They are also changing it from time to time. I'm not sure if the have `docroot` anymore.

Could we add `/var/lib/pulp/artifact` as an artifact storage?
I believe we upload there as well, but I can test to be sure

2020-12-08 19:47 UTC, bmbouter commented on docs/components.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
Yup my system also doesn't have `/var/lib/pulp/media`. It does have a `/var/lib/pulp/pulpcore-selinux/` though with the compiled selinux policies in it...

2020-12-08 19:49 UTC, goosemania commented on docs/components.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
+1 mine also have `pulpcore-selinux`

I also tested the artifact upload. It is saved in the artifact storage as everything else is, `/var/lib/pulp/artifact/`.

2020-12-09 08:47 UTC, mdellweg commented on docs/components.rst
> +`/var/lib/pulp/media`           Uploaded Artifacts are stored here; they should only be served through the `pulp-content` app
@goosemania Thank you for looking at real evidence. I will check and change the table accordingly.

2020-12-09 12:16 UTC, goosemania approved these changes

2020-12-09 12:17 UTC, merged