Add a new field that holds the value of the public key to SigningService
pulp/pulpcore pull request #1012
Opened 2020-11-06 17:00 UTC by lubosmj

closes #7700

2020-11-06 18:19 UTC, lubosmj commented
In order to utilize this change in pulp_rpm, the following has to be done:

```diff
diff --git a/pulp_rpm/app/tasks/publishing.py b/pulp_rpm/app/tasks/publishing.py
index 86cc91e4..061febc1 100644
--- a/pulp_rpm/app/tasks/publishing.py
+++ b/pulp_rpm/app/tasks/publishing.py
@@ -5,9 +5,11 @@ import shutil
 from tempfile import NamedTemporaryFile
 
 import createrepo_c as cr
+import tempfile
 import libcomps
 
 from django.core.files import File
+from django.core.files.base import ContentFile
 from django.core.files.storage import default_storage as storage
 from django.db.models import Q
 
@@ -527,12 +529,16 @@ def create_repomd_xml(content, publication, checksum_types, extra_repomdrecords,
             file=File(open(sign_results['signature'], 'rb'))
         )
 
-        # publish a public key required for further verification
-        PublishedMetadata.create_from_file(
-            relative_path=os.path.join(repodata_path, os.path.basename(sign_results['key'])),
-            publication=publication,
-            file=File(open(sign_results['key'], 'rb'))
-        )
+        with tempfile.NamedTemporaryFile() as tf:
+            tf.write(signing_service.public_key.encode("utf-8"))
+            tf.flush()
+
+            # publish a public key required for further verification
+            PublishedMetadata.create_from_file(
+                relative_path=os.path.join(repodata_path, os.path.basename("public.key")),
+                publication=publication,
+                file=File(open(tf.name, "rb")),
+            )
     else:
         PublishedMetadata.create_from_file(
             relative_path=os.path.join(repodata_path, os.path.basename(repomd_path)),

```

2020-11-09 09:58 UTC, mdellweg requested changes

2020-11-09 09:58 UTC, mdellweg commented on pulpcore/app/serializers/content.py
> +    public_key = serializers.CharField(
would it be possible, that we save the fingerprint of that key to the database too, and report that in the serializer?

2020-11-09 09:58 UTC, mdellweg commented on pulpcore/app/models/content.py
> +            return_value["key"] = self.public_key
WRT the deprecation policy, i believe we need to be a bit more careful here.
The old interface to the plugin returned a filename in `return_value["key"]`, so we should do the same by writing the value of this db field to such a file. I have no idea, how we can warn about the deprecation when accessing that field other than subclassing the `return_value` dict however. In that case we can make the whole "write to file" process lazy.

The "new" interface could be `return_value["public_key"]`.

2020-11-10 16:13 UTC, bmbouter commented on CHANGES/7700.feature
> +Added a new field used for storing the value of the public key in SigningService.
Can the field name be added here please

2020-11-10 16:15 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I imagined this would be a required field. All SigningServices use PKI which use public keys is what I was thinking.

2020-11-10 16:15 UTC, bmbouter commented on pulpcore/app/models/content.py
> +            An absolute path to an external signing script (or executable).
This should be updated to store the key itself, not a path.

2020-11-10 16:16 UTC, bmbouter commented on pulpcore/app/models/content.py
> +            An absolute path to a public key.
This should be updated to store the key itself, not a path.

2020-11-10 16:24 UTC, bmbouter commented on pulpcore/app/models/content.py
> +        if not self.public_key:
I imagine all new SigningServices created will require users to put in a public key with this change. I don't think this needs to go through the deprecation cycle since plugin writers had a plugin key returned to them before and they still will. The deprecation policy I didn't imagine applied to the "scripts", users upgrading will need to take action at that time to recreate their SigningServices. This is my take at least.

2020-11-10 16:25 UTC, bmbouter commented on pulpcore/app/serializers/content.py
> +    public_key = serializers.CharField(
This would be good, but also we could add this later?

2020-11-10 16:25 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I think this is a migration thing. What about existing signing_services?
IIRC django won't even let you add a required field without providing a default.

2020-11-10 16:27 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
With 3.9 signing servies are immutable so I think we've already gotten to the point where users will need to make them new.

2020-11-10 16:32 UTC, mdellweg commented on pulpcore/app/models/content.py
> +        if not self.public_key:
This is about saving new SigningServices? Yes, they should be up to date. And we should not allow to create deprecated stuff in the database.
I would expect to see this warning whenever existing preexisting ones were used.

2020-11-10 16:35 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
So yes to required. Can we also not default it to anything and provide a more verbose default only for the migration?

2020-11-10 17:09 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
We could provide a migration which sets the value at migration time. It could sidestep the hook by calling https://rsinger86.github.io/django-lifecycle/advanced/#suppressing-hooked-methods in the data migration itself. What do you think about that idea?

2020-11-10 17:13 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I thought django would ask you for a migration default if you don't have it on the model.

2020-11-10 18:09 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I was imaging a migraiton that has 3 parts:

1. Add the field but make it optional
2. Perform the data migration populating the field
3. SQL update to make that field required (now that all existing data also has it). This last part would "match" the model code marking the field as required.

2020-11-12 10:15 UTC, lubosmj commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I do not quite understand what are you trying to achieve with those 3 parts, @bmbouter. How do you want to populate the data from an old SigningService object if there was not any `public_key` present back then? It will contain the same data like before. Do you want to extract the value of the public key by executing a signing script and manually reading the value of `return_value["key"]` within the migration?

2020-11-12 15:26 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
> I do not quite understand what are you trying to achieve with those 3 parts, @bmbouter. How do you want to populate the data from an old SigningService object if there was not any `public_key` present back then? It will contain the same data like before. Do you want to extract the value of the public key by executing a signing script and manually reading the value of `return_value["key"]` within the migration?

That's what I was thinking yes. If the migration fails, I think it should probably put in dummy data and log to the user an error and print the error to stderr as well so it's shown in the foreground too. We can't have the migraitons "fail to apply"

@mdellweg what do you think about ^?

2020-11-13 09:04 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
Agreed, we must make the migration apply cleanly at any cost.
Trying to extract the public key is a convenience we offer the user, but it could fail for various reasons (revoked/expired keys is probably just one of them).
So i think, we should make the failing units unusable somehow to force the user to reinstanciate them. Having dummy data in the key field breaks the promise we give our plugins IMHO.

2020-11-13 15:15 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
@mdellweg agreed. In terms of making the failing units unusable, I was thinking it would play out like:

1. The migration logs them and puts an empty string in the public_key field.
2. Then the SQL alter to make public_key required can be applied without error and the transaction can finish.
3. The code expects the public_key data to be accurate and so in cases where it's just `''` the code will receive a RuntimeError. Or perhaps it could even check if its '' and gracefully refuse. Either way is ok with me.

2020-11-20 19:41 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    public_key = models.TextField(default="")
I don't expect this to have a default. It's a required field so it can't have one.

2020-11-20 19:50 UTC, bmbouter commented on pulpcore/app/models/content.py
> +            return_value["key"] = self.public_key
With [this comment](https://github.com/pulp/pulpcore/pull/1012/files#r523015114) I was thinking we would not be ever getting the public_key from the script anymore.

2020-11-20 19:51 UTC, bmbouter commented on pulpcore/app/models/content.py
> +                    if self.public_key:
Similarly here, I was thinking [with this comment](https://github.com/pulp/pulpcore/pull/1012/files#r523015114) we are always getting the key from the database and not from the signing script ever.

2020-11-20 19:51 UTC, bmbouter commented on pulpcore/app/models/content.py
> +                            "Fingerprints of the provided public key and the verified public "
This should be i8ln with `gettext`.

2020-11-27 15:09 UTC, lubosmj commented
I addressed the requested changes. Please take a look at the PR again, @mdellweg and @bmbouter. I tested the PR on pulp_rpm (with the changes from the comment https://github.com/pulp/pulpcore/pull/1012#issuecomment-723228250 and without them) and everything seems to be working.

2020-12-01 20:27 UTC, bmbouter commented on CHANGES/plugin_api/7700.deprecation
> +key is now directly accessible via the model instance as SigningService.public_key.
```suggestion
key is now expected to be saved in the model instance as `SigningService.public_key`.
```

2020-12-08 16:35 UTC, mdellweg reviewed
I don't have any major concerns with the current state. Just some ideas.
Also the deprecation window has probably moved a version.

2020-12-08 16:35 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
> +                   "pulp_created": "2020-11-06T15:42:20.645197Z",
Should we shorten this in the docs with `-----BEGIN PGP PUBLIC KEY BLOCK-----\n\n [...] \n-----END PGP PUBLIC KEY BLOCK-----\n`?
I don't see much value for the reader to see the raw key material.

2020-12-08 16:35 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +                        "service instead.".format(service.name),
If this migration failed, will the resource be non functional? We should add this to the warning.

2020-12-08 16:35 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +                        service.public_key = key.read()
Should we add another try-warn safety layer here, too?

2020-12-08 16:35 UTC, mdellweg commented on pulpcore/app/models/content.py
> +
Ideally this warning will only be triggered when someone accesses this key in the dict.
Is it worth subclassing dict for this?

2020-12-08 16:35 UTC, mdellweg commented on pulpcore/app/serializers/content.py
> +    public_key = serializers.CharField(
It may be beneficial to do it now, to not have to "calculate" it in an upcoming migration.

2020-12-11 16:48 UTC, lubosmj commented
@mdellweg, fingerprints are now calculated during the migration. Have a look.

2020-12-15 09:23 UTC, mdellweg requested changes

2020-12-15 09:23 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +        print_warning(service)
If you do not reraise this exception, the function will return `None` leading to `update_model_fields` to fail with a `KeyError`. I suggest to reraise the exception and catch-ignore it in the loop in line 86, so so subsequent services are still attempted to be migrated, but the whole migration doesn't throw any thing.

2020-12-15 09:23 UTC, mdellweg commented on pulpcore/app/models/content.py
> +            return super().__getitem__(item)
This is exactly what i meant.
I feel like i created a monster. ;)

2020-12-15 09:23 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +            service.pubkey_fingerprint = import_result.fingerprints[0]
:+1:

2020-12-16 08:58 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +        migrations.RunPython(migrate_public_key_values),
Can you please provide a down migration here?

https://docs.djangoproject.com/en/3.1/ref/migration-operations/#runpython

2020-12-17 08:51 UTC, lubosmj commented on pulpcore/app/migrations/0053_add_public_key.py
> +        migrations.RunPython(migrate_public_key_values),
I do not quite understand what you want me to do. What is the down migration?

2020-12-17 08:58 UTC, lubosmj commented on pulpcore/app/migrations/0053_add_public_key.py
> +        migrations.RunPython(migrate_public_key_values),
Were you referring to the `reverse_code` parameter?

2020-12-17 09:36 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +        migrations.RunPython(migrate_public_key_values),
Yes, exactly. And it is probably an empty lambda expression, but it allows to rollback migrations.

2020-12-22 15:19 UTC, lubosmj commented on pulpcore/app/migrations/0053_add_public_key.py
> +        migrations.RunPython(migrate_public_key_values),
I added `migrations.RunPython.noop`.

2020-12-23 09:34 UTC, mdellweg approved these changes
I believe, this now catches all the exceptions we could encounter.

For the sake of simplicity i'd rather have a single try-ecxept-warn-pass around the best-effort migration of every single singing service. But i'm not going to block this PR there.

Still a second pair of eyes on the db-migration would be good. @bmbouter

2020-12-23 09:34 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +        "be valid.".format(service.name),
You cannot "run the migration again".
How about:
```suggestion
        "The public key migration for '{}' failed.  The resource will not "
        "be valid. Consider creating a new signing service instead."
        "".format(service.name),
```

2020-12-23 09:34 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +
There's a newline missing.

2020-12-23 09:34 UTC, mdellweg commented on pulpcore/app/migrations/0053_add_public_key.py
> +            field=models.TextField(),
What happens if two signing services failed to migrate?
Is it correct that this is not a problem (?) because:
* the fields are not unique
* the database allows the fields to stay empty (but the services proved to be unusable anyway)
* removing the default makes the field required for new services

Remember: As long as the database is in a "supported state" (including misconfigured singing services) the migration must pass without exposing an uncaught exception. And i heard, we do not allow migrations to be touched later.

2021-01-25 20:22 UTC, bmbouter commented on pulpcore/app/models/content.py
> +                    "(3.9.0)."
This needs to show 3.10.0 I think right?

2021-01-25 20:23 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    class _WarningsDict(dict):
Please move this class definition to the module level. It's ok to still call it `_WarningsDict` though.

2021-01-25 20:24 UTC, bmbouter commented on pulpcore/app/models/content.py
> +                    "(3.9.0)."
Also all the `3.10.0` strings in this PR can just say `3.10` I think.

2021-01-25 20:29 UTC, bmbouter requested changes
@lubosmj this is excellent. I'm requesting a few small changes and then I'll lgtm.

Please fix the version deprecation strings to be 3.10 and move the _WarningsDict to the module level and we'll be done!

2021-01-26 18:50 UTC, bmbouter approved these changes
Thank you @lubosmj ! This is excellent! I really appreciate all the effort you've put into this.

2021-01-26 18:51 UTC, merged