Added fields controlling connection-timeouts to Remote.
pulp/pulpcore pull request #1026
Opened 2020-11-13 22:29 UTC by ggainey

closes #7201

2020-11-14 15:18 UTC, mdellweg commented on pulpcore/download/factory.py
> +            sock_connect = settings.DEFAULT_CONNECTION_TIMEOUT_SECONDS
```suggestion
        sock_connect = self._remote.sock_connect_timeout or settings.DEFAULT_CONNECTION_TIMEOUT_SECONDS
```
Lazy evaluation ;)

2020-11-15 17:02 UTC, ggainey commented on pulpcore/download/factory.py
> +            sock_connect = settings.DEFAULT_CONNECTION_TIMEOUT_SECONDS
Elegance is a good thing :)

2020-11-16 18:42 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +    def test_timeout_attributes(self):
Can this test be broken up into different indivudal tests?

2020-11-16 18:46 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +class CRUDRemoteTestCase(unittest.TestCase):
It would be really great if these were bindings tests instead of `requests` API calls. We get more value out of testing the bindings because it ensures the api schema producing those bindings is also correct. Most of our existing tests are `requests` based, but net-new tests I hope can all be bindings based. We've been porting pulp_ansible to bindings tests a lot recently, here's an example: https://github.com/pulp/pulp_ansible/pull/423/files#diff-d8871ad5c606deb92237ce777a88530a3522c2ae112096a0e105fb42f8337cf7R71

2020-11-16 18:55 UTC, bmbouter commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
I didn't expect a system-wide default setting. I imagined we would defer to the defaults in aiohttp in all cases.

2020-11-16 18:56 UTC, bmbouter commented on CHANGES/7201.feature
> +Exposed aiohttp.ClientTimeout fields in Remote.
It would be cool if this called out the fields by name each wrapped in doublebackticks (sphinx escaping format).

2020-11-16 18:57 UTC, bmbouter requested changes
Despite my variety of comments, this PR is bigtime going in the right direction.

2020-11-17 13:23 UTC, ggainey commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
Current behavior is a hardcoded sock_connect=600. aiohttp default is 300. Letting the admin override the hardcoded default is better than what we have now.

Also, being on the wrong side of a bad upstream connection means *all* your remotes are going to have problems - it would be nice to let the admin set a global value, rather than having to set every single remote individually. Thinking about it, I'd suggest letting the admin set *all* the ClientTimeout values here, with either empty or 0 meaning "take the aiohttp defaults".  Thoughts?

2020-11-17 13:25 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +class CRUDRemoteTestCase(unittest.TestCase):
Makes sense, can do

2020-11-17 13:25 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +    def test_timeout_attributes(self):
Sure, makes sense

2020-11-17 13:33 UTC, ggainey commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
Just realized current-behavior also hardcodes sock_read=600 as well.

2020-11-17 13:33 UTC, ggainey commented on CHANGES/7201.feature
> +Exposed aiohttp.ClientTimeout fields in Remote.
good idea

2020-11-18 18:51 UTC, ggainey commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
I added DEFAULT_SOCKET_READ_TIMEOUT_SECONDS so that we out of the box recreate the current situation (sock_read and connect default to 600s). Still waiting on "should we allow instance-wide defaults for all four ClientTimeout settings"

2020-11-18 18:51 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +class CRUDRemoteTestCase(unittest.TestCase):
and done!

2020-12-01 20:36 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +class CRUDRemoteTestCase(unittest.TestCase):
thank you!

2020-12-01 20:45 UTC, bmbouter commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
I want to make a case, shocking as it may be
That we defer default values to aiohttp
Previous pulp versions I know
Set them to 600 though,
I do not think it should be

Verse aside, I want us to seriously consider changing these. Those values would be 300 seconds, not 600. Here's the reasoning:

* We can change code-defaults without breaking semver which applies strictly to integration points with Pulp like the API
* I don't see a reason why these values are better than the aiohttp defaults. They do more downloading than we do.
* Pulp should introduce features as requested, global options like these weren't yet requested
* There is precedent for this, look at how this was changed with the download concurrency. If there is a desire for users to "get back their heavior" they can use a mass-set update like `pulpcore-manager dbshell -c SQL COMMANDS HERE`.

2020-12-01 21:08 UTC, ggainey commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
I don't have a huge issue with not-doing this, honestly - as long as what we do instead is "not hardcode 'our' defaults", and just let aiohttp be controlling unless the remote is explicitly changed". I have an allergy to setting things like this in code.

So to be clear - the proposal is "remove DEFAULT_SOCKET_READ_TIMEOUT_SECONDS and DEFAULT_CONNECTION_TIMEOUT_SECONDS , **and** the 600-second-hard-coded-override, and let aiohttp win", yes?

2020-12-01 21:21 UTC, bmbouter commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
yes, that's what I'm proposing. Maybe save a copy of your existing commit in case other reviewers feel differently. But yes, I would lgtm that.

2020-12-01 21:21 UTC, bmbouter commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
Also maybe a .deprecated release note calling out the 600 -> 300 timeout changes.

2020-12-01 21:31 UTC, ggainey commented on docs/settings.rst
> +DEFAULT_CONNECTION_TIMEOUT_SECONDS
Sounds like a fine plan :)

2020-12-03 16:36 UTC, bmbouter commented on CHANGES/7201.feature
> +This replaces the previous hard-coded 600 second timeout for sock_connect and sock_read,
:+1:

2020-12-03 16:40 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +        time.sleep(1)
Can we switch these sleeps to `monitor_task`? You can see an example of it here https://github.com/pulp/pulpcore/blob/98c591ae46a6350e4c96e325f3e1b5e3362c11bd/pulpcore/tests/functional/utils.py#L62

2020-12-03 16:49 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +        time.sleep(1)
> Can we switch these sleeps to `monitor_task`? You can see an example of it here

Ahh perfect - much better, will do!

2020-12-03 18:38 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +        time.sleep(1)
Done!

2020-12-03 19:42 UTC, bmbouter approved these changes
This looks great to me. Thank you so much @ggainey !

2020-12-03 19:58 UTC, goosemania approved these changes
Thanks!

2020-12-03 20:09 UTC, merged