Added pre_save hook to Artifact to enforce checksum rules.
pulp/pulpcore pull request #1027
Opened 2020-11-14 21:10 UTC by ggainey

Closes #7696

2020-11-16 08:48 UTC, mdellweg commented on pulpcore/app/models/content.py
> +
I'm not entirely sure, this is worth the computing power, as it is still possible to add forbidden fields between initialization and saving of the artifact.
Given Artifacts are probably the most central entity in Pulp, this could trade a measurable performance hit for not being safe on the other side.
The before_safe hook is really our parachute here.

2020-11-16 08:48 UTC, mdellweg commented on pulpcore/tests/unit/models/test_content.py
> +        # This will only fire on a Pulp instance that has forbidden md5 in settings.py
This is a unittest. Do you think you can mock that value there?

2020-11-16 15:21 UTC, ggainey commented on pulpcore/app/models/content.py
> +
The cost we're talking about here, is doing a set-intersection on 2 sets of <10 elements, and a single 'if' - microseconds, literally, at worst. If your repo has a million Artifacts, you might add ones of milliseconds to a sync.

There are definitely cases we have to catch at save-time, but the majority-use is "provide the checksums at init". Having this check here, means catching those immediately, rather than going through "manipulate the Artifact and whatever points to it and then fail at save-time".

I'm willing to be overridden here - but I think this is a useful check with minimal performance cost.

2020-11-16 15:21 UTC, ggainey commented on pulpcore/tests/unit/models/test_content.py
> +        # This will only fire on a Pulp instance that has forbidden md5 in settings.py
Fine idea, repush inbound!

2020-11-16 15:56 UTC, mdellweg commented on pulpcore/tests/unit/models/test_content.py
> +    )
:1st_place_medal: 
I just don't understand, why you are mixing the two technologies here.
I'd make them both decorators.

2020-11-16 16:03 UTC, ggainey commented on pulpcore/tests/unit/models/test_content.py
> +    )
Eh, reasonable point. Was trying to keep the "what we're testing" as close to the test as possible, but I can see it being confusing. Lemme fix.

2020-11-16 16:10 UTC, mdellweg approved these changes
Given that you will change the mocking in the tests to a unified appearance, i am going to leave an ACK on this.

2020-11-16 20:25 UTC, bmbouter commented on CHANGES/7696.feature
> +Added pre_save hook to Artifact to enforce checksum rules implied by ALLOWED_CONTENT_CHECKSUMS.
I think this changelog should be for plugin writers since users never call or have access to the save calls directly. So `/CHANGES/plugin_api/7696.feature`.

2020-11-16 20:26 UTC, bmbouter commented on pulpcore/app/models/content.py
> +class MissingDigestValidationError(Exception):
It's not a big thing, but I'm a little uneasy with these custom exceptions declared here and there. Instead can we use Python exceptions and emit them in the right places along with `Raises` docstrings identifying the scenarios they are called?

2020-11-16 20:28 UTC, bmbouter commented on pulpcore/tests/unit/models/test_content.py
> +class ArtifactAlgorithmTestCase(SimpleTestCase):
:+1:

2020-11-16 20:29 UTC, bmbouter commented on pulpcore/tests/unit/models/test_content.py
> +    def test_set_forbidden(self, mock_DIGEST_FIELDS):  # noqa
Why are there so many `# noqa` ?

2020-11-16 20:31 UTC, bmbouter commented on pulpcore/app/models/content.py
> +
I don't see the change in this PR, but if the question: "should we also be checking in `Artifact.__init__()`, I think we should not do both. Checking it in two places with each runtime on each system, is not worth it to benefit a programmer at development who will still experience the error just at save time instead. My opinion at least.

2020-11-17 12:59 UTC, ggainey commented on pulpcore/app/models/content.py
> +class MissingDigestValidationError(Exception):
I prefer specific exceptions because it makes code that looks for exceptions a lot cleaner/easier to understand. If you use generic exceptions, code that wants to respond to specific problems (especially code higher up in a call-chain than the immediate caller) has to do string-matches on exception-messages. If we ever end up localizing messages, it makes such code even more difficult.

However, if The Pulp Way is to use generic python exceptions, I'm ok to adhere to that.

2020-11-17 13:03 UTC, daviddavis commented on pulpcore/app/models/content.py
> +
I also agree. I am hoping that no user ever hits these errors--only developers/plugin writers while they are developing.

2020-11-17 13:03 UTC, ggainey commented on pulpcore/tests/unit/models/test_content.py
> +    def test_set_forbidden(self, mock_DIGEST_FIELDS):  # noqa
PEP8 doesn't like caps-in-argument-names, and pycharm complains about it. I 'assumed' flake and/or black would as well - investigation shows they don't care, so I can just tell pycharm to not worry about it and remove the #noqas :)

2020-11-17 13:05 UTC, daviddavis commented on pulpcore/app/models/content.py
> +class MissingDigestValidationError(Exception):
I also like having specific exceptions. Would a central place to define exceptions solve your concern @bmbouter?

2020-11-17 13:13 UTC, ggainey commented on pulpcore/app/models/content.py
> +
okeydoke, will do

2020-11-17 13:13 UTC, ggainey commented on CHANGES/7696.feature
> +Added pre_save hook to Artifact to enforce checksum rules implied by ALLOWED_CONTENT_CHECKSUMS.
good catch

2020-11-24 19:08 UTC, bmbouter commented on pulpcore/app/models/content.py
> +class MissingDigestValidationError(Exception):
Yes. And if the others can be moved there to that would be extra great.

2020-11-24 19:09 UTC, bmbouter commented on pulpcore/plugin/models/__init__.py
> +    MissingDigestValidationError,
We probably want to move this then to `pulpcore.plugin.exceptions` then.

2020-11-24 19:09 UTC, bmbouter commented on pulpcore/plugin/models/__init__.py
>      UnsupportedDigestValidationError,
Moving this one will reqiure the 1-cycle deprecation ...

2020-11-24 19:10 UTC, bmbouter requested changes
Requested change on where custom exceptions are defined. It's looking great otherwise.

2020-12-01 13:42 UTC, ggainey commented on pulpcore/app/models/content.py
> +class MissingDigestValidationError(Exception):
@bmbouter I'd like to make the consolidation effort its own Thing - see https://pulp.plan.io/issues/7908. That will let this PR/issue remain a .feature, and keep 7908 as strictly a .deprecation. (Obviously, the exception(s) added with this PR I'll move to the right place as part of this PR, repushing shortly)

2020-12-01 20:09 UTC, bmbouter commented on CHANGES/plugin_api/7696.feature
> +Added pre_save hook to Artifact to enforce checksum rules implied by ALLOWED_CONTENT_CHECKSUMS.
Either this PR or the next one I think needs to add a `CHANGES/plugin_api/XXXX.feature` that announces the exceptions available at `pulpcore.plugin.exceptions`. @ggainey is that this PR ok the next one? I'm ok with either.

2020-12-01 20:10 UTC, ggainey commented on CHANGES/plugin_api/7696.feature
> +Added pre_save hook to Artifact to enforce checksum rules implied by ALLOWED_CONTENT_CHECKSUMS.
I'm thinking it would make the most sense as part of https://pulp.plan.io/issues/7908 - will add a note to that effect to that issue.

2020-12-01 20:14 UTC, bmbouter approved these changes
Thank you! This is an important safety feature.

2020-12-01 20:15 UTC, bmbouter commented
I see two approvals!

2020-12-01 20:15 UTC, merged