Fix example for AccessPolicyFromDB
pulp/pulpcore pull request #1029
Opened 2020-11-17 14:55 UTC by mdellweg

[noissue]

2020-11-18 15:01 UTC, bmbouter commented on pulpcore/app/migrations/0042_rbac_for_tasks.py
> +        migrations.RunPython(populate_access_policy, reverse_code=remove_access_policy),
Generally we never modify a migration once it's shipped.

2020-11-18 15:02 UTC, bmbouter commented on pulpcore/app/migrations/0050_namespace_access_policies.py
> +        migrations.RunPython(namespace_access_policies_up, reverse_code=namespace_access_policies_down),
fancy :+1:

2020-11-18 15:05 UTC, bmbouter commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
I think this should be only for plugin writers. Users never modify/populate this data since this field is part of the contract between plugin writers and pulpcore.plugin. It's tech preview and generally unused in plugin code so I don't think it needs to go through the deprecation cycle, but I do think it should be labeled in the plugin writer changelog as a .removal.

2020-11-18 15:07 UTC, bmbouter commented on pulpcore/app/access_policy.py
> +        except AccessPolicyModel.NotFound:
How long will we carry this fallback style behavior? This seems like it could go through the deprecation cycle with a fallback like this... If so it needs warnings that it'll be removed in 3.10 and a deprecation changelog entry.

2020-11-18 15:08 UTC, bmbouter commented on pulpcore/app/access_policy.py
> +                viewset_name=view.__class__.view_name()
oh yeahhhh :cake:

2020-11-18 15:08 UTC, bmbouter requested changes
This is looking really good. I requested some changes, but all mostly small things I think.

2020-11-18 16:58 UTC, mdellweg commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
But users see it and need that name to look the policy up they want to modify.

2020-11-18 17:03 UTC, bmbouter commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
Oh that's true. Actually that got me thinking ... from a user usability perspective `remotes-file/file` is probably just as mysterious a string as `FileRemoteViewSet`. Random idea: what if instead of `viewset_name` it was `viewset_url` and it actually contained a url? Maybe that won't work well at all, just a thought.

2020-11-19 09:00 UTC, mdellweg commented on pulpcore/app/migrations/0042_rbac_for_tasks.py
> +        migrations.RunPython(populate_access_policy, reverse_code=remove_access_policy),
:disappointed: I'll remove it.

2020-11-19 09:02 UTC, mdellweg commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
Would that be unique? I thought you can hook up the viewset with multiple urls. (And if it's possible, someone will do it...)

2020-11-19 09:32 UTC, mdellweg commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
I only see a `urlpattern()` method leading to
```
In [17]: FileRepositoryViewSet.urlpattern()
Out[17]: 'repositories/file/file'

In [18]: TaskViewSet.urlpattern()
Out[18]: 'tasks'
```
That might be ok. Going to check, where it is defined, and if it's guaranteed to exist.

2020-11-19 09:43 UTC, mdellweg commented on CHANGES/7845.bugfix
> +Properly namespaced the `viewset_name` in `AccessPolicy` to avoid naming conflicts in plugins.
Turns out, both live on the `NamedModelViewSet`. With the `view_name` being a tiny little bit more collision free. But things go up in flames anyway if the `urlpattern` isn't unique. So they should be equaly fine with the url to be more user friendly.

2020-11-23 15:49 UTC, bmbouter commented on pulpcore/app/access_policy.py
> +        except AccessPolicyModel.NotFound:
This looks good.

2020-11-23 15:50 UTC, bmbouter commented on pulpcore/app/models/task.py
> +    ACCESS_POLICY_VIEWSET_NAME = "tasks"
So this is just the url representing `/pulp/api/v3/tasks/` ?

2020-11-23 15:51 UTC, mdellweg commented on pulpcore/app/models/task.py
> +    ACCESS_POLICY_VIEWSET_NAME = "tasks"
Yes, it is.

2020-11-23 15:52 UTC, bmbouter approved these changes
This all looks good to me. Thank you!

2020-11-26 10:12 UTC, ipanova approved these changes

2020-11-26 10:13 UTC, merged