Updated pulplift references in the docs
pulp/pulpcore pull request #1033
Opened 2020-11-23 10:42 UTC by mdellweg

fixes #7878
https://pulp.plan.io/issues/7878

This depends on https://github.com/pulp/pulp_installer/pull/498

2020-11-24 15:12 UTC, dralley commented on docs/contributing/dev-setup.rst
> +This repository is for Pulp 3 only, development is done against the master branch of each.
"development is done against the master branch of each." is really confusing in this context as it's not clear what "each" is referring to.  It would be better if we either mentioned this after we mention the plugins, or if we just leave it out.

2020-11-24 19:15 UTC, bmbouter commented on docs/contributing/dev-setup.rst
> +as part of the installer repository, which is based on
nitpick: Can this paragraph be wrapped more. I know it makes the blame more complicated, but this way is less readable in unrendered.

2020-11-24 19:16 UTC, bmbouter commented on docs/contributing/dev-setup.rst
> +This repository is for Pulp 3 only, development is done against the master branch of each.
+1 to remove this sentence altogether.

2020-11-24 19:16 UTC, bmbouter commented on docs/contributing/dev-setup.rst
> +We recommend using ``pulplift`` for developer installations.
Nitpick here also to not wrap at the end of the sentence. Dense paragraphs are more readable I think.

2020-11-24 19:17 UTC, bmbouter requested changes
requested some nitpick changes. Thanks in advance for considering them.

2020-11-25 09:29 UTC, mdellweg commented on docs/contributing/dev-setup.rst
> +as part of the installer repository, which is based on
Not sure how to properly wrap those.

But it's not only about blame. It's every single future review on these lines that touches more lines than needed. And those unwieldy hyper references prove to me that this is actually source code to be compiled into nice looking html, pdf or whatever.

2020-11-30 17:20 UTC, bmbouter commented on docs/contributing/dev-setup.rst
> +`Ansible roles <https://github.com/pulp/pulp_installer#pulp-3-ansible-installer>`_ directly, if you
Sphinx renders links correctly if they are split with a newline.

2020-11-30 17:20 UTC, bmbouter commented on docs/contributing/dev-setup.rst
> +To ease developer setup, we have
This paragraphs is much less readable.

2020-12-08 20:04 UTC, bmbouter approved these changes
This is looking good to me.

2020-12-08 20:16 UTC, dkliban approved these changes

2020-12-08 20:24 UTC, bmbouter commented
I see two lgtm's, I'm merging.

2020-12-08 20:24 UTC, merged