Fixes Put request on api.html
pulp/pulpcore pull request #1034
Opened 2020-11-23 15:36 UTC by ExaneServerTeam

Fixes X-CSRFToken Header not being sent for Ajax Requests

fixes #7888

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2020-11-23 15:37 UTC, ExaneServerTeam commented
Reference
---------
https://docs.djangoproject.com/en/3.1/ref/csrf/#ajax
https://kylebebak.github.io/post/django-rest-framework-auth-csrf
https://stackoverflow.com/questions/42514560/django-and-ajax-csrf-token-missing-despite-being-passed

2020-11-24 14:52 UTC, goosemania commented
@daviddavis , please review

2020-12-07 21:11 UTC, bmbouter commented
I hope to review this soon. Apologies for not getting to it yet.

2021-01-12 14:35 UTC, dkliban commented
@ExaneServerTeam  I left a question on the issue: https://pulp.plan.io/issues/7888#note-3

2021-01-12 15:22 UTC, dkliban commented
@ExaneServerTeam I am not familiar with JavaScript, but I noticed that the code being added already exists in DRF[0] and is being imported by the api.html template[1]. What is the difference between that code and your change?

[0] https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/csrf.js
[1] https://github.com/pulp/pulpcore/blob/3.9/pulpcore/app/templates/rest_framework/api.html#L295

2021-01-12 18:09 UTC, ExaneServerTeam commented
Hello Dennis,

Good catch. This is almost exactly the same chunk of code.
The only thing I can promis is that (At least on my setup) the HEADER ("X-CSRFToken") was not sent..
I do not remember any specific JS issue on the page ...
Let me re investigate

One strange thing to me. getCookie is defined but not used in the current code base.. (To be confirmed)
But was used before
https://github.com/encode/django-rest-framework/commit/daccc2b8f3a1ebe104480748bfac8e92f17d4234

I'll now try to understand how window.drf.csrfToken and window.drf.csrfHeaderName are filled...

Frédéric

2021-01-13 07:59 UTC, ExaneServerTeam commented
Hello,
Thanks for putting me in the right direction. After investigation the solution is a lot more simplier.
A variable assignment was missing on api.html

2021-01-19 08:19 UTC, ExaneServerTeam commented
@dkliban Any thought ?

2021-01-19 10:07 UTC, mdellweg commented on pulpcore/app/templates/rest_framework/api.html
> +          csrfToken: "{{ csrf_token }}"
:+1:

2021-01-19 13:28 UTC, dkliban requested changes
This change looks good to me. You just need to fix the commit message for the CI to pass.

Please squash the two commits and make sure that the commit message has "Fixes: #7888". Right now your commit message is missing the colon after Fixes.

2021-01-19 14:09 UTC, ExaneServerTeam commented
@dkliban Rebased and squashed (My First Squashing session ;))

2021-01-19 14:39 UTC, mdellweg approved these changes

2021-01-19 14:39 UTC, merged