Use subclaassed plugin downloaders during the pulp repair.
pulp/pulpcore pull request #1043
Opened 2020-12-01 15:21 UTC by ipanova

closes #7909
https://pulp.plan.io/issues/7909

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2020-12-01 15:49 UTC, dralley approved these changes

2020-12-01 20:32 UTC, bmbouter commented on CHANGES/7909.bugfix
> +Use subclaassed plugin downloaders during the pulp repair.
```suggestion
Use subclassed plugin downloaders during the pulp repair.
```

2020-12-01 20:33 UTC, bmbouter requested changes
nitpick change requested, then lgtm.

2020-12-01 22:02 UTC, ipanova commented
@bmbouter merge ahead when ci passes

2020-12-03 16:52 UTC, bmbouter approved these changes
Thank you!

2020-12-03 16:52 UTC, merged