Prevent tasking system deadlocks when Redis is restarted/data lost
pulp/pulpcore pull request #1058
Opened 2020-12-14 21:43 UTC by dralley

2020-12-15 08:58 UTC, mdellweg reviewed
Is there a 1 to 1 relationship of workers and queues? In that case it should be possible merge the cleanup into one routine.

As you do not enque the resource job anymore, you should have a look at this line too:
https://github.com/pulp/pulpcore/blob/25e92d0d65bcac08994a420b8c45a2094233fe32/pulpcore/tasking/util.py#L49

2020-12-15 08:58 UTC, mdellweg commented on pulpcore/tasking/worker_watcher.py
> +        _logger.info(_("Cleaning up shutdown worker '%s'.") % worker_name)
Nitpick: I have seen us using `.format(...)` in the other places.

2020-12-15 14:10 UTC, dralley commented
This resource job is actually the "resource manager job" whereas the one I got rid of was the "release resources job".  So unfortunately we still need it since they do different things.

2021-01-21 21:12 UTC, bmbouter commented on pulpcore/tasking/worker_watcher.py
> +def check_dropped_queues():
This name could be clearer I think. Somehow working in the idea that it also cancels would do it for me.

2021-01-21 21:12 UTC, bmbouter commented on pulpcore/tasking/worker_watcher.py
> +def check_dropped_queues():
Maybe `check_and_cancel_missing_tasks` ?

2021-01-21 21:13 UTC, bmbouter commented on pulpcore/tasking/worker_watcher.py
> +    queues and "forgotten". Therefore the Task will never be marked completed in Pulp.
Another sentence here would be good I think. It could add that it's problematic because tasks that never complete never release their resources and that causes the tasking system to deadlock.

2021-01-21 21:14 UTC, bmbouter commented on pulpcore/tasking/worker_watcher.py
> +    # Also go through all of the tasks that were still queued up on the resource manager
Niiiiice :+1:

2021-01-21 21:17 UTC, bmbouter commented on CHANGES/7912.bugfix
> +Provide a mechanism to automatically resolve issues and prevent deadlocks when Redis experiences data loss (such as a restart).
nitpick: add a newline at the end?

2021-01-21 21:25 UTC, bmbouter commented
I ran some hand tests where I simulated OOM kill against a long running task and it was marked as failed nicely.

2021-01-21 21:26 UTC, bmbouter requested changes
I think this PR is very excellent. I am requesting very small docstring, function name, and a newline change.

Thank you for making this! It's much simpler and better! :1st_place_medal:

2021-01-21 22:17 UTC, dkliban approved these changes
This is a great improvement!

2021-01-21 22:21 UTC, dralley commented on pulpcore/tasking/worker_watcher.py
> +        state__in=TASK_INCOMPLETE_STATES, worker__in=Worker.objects.online_workers()
@bmbouter Should this be ```worker__isnull=False```?  In theory I guess you could unplug a machine and after a while the worker is no longer "online", but it's task would still be assigned.

2021-01-22 15:10 UTC, dralley commented on pulpcore/tasking/worker_watcher.py
> +        state__in=TASK_INCOMPLETE_STATES, worker__in=Worker.objects.online_workers()
Although I suppose the worker watcher should handle that

2021-01-22 21:25 UTC, bmbouter commented on pulpcore/tasking/worker_watcher.py
> +        state__in=TASK_INCOMPLETE_STATES, worker__in=Worker.objects.online_workers()
Yeah I tested this actually I pkilled all workers including parents and their workhourse children. They remained in the running state until the worker watcher timeout occurred and they were transitioned to cancelled by the resource manager running its heartbeat check.

2021-01-22 21:26 UTC, bmbouter approved these changes
Thank you!

2021-01-22 21:27 UTC, merged