Add generic list endpoints
pulp/pulpcore pull request #1060
Opened 2020-12-18 12:39 UTC by mdellweg

Allow to list all
  * content
  * content_guards

fixes #7204
https://pulp.plan.io/issues/7204

2020-12-18 12:40 UTC, mdellweg commented
This feels a bit hacky, but is seems to work.
Maybe someone sees a better way to do it.

2021-01-26 20:07 UTC, bmbouter commented on CHANGES/7204.feature
> +Added general endpoints to list content, content_guards and repositories.
nitpick suggestion:

```suggestion
Added general endpoints to list ``Content``, ``ContentGuards``, and ``Repositories``.
```

2021-01-26 20:08 UTC, bmbouter commented
@mdellweg Do these endpoint end up generating bindings also?

2021-01-26 20:08 UTC, bmbouter commented
Would you be willing to add some basic tests to this PR?

2021-01-26 20:12 UTC, bmbouter commented
I tested with `pulp-cli` listing a system with one ansible and one file repository, and it worked nicely. I ran:

```
pulp ansible repository create --name foo
pulp file repository create --name bar
```

Then the `/pulp/api/v3/repositories/` endpoint returns:

```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "pulp_href": "/pulp/api/v3/repositories/file/file/07cf07e8-8e30-49c5-874e-05e587dba5f4/",
            "pulp_created": "2021-01-26T20:10:00.823318Z",
            "versions_href": "/pulp/api/v3/repositories/file/file/07cf07e8-8e30-49c5-874e-05e587dba5f4/versions/",
            "latest_version_href": "/pulp/api/v3/repositories/file/file/07cf07e8-8e30-49c5-874e-05e587dba5f4/versions/0/",
            "name": "bar",
            "description": null,
            "remote": null
        },
        {
            "pulp_href": "/pulp/api/v3/repositories/ansible/ansible/1debeb2f-7265-4800-b257-4aec40b912b3/",
            "pulp_created": "2021-01-26T20:09:53.846428Z",
            "versions_href": "/pulp/api/v3/repositories/ansible/ansible/1debeb2f-7265-4800-b257-4aec40b912b3/versions/",
            "latest_version_href": "/pulp/api/v3/repositories/ansible/ansible/1debeb2f-7265-4800-b257-4aec40b912b3/versions/0/",
            "name": "foo",
            "description": null,
            "remote": null
        }
    ]
}
```

This is delightful.

2021-01-26 20:13 UTC, bmbouter requested changes
My main request is tests. Otherwise I think this is good to go.

2021-01-27 07:01 UTC, mdellweg commented
> @mdellweg Do these endpoint end up generating bindings also?

It seems, they do. See the added test.

2021-01-28 10:11 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +        # cls.content_guard = cls.cert_guards_api.create({"name": utils.uuid4(), "ca_certificate": utils.uuid4()})
@bmbouter Do you know an easy way to get some bytes that are passing the pulpcore validation here?
Other than that, the thing should be ready.

see also: https://github.com/pulp/pulp-cli/pull/97

2021-01-28 16:23 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +    def test_read_all_repos_generic(self):
Can this be split into multiple tests please? It's ok to me if they have one setup though.

2021-01-28 16:34 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +    def test_read_all_repos_generic(self):
ty!

2021-01-28 16:34 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +# coding=utf-8
This is not needed anymore. All python3 files assume utf-8

2021-01-28 16:40 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +        # cls.content_guard = cls.cert_guards_api.create({"name": utils.uuid4(), "ca_certificate": utils.uuid4()})
Yes I think you want to borrow a test from pulp-certguard. https://github.com/pulp/pulp-certguard/blob/master/pulp_certguard/tests/functional/api/test_x509_certguard.py#L26-L42

It uses artifacts that are checked in to that repo. I'd be ok with copying them here also, they are generically generated test data.

Ultimately we want to do away with those checked in assets but we haven't do it yet. The plan is to replace them with runtime-generated certs from [`trustme`](https://trustme.readthedocs.io/en/latest/).

2021-01-28 16:40 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +        # cls.content_guard = cls.cert_guards_api.create({"name": utils.uuid4(), "ca_certificate": utils.uuid4()})
@mdellweg is this what you were wanting to know?

2021-01-28 17:48 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +        # self.assertNotEqual(response.count, 0)
What do you want to do with this line?

2021-01-28 17:56 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_generic_list.py
> +        # self.assertNotEqual(response.count, 0)
Oh, i forgot. It's there to make sure there is actually at least one item to loop on.
I remember a case where no one realized for a long time that the tests inside a loop didn't run because the list to loop was empty.

2021-01-28 21:26 UTC, bmbouter commented on MANIFEST.in
> +recursive-include pulpcore/tests/functional/api/using_plugin/artifacts *
:+1:

2021-01-28 21:28 UTC, bmbouter approved these changes
This looks great to me. Thanks for adding all the tests I asked for and this great change! :+1:

2021-01-28 21:42 UTC, daviddavis commented on pulpcore/app/viewsets/content.py
> +    """ViewSet to list all content."""
This gets exposed to users in our api docs and I think we should avoid technical terms like ViewSet. Maybe "endpoint" is better?

2021-01-28 21:42 UTC, daviddavis commented on pulpcore/app/viewsets/publication.py
> +    """ViewSet to list all content_guards."""
Here as well.

2021-01-28 21:44 UTC, daviddavis commented on pulpcore/app/viewsets/repository.py
> +    """ViewSet to list all repositories."""
And here.

2021-01-29 13:05 UTC, daviddavis approved these changes

2021-01-29 13:49 UTC, merged