Restrict default permissions to admin users
pulp/pulpcore pull request #1064
Opened 2020-12-23 13:20 UTC by mdellweg

fixes #8018
https://pulp.plan.io/issues/8018

2021-01-05 14:26 UTC, mdellweg commented
@jlsherrill We want to confirm with katello if you are always using the admin user.
This should not impact you then.

2021-01-05 14:45 UTC, jlsherrill commented
That's correct!

2021-01-11 12:32 UTC, ipanova approved these changes

2021-01-15 12:41 UTC, ipanova commented
@bmbouter PTAL

2021-01-15 15:06 UTC, bmbouter commented
@newswangerd FYI on this, does galaxy_ng use any non-admin users that you don't define Permission classes explicitly for?

2021-01-15 15:08 UTC, bmbouter requested changes
I think we need a plugin writer `.removal` note calling out this breaking change. For example if a plugin is shipping a viewset that they need non-admin users to have access to they would want to see this in the plugin writer changelog. What do you all think about this?

2021-01-15 15:56 UTC, newswangerd commented
> @newswangerd FYI on this, does galaxy_ng use any non-admin users that you don't define Permission classes explicitly for?

Thanks for the heads up @bmbouter. I don't think this should affect galaxy_ng too much.

2021-01-19 15:22 UTC, bmbouter approved these changes
Thanks!

2021-01-19 16:08 UTC, merged