Switches plugin reporting to use Django name
pulp/pulpcore pull request #1102
Opened 2021-02-01 21:35 UTC by bmbouter

The Status API and the OpenAPI schema API now both use the Django name.
This is a backwards incompatible change, but necessar to fix the bug
which was using Python package names incorrectly instead.

It also enforces the version to be set on the PulpPluginAppConfig
subclass. If an installed plugin does not specify its version Pulp will
refuse to start.

closes #7930

2021-02-01 21:40 UTC, bmbouter commented
This changes from 

```
    "versions": [
        {
            "component": "pulpcore",
            "version": "3.10.0.dev0"
        },
        {
            "component": "pulp_ansible",
            "version": "0.7.0.dev0"
        },
        {
            "component": "pulp_file",
            "version": "1.6.0.dev0"
        }
    ]
```

To

```
    "versions": [
        {
            "component": "core",
            "version": "3.10.0.dev"
        },
        {
            "component": "ansible",
            "version": "0.7.0.dev"
        },
        {
            "component": "file",
            "version": "1.6.0.dev"
        }
    ],
```

2021-02-02 10:12 UTC, mdellweg reviewed
Sounds good to me.
Just a coding style suggestion.

2021-02-02 10:12 UTC, mdellweg commented on pulpcore/app/apps.py
> +            raise ImproperlyConfigured(msg.format(self.label))
:+1:

2021-02-02 10:12 UTC, mdellweg commented on pulpcore/openapi/__init__.py
> +            result["info"]["x-pulp-app-versions"][app.label] = app.version
```suggestion
        result["info"]["x-pulp-app-versions"] = {
            app.label: app.version
            for app in pulp_plugin_configs()
        }
```

2021-02-02 11:13 UTC, goosemania approved these changes
Thanks! Looks good to me.

2021-02-02 11:15 UTC, goosemania commented
> This changes from
> 
> ```
>     "versions": [
>         {
>             "component": "pulpcore",
>             "version": "3.10.0.dev0"
>         },
>         {
>             "component": "pulp_ansible",
>             "version": "0.7.0.dev0"
>         },
>         {
>             "component": "pulp_file",
>             "version": "1.6.0.dev0"
>         }
>     ]
> ```
> 
> To
> 
> ```
>     "versions": [
>         {
>             "component": "core",
>             "version": "3.10.0.dev"
>         },
>         {
>             "component": "ansible",
>             "version": "0.7.0.dev"
>         },
>         {
>             "component": "file",
>             "version": "1.6.0.dev"
>         }
>     ],
> ```

@jlsherrill , FYI, this change is coming in 3.10. I think Katello uses the status endpoint to check pulp services state but I wonder if you check the installed plugins as well.

2021-02-02 12:46 UTC, mdellweg requested changes

2021-02-02 12:46 UTC, mdellweg commented on pulpcore/app/views/status.py
> +            versions.append({"component": app.label, "version": app.version})
I just realized, this changes the keys and not only the trailing "0" in the versions.
This will break the version check logic in the cli.
Can we get back to the old names`

2021-02-02 13:01 UTC, bmbouter commented on pulpcore/app/views/status.py
> +            versions.append({"component": app.label, "version": app.version})
I also thought about this, but I don't see an easy way to. :/ What this change does is hand control over to the plugin for the name it provides. So it's up to the plugins really. Let's talk about it at the pulpcore meeting, I put an agenda item on there.

2021-02-02 13:40 UTC, mdellweg commented on pulpcore/app/views/status.py
> +            versions.append({"component": app.label, "version": app.version})
And BTW. This is what breaks the CI here too.

2021-02-02 19:45 UTC, bmbouter commented
@mdellweg any link on where I should look to fix the CI? Also is this something I'll need to also fix in the plugin template?

2021-02-02 20:11 UTC, mdellweg commented
> @mdellweg any link on where I should look to fix the CI? Also is this something I'll need to also fix in the plugin template?

https://github.com/pulp/pulpcore/blob/master/.ci/ansible/start_container.yaml#L87 is the check that fails.
https://github.com/pulp/pulpcore/blob/master/.github/workflows/scripts/before_install.sh#L37 is where that variable is set.

2021-02-02 20:14 UTC, mdellweg commented
Thinking more about this: The check is really valuable, as it catches oops-we-updated-the-thing-to-test-from-pypi-because-of-dependencies mistakes. But it relies on the assumption that there is only one plugin in the repository.

2021-02-03 19:11 UTC, bmbouter commented
@mdellweg I agree it's valuable but we no longer have info required to perform it (right?). All I can think to do is to disable the check. What are our other options? Can you (or someone on the CI team) give me some advice? Thanks!

2021-02-08 15:26 UTC, mdellweg commented
> @mdellweg I agree it's valuable but we no longer have info required to perform it (right?). All I can think to do is to disable the check. What are our other options? Can you (or someone on the CI team) give me some advice? Thanks!

For _our_ well curated "single_plugins_in_one_repo" we should still able to find the information what version it is supposed to be, right? I really want to avoid testing a released version instead of failing for dependency issues.

2021-02-08 15:30 UTC, bmbouter commented
@mdellweg my apologies. I'm haven't looked into that CI check yet and I'm not up to speed on what it does. Can you elaborate a bit more? Thanks!

2021-02-08 16:01 UTC, mdellweg commented
Sure, it makes sure, that the code that is installed inside the container is the one we are supposed to test.
We had previous incidents, where a plugin by not being compatible with the provided version of pulpcore downgraded pulpcore to a compatible one from pypi, and if it weren't for mismatching functional tests, this would have gone unnoticed.

2021-02-17 16:48 UTC, mdellweg commented on .github/workflows/scripts/before_install.sh
> +echo "component_name: pulp" >> .ci/ansible/vars/main.yaml
```suggestion
echo "component_name: core" >> .ci/ansible/vars/main.yaml
```

2021-02-17 16:49 UTC, mdellweg commented on template_config.yml
> +plugin_app_label: pulp
```suggestion
plugin_app_label: core
```

2021-02-17 16:58 UTC, bmbouter commented on pulpcore/openapi/__init__.py
> +            result["info"]["x-pulp-app-versions"][app.label] = app.version
I'd like to decline this change if that's alright. The list comprehension with the iterator at the end is less readable for me. What I wrote is a bit slower though.

2021-02-17 17:09 UTC, mdellweg commented
I'm about to say ACK here, but we need to merge 
https://github.com/pulp/plugin_template/pull/341
first and roll it out to all plugins (and their still tested stable branches) first.

2021-02-17 18:49 UTC, bmbouter commented
@mdellweg I reapplied the plugin template from https://github.com/pulp/plugin_template/pull/341/files and pushed it here to see if this change will pass with that plugin template change.

2021-02-25 15:06 UTC, mdellweg approved these changes

2021-02-25 15:16 UTC, merged