Enable nesting WorkingDirectory()
pulp/pulpcore pull request #1103
Opened 2021-02-01 22:58 UTC by dralley

closes: #7815
https://pulp.plan.io/issues/7815

2021-02-01 23:15 UTC, dralley commented
@goosemania This is not exactly what was described in the issue, but it's safer because each WorkingDirectory is kept separate rather than having one global working directory for the task.  wdyt?

2021-02-01 23:21 UTC, dralley commented on pulpcore/tasking/storage.py
> +                pass
Alternatively, we could try without using a random suffix first, and only if it collides would we try a random subfolder.

2021-02-01 23:27 UTC, dralley commented
Test failures unrelated

2021-02-02 10:18 UTC, mdellweg commented
Is this a reimplemetation of https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory ?

2021-02-02 12:57 UTC, dralley commented
Yes, basically, I noticed the same thing.  I don't really want to swap the entire implementation right but l now but maybe we could in the future.

2021-02-02 16:57 UTC, goosemania reviewed
In this PR, we recreate worker directory but do not recreate the sub directories in it. Correct? And for every context manager usage plugin will get new sub directory, is my understanding correct? If so and if we choose to do it, we would need to go through the deprecation path I think. It's a change in the current behaviour and it will likely break pulp_rpm which uses this context manager N times throughout sync or publish.
 
I believe one of the problems which was intended to be solved is to always have a directory for a task.
Maybe plugin needs multiple sub dirs, it's a different dimension and you seemed to solve that here, however it would be nice not to let plugin write into other directory by mistake, just because they forgot to use this context manager. And have always a directory set for a task. What do you think?

2021-02-02 16:57 UTC, goosemania commented on pulpcore/tasking/storage.py
> +        os.makedirs(self.path, mode=self.MODE)
Please update the docstring to reflect the changes

2021-02-02 17:13 UTC, dralley commented
> In this PR, we recreate worker directory but do not recreate the sub directories in it. Correct? 

Correct

>And for every context manager usage plugin will get new sub directory, is my understanding correct?

Correct

>If so and if we choose to do it, we would need to go through the deprecation path I think. It's a change in the current behaviour and it will likely break pulp_rpm which uses this context manager N times throughout sync or publish.

I don't understand why?  Does it assume that different ```WorkingDirectory()``` context manager usages are nonetheless always still using the same working directory?

> I believe one of the problems which was intended to be solved is to always have a directory for a task.

That's still true with this change.  It's just that instead of the ```WorkingDirectory``` returning this task directory, it returns a subdirectory of it.  So instead of using

```/var/lib/pulp/tmp/31326@pulp2-nightly-pulp3-source-centos7.localhost.example.com/325b21f9-f07d-4927-8137-6d592a811281/```

it uses

```/var/lib/pulp/tmp/31326@pulp2-nightly-pulp3-source-centos7.localhost.example.com/325b21f9-f07d-4927-8137-6d592a811281/ub91tswg/```

which is one level deeper.

> however it would be nice not to let plugin write into other directory by mistake just because they forgot to use this context manager

That is true.

2021-02-02 17:20 UTC, dralley commented
Just to mention it - the problem with nesting was the "delete and recreate" behavior, which makes sense for the ```WorkerDirectory``` but not so much for the ```WorkingDirectory```.  The second time you enter it would try to use the same directory, notice it already exists, and delete it.  That's not what we want.  We could just have nested calls just re-use the same directory.  But that assumes that the task isn't doing anything internally that could cause path conflicts, which feels like a bad assumption.

2021-02-02 17:31 UTC, goosemania commented
> > If so and if we choose to do it, we would need to go through the deprecation path I think. It's a change in the current behaviour and it will likely break pulp_rpm which uses this context manager N times throughout sync or publish.
> 
> I don't understand why? Does it assume that separate, subsequent `WorkingDirectory()` context manager usages are nonetheless always still using the same "dirty" working directory?

Actually, I think I'm wrong. The working directory was recreated every time, so plugin can't rely on any data being there. Disregard this concern then, I agree that no deprecation is needed then.

> 
> > I believe one of the problems which was intended to be solved is to always have a directory for a task.
> 
> That's still true with this change. It's just that instead of the `WorkingDirectory` returning this task directory, it returns a subdirectory of it. So instead of using
> 
> `/var/lib/pulp/tmp/31326@pulp2-nightly-pulp3-source-centos7.localhost.example.com/325b21f9-f07d-4927-8137-6d592a811281/`
> 
> it uses
> 
> `/var/lib/pulp/tmp/31326@pulp2-nightly-pulp3-source-centos7.localhost.example.com/325b21f9-f07d-4927-8137-6d592a811281/<8 random letters>/`
> 
> which is one level deeper.

I understand this part. The story states that pulpcore ensures that there is always a working dir for a task. And it seems to me that with this PR it's still a plugin responsibility. The allowed nesting makes it easier and more usable but it doesn't eliminate the concern that plugins must remember to use WorkingDirectory context manager.

I'm +1 to the approach with subdir , I just think that additionally we should add the working dir creation by pulpcore for every task and plugin can decide whether to have many subdirs or not but at least the task will always have one. What do you think?

2021-02-04 17:04 UTC, bmbouter commented on pulpcore/tasking/storage.py
> +    https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
I think we should switch to this and stop carrying so much code that stdlib already provides. Also we don't need to have the WorkerDirectory stuff even reusable, I think we should remove this whole module and move the remaining small pieces around `tempfile.TemporaryDirectory` to `pulpcore.tasking.worker`.

2021-02-04 17:05 UTC, bmbouter commented on pulpcore/tasking/storage.py
> +                pass
If we switch to the tempfile based implementation doesn't it guarantee it's free of race conditions and it can do the name picking?

2021-02-04 17:05 UTC, bmbouter commented on pulpcore/tasking/worker.py
> +        with TaskWorkingDirectory(job):
Yeah I think this area of the PR with just the right configuration could remove a huge amount of code.

2021-02-04 17:07 UTC, bmbouter commented
I also think that since the working directories will be managed every time by pulpcore, we don't even need to carry reusable facilities for working directories. If that's true would could deprecate the ones we have in the plugin API with 3.11 and remove them from 3.12 entirely. What do you think about this also?

2021-02-04 17:08 UTC, dralley commented on pulpcore/tasking/storage.py
> +                pass
I partially copied this implementation from ```tempfile```.  It'd be free of race conditions regardless due to being namespaced by worker and task.

2021-02-04 17:21 UTC, dralley commented on pulpcore/tasking/worker.py
> +        with TaskWorkingDirectory(job):
The reason I don't want to mess with it right now is because there are *some* differences, namely that I don't think stdlib ```TemporaryDirectory``` will create intermediate directories that don't already exist, and I'm not certain the permissions stuff is the same.

I'm not against a refactor issue being filed though.

2021-02-04 17:22 UTC, dralley commented on pulpcore/tasking/storage.py
> +    https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
The reason I don't want to mess with it right now is because there are some differences, namely that I don't think stdlib TemporaryDirectory will create intermediate directories that don't already exist, and I'm not certain the permissions stuff is the same. I don't want to scope of my current work to explode too much.

I'm not against a refactor issue being filed though.

2021-02-04 17:28 UTC, dralley commented
>I also think that since the working directories will be managed every time by pulpcore, we don't even need to carry reusable facilities for working directories. If that's true would could deprecate the ones we have in the plugin API with 3.11 and remove them from 3.12 entirely. What do you think about this also?

I don't know about this.  The more we enable doing more and different kinds of work within one task, the more we risk the possibility of file collisions in the working directory.  We already hit that once with the migration plugin.  https://pulp.plan.io/issues/7842

2021-02-04 18:20 UTC, bmbouter commented on pulpcore/tasking/storage.py
> +    https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
Yeah but this piece of work is already a huge refactor. If just unblocking the other issue is the goal (and I can get behind that) then I think just rewriting [this part](https://github.com/pulp/pulpcore/blob/master/pulpcore/tasking/storage.py#L63-L70) to the code below would do:

```
        try:
            os.makedirs(self.path, mode=self.MODE)
        except FileExistsError:
            pass
```

2021-02-04 18:36 UTC, dralley commented on pulpcore/tasking/storage.py
> +    https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
That would have been enough to make it re-entrant but it wouldn't have solved the collision problem I mentioned earlier.  If a plugin writer asks for a new WorkingDirectory they shold get a clean one.

2021-02-04 21:16 UTC, bmbouter commented
I see what you're saying in terms of a) this resolving the problem that blocks you and b) this not changing the behavior plugin writers experience already. I appreciate where you're coming from though. I want to get your work unblocked.

I've not lgtm'd this because I'm stuck on accepting that we're replacing a bunch of code we shouldn't be carrying with an even larger diff of code we shouldn't be carrying. Also code that's duplicated from the stdlib. I don't think this PR necessarily makes our situation worse though, so maybe I should just accept the PR as is.

One thing I could do that would be more helpful is to write the future design on an issue instead of trying to pitch it here.

2021-02-04 21:18 UTC, bmbouter commented
> > I also think that since the working directories will be managed every time by pulpcore, we don't even need to carry reusable facilities for working directories. If that's true would could deprecate the ones we have in the plugin API with 3.11 and remove them from 3.12 entirely. What do you think about this also?
> 
> I don't know about this. The more we enable doing more and different kinds of work within one task, the more we risk the possibility of file collisions in the working directory. We already hit that once with the migration plugin. https://pulp.plan.io/issues/7842

I agree when a new tempdir is needed it should be clean. I think the thing Pulp could do better though is have plugin writers use stdlib tools to get those clean directories instead of interfaces we provide. I'll put this onto the issue I write up though, and it can be separate from this PR.

2021-02-05 03:28 UTC, dralley commented
+1 to filing a refactor issue, I'll definitely take a look over it.  I just can't get hung up here because even once auto-publish is done, we've got a ton of RPM and migration work to get done by March that I need to help with.

2021-02-09 20:42 UTC, bmbouter requested changes
I think this also provides a feature and I want to make sure the release note calls that out. Specifically, it now creates a working directory automatically for each task and changes into it. If that can be clarified some I would lgtm this.

2021-02-09 20:43 UTC, bmbouter commented
FYI I filed the refactor issue here: https://pulp.plan.io/issues/8231 at the pulpcore meeting we are planning to do for 3.11, but we should still merge this for now since it only deprecates in 3.11, the code will still be needed.

2021-02-10 02:55 UTC, dralley commented
@bmbouter I added to the changelog

2021-02-10 14:30 UTC, bmbouter approved these changes
Thanks!

2021-02-10 15:36 UTC, mdellweg approved these changes

2021-02-10 18:16 UTC, goosemania approved these changes

2021-02-10 18:17 UTC, merged