Turn WORKER_TTL into a setting
pulp/pulpcore pull request #1151
Opened 2021-02-23 16:21 UTC by mdellweg

The heartbeat rate will scale proportional to that timeout.

fixes #8291

2021-02-23 17:19 UTC, bmbouter commented on docs/settings.rst
> +^^^^^^^^^^^^^^^
```suggestion
WORKER_TTL
^^^^^^^^^^
```

2021-02-23 17:20 UTC, bmbouter commented on CHANGES/8291.feature
> +Added the ``WORKER_TTL`` setting, that specifies the interval a worker is considered missing after its last heartbeat.
This is well said. :+1:

2021-02-23 17:26 UTC, bmbouter commented on pulpcore/tasking/constants.py
> +    WORKER_TTL=WORKER_TTL,
Can we refactor the code to use the setting directly imported from settings instead of importing it here, setting it here, and then having other things import it from here.

2021-02-23 17:56 UTC, bmbouter commented on pulpcore/tasking/constants.py
> +    JOB_MONITORING_INTERVAL=int(WORKER_TTL / 6),
So I tested to see if this is indeed spacing out the heartbeats and it did not. I think this is the parents RQ process checking in on its child PID the workhorse which is different. I think this should stay at 5.

We do need to do something though because here's what I learned. With a `WORKER_TTL=30` I get one heartbeat every 15 seconds:

```
Feb 23 17:48:40 pulp3-source-fedora33.localhost.example.com rq[31657]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:48:56 pulp3-source-fedora33.localhost.example.com rq[31657]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:49:11 pulp3-source-fedora33.localhost.example.com rq[31657]: pulp [None]: root:ERROR: HEARTBEAT
```

With a `WORKER_TTL=60` I get only one heartbeat every 45 seconds.

```
Feb 23 17:45:49 pulp3-source-fedora33.localhost.example.com rq[31434]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:46:35 pulp3-source-fedora33.localhost.example.com rq[31434]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:47:20 pulp3-source-fedora33.localhost.example.com rq[31434]: pulp [None]: root:ERROR: HEARTBEAT
```

With `WORKER_TTL=120` I get one heartbeat every 105 seconds

```
Feb 23 17:50:41 pulp3-source-fedora33.localhost.example.com rq[31813]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:52:26 pulp3-source-fedora33.localhost.example.com rq[31813]: pulp [None]: root:ERROR: HEARTBEAT
Feb 23 17:54:11 pulp3-source-fedora33.localhost.example.com rq[31813]: pulp [None]: root:ERROR: HEARTBEAT
```

So we're not actually getting more heartbeats, just fewer of them which means a slow db could equally not deliver the one it needs to. It's just being checked less frequently really which I think explains why experimentally changing this on the migration box did work, but not for the reason we think it did.

I tested with this diff:

```
diff --git a/pulpcore/tasking/worker.py b/pulpcore/tasking/worker.py
index d6c9403cd..ab36dad28 100644
--- a/pulpcore/tasking/worker.py
+++ b/pulpcore/tasking/worker.py
@@ -176,6 +176,7 @@ class PulpWorker(Worker):
             args (tuple): unused positional arguments
             kwargs (dict): unused keyword arguments
         """
+        logging.error('HEARTBEAT')
         handle_worker_heartbeat(self.name)
         check_worker_processes()
         if self.is_resource_manager:
```

2021-02-23 17:59 UTC, bmbouter requested changes
So along with this change we need to find out how to have RQ space out its heartbeats.

2021-02-24 09:32 UTC, mdellweg commented on pulpcore/tasking/constants.py
> +    JOB_MONITORING_INTERVAL=int(WORKER_TTL / 6),
Well, it's only sending the heartbeat 15 seconds before it is meant to timeout. The code is there:

https://github.com/rq/rq/pull/945/files#r185680378

2021-03-02 21:12 UTC, bmbouter commented
I looked into the `unlogged` option to fix this and it didn't work out because the FK in postgresql would require us to mark many tables as `unlogged`. So I think we're back to this as our best option.

I filed this: https://github.com/rq/rq/issues/1426

2021-03-02 21:39 UTC, bmbouter commented
I tested this PR against RQ and I think it works https://github.com/rq/rq/pull/1427

2021-03-03 15:53 UTC, bmbouter approved these changes
Given that the "spacing out" will be handled in RQ itself and our code can't control that anyway, I think this is LGTM now. :+1:

2021-03-03 19:23 UTC, dralley approved these changes

2021-03-03 19:28 UTC, bmbouter commented
I see two lgtm's, merging!

2021-03-03 19:28 UTC, merged