Add proxy username and password to remote
pulp/pulpcore pull request #1163
Opened 2021-03-03 13:08 UTC by mdellweg

fixes #8167
https://pulp.plan.io/issues/8167

2021-03-03 13:56 UTC, mdellweg commented
Whichever will be merged last, needs to adjust here:

https://github.com/pulp/pulpcore/pull/1165

2021-03-03 14:01 UTC, daviddavis commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +def move_proxy_creds_up(apps, schema_editor):
:rocket:

2021-03-03 14:02 UTC, daviddavis commented
The code looks good to me. It would be nice to have some tests (at least for the validation).

2021-03-03 15:26 UTC, bmbouter commented on CHANGES/8167.feature
> +Credentials can no longer be specified as part of the ``proxy_url``.
Can this release note identify that a migration moves the credentials from `proxy_url` also?

2021-03-03 15:30 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +            proxy_url = None
This `else` clauses could be avoided if the top of the function defined:

```
proxy_url = None
proxy_username = None
proxy_password = None
```

This is not a required change, just a suggestion to lower the cyclomatic complexity.

2021-03-03 15:31 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +    def validate_proxy_url(self, value):
Can some simple CRUD tests be added for these validation cases please?

2021-03-03 15:32 UTC, bmbouter requested changes
I left some requested changes. Mainly it's small things, and then a few tests please. Thanks for opening this!

2021-03-03 16:35 UTC, mdellweg commented
Needs to be adjusted now given:

https://github.com/pulp/pulpcore/pull/1165

2021-03-03 16:43 UTC, mdellweg commented
also fixes
https://pulp.plan.io/issues/8330

2021-03-03 16:53 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +                _("proxy username and password can only be specified together")
Can this declare the fields with their exact names?

2021-03-03 16:53 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +                _("proxy credentials cannot be specified without a proxy")
Can this declare the exact names also?

2021-03-04 01:34 UTC, rochacbruno approved these changes
LGTM

I left just a couple of suggestions

2021-03-04 01:34 UTC, rochacbruno commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +                pass
Python 3,4+ added `suppress` to avoid the use of `pass` in broader exceptions like this. https://docs.python.org/3.6/library/contextlib.html#contextlib.suppress

```suggestion
            with contextlib.suppress(Exception)
                parsed_url = urlparse(remote.proxy_url)
                url = parsed_url.netloc
                netloc = remote.proxy_username + ":" + remote.proxy_password + "@" + url
                remote.proxy_username = None
                remote.proxy_password = None
                remote.proxy_url = urlunparse(parsed_url._replace(netloc=netloc))
                remote.save()
```

2021-03-04 01:34 UTC, rochacbruno commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +                auth, url = netloc.rsplit("@", maxsplit=1)
on urllib3 (included as dependency of requests) there is a `parse_url` which already splits auth items we used that on galaxy here: https://github.com/ansible/galaxy_ng/blob/master/galaxy_ng/app/common/proxy_url.py#L42

2021-03-04 01:34 UTC, rochacbruno commented on pulpcore/app/serializers/repository.py
>      proxy_url = serializers.CharField(
Any reason to not use a `URLField` ?

2021-03-04 01:34 UTC, rochacbruno commented on pulpcore/app/serializers/repository.py
> +    proxy_password = serializers.CharField(
adding `style={'input_type': 'password'}` makes the generated API UI form to replace chars with `***` on password.

2021-03-04 09:55 UTC, mdellweg commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +                auth, url = netloc.rsplit("@", maxsplit=1)
I was about to say, that i tested this migration up and down and i didn't want to touch it anymore if not needed. But i'll take a look. :+1:

2021-03-04 09:55 UTC, mdellweg commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +                pass
Interesting!

2021-03-04 10:08 UTC, mdellweg commented on pulpcore/app/migrations/0060_data_migration_proxy_creds.py
> +                auth, url = netloc.rsplit("@", maxsplit=1)
I do not see, that urllib3 is a dependency of pulpcore yet, so i'm going to stick with the standard library here.

2021-03-04 12:05 UTC, daviddavis commented on pulpcore/app/serializers/repository.py
>      proxy_url = serializers.CharField(
We've had problems in the past with `URLField`. Not sure if it's still an issue.

https://github.com/pulp/pulpcore/blob/0db2dcbb043cf6b00f93f0b661a25b1ba90fcd97/docs/plugins/reference/how-plugins-work.rst#serializer-and-openapi-schema

2021-03-04 15:28 UTC, mdellweg commented
See also: https://github.com/pulp/pulp-cli/pull/169

2021-03-05 15:42 UTC, daviddavis approved these changes

2021-03-05 15:44 UTC, bmbouter approved these changes
This looks great, thank you!

2021-03-05 15:44 UTC, merged

2021-03-11 16:38 UTC, rochacbruno commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
I think proxy_username and proxy_url was not meant to be `write_only`. Those 2 fields can return to the get request and only `proxy_password` are write only. @mdellweg

2021-03-11 16:45 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
`proxy_url` is readable. and with `proxy_username` i followed the example of `username`.

I think @daviddavis started there.

2021-03-11 17:47 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
This came from the original story as planned here: https://pulp.plan.io/issues/8202

It's debateable as to whether username and proxy_username are really sensitive, but as it stands now (for better or worse) they are considered sensitive.

@rochacbruno how does this affect your use of pulpcore? Can you share some insight into this debate either way?

2021-03-11 18:19 UTC, rochacbruno commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
@bmbouter for us it is ok, we can overwrite that property, I am also not sure if we consider usernames sensitive, I personally think that in terms of UX user will want to know which username is in use, what do you think @newswangerd ?

2021-03-11 18:39 UTC, bmbouter commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
If it's not causing a problem then I'm inclined to leave it redacted because since it's a subjective thing and security related I'd like to default the most secure option. In that case I think, if its in doubt, consider it sensitive. If it causes a practical problem though, let us know for sure.

2021-03-11 20:02 UTC, newswangerd commented on pulpcore/app/serializers/repository.py
> +        write_only=True,
@rochacbruno for our serializers I think we should leave usernames exposed. Users will want to know which account they've configured for authentication if they ever have to update a token or need to check permissions.