Add dynaconf nested value example
pulp/pulpcore pull request #1203
Opened 2021-03-22 20:01 UTC by dannysauer

Add an example of how to specify an array value and a dict key in the auth methods section (which is particularly useful for people using k8s).  Also expand/clarify a bit what the existing example is doing.

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-03-23 14:50 UTC, bmbouter requested changes
This docs change looks great. To merge it we'll need a changelog entry, and to have that we need an issue filed. File a short problem description [here](https://pulp.plan.io/issues/new) and add the 'Documentation' tag.

Then add a changelog entry to the CHANGES/XXXX.doc with the issue number.

Lastly, in your commit add `fixes #XXXX` so the automation will associate the two.

Let me know if you need any help. Sorry for all the steps We're working on simplifying our process, but it's not there yet.

Also we have docs on this here:  https://docs.pulpproject.org/pulpcore/contributing/git.html#commit-message

2021-04-06 14:26 UTC, daviddavis commented
@dannysauer ping. any chance you can fix ^ ?

2021-04-20 13:52 UTC, daviddavis commented
Closing this out due to inactivity. Please comment or reopen if you find time to work on this. Thanks.

2021-04-20 13:52 UTC, closed without merging

2021-04-29 21:32 UTC, dannysauer commented
Finally got Pulp into prod, so had time to create an account and fix this stuff up.  Sorry it took so long. :)