Allow plugins to unset attribute in NamedModelViewSet
pulp/pulpcore pull request #1205
Opened 2021-03-23 19:22 UTC by awcrosby

Allow plugins to set `queryset_filtering_required_permission` attribute to
`None` and have it behave the same way as if the attribute were not present.

fixes #8438
https://pulp.plan.io/issues/8438

2021-03-24 09:13 UTC, mdellweg commented on pulpcore/app/viewsets/base.py
> +                qs = get_objects_for_user(self.request.user, permission_name, klass=qs)
Can you replace the try - except - else structure here (L330) with
`getattr(self, "queryset_filtering_required_permission", None)`
That way, we can absorb the `AttributeError` in the `if permission_name` check.

2021-03-26 18:21 UTC, awcrosby commented on pulpcore/app/viewsets/base.py
> +                qs = get_objects_for_user(self.request.user, permission_name, klass=qs)
Thanks - updated.

2021-03-29 09:04 UTC, ipanova approved these changes

2021-03-29 09:13 UTC, mdellweg approved these changes

2021-03-29 09:14 UTC, mdellweg requested changes

2021-03-29 09:14 UTC, mdellweg commented on CHANGES/8438.bugfix
> +Allow plugins to unset attribute in NamedModelViewSet
Can this be moved to `CHANGES/plugin` ?

2021-03-29 09:14 UTC, mdellweg commented on CHANGES/8438.bugfix
> +Allow plugins to unset attribute in NamedModelViewSet
Sorry, didn't see this earlier.

2021-03-29 13:57 UTC, awcrosby commented on CHANGES/8438.bugfix
> +Allow plugins to unset attribute in NamedModelViewSet
No problem. I assume you meant ` CHANGES/plugin_api` as I didn't see ` CHANGES/plugin` listed in the docs, but if not just let me know.

2021-03-29 15:21 UTC, mdellweg approved these changes
Just one last suggestion to the changelog before merging.

2021-03-29 15:21 UTC, mdellweg commented on CHANGES/plugin_api/8438.bugfix
> +Allow plugins to unset attribute in NamedModelViewSet
```suggestion
Allow plugins to unset the ``queryset_filtering_required_permission`` attribute in ``NamedModelViewSet``.
```

2021-03-29 17:49 UTC, merged