Fix race condition in handling of reserved resources
pulp/pulpcore pull request #1228
Opened 2021-04-02 00:50 UTC by dralley

closes: #8352
https://pulp.plan.io/issues/8352

2021-04-02 00:52 UTC, dralley commented
@bmbouter This is only half of it, I think for the resource manager bits we may want to get on a call to discuss.  I made an attempt but the complexity of the code makes it quite difficult to put the ```select_for_update``` where it needs to go.

You can go ahead and review this portion though.

2021-04-05 20:47 UTC, daviddavis commented
The code looks good to me. I am going to try to test out/debug the code some tomorrow with some sleep statements so I can understand it a bit better.

2021-04-05 20:49 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        with transaction.atomic():
I'm about 70% certain we also need a ```select_for_update()``` here... however, apparently it doesn't get along with the ```distinct()``` on line 46.  Any ideas?  Or is it not necessary?

2021-04-06 03:09 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        with transaction.atomic():
The "simple" option might be to just ignore locking during `acquire_worker` and just drop a `worker = Worker.objects.select_for_update().get(pk=worker.pk)` on line 127.  I don't like the idea of querying twice but it would work.  And it might be "good enough" if we want a fast patch with minimal risk.

Would still like to do better though.

2021-04-06 14:21 UTC, fao89 commented
@cutwater

2021-04-07 00:32 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        with transaction.atomic():
I implemented ^

2021-04-07 12:32 UTC, cutwater requested changes

2021-04-07 12:32 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +        with transaction.atomic():
@dralley `select_for_update` is 100% needed here to prevent related tables (resource reservation) from modification if another transaction holds a lock. An alternative to double query can be rewriting the query on line 48 to eliminate DISTINCT. However as a workaround and immediate solution it is acceptable in my opinion.

2021-04-07 12:47 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
I wonder if this is still susceptible to a race condition? 

1. Worker is returned from `_acquire_worker()`
2. Worker is cleaned up
3. Worker is fetched here with `get()` and assigned reservations

2021-04-07 12:49 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
Good catch. Yes, it will. Here worker status is not checked.

2021-04-07 13:57 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
Alternatively, I believe this should work:

```
Worker.objects.select_for_update.filter(pk__in=Worker.objects.filter(reservations__resource__in=resources))
```

2021-04-07 15:00 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
Apart from this question, the rest looks good to me.

2021-04-07 15:02 UTC, dralley commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
@daviddavis Is this meant to go on line 132 or on line 48?  It has different semantics from line 48.

2021-04-07 15:08 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +                worker = Worker.objects.select_for_update().get(pk=worker.pk)
I think this could potentially work for line 48:

```python
return Worker.objects.select_for_update().filter(pk__in=Worker.objects.filter(reservations__resource__in=resources)).get()
```

2021-04-07 15:16 UTC, cutwater approved these changes
LGTM

2021-04-07 15:20 UTC, daviddavis approved these changes

2021-04-07 16:07 UTC, mdellweg approved these changes

2021-04-07 16:13 UTC, dralley commented
@daviddavis This change appears as though it might be causing deadlocks?  If I run the tests locally it hangs on the very first one.

2021-04-07 18:26 UTC, dralley commented
@cutwater @mdellweg Please re-review the last patch

2021-04-07 19:04 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        return Worker.objects.select_for_update().filter(pk__in=workers_qs_no_res).first()
I guess the selected worker isn't necessarily random anymore.

2021-04-07 19:11 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +        return Worker.objects.select_for_update().filter(pk__in=workers_qs_no_res).first()
Let's fix that. What if we did this:

```python
workers_qs_no_res = (
        workers_qs.annotate(models.Count("reservations"))
        .filter(reservations__count=0)
        .order_by("?")[0:1]
    )
```

2021-04-07 19:13 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +        return Worker.objects.select_for_update().filter(pk__in=workers_qs_no_res).first()
Actually I think this is better:

```suggestion
        return Worker.objects.select_for_update().filter(pk__in=workers_qs_no_res[0:1]).first()
```

2021-04-08 07:45 UTC, mdellweg approved these changes

2021-04-08 09:14 UTC, cutwater requested changes

2021-04-08 09:14 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    except IndexError:
If query fetches no rows, `.first()` will not throw `IndexError`, but return `None`

2021-04-08 13:11 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +    except IndexError:
There is no `limit()` method for queryset. You have to use `[0:1]`.

2021-04-08 13:37 UTC, dralley commented on pulpcore/tasking/tasks.py
> +    except IndexError:
Updated

2021-04-08 13:45 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    except IndexError:
@daviddavis `.get()` implies `LIMIT 1`, why `[0:1]` needed here?

2021-04-08 13:47 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +    except IndexError:
my experience says, that `get` raises the MultipleReturned exception.

2021-04-08 13:47 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    except IndexError:
Why do you want to get an exception here instead of simply checking `first()` return value?

2021-04-08 13:48 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    except IndexError:
Also `.get()` doesn't raise `IndexError`

2021-04-08 13:50 UTC, cutwater requested changes

2021-04-08 13:50 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +        raise Worker.model.DoesNotExist()
```suggestion
    # A randomly-selected Worker instance that has zero ReservedResource entries
    # associated with it.
    return (
        Worker.objects.select_for_update()
        .filter(pk__in=workers_qs_no_res)
        .order_by("?")[0:1]
        .get()
    )
```

2021-04-08 13:50 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    except IndexError:
@mdellweg yes, my bad. `.get()` raises MultipleReturned indeed.

2021-04-08 13:51 UTC, dralley commented on pulpcore/tasking/tasks.py
> +    except IndexError:
Early morning drowsiness :)  That's probably the simplest solution, I can do that.

2021-04-08 13:51 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +        raise Worker.model.DoesNotExist()
While this approach is offered by official Django docs, it looks odd.

2021-04-08 13:54 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        raise Worker.model.DoesNotExist()
@cutwater I went with your recommendation to just check the value of what is returned by `first()`

2021-04-08 13:57 UTC, daviddavis commented on pulpcore/tasking/tasks.py
> +        raise Worker.model.DoesNotExist()
Should this be `Worker.DoesNotExist()`?

2021-04-08 13:57 UTC, cutwater requested changes

2021-04-08 13:57 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +    if not worker:
Minor comment: I'd rather use an explicit check here
```if worker is not None```

2021-04-08 13:59 UTC, dralley commented on pulpcore/tasking/tasks.py
> +        raise Worker.model.DoesNotExist()
I think there's an alias - this is copied over so if it didn't work it would have broken before now.  But I'll change it anyway

2021-04-08 14:00 UTC, dralley commented on pulpcore/tasking/tasks.py
> +    if not worker:
Updated to `if worker is None`

2021-04-08 14:01 UTC, cutwater requested changes

2021-04-08 14:01 UTC, cutwater commented on pulpcore/tasking/tasks.py
> +        except (Worker.DoesNotExist, IntegrityError):
Having `break` statement at the end of the loop looks odd.

IMO this is more readable:

```

except (Worker.DoesNotExist, IntegrityError):
    # if worker is ready, or we have a worker but we can't create the reservations, wait
    time.sleep(0.25)
else:
    break
```

2021-04-08 14:03 UTC, cutwater commented on pulpcore/tasking/tasks.py
>              continue
I meant that `continue` is not needed here anymore.

2021-04-08 14:13 UTC, cutwater approved these changes
LGTM

2021-04-08 14:14 UTC, cutwater commented
@dralley Thank you for addressing my comments.

2021-04-08 14:17 UTC, daviddavis approved these changes

2021-04-08 14:22 UTC, dralley commented
CI failure looks unrelated

2021-04-08 14:53 UTC, merged

2021-04-08 14:54 UTC, dralley commented
@cutwater Merged.  Do you need a new build with this patch or do you plan to upgrade to 3.12?