Tasking system redesign
pulp/pulpcore pull request #1261
Opened 2021-04-16 11:34 UTC by mdellweg

This is supposed to be the successor of:
https://github.com/pulp/pulpcore/pull/1222

2021-04-16 11:47 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +        return json.JSONEncoder.default(self, obj)
```suggestion
    def default(self, obj):
        if isinstance(obj, uuid.UUID):
            deprecation_logger.warn(
                _(
                    "The argument {obj} is of type {type}, which is not JSON serializable. The use "
                    "of non JSON serializable objects for `args` and `kwargs` to tasks is "
                    "deprecated as of pulpcore==3.12. See the traceback below for more info."
                ).format(obj=obj, type=type(obj))
            )
            return str(obj)
        return json.JSONEncoder.default(self, obj)
```

Also we could just not warn about it and keep the conversion of UUIDs as a convenience to our plugin writers.

2021-04-16 11:48 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +    return int.from_bytes(_digest, byteorder='big', signed=True)
@bmbouter The signed here is probably what stopped your implementation from working.

2021-04-16 11:49 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +            required_resources.append(util.get_url(task))
I thought it might be a good idea to lock on the task too, because we are about to change its state.

2021-04-16 12:01 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +            required_locks = sorted((_hash_to_u64(resource) for resource in required_resources))
Actually, since we are using `pg_try_advisory_lock`, maybe there cannot be deadlocks anyway.

2021-04-16 12:04 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +    def perform_task(self, task):
Should we wrap this function into a Thread, or even subprocess to ensure memory cleanup and postgres session cleanup?

2021-04-16 12:46 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                parent_task=None,  # TODO implement me!
How is a parent task defined?
Can a parent task be considered finished before all child tasks are?

2021-04-22 13:47 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                    with AdvisoryLock(_task_lock(task)):
Would be nice if python had something like a ternary context manager, or an if with a finally.

2021-04-22 14:46 UTC, dralley commented on pulpcore/app/models/task.py
> +            resources required for the task.
How is the function (or path of the function) stored?

2021-04-22 14:47 UTC, dralley commented on pulpcore/tasking/tasks.py
> +                name=f"{func.__module__}.{func.__name__}",
Ah, stored here?

2021-04-22 16:29 UTC, mdellweg commented
There are still 2 tests failing. I think it is in the way, task_groups are handled. I could use some help.

2021-04-22 16:38 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +            required_resources.append(util.get_url(task))
After good discussions, we came to the conclusion, that:
1. It is absolutely necessary to lock on the task.
2. We don't even need to lock on the resources individually.
3. The task locks provide a nice way to identify abandoned tasks, that need cleanup.

2021-04-22 17:24 UTC, mdellweg commented on pulpcore/app/models/task.py
> +    required_resources = JSONField(null=True)
Should we make this an array field?
https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/fields/#django.contrib.postgres.fields.ArrayField

2021-04-26 16:32 UTC, mdellweg commented
Task canceling is not yet implemented. But there only seems to be one blinker test in the the cli part that is (sometimes) able to find that inability.

2021-04-26 16:45 UTC, dralley commented on pulpcore/tasking/worker.py
> +    def perform_task(self, task):
That's actually a good question.  My initial response is that it needs to be a subprocess, because things can go Badly Wrong (segfault, OOM killed, unexpected errors, memory leaks) and because we need a way to hard-kill it.

But I believe we have systemd auto-restart service turned on (or could do so, if we don't already), so if something goes Badly Wrong we could *possibly* just let the whole worker die and be respawned by systemd.  That might have further implications we would need to think through though.  We'd be churning the "online workers".

2021-04-26 16:53 UTC, dralley commented on pulpcore/tasking/tasks.py
> +                parent_task=None,  # TODO implement me!
parent task = if a task was spawned inside another task, that task is a child, and the task that spawned it is the parent

yes, parent can be marked finished before children.

2021-04-30 17:43 UTC, dralley commented on CHANGES/plugin_api/8501.removal
> +The usage of non-JSON serializable types of ``args`` and ``kwargs`` to tasks is no longer supported.
I would mention that `uuid.UUID` objects get automatically cast to strings.

2021-05-03 13:32 UTC, bmbouter commented on CHANGES/plugin_api/8501.removal
> +The usage of non-JSON serializable types of ``args`` and ``kwargs`` to tasks is no longer supported.
Oh yeah I think we wanted to remove that if we could, but I'm out of touch with what version that would be done. I couldn't do it when I made the original PoC at that point yet.

2021-05-04 12:14 UTC, mdellweg commented on CHANGES/plugin_api/8501.removal
> +The usage of non-JSON serializable types of ``args`` and ``kwargs`` to tasks is no longer supported.
The question is, whether we explicitly allow the automatic conversion of UUID because it makes the life of plugin writers easier, and we can provide the conversion without risk.

2021-05-06 10:40 UTC, ipanova commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
Pulp has a new experimental worker type, which if set to True, starts workers with the ``pulpcore-worker`` command. Defaults to ``False``.

2021-05-06 11:37 UTC, mdellweg commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
That is a good observation. What you describe would be ideal: The user changes the option and restarts pulp, and the startup scripts do the-right-thing (tm).
The reality however today, is that the duty of starting the right worker type is upon the user / the installer / the container setup / the <fill in your deployment mechanism>.
It is even worse today, because the "wrong type of worker" will fail to start up and the systemd files will respawn them infinitely.
I can start to work on the installer side right away, but the problem is that we can never assume, that we can cover _all_ deployments here.
I can however try to merge the old and the new type worker into a single entrypoint.

BTW The single container is already doing the-right-thing.

2021-05-06 13:07 UTC, ipanova commented on pulpcore/tasking/pulpcore_worker.py
> +    def superwise_task(self, task):
unless the task is really meant to be super wise i think it should be `supervise` :D

2021-05-06 13:15 UTC, ipanova commented on pulpcore/tasking/pulpcore_worker.py
> +        self.worker, created = Worker.objects.get_or_create(name=self.name)
Worker.objects.get_or_create(name=self.name)[0], i don't see `created` to be used anywhere

2021-05-06 13:15 UTC, bmbouter commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
That would be ideal, but we would have to have everyone switch to the new version since that is the long-lived one. That may be doable? Is this what you were thinking @mdellweg?

2021-05-06 13:27 UTC, ipanova commented on pulpcore/tasking/pulpcore_worker.py
> +    connection.connection = None
with all these connections opened should not we also close them?

2021-05-06 15:28 UTC, mdellweg commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
Well, we'd had a single entrypoint in pulpcore setup.py that loads either worker type. And we 'd need the deployments to switch to that entrypoint. Then switching is just a matter of the configuration.
Yes, i think this is doable.

2021-05-06 15:31 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    connection.connection = None
Closing them is the real problem. If you close the connection in the subprocess, the main process will complain that someone closed its connection (and the locks would be gone).
Forgetting about the connection in the subprocess seems to work. And they won't pile up, as it is always the same connection that is going to be forgotton in the subprocess.

2021-05-06 15:33 UTC, mdellweg commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
I'm not quite sure what to do with the resource-manager however.
If we just close the process, it will keep respawning.

2021-05-06 15:47 UTC, mdellweg commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
https://github.com/pulp/pulpcore/pull/1261/commits/c33214abf808cca7a0643a6c9a515fdb6572a018 is what i came up with so far. There are probably a bunch of rq config things more to consider.

2021-05-07 09:42 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +        self.worker, created = Worker.objects.get_or_create(name=self.name)
Maybe we should just call `self.beat()` here, anyway.

2021-05-07 09:45 UTC, mdellweg commented on pulpcore/tasking/worker_wrapper.py
> +            worker.work()
@dralley @bmbouter Maybe one of you knows, which set of configuration options we need to digests here.
Probably at least the ones from `pulpcore.rqconfig`?

2021-05-12 02:18 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +        )
Maybe we should do this in multiple steps, with locking?  Or is this covered by one of the `advisory_lock`s already.

```python
with transaction.atomic():
    tasks = Task.objects.filter(pk=task.pk, state=TASK_STATES.RUNNING)
    tasks.update(
        state=TASK_STATES.CANCELED
    )
    _delete_incomplete_resources(task)
    # .....
```

2021-05-12 02:19 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +    def cancel_abandoned_task(self, task):
Let's leave some comments for any methods that have an depend on external locks

2021-05-12 02:25 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +            ).order_by("pulp_created"):
Do we have an index on the date?  Otherwise this may be quite slow.

2021-05-12 02:31 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +                        continue
Could you explain the semantics above?  How do we know that there is no lock?  Do we really need the refresh, or can we avoid that race entirely with locking?

2021-05-12 07:21 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    def cancel_abandoned_task(self, task):
I'll see how it works out. I believe i factored it into a function, because the level of indentation went crazy.
Too many `try: with:`...
+1 to stating the locking explicitly.

2021-05-12 07:25 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                        continue
If you are referring to the refresh i am thinking, yes we need it. Another process could have done the cleanup and released the lock already before we got it. And at that point, we have outdated data.

The logic here is: We have the lock for that task, and it is in "running" state, but we are not running it, so the process that was supposed to run that task must have died (and thereby released the lock prematurely).

2021-05-17 08:09 UTC, mdellweg commented on docs/settings.rst
> +    Pulp has a new experimental worker type which is startable with the ``pulpcore-worker`` command. If
We have the new worker entrypoint in master now.

2021-05-17 08:10 UTC, mdellweg commented on pulpcore/tasking/worker_wrapper.py
> +            worker.work()
That code is merged with another PR now.

2021-05-17 08:45 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    def cancel_abandoned_task(self, task):
On a second thought, i like this function as a way to structure the higher level concept of looping over tasks from handling a single task.

2021-06-02 19:30 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in Task.objects.all():
`.iterator()`

2021-06-02 19:32 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
I presume we decided against using more specialized data types like `ArrayField` and `HStoreField`?

2021-06-02 19:35 UTC, bmbouter commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
I prefer JSON for two reasons:
1) json is always save, e.g. never pickle
2) it encourages plugin writers to pass simple data types instead of potentially reusing an object it fetched at dispatch time.

2021-06-02 19:43 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
I'm not sure I understand either of these, could you elaborate a bit?

2021-06-02 19:43 UTC, bmbouter commented on pulpcore/app/serializers/task.py
> +    required_resources = serializers.ListField(
Maybe this is right, but this part is unexpected to me. When I view task output now I get:

```
    "reserved_resources_record": [
      "/pulp/api/v3/repositories/file/file/06f4a9bd-94c7-4a9d-8e5f-f82945a48dfa/",
      "/pulp/api/v3/remotes/file/file/3d033c12-c6fa-4e84-a501-db2cdb96d42c/"
    ],
    "required_resources": [
      "/pulp/api/v3/repositories/file/file/06f4a9bd-94c7-4a9d-8e5f-f82945a48dfa/",
      "/pulp/api/v3/remotes/file/file/3d033c12-c6fa-4e84-a501-db2cdb96d42c/"
    ]
```

Why introduce a new field to store the same info as `reserved_resources_record` ?

2021-06-02 19:44 UTC, bmbouter commented on pulpcore/app/tasks/importer.py
> +    current_task.refresh_from_db()
Why do we need to call `refresh_from_db()` pattern when we call `task.update(...)` ?

2021-06-02 19:46 UTC, bmbouter commented on pulpcore/tasking/entrypoint.py
> +        from pulpcore.tasking.pulpcore_worker import NewPulpWorker
Is moving this to the imports at the top an option? I suspect it's not but wanted to ask.

2021-06-02 19:51 UTC, bmbouter commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
Sure, in Celery and Pulp2 we had an issue where the tasking system would allow complex types as arguments. The concern was that pickled objects could allow for arbitrary code execution. The solution was to switch to using JSON serializers.

The second one is a similar problem, only instead of a security concern it's a stale-data concern where plugin writers could pass an instance of an object they got from the db instead of the pk for the task to then look it up. With JSON they can only pass python primatives.

I'm not sure what typing is allowed for storage in `ArrayField` and `HStoreField` but I know JSON is safe and only allows Python primitives.

2021-06-02 19:51 UTC, dralley commented on pulpcore/app/serializers/task.py
> +    required_resources = serializers.ListField(
I agree that we can probably avoid this.

Delete `ReservedResourcesSerializer`, replace it with a method that either gets the arraylist or joins the reserved resources depending on which worker mode Pulp is in.  And then use either a `JsonField` or a `ListField` to display the `List[str]`

2021-06-02 20:09 UTC, bmbouter commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
Can you clarify for me once more what an abandoned task is?

2021-06-02 20:17 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
>Sure, in Celery and Pulp2 we had an issue where the tasking system would allow complex types as arguments. The concern was that pickled objects could allow for arbitrary code execution. The solution was to switch to using JSON serializers.

I think for Postgresql though, that isn't an issue.  To the best of my knowledge Django ArrayField and HStoreField don't do any pickling, at least, I couldn't find any in their implementations.

I think the answer is "Python primitives + any datatype that has a SQL type"

2021-06-02 20:19 UTC, bmbouter commented on pulpcore/tasking/pulpcore_worker.py
> +        with TemporaryDirectory(dir="."):
I verified this was `/var/lib/pulp/tmp/104579@pulp3-source-fedora34.localhost.example.com`. Nice.

2021-06-02 20:23 UTC, bmbouter commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
The concern with pickling was when data being passing as args/kwargs is untrusted.

Cases like `ArrayField[Artifact]` are what I want us to prevent, that's basically the second concern. Plugin writers shouldn't pass around instances they got from the db because things change in the db, e.g. imagine passing an Artifact and then orphan cleanup happens.

2021-06-02 20:24 UTC, bmbouter commented on pulpcore/tasking/util.py
> +                cursor.execute("SELECT pg_notify('pulp_worker_cancel', %s)", (str(task.pk),))
To confirm my understanding, this wakes up all workers right?

2021-06-02 20:27 UTC, bmbouter requested changes
Overall this is looking great. I asked a few informational questions. The one thing I think we need to change is the removal of the new serializer field.

Also I tested this locally and it worked great! It's really, really nice!

2021-06-02 20:27 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
@bmbouter It doesn't pass instances though, it passes `artifact[pk]`, and instantiates it on the other end.  As far as I can tell it is the same thing as passing the PK doing it manually.

2021-06-02 20:32 UTC, bmbouter commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
What is better about doing it with those other more complex types? Will it work with multi-table inheritance? The benefits of using JSON are simplicity (anyone who knows Python can understand it), and explicitness re-lookup up the data explicitly makes the tasking code very clear.

2021-06-02 20:38 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
HStoreField is string-to-string only, no complex data types.

https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/fields/#django.contrib.postgres.fields.HStoreField

ArrayField only takes subclasses of `Field`, so `CharField`, `IntField`, etc.  So, not arbitrary models, unless you custom-define one.

2021-06-02 21:35 UTC, dralley commented on pulpcore/app/models/task.py
> +        Task.objects.filter(pk=self.pk).update(
Do we not want to apply the same check from [here](https://github.com/pulp/pulpcore/pull/1261/files#diff-b6921076eabe69f8f887286bbac04f5abb8c91b5e2e747b99ea932c5abf17135R367) to avoid setting an already-completed task as failed?

2021-06-02 22:07 UTC, dralley commented on pulpcore/app/tasks/importer.py
> +    current_task.refresh_from_db()
I think it's just being defensive about `current_task` having the correct state.

However it doesn't look like `current_task` is used again, so maybe that isn't necessary.

2021-06-02 22:12 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
Presumably a task that says it is still running, but actually is not.

I'm not sure if this is actually specific to "abandoned" tasks though, it seems like it would generically cancel any task.  In which case maybe it should be named as such?  (we do need to avoid name collisions with older functions however).

2021-06-03 00:56 UTC, dralley commented
I was able to get a fairly repeatable hang with this script. The second task gets stuck in "waiting" and remains that way after 5 minutes.  I'm not 100% sure but I don't *think* it blocks other tasks from completing, so that's nice.

```bash
export BASE_ADDR=http://localhost:24817


http POST $BASE_ADDR/pulp/api/v3/remotes/file/file/ name=foo$I url=bar
export REMOTE_HREF=$(http $BASE_ADDR/pulp/api/v3/remotes/file/file/ | jq -r '.results[0] | .pulp_href')

sudo systemctl stop pulpcore-worker@1 pulpcore-worker@2

http PATCH :$REMOTE_HREF name=test$RANDOM
sudo systemctl restart postgresql

sudo systemctl start pulpcore-worker@1 pulpcore-worker@2

# this task will be stuck forever
http PATCH :$REMOTE_HREF name=test$RANDOM
```

2021-06-03 01:46 UTC, dralley commented on docs/components.rst
> +increasing the number of worker processes. Each worker can handle on task at a time, and idle
typo: s/on/one

2021-06-03 02:51 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +                        resource in taken_resources for resource in task.required_resources or []
I would split the `task.required_resources or []` onto a separate line, it feels like a little bit too much going on

2021-06-03 03:15 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +                with suppress(AdvisoryLockError), task:
I'm not sure I like how implicit these codepaths are.

`task` is used as a context manager and potentially throws an `AdvisoryLockError`, which we deliberately suppress.  If it does throw an `AdvisoryLockError`, what happens?

* I ***think*** it acts like a `try: ...... except: pass``` and just moves on to the next iteration of the loop, but that took a fair amount of time and reading of the `contextlib` documentation.

2021-06-03 03:25 UTC, dralley commented on pulpcore/tasking/util.py
> +            time.sleep(0.5)
I'm not sure if we still need the `time.sleep(0.5)` or not, that was an RQ hack.

Also does the TODO above need to be addressed still?

2021-06-03 03:27 UTC, dralley commented on pulpcore/tasking/util.py
> +class AdvisoryLock:
It looks like `Task` just copied and pasted this implementation, maybe we should subclass instead

2021-06-03 03:33 UTC, dralley commented
@mdellweg Excellent work!  I'm overall very impressed.  I left a few comments, most are minor, and one relatively small bug that I was able to find.

2021-06-04 17:18 UTC, bmbouter commented
This error was reported on IRC by wibbit. He says he see's it in the logs several times:

```
Internal Server Error: /pulp/api/v3/tasks/c142ca54-6490-4a07-85d5-a90f96ee1c49/
Traceback (most recent call last):
  File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bats/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/bats/lib/python3.8/site-packages/pulpcore/app/viewsets/base.py", line 301, in initial
    super().initial(request, *args, **kwargs)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 26, in has_permission
    return self._evaluate_statements(statements, request, view, action)
  File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 62, in _evaluate_statements
    matched = self._get_statements_matching_context_conditions(
  File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 181, in _get_statements_matching_context_conditions
    passed = bool(boolExpr.parseString(condition)[0])
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1710, in _parseNoCache
    tokens = fn(instring, tokensStart, retTokens)
  File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1316, in wrapper
    ret = func(*args[limit[0]:])
TypeError: __init__() missing 1 required positional argument: 't'
```

2021-06-07 10:36 UTC, mdellweg commented
> This error was reported on IRC by wibbit. He says he see's it in the log below several times.

Looking at the traceback, i believe the real error might be hidden inside the `raise_uncaught_exception`, while the trace we see is then in turn produced by a failure to parse an access policy. We may need to fix the latter to see the former.

2021-06-07 10:39 UTC, mdellweg commented on pulpcore/tasking/util.py
> +                cursor.execute("SELECT pg_notify('pulp_worker_cancel', %s)", (str(task.pk),))
This is not waking up any workers, but notifying all workers, that are currently listening to the "pulp_worker_cancel" channel. All workers whose task.pk does not match will ignore the message.
Workers is sleep state (without a task) will not listen here.

2021-06-07 10:42 UTC, mdellweg commented on pulpcore/tasking/entrypoint.py
> +        from pulpcore.tasking.pulpcore_worker import NewPulpWorker
I put it here to match with the rather voluminous imports of "all the rq libraries".
As this is really a diverting wrapper to call into other code depending on a condition, i thought it was wise to import this other code late/lazy.

2021-06-07 10:44 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in Task.objects.all():
Do you mean this?
```suggestion
    for task in Task.objects.iterator():
```

2021-06-07 10:51 UTC, mdellweg commented on pulpcore/app/serializers/task.py
> +    required_resources = serializers.ListField(
The old name did not quite match the purpose for the new use. And yes, i didn't want to change the old code too much.
At this point, i would be confident to completely remove the `ReservedResourceRecord` model in favour of the new HSTORE field.
Is the complaint that the data is shown twice in the task output? Should we stick to the old name only? I guess, out side the internal tasking code it is still a "record of used resources".

2021-06-07 10:57 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +    current_task.refresh_from_db()
Maybe i should have used `save` with `update_fields`.
I only learned about it later. But it is crucial to not save all of the task, because it's state is managed elsewhere.
Thinking about it, i remember that the original problem was that the call to save its state as final removed the task_group again. So this change was in line to be consistent about only changing relevant rows.

2021-06-07 11:01 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
An abandoned task is is `state=running`, but no worker is holding it's lock.
So the line of reasoning here is:
I am a worker. While looping tasks, i got the lock for this one. It claims to be running, which cannot be true (another worker would hold the lock). Therefore i am on the hook to cancel it.

2021-06-07 11:05 UTC, mdellweg commented
> **edit:** I might have accidentally been using the old tasking system? `pulpcore-worker` was printing RQ logs despite my `settings.py` being correct. Not sure if I'm doing something improperly.

@dralley Are you sure, your systemd scripts use the new entry points?

2021-06-07 11:22 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in Task.objects.all():
Yes

2021-06-07 11:22 UTC, mdellweg commented on pulpcore/tasking/util.py
> +class AdvisoryLock:
Actually, this class isn't used anywhere. I just didn't want it to go to waste, when i folded it into the task.
I'll remove it.

2021-06-07 11:34 UTC, mdellweg commented on pulpcore/tasking/util.py
> +            time.sleep(0.5)
The time sleep is there to give the notified worker some time to cancel the task.
The TODO means, there is a slight chance, that a cancel request might not cancel the task because a worker is evaluating this task for pickup atm. And i do not how likely that is to happen, nor how to solve it without checking the cancelled state later. We could state that cancel (in the rest api) is fire and forget, and the user needs to check whether it succeeded.
Another solution might involve a new task state `TO_BE_CANCELLED` that can be set from `RUNNING` or `WAITING` without having the lock.

2021-06-07 11:42 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                with suppress(AdvisoryLockError), task:
That is exactly it. I was looking for a combined version of `if` and `with` but no luck.
The exception ensures, that the block inside will only run _with_ the lock in place. But we don't have rescue code. And i think suppress is the pythonic way for this case.
I will add a comment.

2021-06-07 12:27 UTC, mdellweg commented on pulpcore/app/models/task.py
> +        Task.objects.filter(pk=self.pk).update(
I'll add it. However, only the worker that is working on that task will ever want to set it to failed.

2021-06-07 12:59 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
An inline comment would be good here as well

2021-06-07 12:59 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
Does this mean that a worker can only clean up its own tasks?

2021-06-07 13:24 UTC, dralley commented
>@dralley Are you sure, your systemd scripts use the new entry points?

I think the problem is that the documentation doesn't make it clear that the installer needs to be re-run / the service files edited.  It just says

> To switch to using this worker model, one needs to set ``USE_NEW_WORKER_STYLE=True`` in pulp
settings, and start the worker processes via ``pulpcore-worker``.

> ...

> If ``True``, the ``pulpcore-worker`` command will start workers of the new type.  If ``False``
    it will chainload into the traditional ``rq`` based system.  Also the ``pulpcore-api``
    processes will dispatch their tasks accordingly.  When changing this value, all ``pulpcore``
    (at least api and worker) processes must be restarted.

2021-06-07 15:02 UTC, bmbouter commented on pulpcore/tasking/util.py
> +            time.sleep(0.5)
I think it's ok if it's fire-and-foreget if there is guaranteed eventual consistency. So my question is: design wise, how can we ensure 100% of cancel requests eventually cancel? Is that in place with this design or is there more/alternate work needed?

2021-06-07 15:05 UTC, bmbouter commented
[idea] What do you think about making a "performance" test that fires say 500 tasks and ensures they all run to completion without error? I suggest this because it seems like a) it would be easy and b) it would be helpful in sanity checking the correctness.

I say performance because I think we do not want this to run as part of the normal "functional" tests which run with every PR.

@mdellweg and @dralley wdyt?

2021-06-07 15:06 UTC, bmbouter commented on pulpcore/tasking/util.py
> +                cursor.execute("SELECT pg_notify('pulp_worker_cancel', %s)", (str(task.pk),))
Great, ty

2021-06-07 15:06 UTC, bmbouter commented on pulpcore/app/tasks/importer.py
> +    current_task.refresh_from_db()
Personally I think using `update_fields` would be much better. This pattern does concern me slightly. Not a whole lot, but some.

2021-06-07 15:08 UTC, bmbouter commented on pulpcore/app/serializers/task.py
> +    required_resources = serializers.ListField(
I think we should stick to the old name, but have it use the new implementation. I don't see a motivation to change this part of the API, even with an additive change. The `reserved_resources_record` is still pretty easy.

2021-06-07 15:09 UTC, dralley commented
I agree, although I would actually try to have more of a "tasking torture test suite" than just a set of performance tests.  We could of course do both.

2021-06-07 15:10 UTC, mdellweg commented on pulpcore/tasking/util.py
> +            time.sleep(0.5)
No it isnt. ATM it tries to cancel the task right away (holding its lock). If impossible, it sends a signal on the cancel channel. But that will only be heard if some worker is listening for it, or put another way, handling that task.
But the lock could have been held by a worker just to realize the task is not ready yet. And if you try to cancel in that exact timeframe, nothing will happen.
I need to brainstorm a little more what options we do have.

2021-06-07 15:13 UTC, bmbouter commented
> I agree, although I would actually try to have more of a "tasking torture test suite" than just a set of performance tests. We could of course do both.

+1 to this. this is roughly what I was trying to express also.

2021-06-07 15:15 UTC, dralley commented
BTW my idea of what this would be would include things like "restart postgresql mid-task" as the script I posted earlier does.

2021-06-07 16:16 UTC, wibbit commented
> This error was reported on IRC by wibbit. He says he see's it in the log below several times.
> 
> The only pulp code here is `File "/opt/bats/lib/python3.8/site-packages/pulpcore/app/viewsets/base.py", line 301, in initial` and I that likely is in the WSGI layer, but the ISE gives a pulp task endpoint, so that's confusing. Also wibbit reported that for this task when he later requested it, it gave him a 404...
> 
> Perhaps it's failing in the task itself, but very early??
> 
> ```
> Internal Server Error: /pulp/api/v3/tasks/c142ca54-6490-4a07-85d5-a90f96ee1c49/
> Traceback (most recent call last):
>   File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/opt/bats/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/opt/bats/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
>     self.initial(request, *args, **kwargs)
>   File "/opt/bats/lib/python3.8/site-packages/pulpcore/app/viewsets/base.py", line 301, in initial
>     super().initial(request, *args, **kwargs)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
>     self.check_permissions(request)
>   File "/opt/bats/lib/python3.8/site-packages/rest_framework/views.py", line 332, in check_permissions
>     if not permission.has_permission(request, self):
>   File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 26, in has_permission
>     return self._evaluate_statements(statements, request, view, action)
>   File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 62, in _evaluate_statements
>     matched = self._get_statements_matching_context_conditions(
>   File "/opt/bats/lib/python3.8/site-packages/rest_access_policy/access_policy.py", line 181, in _get_statements_matching_context_conditions
>     passed = bool(boolExpr.parseString(condition)[0])
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1937, in parseString
>     loc, tokens = self._parse(instring, 0)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
>     return self.expr._parse(instring, loc, doActions, callPreParse=False)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
>     return self.expr._parse(instring, loc, doActions, callPreParse=False)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
>     ret = e._parse(instring, loc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
>     return self.expr._parse(instring, loc, doActions, callPreParse=False)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
>     ret = e._parse(instring, loc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4445, in parseImpl
>     return self.expr._parse(instring, loc, doActions, callPreParse=False)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1677, in _parseNoCache
>     loc, tokens = self.parseImpl(instring, preloc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 4237, in parseImpl
>     ret = e._parse(instring, loc, doActions)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1710, in _parseNoCache
>     tokens = fn(instring, tokensStart, retTokens)
>   File "/opt/bats/lib/python3.8/site-packages/pyparsing.py", line 1316, in wrapper
>     ret = func(*args[limit[0]:])
> TypeError: __init__() missing 1 required positional argument: 't'
> ```

I think this can be traced back to my trying the use of Threads for the gunicorn process as opposed to Processes.

I can 100% cause the error when I have threads configured, however, when threads are not configured, and I use processes, (3 * 15 threads v's 45) I am not able to replicate the issue.

So I think this at least can be ignored (unless of course you expect to be able to use threads :)

2021-06-08 08:58 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
Yes and no. When a worker is shut down, it closes its postgres connection (or eventually it times out). So the advisory lock will vanish. That is what an abandoned task is all about.
The next worker looking for tasks will see this task, get it's lock (only now we can consider it to own that task), and clean it up. That way, we can ensure that only one worker will try to clean up that task.
If that worker is killed while cleaning up, the next worker coming at this task will continue.

2021-06-08 09:09 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +        """Cancel and clean up an abandoned task.
Having said that, the next worker will see the task being cancelled in the current implementation, so it won't be cleaned up.
Maybe we should first mark the task as cancelling and only when nicely cleaned up set it to cancelled.
That mechanism may solve the other problem identified in the TODO of the cancel call too.

2021-06-08 09:24 UTC, mdellweg commented
> > @dralley Are you sure, your systemd scripts use the new entry points?
> 
> I think the problem is that the documentation doesn't make it clear that the installer needs to be re-run / the service files edited. It just says
> 
> > To switch to using this worker model, one needs to set `USE_NEW_WORKER_STYLE=True` in pulp
> > settings, and start the worker processes via `pulpcore-worker`.
> 
> > ...
> 
> > If `True`, the `pulpcore-worker` command will start workers of the new type.  If `False`
> > it will chainload into the traditional `rq` based system.  Also the `pulpcore-api`
> > processes will dispatch their tasks accordingly.  When changing this value, all `pulpcore`
> > (at least api and worker) processes must be restarted.
> 
> So I didn't touch my services apart from changing settings.py and restarting them

I'm not sure this is an issue here. If we expect the change to come in the next version of pulpcore, we can expect the installer to be rerun. (actually that change will already be rolled out with the current version of pulpcore, and it's installer). On the other hand, for manual installations, it is covered by the docs already. What we do not have at all is instructions to update a manual installation. The best hint there is the entry in the changelog.

2021-06-08 15:43 UTC, mdellweg commented
To sum up the current state as i see it, we have two discussion points left:
1. Cancelling tasks is (at least theoretically) slightly probablistic.
2. We don not have good tests to torture the (new or old) tasking system.

While i'm happy to sort out the former in this PR (with the help of some good discussion), i'd love to state that the latter is probably out of scope for this PR, because we might want its not limited to this new feature.

2021-06-08 15:51 UTC, bmbouter commented
> To sum up the current state as i see it, we have two discussion points left:
> 
>     1. Cancelling tasks is (at least theoretically) slightly probablistic.
> 
>     2. We don not have good tests to torture the (new or old) tasking system.
> 
> 
> While i'm happy to sort out the former in this PR (with the help of some good discussion), i'd love to state that the latter is probably out of scope for this PR, because we might want its not limited to this new feature.
> WDYT: @dralley @bmbouter

I agree with this approach. Have this PR handle cancellation correctly (let us know what we can do to help that along), and have another PR add a test that tortures the tasking system while restarting workers.

2021-06-08 15:53 UTC, dralley commented
>What we do not have at all is instructions to update a manual installation. The best hint there is the entry in the changelog.

I think we need this, because the default is to use the old tasking system.  Users need to know that if they want to upgrade and then try the new tasking system briefly, it is not as simple as just doing what is described in the docs.  They need to re-run the installer any time they switch back and forth.

2021-06-08 15:57 UTC, mdellweg commented
> > What we do not have at all is instructions to update a manual installation. The best hint there is the entry in the changelog.
> 
> I think we need this, because the default is to use the old tasking system. Users need to know that if they want to upgrade and then try the new tasking system briefly, it is not as simple as just doing what is described in the docs. They need to re-run the installer any time they switch back and forth.

They don't need to. Starting from 3.13 all workers should be started with the new entrypoint. That's the very reason why we introduced it. It can merely be seen as a legacy convenience, that calling rq still works.

2021-06-08 16:19 UTC, dralley commented
Ok, I believe I understand now.  The problem is just that my development environment in particular was out of date and needed to be recreated.

2021-06-08 16:20 UTC, dralley commented
I agree that the test suite is out of scope for this PR

2021-06-08 18:42 UTC, dralley commented on pulpcore/app/serializers/task.py
> +    reserved_resources_record = serializers.ListField(
`ListField` should have a `child` defined ideally https://www.django-rest-framework.org/api-guide/fields/#listfield

2021-06-09 10:08 UTC, mdellweg commented on pulpcore/app/serializers/task.py
> +    reserved_resources_record = serializers.ListField(
I added it. And then realized, that we use this serializer read only. But it's better this way.

2021-06-09 18:35 UTC, mdellweg commented
> I have a naive thought about cancellation. Perhaps this is maybe already how it works, but here's the idea. What if:
> 
>     1. Setting the task state to cancelled occurred atomically in the webserver's cancel view
> 
>     2. The worker was notified to wakeup and if it's processing that task ID just stop doing so

That's almost what i was thinking. However i thought, the api-worker can set the task to cancelling regardless of any locks (but only from waiting or running), and then send the notify in case any worker is performing that task. And the next worker to get the lock for the task will first attempt to clean up the unfinished created resources, and on success set the state to the final cancelled.
When a worker is trying to start working on the task, it will be unable to set it from cancelling to running, and otoh, if it will transition it from waiting to running, it will already listen for the cancel channel. And if a worker is killed mid-cleanup, the next one will finish the process.

2021-06-10 16:02 UTC, dralley commented
Given wibbit's seal of approval after testing at scale, the number of the issues with the old system, and the recommendations we're already willing to provide to Katello, perhaps we should consider providing the new tasking system as the default with the ability to easily fall back to the old system?

2021-06-11 18:29 UTC, dralley approved these changes

2021-06-11 18:51 UTC, bmbouter approved these changes
I took another look through this, and I think it's good to go. @mdellweg please squash the commits before merging.

2021-06-12 12:25 UTC, mdellweg commented
@bmbouter The two commits i intend to quash are labeled with "Adds new worker type" and "Introduce new task state canceling".
And if you insist, i could also squash "Delete unused code `mark_worker_online`" and "Activate new worker style in subset of tests", but i want to keep "Add orphan cleanup stop gap in pulpcore-worker" separate, as i think it can eventually be reverted cleanly.

2021-06-14 14:55 UTC, merged