Fix pulp export creation task dispatching
pulp/pulpcore pull request #1263
Opened 2021-04-19 11:56 UTC by mdellweg

[noissue]

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-04-19 12:19 UTC, ggainey requested changes
A minor nit and an observation, but generally looks good to me! Thanks for doing the work!

2021-04-19 12:19 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +        validated_data (dict): serializer output
I don't see validated_data in the args list

2021-04-19 12:19 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +    serializer.is_valid(raise_exception=True)
With this change, we validate the data twice - once at the viewset, so we can return errors quickly, and then again in the task, so we can use the resulting validated data. I don't think this is a huge issue - but it does double the db-accesses for this path. Not sure there's anything to be done about it, given the constraints that drive this change though.

2021-04-19 12:22 UTC, mdellweg commented on pulpcore/app/tasks/export.py
> +        validated_data (dict): serializer output
right (it was there for a brief moment...)

2021-04-19 12:25 UTC, mdellweg commented on pulpcore/app/tasks/export.py
> +    serializer.is_valid(raise_exception=True)
Yes. But my view is, that both validations can be separated by a significant amount of time. And the circumstances might even make once valid data invalid at the point the task is ready to start. So we really should validate it there.

2021-04-19 12:27 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +    serializer.is_valid(raise_exception=True)
That's a good observation, concur.

2021-04-19 15:03 UTC, ggainey approved these changes

2021-04-20 09:54 UTC, ipanova approved these changes

2021-04-20 18:06 UTC, daviddavis approved these changes

2021-04-21 07:41 UTC, merged