Update signing docs
pulp/pulpcore pull request #1269
Opened 2021-04-21 16:27 UTC by mdellweg

Please look at the two commits separately.

In the second one i added a service command to produce a AsciiArmoredSigningService, but i don't know it it is ready for consumption, as it is not yet able to create e.g. a pulp_deb provided one.

2021-04-21 16:32 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +    TODO extend this command to create any type of signing service.
How are we supposed to specify them?

2021-04-21 17:36 UTC, ipanova commented on docs/workflows/signed-metadata.rst
> +0. Make sure, the service user ``pulp`` has access to ``gpg`` and that the keypair is
if it is not a big of a trouble, can we start numbering of the steps/instructions with `1`?

2021-04-21 17:38 UTC, ipanova commented on docs/workflows/signed-metadata.rst
> +   .. note::
is it worth mentioning that this command is in tech-preview since it's a new one?

2021-04-22 09:33 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
> +0. Make sure, the service user ``pulp`` has access to ``gpg`` and that the keypair is
Sure. I am thinking about turning this into a precondition.

2021-04-22 09:33 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
> +   .. note::
Good call.

2021-04-26 18:16 UTC, ggainey requested changes
A few minor nits. The only thing I really need to see, is calling out add-signing-service in towncrier. Looks good otherwise!

2021-04-26 18:16 UTC, ggainey commented on CHANGES/8609.doc
> +Updated signing service workflow. Removed old deprecation warning.
Need to call out the new add-signing-service in towncrier. That kind of mixes a feature into this .doc - do we switch to .feature? I'm not sure what the right thing to do is here. At a minimum, need to call out the new function.

2021-04-26 18:16 UTC, ggainey commented on docs/workflows/signed-metadata.rst
> +1. Make sure, the service user ``pulp`` has access to ``gpg`` and that the keypair is
Lose the comma.

2021-04-26 18:16 UTC, ggainey commented on docs/workflows/signed-metadata.rst
> +   hardware cryptografic device.
cryptographic

2021-04-27 14:23 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
> +   hardware cryptografic device.
:man_facepalming:

2021-05-05 16:45 UTC, ggainey approved these changes
shippit :)

2021-05-12 17:41 UTC, bmbouter commented on CHANGES/8609.doc
> +Updated signing service workflow. Removed old deprecation warning.
This seems right to me. If there is a doc part to the work, it gets `.doc` in addition to the other `.feature` part.

2021-05-12 17:43 UTC, bmbouter approved these changes
This looks right to me. Thanks!

2021-05-13 10:20 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        print(fingerprint)
did you mean to print this? if yes maybe make the message a bit more user friendly?

2021-05-13 10:22 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +            "key-id",
so I always get conflicted with dash or underscores, I see in other management command uderscore used instead. Should we switch to it as well, for consistency? https://github.com/pulp/pulpcore/blob/master/pulpcore/app/management/commands/stage-profile-summary.py#L17

2021-05-13 10:23 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        SigningService.objects.create(
can use here get_or_create? If this command will be run twice in a row, create() will fail.

2021-05-13 10:26 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        script_path = Path(script).resolve(strict=True)
how about catching FileNotFound error?

2021-05-13 10:37 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        app_label, service_class = options["class"].split(":")
maybe too defensive, but maybe worth adding validation here, that signign service was provided in the expected format separated by `:`, also note that this  option is not required

2021-05-13 10:37 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        SigningService = apps.get_model(app_label, service_class)
i would catch a lookup error here :)

2021-05-13 13:15 UTC, bmbouter commented on pulpcore/app/management/commands/add-signing-service.py
> +            "key-id",
+1 for underscores. In looking at `pulpcore-manager` output underscores seem most common. In another PR maybe we should switch the stage-profile-summary which is still tech preview also.

2021-05-14 09:48 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +        print(fingerprint)
Only for debugging purposes.

2021-05-14 09:51 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +            "key-id",
You know what? I'll scrap the id part altogether.

2021-05-14 09:54 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +        SigningService.objects.create(
I'm conflicted here, because signing services have unique names. And if the service does exist, it is immutable, so with a get_or_create i will not necessarily get what i ask for.
However, i can improve the error reporting here.

2021-05-14 10:06 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +        app_label, service_class = options["class"].split(":")
It has a default value, so it will always be present.
I'll add some validation to tell the user what went wrong.

2021-05-14 10:50 UTC, ipanova commented on pulpcore/app/management/commands/add-signing-service.py
> +        app_label, service_class = options["class"].split(":")
you're right, i have not noticed the `default`

2021-05-17 07:53 UTC, mdellweg commented on pulpcore/app/management/commands/add-signing-service.py
> +            "key-id",
It is the key you reference, and it can be the fingerprint, last 8 or 16 digits of it, or part of the user id on the key (if unambiguous).

2021-05-17 09:17 UTC, ipanova approved these changes
Thank you for addressing all the comments!

2021-05-17 09:48 UTC, merged