Convert UUID to str() for new tasking API
pulp/pulpcore pull request #1270
Opened 2021-04-21 20:14 UTC by dralley

[noissue]

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-04-21 20:19 UTC, daviddavis approved these changes

2021-04-21 20:24 UTC, ipanova commented
@dralley there are more of the instances in out codepath that need this change https://github.com/pulp/pulpcore/blob/master/pulpcore/plugin/actions.py#L57 I suggest doing git grep dispatch and inspect the results.

2021-04-21 20:33 UTC, dralley commented
@ipanova +1

2021-04-21 21:19 UTC, ipanova requested changes
Can you also update the example in the docs?`docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst`

A bit more things to go through ;)
$ git grep 'dispatch('
docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst:            result = dispatch(
pulpcore/app/tasks/importer.py:                dispatch(
pulpcore/app/views/orphans.py:        task = dispatch(orphan_cleanup, [])
pulpcore/app/views/repair.py:        task = dispatch(repair_all_artifacts, [], args=[verify_checksums])
pulpcore/app/viewsets/base.py:        task = dispatch(
pulpcore/app/viewsets/base.py:        task = dispatch(
pulpcore/app/viewsets/base.py:        task = dispatch(
pulpcore/app/viewsets/exporter.py:        task = dispatch(
pulpcore/app/viewsets/importer.py:        task = dispatch(
pulpcore/app/viewsets/repository.py:        task = dispatch(
pulpcore/app/viewsets/repository.py:        task = dispatch(
pulpcore/app/viewsets/upload.py:        task = dispatch(tasks.upload.commit, [upload], args=(upload.pk, sha256))
pulpcore/plugin/actions.py:        task = dispatch(
pulpcore/plugin/viewsets/content.py:        task = dispatch(
pulpcore/plugin/viewsets/content.py:        task = dispatch(
pulpcore/tasking/tasks.py:def dispatch(func, resources, args=None, kwargs=None, task_group=None):

2021-04-21 21:22 UTC, dralley commented
@ipanova Yeah, I've been looking, I wasn't done just then :)  I just pushed the ones you suggested immediately.  The docs suggestion is good, I will do that.

2021-04-21 21:25 UTC, ipanova commented
> @ipanova Yeah, I've been looking, I wasn't done just then :) I just pushed the ones you suggested immediately. The docs suggestion is good, I will do that.

sorry, it was not clear whether you are done pushing or not ;) >.>

2021-04-22 09:20 UTC, mdellweg commented
Actually, i think we could spare a lot of churn if we just tell our json serializer how to handle UUID. We have it all over the place.

2021-04-22 13:14 UTC, dralley commented
@mdellweg Fair.  So you basically just want to un-deprecate that one particular case?

2021-04-22 14:01 UTC, mdellweg commented
I'm currently using this version of the JSON serializer, and i think it works quite nicely with the tasking POC.

https://github.com/pulp/pulpcore/pull/1261/files#diff-5305e94381b5ae9dbdef02048b0f1838270a6f5626a51ab6df03f3087631ddc1R235-R246

It's just so much more convenient to simply accept the PK field. And we know that it can only be UUID or int, right?

2021-05-10 16:22 UTC, closed without merging