Stabilize URLs before generating redirects
pulp/pulpcore pull request #1295
Opened 2021-04-29 22:44 UTC by dannysauer

The aio URL object mangles query strings when they're passed in. Specifically, it unescapes http entities which are escaped but which don't need escaped.  This is normally ok, but in the case of signed CloudFront URLs, changing anything about the URL invalidates the signature, including the querystring.  By pre-creating a yarl.URL object before raising the redirect exception, the parsing doesn't happen in aiohttp.  Passing in the "encoding=True" stops the reparsing when the object is created.

Fixes #8670
Relates to #1294, and boto/botocore#2363

2021-05-05 14:50 UTC, dannysauer commented
I'll do the squash and force-push after confirming that there aren't more linter changes. :)

2021-05-07 15:57 UTC, dannysauer commented
Do I need to add yarl to the setup.py, since it's not directly included from Pulp anywhere else?  It's an implicit dependency already pulled in via aiohttp.  I don't think any specific version would be required, since URL has been in Yarl since The Beginning.

2021-05-10 07:46 UTC, mdellweg commented on CHANGES/8670.bugfix
> +Pre-create Yarl.URL object before raising redirect when S3 or Azure storage backends are used, preventing html entinty re-encoding or decoding with signed URLs
For changelogs, we try to describe the problem, that was solved (as it would be interesting to the end user) in past tense. Ideally an admin would be able to recognize his failure in the bugfix section.
The how is more likely to be in the commit message (do not change that one, it's perfect).
So probably something like "Added URL querystring normalization for redirected signed cloud storage URLs to prevent invalidating the signature."

2021-05-11 19:38 UTC, dkliban commented
'

> @dkliban I was told the other way around for click yesterday. And i opt for explicit.

@dannysauer Let's be explicit and add it as a requirement. All the code changes look good to me.

2021-06-01 13:05 UTC, dkliban commented
@dannysauer How are these changes coming along?

2021-06-01 13:18 UTC, dannysauer commented
> @dannysauer How are these changes coming along?

Forgotten about. 😂 Thanks for the reminder.

2021-06-08 15:27 UTC, dannysauer commented
Finally got around to rebasing, integrating the changelog suggestion, and adding `yarl` to the requirements.txt.

2021-06-08 16:13 UTC, dralley requested changes

2021-06-08 16:13 UTC, dralley commented on requirements.txt
> +yarl>1.0.0
Use `yarl~=1.0.0` so that we don't pick up any new major versions.

2021-06-08 16:15 UTC, dralley approved these changes
I changed my mind, we probably don't need to be too selective about the Yarl version since as you mentioned `URL()` is fairly stable.

2021-06-08 22:22 UTC, dannysauer commented
> I changed my mind, we probably don't need to be too selective about the Yarl version since as you mentioned `URL()` is fairly stable.

I went back-and-forth on that, and figured it made more sense to just call out the minimum stable version. I'm [using 1.6.3](https://github.com/Kong/docker-pulp/blob/011ee381713ce44476eec8f5e24bc644d62c4d52/pulp-core/requirements.txt#L92) in our Docker container, for what that's worth.

2021-06-15 13:11 UTC, dkliban approved these changes
The upgrade tests failed because the test was bad. We've fixed the test since the CI ran on this PR. I am going to merge this change. Thank you for the contribution!

2021-06-15 13:12 UTC, merged