Add a remove-plugin command
pulp/pulpcore pull request #1434
Opened 2021-06-22 18:42 UTC by goosemania

closes #7822
https://pulp.plan.io/issues/7822

2021-06-22 18:54 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +          - all default access policies are in core_accesspolicy, can be identified by view_name?
Any thought/ideas are welcome

2021-06-22 18:54 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
This causes an unexpected problem. Any thoughts are welcome.
Setup: 
 - have pulp_rpm and pulp_file
 - remove pulp_rpm
 - removal of pulp_file fails due to relations(?) to the pulp_rpm models (I suspect some django smartness combined with master-detail models)

Here how the failure looks:
```$ pulpcore-manager remove-plugin file
pulp [None]: pulp_2to3_migration.app.plugin:INFO: Plugin pulp_deb is not installed in pulp3 therefore it will not be migrated from pulp2
Checking if Pulp services are running, it can take up to 30s...
Cleaning up the database for file plugin...
Removing model: <class 'pulp_file.app.models.FileContent'>
Removing model: <class 'pulp_file.app.models.FileRemote'>
Traceback (most recent call last):
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "rpm_rpmrepository" does not exist
LINE 1: ...heck", "rpm_rpmrepository"."sqlite_metadata" FROM "rpm_rpmre...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/pulp/bin/pulpcore-manager", line 33, in <module>
    sys.exit(load_entry_point('pulpcore', 'console_scripts', 'pulpcore-manager')())
  File "/home/vagrant/devel/pulpcore/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/devel/pulpcore/pulpcore/app/management/commands/remove-plugin.py", line 133, in handle
    self._remove_plugin_data(app_label=plugin_name)
  File "/home/vagrant/devel/pulpcore/pulpcore/app/management/commands/remove-plugin.py", line 51, in _remove_plugin_data
    model.objects.filter().delete()
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/query.py", line 710, in delete
    collector.collect(del_query)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/deletion.py", line 223, in collect
    elif sub_objs:
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "rpm_rpmrepository" does not exist
LINE 1: ...heck", "rpm_rpmrepository"."sqlite_metadata" FROM "rpm_rpmre...

```

The same happens if you try to remove any FileRemote instance when rpm plugin is removed/uninstalled.
If you look at FileRemote instance, it has some managers/relations/attributes available which has rpm in it.
```
In [4]: dir(my_file_remote_instance)

Out[4]:
[...
 'remote_ptr',
 'remote_ptr_id',
 'remoteartifact_set',
 'repository_set',
 'rpm_rpmremote',
 'rpm_rpmrepository',
 'rpm_ulnremote',
...]
```
This happened when I tried to remove one plugin after another without uninstalling python package. Need to test if it's still teh case with python package installed.

2021-06-22 19:07 UTC, dralley commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
Does it still happen post-restart?

2021-06-23 08:27 UTC, mdellweg commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
I think you either need to pip uninstall the plugin or find a way to stop pulpcore from autoloading it after it was "removed".

2021-06-23 10:11 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
I'm not sure it is safe to pip uninstall, what if it was an rpm install?

2021-06-23 11:10 UTC, mdellweg commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
right then it should be a rpm uninstall accordingly.
What i meant is, that you'd need to get the source files out of the system, or a way for pulp to not consider loading them.

2021-06-25 16:50 UTC, goosemania commented
@bmbouter , @mdellweg , @dralley , could you provide feedback for the approach in general?
I'm waiting on it to proceed with implementing and polishing the details. 
It would be helpful to get feedback today or early next week, since next week is the last one before my pto and it would be good to wrap this work up to the extent possible.
It's not critical though but if you have time, I'd appreciate it.

2021-06-25 16:55 UTC, mdellweg commented on pulpcore/app/management/commands/remove-plugin.py
> +        while models_to_delete and len(models_to_delete) < prev_model_count:
The greedy algorithm ;)

2021-06-25 16:59 UTC, mdellweg commented
Yes, i can see this approach going forward.

2021-07-02 16:03 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +            call_command("migrate", app_label=app_label, migration_name="zero", fake=True)
nice

2021-07-02 16:04 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +        available_plugins = {app.label for app in pulp_plugin_configs()} - {"core"}
This could also raise a `CommandError` above here if `"core"`.

2021-07-02 16:06 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +        while is_pulp_running and time.time() - check_started < waiting_time:
nice

2021-07-02 16:06 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +                    "Please stop the services."
Maybe identifying the services by name would be helpful here? Just a thought.

2021-07-02 16:12 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +          - all default access policies are in core_accesspolicy, can be identified by view_name?
I think it can search through all the viewsets similar to how this code does it: https://github.com/pulp/pulpcore/blob/master/pulpcore/app/apps.py#L204-L218 Roughly the idea is to find the `viewset_name` and then call delete on the `AccessPolicy`. Let me know if I can give more info here.

2021-07-02 16:12 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +        TODO:
Is the plan to resolve all of these before merging?

2021-07-02 16:13 UTC, bmbouter commented
Overall this seems like the most reasonable/feasible approach. Thank you for putting this together!

2021-07-02 16:34 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +        TODO:
Definitely

2021-07-02 19:20 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +        waiting_time = max(settings.CONTENT_APP_TTL, settings.WORKER_TTL)
A note for myself. Settings are optional(?).

```
$ pulpcore-manager remove-plugin rpm
pulp: pulp_2to3_migration.app.plugin:INFO: Plugin pulp_deb is not installed in pulp3 therefore it will not be migrated from pulp2
System check identified some issues:

WARNINGS:
?: (guardian.W001) Guardian authentication backend is not hooked. You can add this in settings as eg: `AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend')`.
Traceback (most recent call last):
  File "/bin/pulpcore-manager", line 11, in <module>
    load_entry_point('pulpcore==3.7.6', 'console_scripts', 'pulpcore-manager')()
  File "/usr/lib/python3.6/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/pulpcore/app/management/commands/remove-plugin.py", line 118, in handle
    waiting_time = max(settings.CONTENT_APP_TTL, settings.WORKER_TTL)
  File "/usr/lib/python3.6/site-packages/dynaconf/base.py", line 164, in __getattr__
    value = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'WORKER_TTL'
```

2021-07-02 19:24 UTC, bmbouter commented on pulpcore/app/management/commands/remove-plugin.py
> +        waiting_time = max(settings.CONTENT_APP_TTL, settings.WORKER_TTL)
They got introduced later, in newer versions they'll always be there https://github.com/pulp/pulpcore/blob/master/pulpcore/app/settings.py#L230 (maybe this was already obvious).

2021-07-02 19:35 UTC, goosemania commented
In my test, it took ~55 sec to remove RPM plugin with the following amount of migrated data to Pulp3:
> db.units_erratum.count()
4680
> db.units_rpm.count()
13608
> db.repos.count()
1209

On the same system, removing pulp-2to3-migration took ~35 sec.

This doesn't look like a large system, I'd say it's a small one.
What is the acceptable downtime for removing a plugin?

I doubt people will remove rpm plugin, but still, it feels like the system can be down for minutes.
Any thoughts? @bmbouter @dralley  @mdellweg 
Should we require services to be down or can we do some pre-work to require shutting them down later or for a short period of time?
E.g. disable plugin somehow and restart the services, then can safely remove in the background.

2021-11-08 19:08 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +                    model.objects.filter().delete()
I can't do any uninstallation because I do not know how it was installed and I might not have the right perms. User needs to uninstall the plugin themselves.
I seem not to be able to reproduce this problem anymore, it might be that now when all the proper cleanup is happening, it's no longer a problem. I'll keep an eye on it though.

2021-11-09 10:38 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +                    "Please stop the services."
I'm going to list all services,  even if not all of them are running, would that work for you? not sure what is the best way to check if pulpcore-api is running without requiring bindings to be installed (to make an api request and see if it works) or without using `ps`.

2021-11-09 17:24 UTC, goosemania commented on pulpcore/app/apps.py
> +            _populate_access_policies, sender=self, dispatch_uid="populate_access_policy"
I thought I'd give this identifier a more meaningful name since I use it. Let me know if there was a purpose to keep it vague.

2021-11-09 17:28 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +        except (IrreversibleError, Exception):
The intention here is to show that it was mostly for irreversible errors but actually any exception needs to be handled so user do not end up with a non-atomic migration half-applied/unaplied and have no easy way out.
There is no need to have 2 exceptions listed here from the programming point of view. Let me know if it's less confusing to keep a general `Exception` only.

2021-11-09 17:29 UTC, goosemania commented
This awaits a test to be written, other than that it is ready for review.

2021-11-10 12:38 UTC, mdellweg commented on pulpcore/app/apps.py
> +            _populate_access_policies, sender=self, dispatch_uid="populate_access_policy"
No. It was copied from the django example, i think.

2021-11-10 12:42 UTC, mdellweg commented on pulpcore/app/management/commands/remove-plugin.py
> +            post_migrate.disconnect(sender=app_config, dispatch_uid="populate_access_policy")
Do you think instead of disconnecting we could try to make the signal handler look for some indicator (existing table, ..., ???) and actually remove the stale access_policies from db?

2021-11-11 11:01 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +            post_migrate.disconnect(sender=app_config, dispatch_uid="populate_access_policy")
That's a good idea if we have a reliable way to identify those

2021-11-11 11:18 UTC, mdellweg commented on pulpcore/app/management/commands/remove-plugin.py
> +            post_migrate.disconnect(sender=app_config, dispatch_uid="populate_access_policy")
I tried to find an easy way to see it the applied migration was the last one for the plugin. No luck yet.

2021-11-17 18:50 UTC, goosemania commented
Awaits the Roles PR in order to address roles removal.
LOCKED_ROLES related to a plugin should be removed, the rest should not be touched.
Documentation should be clear that custom roles will lose any permissions which belong to the removed plugin. In the extreme case it is possible that the custom role will remain but have no permissions. It's a responsibility of a user to deal with that.

2021-12-16 22:16 UTC, goosemania commented
> Awaits the Roles PR in order to address roles removal. LOCKED_ROLES related to a plugin should be removed, the rest should not be touched. Documentation should be clear that custom roles will lose any permissions which belong to the removed plugin. In the extreme case it is possible that the custom role will remain but have no permissions. It's a responsibility of a user to deal with that.

Awaits roles usage in container plugin to be able to test against.

2022-02-07 13:03 UTC, goosemania commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    )
I have this weird plugin removal test where I'm removing a plugin, then adding it back, and then I'd like to run a test to check that the plugin is functional.
I would like to reuse an existing test and so far I do not see a good way to do it.
If I use fixtures and I pass them as parameters to my test, the records in the db are created before I removed the plugin (aka cleaned the db), so by the time I'd like to call the existing test, my fixtures data is outdated, it would be good to force it to be recreated again. Is there a way? The smallest scope is a test itself, and I need to recreate it within a test :/

As a hack, I was thinking to split the test into multiple ones and enforce the order with [a pytest hook](https://docs.pytest.org/en/6.2.x/_modules/_pytest/hookspec.html#pytest_collection_modifyitems) but it's so hacky that I have not even tried to do that.

This plugin removal test needs to go into every plugin, so I thought to add it to the plugin template, leaving it for a plugin writer to decide which test(s) they want to run after the plugin is installed back. So it would be good to have this PR/test as a showcase for other plugins.

Any thoughts or ideas? @bmbouter @mdellweg

2022-02-07 13:07 UTC, goosemania commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    # call_command("migrate", "file")
leftovers, needs to be removed

2022-02-07 19:05 UTC, bmbouter commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    from pulpcore.tests.functional.api.using_plugin.test_sync import test_http_sync_no_ssl
I think if you `from foo import x as y` and it didn't start with `test_` I believe it would not be collected.

2022-02-07 19:06 UTC, bmbouter commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    sleep(2)
Do we have a utility to monitor via the status API when pulp is functional? That would be ideal. If not maybe we make one? It would be a nice pytest fixture for pulp-smash. Not required in this PR tho.

2022-02-07 19:10 UTC, bmbouter commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    )
I'm a little unclear on if the code here is working and you are looking for a better way or if this is not working at all. Also when you say "the records in the db are created before...." what records are these?

2022-02-08 02:36 UTC, dralley commented on pulpcore/app/management/commands/remove-plugin.py
> +        "Destructive! [tech-preview]"
Suggestion: put `[tech-preview]` first

2022-02-08 02:41 UTC, dralley commented on pulpcore/app/management/commands/remove-plugin.py
> +        while is_pulp_running and time.time() - check_started < waiting_time:
Can we clarify the order of operations with `()`?

2022-02-08 04:51 UTC, dralley commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    pulp_services = ("pulpcore-content", "pulpcore-api", "pulpcore-worker@1", "pulpcore-worker@2")
This feels like something we ought to have a utility for enumerating

2022-02-08 04:56 UTC, dralley commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    sleep(2)
+1, although the bindings might make it easy enough to get by without?  I haven't seen an example of it, our tests don't use it https://github.com/pulp/pulpcore/blob/main/pulpcore/tests/functional/api/test_status.py

2022-02-08 08:42 UTC, goosemania commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    )
> "the records in the db are created before...."

Fixture data is generated at the beginning of the test `test_remove_plugin`, e.g. a file repo with uuid XXXX is created in the db. By the time I'm trying to execute the test `test_http_sync_no_ssl`, I've already removed and installed back the plugin, so there are no db records for that plugin. At the same time fixture data is not regenerated, it is cached and outdated, so `test_http_sync_no_ssl` fails because it can't find a file repo which the fixture provides.

2022-02-08 08:45 UTC, goosemania commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    )
@bmbouter , fyi, @mdellweg  and I had [a discussion on matrix](https://matrix.to/#/!aVApiNMtnstWbwDcVU:matrix.org/$9bKEdSbYbIBSvZYcWin5dY5CyAp6Wvi3-vVL4JVIA4M?via=libera.chat&via=matrix.org&via=x9c4.spdns.org) that the test looks like it's following a pattern close to the upgrade one, and we might need to have something similar for this test.

2022-02-11 16:21 UTC, goosemania commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    pulp_services = ("pulpcore-content", "pulpcore-api", "pulpcore-worker@1", "pulpcore-worker@2")
could you elaborate?

2022-02-11 18:14 UTC, dralley commented on pulpcore/tests/functional/management/using_plugin/test_remove_plugin.py
> +    pulp_services = ("pulpcore-content", "pulpcore-api", "pulpcore-worker@1", "pulpcore-worker@2")
I mean we have potentially many pulpcore-workers and we want to start and stop all of them, this makes the assumption that the installation only has two.  If we can't use a wildcard to start / stop all worker services, we should probably enumerate them somehow.

I don't consider this a blocking issue though.

2022-02-22 09:45 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_remove_plugin.py
> +cli = smash_cli.Client(cfg)
We have session fixtures for these now. ;)

https://github.com/pulp/pulp-smash/blob/main/pulp_smash/pulp3/pytest_plugin/__init__.py#L246

2022-02-22 13:56 UTC, mdellweg approved these changes

2022-02-22 14:30 UTC, dralley requested changes

2022-02-22 14:30 UTC, dralley commented on docs/workflows/plugin-removal.rst
> +  * a plugin is no longer need
s/need/needed

2022-02-22 14:30 UTC, dralley commented on pulpcore/app/apps.py
> -            dispatch_uid="polulate_access_policies_identifier",
Is this a separate issue that needs to be backported?  Or would we want to backport this whole feature.

2022-02-22 14:30 UTC, dralley commented on pulpcore/app/management/commands/remove-plugin.py
> +        AccessPolicy.objects.filter(viewset_name__in=viewset_names, customized=False).delete()
I'm not familiar with AccessPolicy, what happens with `customized=True`?

2022-02-22 15:43 UTC, goosemania commented on pulpcore/app/management/commands/remove-plugin.py
> +        AccessPolicy.objects.filter(viewset_name__in=viewset_names, customized=False).delete()
`customized=True` is set for access policies created by users, we are not touching them, it's their business to deal with them.

2022-02-22 15:46 UTC, mdellweg commented on pulpcore/app/apps.py
> -            dispatch_uid="polulate_access_policies_identifier",
It was an identifier with and without the typo. ;)

2022-02-22 15:46 UTC, dralley commented on pulpcore/app/apps.py
> -            dispatch_uid="polulate_access_policies_identifier",
+1

2022-02-22 15:47 UTC, goosemania commented on docs/workflows/plugin-removal.rst
> +  * a plugin is no longer need
pushing

2022-02-22 15:50 UTC, dralley approved these changes

2022-02-22 16:31 UTC, merged

2022-02-28 18:38 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_remove_plugin.py
> +def test_remove_plugin(
I'm really happy with how this turned out. Thanks!