Reclaim disk space story.
pulp/pulpcore pull request #1452
Opened 2021-07-01 13:37 UTC by ipanova

closes #8459

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-07-01 13:44 UTC, ipanova commented on pulpcore/app/viewsets/reclaim.py
> +            repos,
initial story was about reclaiming disk space only on for a set of repos. Is it worth adding reclaim disk space for *all* the repos? In that case this task should probably be a blocking one.

2021-07-02 10:21 UTC, mdellweg commented on pulpcore/app/viewsets/reclaim.py
> +            repos,
I'd say, we don't want any globally locking tasks.

2021-07-16 15:55 UTC, ipanova commented on pulpcore/app/tasks/reclaim_space.py
> +        pk__in=artifacts_before
this was an attempt for optimization in case there would be tons of orphaned artifacts not really related to this operation they would be removed together with this call and it would take more time

2021-07-17 03:11 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +Pulp provides some feature for reclaiming disk space for:
"some" feels like a typo, maybe rwrite as "Pulp provides the ability to reclaim disk space for"?

2021-07-17 03:12 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +  * content that one no longer needs to serve but wants to keep it in the repo for historical
Same with "wants"

2021-07-17 03:15 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    stored files and free disk space if these packages are unlikely to be used again.
It would be a neat idea (for the future) to let a user configure this to be done automatically for old repository versions after a new one is created.

2021-07-17 03:18 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    removed because content set will not change.
Rewriting this slightly:

> Artifacts that are exclusive to the list of provided repos. The content of the repository versions will not change and no repository versions will be created or removed.

2021-07-17 03:18 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +  * willingly, a ``epo_versions_keeplist`` option can be specified that will contain list of
Typo, "epo_versions_keeplist"

2021-07-17 03:20 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    ``repo_version_hrefs`` which will be excluded from Artifact removal.
"repo_version_hrefs" doesn't look like it's a parameter and it's not a resource type, maybe it should be "repo version ``href``s?

2021-07-17 03:38 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
Typo "cosumable"

I'm conflicted about this because `RemoteArtifact` is a very low-level detail and not something that we should expect users to know or care about.  But the risk of corruption makes it important, which feels like a major red flag.

Is a `force` flag a hard requirement?  Do we expect users to have a critical need to be able to delete content for which there is no longer any remote?

If it's not, I would be more comfortable leaving it out.  Or considering implementing something like [method 1d](https://hackmd.io/_3gsUVdyQwy50Nc5pMXN-g) to prevent the entire issue.

2021-07-17 03:41 UTC, dralley commented on pulpcore/app/serializers/reclaim.py
> +    )
A neat idea (for the future - not now) would be to let a user configure this to be done automatically for old repository versions after a new one is created.

2021-07-17 03:52 UTC, dralley commented on pulpcore/app/serializers/reclaim.py
> +            hrefs_to_return.append(NamedModelViewSet.get_resource(href, Repository))
If this is called with hundreds or thousands of repo hrefs it might be a problem https://pulp.plan.io/issues/7483

But it's less likely to be a big issue then it was with content, where often tens of thousands were being passed at a time.

2021-07-17 03:57 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +        Artifact.objects.filter(content_memberships__isnull=True).values_list("pk", flat=True)
If this is only being used once (on line 35), I would recommend not casting it to a list, and not using `values_list`.  Django can just fold it into the query on line 35 and avoid two separate queries where it has to move the results over to Python and then back.

2021-07-17 03:59 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +    for ca in ca_qs:
`.iterator()`

2021-07-17 15:48 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +        c_reclaim_qs = set(c_reclaim_qs).difference(rv_content)
Can this be done without casting to a set?

2021-07-17 15:52 UTC, dralley commented on pulpcore/app/viewsets/reclaim.py
> +        force = serializer.validated_data.get("force", False)
I don't recall if there was an actual reason why we do this, but the RPM Copy Serializer does all of the business logic validation (checking that the hrefs are valid and exist) in the viewset (here) rather than the serializer.

This isn't a suggestion at all, I'm just pointing it out.

2021-07-19 11:05 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
automation hub needs a way to reclaim disk space for content that has been uploaded https://hackmd.io/e78_-T2rQRWvXaGjHT6Kyw#First-workflow-container-where-versions-are-kept-for-history

2021-07-19 11:08 UTC, ipanova commented on pulpcore/app/tasks/reclaim_space.py
> +        Artifact.objects.filter(content_memberships__isnull=True).values_list("pk", flat=True)
i actually need to evaluate the query here and register the results because if i don't do it then on line 35 when it will be evaluated it will have different results since between lines 12 and 35 i'm actually creating more orphan artifacts.

2021-07-19 14:06 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
Then we really need to make sure that it fails as gracefully as possible if purged content is attempted to be downloaded.

2021-07-19 14:08 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +        Artifact.objects.filter(content_memberships__isnull=True).values_list("pk", flat=True)
Could the order of lines 32 and 35 be swapped?

2021-07-19 16:52 UTC, daviddavis commented on CHANGES/8459.feature
> +As a user I want to reclaim disk space for a list of repositories.
```suggestion
Added feature to reclaim disk space for a list of repositories.
```

2021-07-19 16:52 UTC, daviddavis commented on docs/workflows/reclaim-disk-space.rst
> +    Pulp reclaim disk space feature are in tech-preview and may change in backwards incompatible
```suggestion
    Pulp's reclaim disk space feature is in tech-preview and may change in backwards incompatible
```

2021-07-19 16:53 UTC, daviddavis commented on docs/workflows/reclaim-disk-space.rst
> +    purpose.
```suggestion
  * content that one no longer needs to serve but would like to keep in the repo for historical reasons
```

2021-07-19 16:55 UTC, daviddavis commented on docs/workflows/reclaim-disk-space.rst
> +As a result of this request disk space will be freed-up for:
```suggestion
As a result of this request, disk space will be freed-up for:
```

2021-07-19 16:56 UTC, daviddavis commented on docs/workflows/reclaim-disk-space.rst
> +  * willingly, a ``repo_versions_keeplist`` option can be specified that will contain list of repo
```suggestion
  * an optional ``repo_versions_keeplist`` option can be specified that will contain list of repo
```

2021-07-19 16:59 UTC, daviddavis commented on docs/workflows/reclaim-disk-space.rst
> +  The task will trim Artifacts regardless of the download policy. Content app would be able to stream artifact if it is locally available, otherwise with the help of RemoteArtifact (if available) it
Does trim here mean delete?

```suggestion
The task will clean up Artifacts regardless of the download policy. The content app will be able to
stream artifact if it is locally available, otherwise using the RemoteArtifact (if available), it
will download artifact from the remote source.
```

2021-07-19 17:06 UTC, daviddavis commented on pulpcore/app/viewsets/reclaim.py
> +        force = serializer.validated_data.get("force", False)
Yea, I think probably the RPM code ought to be updated to perform its validation in a serializer.

2021-07-19 17:18 UTC, daviddavis commented on pulpcore/app/tasks/reclaim_space.py
> +        pk__in=artifacts_before
It seems to me that this could be problematic. Won't this clean up orphan artifacts that got created after `artifacts_before` got set?

2021-07-20 13:17 UTC, ipanova commented on pulpcore/app/tasks/reclaim_space.py
> +        pk__in=artifacts_before
yes it will :/  is your suggestion to directly collect the artifact pks as a loop throug the ca_qs?

2021-07-20 13:18 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
that's a good point, i will need to look into this and confirm

2021-07-20 13:19 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +  The task will trim Artifacts regardless of the download policy. Content app would be able to stream artifact if it is locally available, otherwise with the help of RemoteArtifact (if available) it
yes

2021-07-20 13:20 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
https://pulp.plan.io/issues/8305 is probably a good place to write the results

2021-07-20 13:24 UTC, daviddavis commented on pulpcore/app/tasks/reclaim_space.py
> +        pk__in=artifacts_before
That's my thought. Any downsides to that?

2021-07-20 14:17 UTC, ipanova commented on pulpcore/app/tasks/reclaim_space.py
> +        pk__in=artifacts_before
i guess none, just did not cross my mind earlier since this idea with optimization of orphaned artifacts just gave me tunnel vision :D

2021-07-20 15:08 UTC, ipanova commented on pulpcore/app/tasks/reclaim_space.py
> +        Artifact.objects.filter(content_memberships__isnull=True).values_list("pk", flat=True)
i have removed this completely and replaced with https://github.com/pulp/pulpcore/pull/1452#discussion_r673113048

2021-07-20 16:47 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
I have not manually tested rpm plugin yet,  but skimmed through pulpcore code - plugins that use directly pulp's content app handler, should be able to gracefully handle this. Uploaded content will have artifact set to none as well it won't have any remoteartifacts so a 404 will just be raised https://github.com/pulp/pulpcore/blob/master/pulpcore/content/handler.py#L681.
Since pulp-container has a subclassed version of handler, i needed to modify couple of lines which led to this output:
```
$ podman pull localhost:24817/test/repo --tls-verify=false
Trying to pull localhost:24817/test/repo:latest...
Error: Error initializing source docker://localhost:24817/test/repo:latest: Error reading manifest latest in localhost:24817/test/repo: StatusCode: 404, 404: Not Found
(pulp) [vagrant@pulp3-source-fedora34 ~]$ 
```

tldr, i think we're fine just need to audit plugins that subclass the Handler.

2021-07-21 02:31 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-consumable content afterwards.
I still feel like we shouldn't need to explain `RemoteArtifacts` to the user -- and probably the `--force` option should have some kind of high-visibility note or warning box to call out the potential for things to go wrong.  We can make it available but the user should understand that it's something they really really shouldn't do unless they know what they are doing.

2021-07-21 02:41 UTC, dralley requested changes

2021-07-21 02:41 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +  * by default, the task will remove only those Artifacts that have a corresponding RemoteArtifact.
I think the two bullet points about the `--force` option should be in a separate paragraph from the rest (or maybe in a "note" box) for visibility.  Alternatively we should use a big "warning" box such as the one on this page: https://docs.pulpproject.org/pulpcore/workflows/repairing-pulp.html

We can make it available but it should be clear that the user should never use this option without understanding the full implications.  I still think that needing to explain low-level details such as `RemoteArtifact` is a red flag and a usability problem.

We should also call out that if the content cannot be guaranteed to be / stay available at the remote source, either due to changes at the remote source or changes to the remote configuration.

2021-07-21 15:06 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +  * by default, the task will remove only those Artifacts that have a corresponding RemoteArtifact.
@dralley i tried to re-word couple of things is this is more user friendly and we don't talk about low-level stuff such ass 'remote artifact'. Let me know if that looks better to you and if i need to make any further adjustments.

2021-07-21 15:12 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +known upstream urls. In case upstream stopped serving the corresponding file , Pulp won't be able to
Extra space before the comma

2021-07-21 15:14 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +   the known upstream urls. In case upstream stopped serving the corresponding file , Pulp won't be
Extra space before the comma

2021-07-21 15:16 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    into Pulp.
The meaning of this isn't totally clear, do you mean content that is already part of a repository version?

2021-07-21 15:17 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
@ipanova Do you think it would be reasonable to prevent content with no Artifact and no RemoteArtifact from being added to new repository versions via one of the validation hooks?

2021-07-21 15:18 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    into Pulp.
i mean content that was synchronized in pulp. there are just 2 ways how to get content into pulp - you whether upload it or synchronize it.

2021-07-21 15:23 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    into Pulp.
I think it would make more sense to reverse it, i.e. "by default, the task will *not* remove artifacts from content that were uploaded directly into Pulp"

2021-07-21 15:26 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
don't we fall into the same category of the issue we have with the removal of remote, remoteartifacts are being removed as well? in case it was an on_demand content the ca will not have either artifact nor remoteartifact?

2021-07-21 15:33 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
what i am trying to say is whatether we'd decide to do with such content that does not have RA and artifact it should be done in a separate PR after figuring out what to do with https://hackmd.io/_3gsUVdyQwy50Nc5pMXN-g
but yeah, you've opened the pandora box here by asking this question :D

2021-07-21 15:35 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
@ipanova I think it can be left for #8305, as long as we actually address #8305 soon :)

2021-07-21 15:36 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
#soon

2021-07-21 15:37 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
i have added a comment to that issue with your proposal of the validation hooks so it can be discussed whenever relevant.

2021-07-21 17:22 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    This, however, will lead to a non-cosumable content afterwards.
Would you mind filing an issue to do that?

2021-07-21 17:23 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +    be specified. This, however, will lead to a non-consumable content afterwards.
Thanks!

2021-07-22 10:16 UTC, ipanova commented on docs/workflows/reclaim-disk-space.rst
> +    into Pulp.
sure, if this is more readable i'll update.

2021-07-22 19:55 UTC, daviddavis commented on pulpcore/app/tasks/reclaim_space.py
> +    # respect timestamp when it will be added
Is this is a reference to `timestamp_of_interest`? I probably wouldn't respect that timestamp here. For one thing, it only applies to orphan cleanup and I wouldn't consider this to be part of orphan cleanup.

2021-07-22 19:56 UTC, daviddavis commented on pulpcore/app/tasks/reclaim_space.py
> +        # we need to manually call delete() because it cleans up the file on the filesystem
:+1:

2021-07-26 16:13 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +        if not ca.content.cast().protected_from_reclaim:
: /

Is there a chance we could do what we do in the `QueryExistingContent` stage?  It could be simpler since we would be dealing with `pk` instead of `natural_key`

2021-07-28 17:19 UTC, mdellweg commented
I believe the `PROTECT_FROM_RECLAIM` shoudhave a note in `CHANGES/plugin_api`.

2021-08-02 11:28 UTC, ipanova commented
@daviddavis @dralley can I get a final review/approval? I have submitted PRs to the plugins which depend on this change

2021-08-02 16:32 UTC, daviddavis approved these changes

2021-08-02 16:32 UTC, daviddavis commented on pulpcore/app/tasks/reclaim_space.py
> +def reclaim_space(repo_pks, keeplist_rv_pks=None, force=False):
Some docstring here might be helpful so one doesn't have to go look at the serializer to understand the args.

2021-08-03 04:04 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +  * repos that have on_demand download policy and one would want to clear out downloaded files for
s/have/were synced with

2021-08-03 04:07 UTC, dralley commented on docs/workflows/reclaim-disk-space.rst
> +
Maybe we should get rid of the list and switch it to paragraph form?  Points two and three don't match with the caption above.

2021-08-04 03:23 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +    progress_bar.save()
Why not use as a context manager?

2021-08-04 03:24 UTC, dralley approved these changes

2021-08-04 09:40 UTC, merged