Adds Range header support to content app
pulp/pulpcore pull request #1473
Opened 2021-07-08 15:56 UTC by bmbouter

This unskips the `Range` header and adds support for it to the content
app.

closes #8865

2021-07-08 16:17 UTC, dralley commented on pulpcore/content/handler.py
> +        # pydevd_pycharm.settrace('localhost', port=29437, stdoutToServer=True, stderrToServer=True)
^

2021-07-08 16:19 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        headers = {"Range": "bytes=2-11"}  # first 10 bytes
Fix the comment, and it would be good to do a second request with a different range to make sure the potential caching issues @gerrod3 mentioned aren't there.  Likewise a range request after a non-range-request for the same file.

2021-07-08 16:19 UTC, bmbouter commented on pulpcore/content/handler.py
> +        # pydevd_pycharm.settrace('localhost', port=29437, stdoutToServer=True, stderrToServer=True)
Yeah this is not ready for review yet. I want to see what the CI says. I'll convert to draft.

2021-07-08 16:20 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        headers = {"Range": "bytes=2-11"}  # first 10 bytes
Good ideal. I'm adding a bunch of tests actually.

2021-07-08 21:06 UTC, dralley commented on pulpcore/content/handler.py
> +        rng = request.http_range
What I would maybe do instead is `range_start, range_stop = request.http_range.start, request.http_range.stop`, because `rng` mentally maps to "random number generator" for me

2021-07-08 22:36 UTC, dralley commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
I'm not sure I understand this part.  Why are we rewriting the content-length?

2021-07-09 00:10 UTC, gerrod3 reviewed
I think a test(s) for ranges with files that would be chunked is needed to verify this fix works correctly (see comments below). Use this fixture https://fixtures.pulpproject.org/file-chunked/. Also an additional test for streamed content should be added.

2021-07-09 00:10 UTC, gerrod3 commented on pulpcore/content/handler.py
> +        rng = request.http_range
I agree with associating `rng` with random number generator.

2021-07-09 00:10 UTC, gerrod3 commented on CHANGES/8865.bugfix
> +clients.
Is it worth mentioning that this only occurred when content wasn't present in Pulp yet, i.e. `remote.policy != Remote.IMMEDIATE`?

2021-07-09 01:09 UTC, dralley commented on CHANGES/8865.bugfix
> +clients.
I think so, personally

2021-07-09 13:19 UTC, bmbouter commented on pulpcore/content/handler.py
> +        rng = request.http_range
I'll change this now. ty

2021-07-09 13:24 UTC, bmbouter commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
If we pass the `Content-Length` header back unmodified then even though say the range is asking for 10 bytes of 1024, and we're only returning 10 bytes, the `Content-Length` would show 1024 incorrectly. Also we do this here because some server's don't return the `Content-Length` at which point we don't know enough to set it.

2021-07-09 13:28 UTC, bmbouter commented on pulpcore/content/handler.py
> +                await response.write(data)
I'll add a test using the fixture to cause chunking. I think it does because when I developed the patch I modified chunk size [here](https://github.com/pulp/pulpcore/blob/master/pulpcore/download/http.py#L210) to be 3 bytes for files of size 1024. Adding a test from the start would have been better than that tho.

2021-07-09 13:32 UTC, bmbouter commented on pulpcore/content/handler.py
>                  await original_handle_data(data)
Now this I think would not work. I'll add a streamed test and also use the local var instead of `._size`. ty!

2021-07-09 13:33 UTC, bmbouter commented on CHANGES/8865.bugfix
> +clients.
I will update this also. Ty!

2021-07-09 13:37 UTC, bmbouter commented on pulpcore/content/handler.py
>                  await original_handle_data(data)
I added a `test_content_served_streamed_with_range_request_valid_middle_range` and it seemed to work as-is. Hmmmm

2021-07-09 13:47 UTC, bmbouter commented on pulpcore/content/handler.py
>                  await original_handle_data(data)
It's because it's not using chunking! I'm switching all of these tests to use the chunking fixture...

2021-07-09 14:27 UTC, bmbouter commented on pulpcore/content/handler.py
>                  await original_handle_data(data)
Yes this new test is failing. I'm fixing it.

2021-07-09 20:27 UTC, gerrod3 commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
Not sure if this math for these values are right. Testing with httpie, `http HEAD https://fixtures.pulpproject.org/file/1.iso Range:bytes=40-50` returns `content-length: 11 content-range: bytes 40-50/1024`. Is either the range start or stop auto decremented by `aiohttp`?

2021-07-09 20:27 UTC, daviddavis approved these changes

2021-07-09 20:34 UTC, gerrod3 commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
Looking at the tests constants below, they seem to be correct after manually checking them against httpie and the fixtures, so I think this math must be correct if the tests pass even if it's not intuitive from the code.

2021-07-09 20:37 UTC, bmbouter commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
Yeah it's a little confusing but aiohttp does modify it by one I believe because start is inclusive and end is exclusive. https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.http_range

Take this test for example, it [asserts the content-length is 1200401](https://github.com/pulp/pulpcore/pull/1473/files#diff-c2f1bc66265b714bc14821751e842441c1d63c1b629c807144bf1fdaf162ad1aR353) and when I run `http HEAD https://fixtures.pulpproject.org/file-chunked/1.iso Range:bytes=1048176-2248576` I get

```
HTTP/1.1 206 Partial Content
cache-control: private
content-length: 1200401
content-range: bytes 1048176-2248576/10485760
content-type: application/octet-stream
date: Fri, 09 Jul 2021 20:35:02 GMT
etag: "60d0dd9f-a00000"
last-modified: Mon, 21 Jun 2021 18:42:39 GMT
server: nginx/1.14.1
set-cookie: dd6ec0a439e94ec1afa8091bd8cb5f4f=84e1263ecb996dab7f6f4ae499835116; path=/; HttpOnly; Secure; SameSite=None
```

I really really like the thoroughness and attention to detail you're showing here!

2021-07-09 20:38 UTC, dralley requested changes

2021-07-09 20:38 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        self.assertRaises(
We should ensure that HTTP 416 is being raised, which is the correct status code.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416

2021-07-09 20:38 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +            "immediate", url="https://fixtures.pulpproject.org/file-chunked/PULP_MANIFEST"
Add this URL to constants.py and import it to avoid duplicates.

2021-07-09 20:42 UTC, dralley commented on pulpcore/content/handler.py
> +                    response.headers[name] = str(range_bytes)
@gerrod3 Since the ranges start from 0, index 10 is the 11th byte, and likewise in this instance.  So I think the math is correct.

See the example given in the middle of page 13 https://datatracker.ietf.org/doc/html/rfc7233#section-4.2

2021-07-09 20:59 UTC, dralley approved these changes

2021-07-09 21:00 UTC, merged