Fix on_demand downloads from file:// urls
pulp/pulpcore pull request #1491
Opened 2021-07-13 22:08 UTC by gerrod3

fixes: #9078

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-07-13 22:34 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +                    fd.write(utils.http_get(urljoin(FILE_FIXTURE_URL, file)))
@dkliban I need a way to write these temporary files into the Pulp container for the CI. Any ideas?

2021-07-13 22:38 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +                    fd.write(utils.http_get(urljoin(FILE_FIXTURE_URL, file)))
@gerrod3 https://github.com/pulp/pulp_file/pull/528/files#diff-bca5f0b916aca91596114e579ea90e23aec2287619d80a5dbfbbca99697cd303R35-R52

2021-07-13 23:05 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +                    fd.write(utils.http_get(urljoin(FILE_FIXTURE_URL, file)))
Although since this would be the third use of it, maybe it needs to be a helper utility in pulp-smash

`def wget_download_fixture(url, path)`

2021-07-14 13:17 UTC, dralley commented
For discussion: https://pulp.plan.io/issues/9078#note-6

2021-07-14 17:34 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        with TemporaryDirectory(dir="/tmp") as td:
Can we extract this out into a pulp-smash helper utility?

2021-07-20 20:03 UTC, bmbouter commented on pulpcore/download/file.py
> +import aiofiles, aiofiles.os
This should be left as-is since the dot-access is already available on `aiofiles` as is.

2021-07-20 20:06 UTC, bmbouter commented on pulpcore/download/base.py
> +        headers_ready_callback=None,
We want to fix this differently because we don't want to bring the notion of headers into the the base downloader. Instead we need to probably adjust how the content app handles the starting of the streaming response.

2021-07-20 20:07 UTC, dralley commented on pulpcore/download/file.py
> +import aiofiles, aiofiles.os
I don't think that is (necessarily) the case since the `os` module is not part of `__all__`

https://github.com/Tinche/aiofiles/blob/master/src/aiofiles/__init__.py

2021-07-20 20:08 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        """Assert on_demand content from filesystem can be downloaded."""
Please do try to make a generic helper in `pulp_smash` if possible since we have a few different places that are using this approach now.

If it's not possible due to the specifics of this particular usage then that's OK.

2021-07-20 20:10 UTC, bmbouter commented on pulpcore/download/file.py
> +import aiofiles, aiofiles.os
If they aren't declaring it in their `_all_` then maybe we shouldn't use it? It's mute anyway though we need to do this PR differently.

2021-07-20 20:14 UTC, dralley commented on pulpcore/download/file.py
> +import aiofiles, aiofiles.os
I don't think that's the case, they're just taking a respectful approach to namespaces.  Every function in `aiofiles` maps to a non-async function of the same name so putting everything in `__all__` would cause issues if anyone was silly enough to `import *`

2021-07-20 20:16 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        with TemporaryDirectory(dir="/tmp") as td:
Yeah we need the test to assume the system under test is not localhost so we can't use this approach. We need to place the files on the remote system. There is a similar approach here https://github.com/pulp/pulp_file/pull/528

2021-07-20 20:28 UTC, bmbouter requested changes
We need to find a way fix this without introducing the notion of an http-only concept to base.

Overall the issue is that the content app is expecting an http downloader here https://github.com/pulp/pulpcore/blob/master/pulpcore/content/handler.py#L869-L871

2021-07-20 20:41 UTC, gerrod3 commented
Closing since this issue is probably pretty rare to run into and this isn't the best solution to fix it. See https://pulp.plan.io/issues/9078?pn=1#note-9.

2021-07-20 20:41 UTC, closed without merging