Acs artifact stage
pulp/pulpcore pull request #1496
Opened 2021-07-16 10:33 UTC by pavelpicka

New optional stage for ACS. 

Be aware that this PR is on top commit used in https://github.com/pulp/pulpcore/pull/1437. Before merge please rebase and drop commit with ACS models.

2021-09-02 15:19 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                checksum_type = "sha256"
This assumes that all RemoteArtifacts in a batch will have the same checksum type?

2021-09-02 15:20 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                    **{checksum_type + "__in": batch_remote_artifacts_checksums},
```suggestion
                    **{f"{checksum_type}__in": batch_remote_artifacts_checksums},
```

2021-09-02 15:23 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                ).select_related("remote")
I think you could probably simplify this using [the `acs()` queryset method](https://github.com/pulp/pulpcore/pull/1605/files#diff-81f6a78175bb93934b6beff952646d3ca1ef3731f1ff14492d4ec77bfc3fdf82R574-R576):

```suggestion
                existing_ras = RemoteArtifact.objects.acs().filter(
                    **{f"{checksum_type}__in": batch_remote_artifacts_checksums}
                )
```

2021-09-02 15:25 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                            ).first()
These queries are going to execute for each `d_artifact`. I think you could eliminate them by storing a dictionary of remote artifacts and looking them up by checksum.

2021-09-02 15:42 UTC, pavelpicka commented on pulpcore/plugin/stages/artifact_stages.py
> +                checksum_type = "sha256"
It does.

2021-09-02 16:17 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +                checksum_type = "sha256"
I only spent a few minutes just now looking at this, but I'm not sure this is a valid assumption.

2021-09-06 10:07 UTC, pavelpicka commented on pulpcore/plugin/stages/artifact_stages.py
> +                checksum_type = "sha256"
Updated to take existing checksum from each d_artifact and look for ACS by it.

2021-09-06 10:08 UTC, pavelpicka commented on pulpcore/plugin/stages/artifact_stages.py
> +                            ).first()
to take URL it works well, but still we need to 'get' remote (not only the remote_id).

2021-09-07 15:18 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                            ).first()
Right, I was imagining that the dict would relate checksum type + checksum digest to remote.

2021-09-08 13:05 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                                    batch_checksums[cks_type] = list()
What if you made `batch_checksums` a `defaultdict(list)`?

2021-09-08 13:51 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                                ]
I think this list comprehension is inefficient since you only need the first match. If you used a dict data structure, you wouldn't need this list comprehension at all.

2021-09-08 16:26 UTC, bmbouter commented on CHANGES/8748.feature
> +Added optional stage for Alternate Content Source support.
This is a plugin API change, so this needs to be `CHANGES/plugin_api/8748.feature`.

2021-09-08 16:45 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +                            ):
```suggestion
                            if getattr(d_artifact.artifact, checksum_type, False):
```

2021-09-08 20:54 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +    async def run(self):
In reading over this code, it reads well enough, but I'd really like to run it. I'd be open to merging this and then having the test of pulp_file allow us to step through it more effectively.

2021-09-09 13:44 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +    async def run(self):
@daviddavis wdyt ^?

2021-09-09 14:50 UTC, daviddavis commented on pulpcore/plugin/stages/artifact_stages.py
> +    async def run(self):
That works for me assuming the 2 open items of feedback are addressed.

2021-09-09 14:53 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +                    .prefetch_related("remote")
Use `select_related()` if you are able to do so

2021-09-09 16:41 UTC, daviddavis approved these changes

2021-09-09 17:23 UTC, bmbouter approved these changes

2021-09-09 17:36 UTC, daviddavis requested changes
Can you squash the commits and address @dralley's comment? Then I think we can merge.

2021-09-10 14:00 UTC, ipanova commented on pulpcore/plugin/stages/artifact_stages.py
> +    A Stages API stage to download :class:`~pulpcore.plugin.models.Artifact` files from Alternative
s/A Stages API stage to download/ API Stage
s/Alternative/Alternate/

2021-09-10 14:03 UTC, ipanova commented on pulpcore/plugin/stages/declarative_version.py
> +            acs (bool): 'True' adding stage to look for a content in Alternate Content Sources.
"When set to 'True' a new stage is added to look for..."

2021-09-10 14:33 UTC, daviddavis approved these changes

2021-09-10 15:01 UTC, merged