Fix disk usage during the synchronization
pulp/pulpcore pull request #1498
Opened 2021-07-16 16:14 UTC by lubosmj

2021-07-16 16:35 UTC, dralley commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
This may have some performance implications.

2021-07-16 16:38 UTC, dralley commented on pulpcore/app/models/storage.py
> +    in-memory or outside of MEDIA_ROOT, the data is written/copied in chunks to the new location.
Should this second instance of `MEDIA_ROOT` be changed also?

2021-07-16 16:50 UTC, lubosmj commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
In the commit message, I am trying to say what size of the memory needs to be allocated for one task during the synchronization in /var/lib/pulp. Regarding the performance implications, I am again referring to @fao89's comments https://github.com/pulp/pulpcore/pull/440/files where he suggested re-evaluating these defaults.

2021-07-16 16:59 UTC, dralley commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
Oh I'm definitely not suggesting we don't do it, I'm just pointing it out as something we should maybe look into in the future.

2021-07-16 17:02 UTC, dralley commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
@lubosmj Why not override it for the particular stages that need a smaller batch size? https://github.com/pulp/pulpcore/blob/master/pulpcore/plugin/stages/artifact_stages.py#L236

2021-07-16 17:20 UTC, lubosmj commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
@dralley alright, you persuaded me.

2021-07-16 17:53 UTC, dralley commented on pulpcore/plugin/stages/api.py
> +    async def batches(self, minsize=250):
Cool -- I believe the commits can also be squashed in that case, since it is a more self-contained change.

2021-07-16 19:26 UTC, dralley commented
We fixed the CI so you should rebase when you see this on Monday

2021-07-16 20:12 UTC, dralley approved these changes

2021-07-20 20:30 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I think there is sufficient evidence to change this number from the default. I recommend removing this part of the diff.

2021-07-20 20:31 UTC, bmbouter commented on pulpcore/app/models/storage.py
> +                str(settings.DEPLOY_ROOT)
This part looks good though.

Also what happens if you don't have the `str()` in it?

2021-07-20 20:35 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I recommended this as a reminder of "why use something special here" when we go working in this code.  It could be made a little more concise though.

2021-07-20 20:39 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I mean specifying minsize at all. Do we want it saving in batches of 250 versus the default of 500? I didn't think we had a good reason to change it. Maybe we do?

2021-07-20 20:58 UTC, lubosmj commented on pulpcore/app/models/storage.py
> +                str(settings.DEPLOY_ROOT)
An error is raised since the method expects only strings.

2021-07-20 20:59 UTC, lubosmj commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
The rationale behind this change is here: https://github.com/pulp/pulpcore/pull/1465#discussion_r664795959.

2021-07-20 21:26 UTC, dralley commented on pulpcore/app/models/storage.py
> +                str(settings.DEPLOY_ROOT)
From `settings.py`

```
DEPLOY_ROOT = Path("/var/lib/pulp")
MEDIA_ROOT = str(DEPLOY_ROOT / "media")  # Django 3.1 adds support for pathlib.Path
```

This is weird to me - perhaps (going by the comment) we can address the inconsistency post upgrade to Django 3?

(But it should remain separate from this PR because we need to backport it).

2021-07-20 21:32 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
@bmbouter The rationale @lubosmj gave makes sense to me.  

Basically because `minsize` is the minimum batch size, that means that 500 artifacts must build up in the `ArtifactSaver` input queue (read: all artifacts downloaded for 500 content units) before `ArtifactSaver` will start processing them (which allows deleting the temporary files).

I actually think that we need to file a refactor issue for this problem still because simply lowering the cap to 250 content units is only an indirect means of reducing the disk consumption - we could still have trouble with 250 content that have very large artifacts.  But that would be a much larger task.

2021-07-21 13:25 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I thought this over and now I think lowering the batch size will likely improve our performance. Even though it has a negative impact on the number of round trips to the DB for the bulk_save calls, the amount of time lost there would likely be significantly less than the time lost by waiting to start moving large files into place and trying to move a huge number of files at once. So maybe even lower it further to like 100? I'm also ok with 250.

Thanks for talking this over.

2021-07-21 13:27 UTC, bmbouter approved these changes
Thanks @lubosmj !

2021-07-21 13:31 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I'd also be fine with any number between 100 and 250.  200 might be a good choice.

I'm not sure about the performance benefits because we don't do any asynchronous file IO, only blocking, so we're waiting either way - but I also agree that it won't hurt performance significantly.

2021-07-21 13:35 UTC, dkliban approved these changes

2021-07-21 13:36 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
Yeah actually that matters a lot on if this will bring a performance benefit or not. I was misremembering thinking that we were using aiofiles here but we're not. iirc, aiofiles uses a threadpool underneath to make the file saving async but in this case it's already saved in /var/lib/pulp/ so even if it's synchronous there won't be any actual bit moving+saving so the filesystem operation will be very fast.

So if all ^ is right, this means that lowering the batch size will negatively affect performance by causing additional DB RTTs. After thinking about this more I don't think this is even having an effect on disk size because the files are both on the same volume and they aren't actually being moved so regardless of the move the same number of inodes will be used.

And if ^ is right, I think we should leave the batching alone.

2021-07-21 13:37 UTC, bmbouter requested changes
let's figure out if the batching change is helpful or not. I don't think it is.

2021-07-21 13:40 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I don't think we *can* leave batching alone, because of the disk space issue, and in the event of an on-demand sync I don't think it would be a significant contributor to the overall runtime of the sync task.

And IIRC the `ArtifactSaver` stage should be a no-op in the `on_demand` case so no impact there.

2021-07-21 13:43 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
I'm confused. The files pre and post save are on the save volume. How can we be "increasing disk size during sync" by moving files less often when they are on the same filesystem?

2021-07-21 13:46 UTC, dralley commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
Ok, I think I see what you mean now.  Needed to re-read the PR.

2021-07-21 14:09 UTC, lubosmj commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
Yes. Since we are not copying files anymore, but rather moving, the behaviour I described is not valid. Files were copied before the change. Therefore, I can get rid of `minsize=250`. Sorry for the inconvenience created.

2021-07-21 14:10 UTC, bmbouter commented on pulpcore/plugin/stages/artifact_stages.py
> +        async for batch in self.batches(minsize=250):
It's no inconvenience. Things are complicated, and we gotta talk them out.

2021-07-21 14:44 UTC, bmbouter approved these changes
Thank you!

2021-07-21 14:45 UTC, merged