Fix out of memory error when exporting large repos
pulp/pulpcore pull request #1782
Opened 2021-12-19 11:53 UTC by hao-yu

json.dumps method consumes a lot of memory when converting data
to json string. While processing data, it seems to create
python object which is a number of times larger than the
parsing data. For example, a 5GB data is resulting more than 20GB
consumed.

This commit fixes it by using json.dump method. Data is processed
in chunk and write into a temporary file. Generator is also being
used to fetch rows from database in batch so that it doesn't need
to load the whole resultset to memory.

closes #9645

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2021-12-20 15:00 UTC, dkliban requested changes
You need to add a CHANGES/9645.bugfix file with an entry for the change log.

2021-12-20 18:34 UTC, dkliban commented on pulpcore/app/importexport.py
> +log = logging.getLogger(__name__)
did you mean to leave this here? i don't see it used anywhere

2021-12-21 01:05 UTC, hao-yu commented on pulpcore/app/importexport.py
> +log = logging.getLogger(__name__)
Yes. I just thought it is handy to have it for debugging in the future. I can remove if you don't like it. :)

2021-12-21 01:10 UTC, hao-yu commented
Added CHANGES/9645.bugfix

2021-12-21 02:34 UTC, hao-yu commented on pulpcore/app/importexport.py
> +        self.batch_size = 2000
Based on my tests for rhel 7 server rpms repo, memory usage <700MB max when batch size is set to 1000. Memory usage <1GB max when batch size is set to 2000.

2021-12-22 13:33 UTC, hao-yu commented
@dkliban you want me to fix the format?

2021-12-22 21:38 UTC, dkliban commented
@hao-yu yea, please squash the formatting changes into a single commit. You can remove it from draft.

2021-12-23 22:09 UTC, parthaa commented
I tested this patch and it worked great. I have an additional patch to this PR to fix the import OOM also
```patch
diff --git a/pulpcore/app/tasks/importer.py b/pulpcore/app/tasks/importer.py
index 7f89f88..35291e6 100644
--- a/app/tasks/importer.py
+++ b/app/tasks/importer.py
@@ -59,7 +59,7 @@ def _import_file(fpath, resource_class, do_raise=True):
     try:
         log.info(_("Importing file {}.").format(fpath))
         with open(fpath, "r") as json_file:
-            data = Dataset().load(json_file.read(), format="json")
+            data = Dataset().load(json_file, format="json")
             resource = resource_class()
             log.info(_("...Importing resource {}.").format(resource.__class__.__name__))
             return resource.import_data(data, raise_errors=do_raise)
```

2021-12-24 02:21 UTC, hao-yu commented
@dkliban Squashed changes into 1 commit.

@parthaa I added the additional patch to this PR.  Can you please double check if it is correct?

2021-12-25 09:56 UTC, mdellweg commented on pulpcore/app/importexport.py
Importing from hidden interfaces is dangerous.

2021-12-25 09:56 UTC, mdellweg commented on pulpcore/app/importexport.py
> +
Why is this inheriting list?

2021-12-25 09:56 UTC, mdellweg commented on pulpcore/app/importexport.py
Please use as a context manager

2021-12-25 10:44 UTC, hao-yu commented on pulpcore/app/importexport.py
Any better suggestion? I thought about copy the entire method to here?

2021-12-25 10:45 UTC, hao-yu commented on pulpcore/app/importexport.py
> +
because it needs to be json serializable such as list, tuple or dict.

2021-12-25 11:01 UTC, hao-yu commented on pulpcore/app/importexport.py
which line you are referring here?

2022-01-03 10:06 UTC, mdellweg commented on pulpcore/app/importexport.py
> +
I'd prefer to make json dump aware of this type.
Inheriting from list and not even call it's `__init__` will lead to an object in a very weird state.
Can you add a `toJson` method?

2022-01-03 10:07 UTC, mdellweg commented on pulpcore/app/importexport.py
Sorry, the mobile beast always annotates the wrong lines.

The NamedTemporaryFile should be used as a context manager.

2022-01-03 11:03 UTC, hao-yu commented on pulpcore/app/importexport.py
> +
I can add the super().__init__([]) with empty list to the inherited class to ensure it is called. Can you explain more about the toJson method you suggested and how you mean make json dump aware of that type?

2022-01-03 11:05 UTC, hao-yu commented on pulpcore/app/importexport.py
I think there is no much point using the context manager here as doing this I need to manually flush() the buffer and use seek() and tell() to get the file size and having 2 open file handlers reading the same file.

2022-01-03 13:23 UTC, mdellweg commented on pulpcore/app/importexport.py
It will take care of the unlink. Even in case of exceptions.

2022-01-03 13:32 UTC, mdellweg commented on pulpcore/app/importexport.py
Would `StringIO` instead of a real file help to trigger the streaming in the encoding process?

2022-01-03 13:42 UTC, mdellweg commented on pulpcore/app/importexport.py
> +
Usually, you can extend the `jsonEncoder` or pass a default handler with `json.dump`.
Honestly, i'm unsure if any of this helps to encode the iterator in a streaming manner.

2022-01-03 14:04 UTC, mdellweg commented on pulpcore/app/importexport.py
> +            yield from dataset.dict
Not sure, i understand this correctly. Don't we loose the keys from that dict? Shouldn't we use `yield from dataset.dict.items()`?
The more i think about this i wish, this issue of export not being streamed could be resolve in django-import-export.

2022-01-04 08:28 UTC, hao-yu commented on pulpcore/app/importexport.py
> +            yield from dataset.dict
`dataset.dict` returns a list of ordered dicts

2022-01-04 08:29 UTC, hao-yu commented on pulpcore/app/importexport.py
yup. we don't want to load every thing into memory

2022-01-04 09:37 UTC, mdellweg commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
If i read the DIE code correctly, this is the line where the whole resource table will be loaded into memory and transformed into a tablib format (https://github.com/django-import-export/django-import-export/blob/main/import_export/resources.py#L938).

So what i would like to see is a way to tell export (or a new method) to stream it's results in a certain format to a file.
For our usecase we could restrict ourselves to `def stream_json(output_stream)`. Can this be done on the pulpcore subclass of `ModelResource`?

Sorry, to keep pushing you, but to me this PR is very confusing and looks brittle.

2022-01-04 15:15 UTC, parthaa commented on pulpcore/app/importexport.py
@mdellweg To put it in perspective RHEL 7 export json is 5 GB.

2022-01-05 01:41 UTC, hao-yu commented on pulpcore/app/importexport.py
5 GB is just the file size. It is still not counting after they loaded into json objects. It will be multiplies of 5GB as I described in the bug

2022-01-05 01:45 UTC, hao-yu commented on pulpcore/app/importexport.py
> +
I had a look on `cls` and `default.` I don't see that I can utilize them in the way that could save memory. Even I override the `default` method, it still needs to return an json encodable value, such as list.

2022-01-05 02:16 UTC, hao-yu commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
I thought about it earlier. I think this will only work if `json.dump` support the streaming too but it seems not. Unless we manually do it. Like write '[',  for each chunk of dicts  write to file, close ']'. https://stackoverflow.com/questions/24239613/memoryerror-using-json-dumps

2022-01-05 04:26 UTC, parthaa commented
side question - Will splitting json to multiple files work better ? Like keep 5K entries per file ?

2022-01-05 10:17 UTC, mdellweg commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
Looking into the code of the json module, the iterative encoding really only works with `list`, `tuple` and `dict`, which is really unfortunate. Can you maybe try if `tuple` serves as well and add an explaining comment to it?
Still i see two issues to solve here: The aforementioned `json.dump` not working with iterators, and the fact that `resource.export` does not supply an iterator.
Not sure if the latter is better served by an all inclusive `export-to-file` method on the Model resource, or an iterator based version of `export` (needing all attached libraries like `tablib` to be made aware of iterators).
I will think about this more and come back here.

2022-01-06 01:04 UTC, hao-yu commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
You mean try to inherit from tuple instead of list? Can you explain a bit what is the benefit of doing that?

2022-01-06 11:02 UTC, mdellweg commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
It _is_ the same kind of hackery, but i think the tuple (being read only) brings a lot less functionality that can interfere.

2022-01-06 13:03 UTC, hao-yu commented on pulpcore/app/importexport.py
> -    dataset = resource.export(resource.queryset)
I can change it but I don't think that will make any difference because the list or tuple is just empty. The reason that we inherit the list/tuple is just to make it iterable and fetch the records on demand. AFAIK, Json module uses the same method to encode both tuple and list and it just iterate the provided list/tuple nothing else.

2022-01-10 10:58 UTC, mdellweg commented on pulpcore/app/importexport.py
I still want the tempfile to be used as a context manager. Yes we close it manually, but the `unlink` call should be done by the context cleanup.

2022-01-10 11:05 UTC, mdellweg commented on pulpcore/app/importexport.py
> +
Can you add something like:
"Because the underlying libraries (json; django-import-export) do not support to stream the output to file, we export the 
data in batches to memory and concatenate the json lists via string manipulation."

2022-01-10 17:19 UTC, mdellweg approved these changes
I think, this is it.
@ggainey I want your signoff too.

2022-01-10 17:22 UTC, mdellweg commented
We use black for formatting code:
https://github.com/pulp/pulpcore/runs/4764870730?check_suite_focus=true#step:6:8

2022-01-17 20:12 UTC, ggainey approved these changes
The discussion and related changes look good to me. The import-tests are clean. I have had issues testing w/ RHEL7 imp/exp on my system, but it's been due to my-environment-problems. I'm good to go w/ this!

2022-01-18 14:55 UTC, dkliban approved these changes

2022-01-18 14:55 UTC, merged

2022-01-19 16:41 UTC, jlsherrill commented
@pulp/pulpcore request to backport this to 3.14.z

2022-01-19 17:39 UTC, dralley commented
@jlsherrill https://github.com/pulp/pulpcore/issues/2107