Telemetry posting PoC
pulp/pulpcore pull request #2118
Opened 2022-01-19 21:46 UTC by bmbouter

[noissue]

2022-01-20 11:54 UTC, mdellweg commented on pulpcore/app/models/task.py
> +class PeriodicTask(LifecycleModel):
As i recall, one of the design goals of pulp3 was to stay out of the scheduler business. Do you think this can be handled by a regular task with a cron like utility?

2022-01-20 18:18 UTC, bmbouter commented on pulpcore/app/models/task.py
> +class PeriodicTask(LifecycleModel):
We got out of the business for a few reasons, but I'll try to explain why this isn't getting back into that business.

The feature we stopped offering was offering user-editable period tasks that capture all the various parameters they wanted on the schedules they wanted. This was a highly complex feature. Also it required additional components to be deployed, e.g. celerybeat, which if users were going to have to do that they should just use cron.

This is different because these tasks are not running user workload but are instead an aspect of Pulp's internal correctness. They don't contain any parameters at all actually. We don't want to have a separate dispatcher required because then making that work everywhere (k8s, single-container, rpm installs, clustered installs, ansible installer installs, etc) is very complex. Vendoring the dispatcher in Pulp itself will have it work everywhere.

I named it PeriodicTask because it's possible Pulp may have some other periodic correctness tasks to run, so the idea was to make the modelling just a bit more general, but this could also be written exclusively for the telemetry posting periodic task.

More questions and input is welcome.

2022-01-21 09:44 UTC, mdellweg commented on pulpcore/app/models/task.py
> +class PeriodicTask(LifecycleModel):
I see this task to be called in the content handler, but the code is interleaved with other tasking system code. This is confusing to understand.
My question is: Do we need to have a db record for this? How is it different from the heartbeating we do in the handlers already? Can we not async-run a piece of code with a configured time interval?
Maybe it get's clearer once the periodic task actually collects data.

2022-02-07 16:29 UTC, mdellweg commented on pulpcore/app/models/task.py
> +    task_name = models.CharField(max_length=256, unique=True)
Now they really start looking like tasks. :D

2022-03-17 11:25 UTC, mdellweg commented on pulpcore/app/migrations/0089_create_system_id_and_telemetry_task_schedule.py
> +def create_system_ID(apps, schema_editor):
I sill believe, that datamigrations are there to migrate / repair existing data. Seeding data should be moved to a post_migrate hook. You cannot be sure it exists in cases of truncated databases (`pulpcore-manager flush`). Also it makes squashing migrations harder.

2022-03-18 14:50 UTC, bmbouter commented on pulpcore/app/migrations/0089_create_system_id_and_telemetry_task_schedule.py
> +def create_system_ID(apps, schema_editor):
The downside of using post_migrate hook is that now that code has to deal with both the case where it's the first time it's creating data, or if the data is already there and now it's being changed due to the seed data changing over versions of the code.

The really nice thing about migrations is that when you seed the data with it's first value, you can just create it, you know its the first time it's run. Then if it changes later, you're guaranteed the data is already there and you just have to update it. In both situations what you needed to handle is just simpler. Using a post-migrate hook, now that code has to handle all of these cases correctly no matter what that system had on it before. This does not seem better (especially when `flush` is not something I think anyone should run).

2022-03-18 15:14 UTC, mdellweg commented on pulpcore/app/migrations/0089_create_system_id_and_telemetry_task_schedule.py
> +def create_system_ID(apps, schema_editor):
It's not hard to just have it in an idempotent way:
https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update-or-create

2022-05-26 13:52 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
> +STAGING_URL = "https://staging-analytics-pulpproject-org.pulpproject.workers.dev/"
We don't have a staging URL, I will delete this.

2022-05-27 17:58 UTC, dralley commented on pulpcore/app/tasks/telemetry.py
> +    pydevd_pycharm.settrace("localhost", port=29437, stdoutToServer=True, stderrToServer=True)
leftovers

2022-05-27 18:02 UTC, bmbouter commented on pulpcore/app/migrations/0090_create_system_id_and_telemetry_task_schedule.py
> +    dispatch_interval = timedelta(minutes=10)
This is not right, this needs to be 1 day.

2022-05-30 07:27 UTC, mdellweg requested changes

2022-05-30 07:27 UTC, mdellweg commented on pulpcore/app/migrations/0090_create_system_id_and_telemetry_task_schedule.py
> +        migrations.RunPython(create_periodic_task),
I still believe, we should never create data in a migration, but only migrate it.

2022-05-31 14:02 UTC, mdellweg commented on pulpcore/app/migrations/0090_create_system_id_and_telemetry_task_schedule.py
> +        migrations.RunPython(create_periodic_task),
yes

2022-06-02 09:46 UTC, mdellweg reviewed
Some more suggestions...

2022-06-02 09:46 UTC, mdellweg commented on pulpcore/app/apps.py
> +        )
Is it possible to connect these hooks in the PulpAppConfig object, so they will only emit once?

2022-06-02 09:46 UTC, mdellweg commented on pulpcore/app/apps.py
> +        name=name, task_name=task_name, dispatch_interval=dispatch_interval
Should we move `task_name` and `dispatch_interval` to defaults?
Maybe even use https://docs.djangoproject.com/en/3.2/ref/models/querysets/#update-or-create to keep the record up to date.

2022-06-02 09:46 UTC, mdellweg commented on pulpcore/app/apps.py
> +        SystemID().save()
Could this be `SystemID.get_or_create()` ?

2022-06-02 09:46 UTC, mdellweg commented on pulpcore/app/apps.py
> +    from pulpcore.app.models import TaskSchedule
Not sure it is needed...
```suggestion
    TaskSchedule = apps.get_model("core", "TaskSchedule")
```

2022-06-02 09:46 UTC, mdellweg commented on pulpcore/app/apps.py
> +def _populate_telemetry_periodic_task(sender, apps, verbosity, **kwargs):
Not using it...
```suggestion
def _populate_telemetry_periodic_task(sender, apps, **kwargs):
```

2022-06-09 11:57 UTC, ipanova commented on pulpcore/app/apps.py
> +    if num_system_ids == 0:
you could use `if not SystemID.objects.exists()` instead, i read somewhere it is more performant

2022-06-09 11:57 UTC, ipanova commented on pulpcore/app/tasks/telemetry.py
> +        logger.error("Timeout sending analytics to %s", url)
maybe `Timed out while sending analytics`?

2022-06-10 18:49 UTC, bmbouter commented on pulpcore/app/apps.py
> +        )
I don't know how to do that actually. Do you?

2022-06-10 18:59 UTC, bmbouter commented on pulpcore/app/apps.py
> +        SystemID().save()
I don't think one can be because it's uuid as the pk so it would never recognize the existing one and the new one as the same.

2022-06-10 19:11 UTC, bmbouter commented on pulpcore/app/apps.py
> +    if num_system_ids == 0:
Yes this is better, ty.

2022-06-10 19:25 UTC, bmbouter commented on pulpcore/app/apps.py
> +        )
I didn't understand, but now I do. I made this change and it was much nicer than guarding those callables on the caller name.

2022-06-10 20:14 UTC, bmbouter commented
@mdellweg @ipanova I believe it's ready for re-review please.

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +async def post_telemetry():
Despite loving the idea of running this task in an async fashion, i do not see any place yet where we attempt to gather data in parallel.
Remember this task code will run in an isolated process. It can only be parallel to itself.

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +async def _get_posting_url():
This function would only benefit from being async if pulp_plugin_configs were.

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +    online_workers_hosts = await _num_hosts(online_workers)
Use asyncio.gather to run these in parallel. Then again they will be serialized in the threadpool for the single db-connection to use.

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +    data.update(await _build_online_workers_data())
asyncio.gather?

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/content/__init__.py
> +)
Where did that come from?

2022-06-13 09:34 UTC, mdellweg commented on pulpcore/app/apps.py
> +    )
:+1:

2022-06-13 15:28 UTC, bmbouter commented on pulpcore/content/__init__.py
> +)
This came from black iirc, but I'm not sure why. I'll remove it and see if black wants it back.

2022-06-13 15:30 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
> +async def post_telemetry():
It was done just for convenient use of asyncio.download, but I can also add a `gather` instead since it is async.

2022-06-13 15:30 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
> +async def _get_posting_url():
:+1: I'll convert to sync

2022-06-13 17:48 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
> +    online_workers_hosts = await _num_hosts(online_workers)
For readability I want to leave this one alone.

2022-06-13 17:48 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
> +    data.update(await _build_online_workers_data())
I did switch this one to `gather`.

2022-06-14 00:03 UTC, bmbouter commented
@mdellweg @ipanova I pushed this latest revision if you wouldn't mind taking a look. Thanks!

2022-06-14 11:52 UTC, mdellweg approved these changes

2022-06-14 12:54 UTC, ipanova approved these changes

2022-06-14 12:54 UTC, ipanova commented on pulpcore/app/models/telemetry.py
> +        if SystemID.objects.count() > 1:
can use here exists() too

2022-06-14 13:40 UTC, merged