Fixes #2168 - Setting for flexible imports
pulp/pulpcore pull request #2177
Opened 2022-01-31 04:54 UTC by parthaa

Customers want the flexibility in their import archive (since they tend
to be in disconnected environments.) This patch introduces a
IMPORT_MAPPED_REPOS_ONLY application wide setting that allows pulp to
turn on the "leniency" mode and import only the repositories specified
in the importer repository mapping and ignore the rest. The default
behavior remains the same (IMPORT_MAPPED_REPOS_ONLY is false by
default)

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2022-02-02 13:22 UTC, ggainey requested changes
@parthaa - Generally speaking, looks like a reasonable approach. See my comment RE artifacts tho.

Please rebase against latest-main to make the linter happy. I'm not sure what's going on with the single-commit-test - I only see one, Maybe once you rebase/force-push it'll resolve the problem.

2022-02-02 13:22 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                if not repo:
This will let us avoid creating any non-mapped repository - but all the Artifacts will be pulled in regardless. That means you'll likely end up with a lot of orphaned-content. I don't know if that's a problem for your use-case, but it's def something to think about explicitly.

2022-02-02 14:52 UTC, parthaa commented on pulpcore/app/tasks/importer.py
> +                if not repo:
Thats a good point. I wonder if we can tie  this config setting to artifact import also or is it out of our control?

2022-02-02 15:22 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                if not repo:
> Thats a good point. I wonder if we can tie this config setting to artifact import also or is it out of our control?

No - because artifacts cross repo-boundaries, imp/exp doesn't know which repos in the export required an artifact, just "here is the set of all artifacts requested by all repositories in the export". When you go to import, even if you only want one repo on the destination machine, you're going to get ALL the Artifacts, until orphan-cleanup deletes the ones you don't want. PulpImport/Export assumes tailored exports.

I understand the use-case driving this, but I'm not convinced it makes more sense than restricting at export-time...

2022-02-02 15:25 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                if not repo:
The import-flow requires/assumes that all artifacts are imported as one task, and once that completes, repos are imported as parallel tasks. You can't import a repo unless/until its artifacts exist. And you can't know which artifacts belong to what, until you're "inside" the repo, and can look at its ContentArtifact records. I don't think there is a way to do what you want, without basically rewriting import.

2022-02-02 15:49 UTC, parthaa commented on pulpcore/app/tasks/importer.py
> +                if not repo:
Oh I see. So then I 'd think as long as we document that you need at least  2 times the space of the import archive (even if you are only using 50% of it and have to do orphan cleanup.) we should be okay?. If the user cares about space they should be creating a separate content view and managing it.

2022-02-02 15:53 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                if not repo:
> Oh I see. So then I 'd think as long as we document that you need at least 2 times the space of the import archive (even if you are only using 50% of it and have to do orphan cleanup.) we should be okay?. If the user cares about space they should be creating a separate content view and managing it.

That sounds like an eminently-reasonable approach :)

2022-02-02 15:58 UTC, parthaa commented on pulpcore/app/tasks/importer.py
> +                if not repo:
I asked the TAM for the interested customer if it is a reasonable thing. Will update the card once I hear back one way or the other.

2022-02-03 09:20 UTC, mdellweg commented on pulpcore/app/settings.py
> +
I'm unsure, this should be a global option. Have you considered making this a import parameter (in the POST payload)?

2022-02-03 12:45 UTC, ggainey commented on pulpcore/app/settings.py
> +
If we do thjis, it should be global - it's the administrator saying "I am OK with doing partial imports". But this whole RFE has some insurmountable problems, suggest we leave it unless/until we get clarification from stakeholder.

2022-02-04 15:36 UTC, bmbouter commented on pulpcore/app/settings.py
> +
I don't have an opinion on adding a setting or not, but if we do, it needs docs https://docs.pulpproject.org/pulpcore/configuration/settings.html#pulp-settings

2022-02-04 15:37 UTC, bmbouter commented
I'm reading here this PR is still in progress so I've converted it to a draft until it's ready for review+merge.

2022-02-08 14:55 UTC, ggainey commented
@parthaa I know there's a lot of discussion going on here - given the Way Things Work in pulp, I'd like to propose we just close this PR unless/until we get clarity. Opinion?

2022-02-15 14:48 UTC, ggainey commented
Closing until someone yells at us

2022-02-15 14:48 UTC, closed without merging