Adds the `handle_creation_hooks` interface
pulp/pulpcore pull request #2198
Opened 2022-02-02 20:39 UTC by bmbouter

This change adds the `handle_creation_hooks` interface to the
``AccessPolicyFromDB`` method. If the AccessPolicy configured does not
have that interface, new model instances created will not have
permissions automatically added to them.

closes #2116

2022-02-02 20:50 UTC, bmbouter commented
I posted this and I think it does what is asked of the immediate issue, but I realize it likely should do much more? Here are two main lines of questions I have:

1) The things added here to `AccessPolicyFromDB` should like be on `AccessPolicy` directly. Or maybe those objects should be combined? We should think about why we even have two.

2) The `REGISTERED_CREATION_HOOKS` should likely be decoupled from `AutoAddObjPermsMixin` entirely as they don't make sense unless you have an `AccessPolicy` configured that has a notion of `creation_hooks`.

@mdellweg and @gerrod3, let's discuss ^ at the RTFM working group sometime. @newswangerd FYI also.

2022-02-03 10:04 UTC, mdellweg commented on CHANGES/plugin_api/2116.feature
> +to add object-level permissions to.
Not sure this needs to called out for the plugin writer. It's the same hooks specified in the same way. Nothing changes for plugins. We just introduce one additional abstraction to make the actual calls dependent on a condition the plugin writer has no control over.

2022-02-03 10:11 UTC, mdellweg commented
> I posted this and I think it does what is asked of the immediate issue, but I realize it likely should do much more? Here are two main lines of questions I have:
> 
>     1. The things added here to `AccessPolicyFromDB` should like be on `AccessPolicy` directly. Or maybe those objects should be combined? We should think about why we even have two.

`AccessPolicy` sadly is a bit ambiguous. Let's assume you mean the model, then no. One of them is a model and the other one is a permission class. Completely separate hierarchies.

> 
>     2. The `REGISTERED_CREATION_HOOKS` should likely be decoupled from `AutoAddObjPermsMixin` entirely as they don't make sense unless you have an `AccessPolicy` configured that has a notion of `creation_hooks`.

I don't see a reason. The whole purpose of the Mixin is to support calling creation_hooks. So this seems like the right domain for that concern. Also the specific model must register their hooks in this struct. So it must end in that class.

2022-02-03 10:47 UTC, mdellweg commented on pulpcore/app/models/access_policy.py
> +            access_policy.handle_creation_hooks(self)
This is not doing the logic. I think, you need to find the ViewSet class and loop over all configured permission classes and try to call the interface on those.
Remember the access policy is just a glorified permission class we want to allow to be configured.

2022-02-03 14:25 UTC, gerrod3 commented
>     2. The `REGISTERED_CREATION_HOOKS` should likely be decoupled from `AutoAddObjPermsMixin` entirely as they don't make sense unless you have an `AccessPolicy` configured that has a notion of `creation_hooks`.

I remember asking @mdellweg if `REGISTERED_CREATION_HOOKS` could live on the viewset (or something similar) and just have `AutoAddObjPermsMixin` add to the value, but I think he said it wasn't possible. Maybe it should be revisted because I think it would be hard to add other creation_hooks if you are using that mixin.

2022-02-04 12:24 UTC, mdellweg commented
> > ```
> > 2. The `REGISTERED_CREATION_HOOKS` should likely be decoupled from `AutoAddObjPermsMixin` entirely as they don't make sense unless you have an `AccessPolicy` configured that has a notion of `creation_hooks`.
> > ```
> 
> I remember asking @mdellweg if `REGISTERED_CREATION_HOOKS` could live on the viewset (or something similar) and just have `AutoAddObjPermsMixin` add to the value, but I think he said it wasn't possible. Maybe it should be revisted because I think it would be hard to add other creation_hooks if you are using that mixin.

I think, the core of the confusion is, that we define rules for views, but actually we want to allow access to models. So one question is, how tightly coupled Model an Viewset are. The other is how much of the logic we want to delegate to the Model. And maybe this goes very far. Permissions and Roles are already with the Model and the view always knows about the attached model. We go through a lot of complicated calls to find the hooks on the view when we only have the model (post creation hooks...).

2022-02-07 14:18 UTC, bmbouter commented on pulpcore/app/models/access_policy.py
> +            access_policy.handle_creation_hooks(self)
I got this implemented, but I haven't pushed it yet. What I need to understand though is after calling `AccessPolicyInDB.handle_creation_hooks` does it call back to the model and/or viewset? I *think* the idea is to have it call back to the model just like this PR does, but I'm a little unsure.

2022-02-07 14:20 UTC, mdellweg commented on pulpcore/app/models/access_policy.py
> +            access_policy.handle_creation_hooks(self)
It does call back, because the hooks themselves are on the viewset (or was it the model?).
Whether the hooks are enumerated by a method in the access policy or by one in the viewset, i don't care.

2022-02-07 19:46 UTC, bmbouter commented on CHANGES/plugin_api/2116.feature
> +to add object-level permissions to.
I think there possibly is something here that is new. I've reworded it; lmk what you think please.

2022-02-08 10:14 UTC, mdellweg requested changes

2022-02-08 10:14 UTC, mdellweg commented on CHANGES/2116.feature
> +permission assignment provided by the ``creation_hooks`` portion of an ``AccessPolicyFromDB``.
I am starting to wonder, what happens if you define 2 permission classes with the creation hooks interface and both hook back into the models creation hooks. Should we consider that a configuration error and document a warning?

2022-02-08 10:14 UTC, mdellweg commented on pulpcore/app/models/access_policy.py
> +        for viewset in access_policy.named_viewsets:
Why are we looking at the viewsets for the access_policy?

2022-02-08 13:42 UTC, mdellweg commented on pulpcore/app/models/access_policy.py
> +        for viewset in access_policy.named_viewsets:
```suggestion
        for viewset in self.named_viewsets:
```

2022-02-08 13:46 UTC, mdellweg commented on pulpcore/app/models/access_policy.py
> +        for viewset in access_policy.named_viewsets:
Maybe we should not loop but use the one viewset described by ACCESS_POLICY_VIEWSET_NAME

2022-02-08 16:14 UTC, bmbouter commented on CHANGES/2116.feature
> +permission assignment provided by the ``creation_hooks`` portion of an ``AccessPolicyFromDB``.
Mainly for the sake of time, I'd prefer to wait until we run into this problem to add warnings for that case.

2022-02-08 16:17 UTC, bmbouter commented
@mdellweg @gerrod3 @newswangerd here's my revised push, please review.

2022-02-08 16:28 UTC, gerrod3 commented on pulpcore/app/models/base.py
> +
Is this still needed?

2022-02-08 16:32 UTC, newswangerd commented on pulpcore/app/models/base.py
> +    def named_viewsets(self):
Does this need to be here? I don't see it used anywhere else

2022-02-08 16:46 UTC, newswangerd commented on pulpcore/app/access_policy.py
> +    def handle_creation_hooks(obj, access_policy_model_obj):
I'm wondering if `access_policy_model_obj` is the right object to pass here. If a user isn't using `AccessPolicyFromDB`, then there's not necessarily a guarantee that an access policy object for the viewset will exist in the database.

I wonder if it would be better to pass the viewset and have this function perform the DB lookup for the object? I suppose there's no way to disable the access policy initialization, so maybe it doesn't matter.

2022-02-08 16:48 UTC, bmbouter commented on pulpcore/app/models/base.py
> +    def named_viewsets(self):
It does not it was used before, but I can remove it now.

2022-02-08 16:54 UTC, bmbouter commented on pulpcore/app/models/base.py
> +    def named_viewsets(self):
pushed

2022-02-08 16:54 UTC, bmbouter commented on pulpcore/app/models/base.py
> +
I removed it.

2022-02-08 17:23 UTC, mdellweg commented on pulpcore/app/access_policy.py
> +    def handle_creation_hooks(obj, access_policy_model_obj):
I agree, the access policy already has the lookup policy statements for that. This way, we can make use of creation hooks in policies provided by any means. And this circles back nicely to the original request.

2022-02-08 17:49 UTC, mdellweg commented on pulpcore/app/access_policy.py
> +    def handle_creation_hooks(obj, access_policy_model_obj):
The other pr seems to be ahead of yours again in breaking down that function.  😆

2022-02-08 18:47 UTC, bmbouter commented on pulpcore/app/access_policy.py
> +    def handle_creation_hooks(obj):
@newswangerd @mdellweg is this what you meant? Note I didn't even include the viewset because I'm not sure why it's needed more generally.

2022-02-08 22:30 UTC, mdellweg commented on pulpcore/app/access_policy.py
> +            )
I'm not sure this warning is valuable anymore, when the whole idea of this change is based on the premise to be more flexible to different configurations.

2022-02-08 22:36 UTC, mdellweg commented on pulpcore/app/access_policy.py
> +            )
Actually i was thinking about this transformation:
https://github.com/pulp/pulpcore/pull/2166/files#diff-f3d57ed180a61179704601b8a978567bf8e5c5c54e95458ed8b0b49bbc150f3cR14

The benefit is that a subclassed AccessPolicy can just overwrite their `get_access_policy` method and still get all the glory from `creation_hooks`.

2022-02-09 15:33 UTC, mdellweg approved these changes
Now this looks so nice to me!

2022-02-09 15:33 UTC, mdellweg commented on pulpcore/app/access_policy.py
> +    def get_access_policy(viewset):
Now the nice thing is by subclassing that method, you can completely reroute the whole access policy lookup.

2022-02-09 16:04 UTC, newswangerd approved these changes

2022-02-09 16:10 UTC, gerrod3 approved these changes

2022-02-09 16:19 UTC, newswangerd requested changes

2022-02-09 16:19 UTC, newswangerd commented on pulpcore/app/access_policy.py
>      def get_policy_statements(self, request, view):
Shouldn't this be updated to use `cls.get_access_policy`?

2022-02-09 16:23 UTC, mdellweg requested changes

2022-02-09 16:23 UTC, mdellweg commented on pulpcore/app/access_policy.py
>      def get_policy_statements(self, request, view):
Oh right. Good catch!

2022-02-09 17:54 UTC, bmbouter commented on pulpcore/app/access_policy.py
>      def get_policy_statements(self, request, view):
I updated this, please let me know what you think.

2022-02-09 19:47 UTC, mdellweg approved these changes

2022-02-09 19:50 UTC, bmbouter commented
In refactoring the usage to all use the new method to find the access policy, I had to revise this implementation a bit. I learned a few things.

1) The `AttributeError` being caught was raised by `get_view_urlpattern` and specifically in cases where the view/viewset doesn't define a `urlpattern()` method. Sound familiar @newswangerd ?

2) The OrphanCleanupView is one of those views and it would need a `urlpattern()` in order for us to RBAC it. After everything does that we probably could remove the AttributeError being caught here again.

2022-02-09 20:14 UTC, merged

2022-02-10 11:27 UTC, mdellweg commented
> In refactoring the usage to all use the new method to find the access policy, I had to revise this implementation a bit. I learned a few things.
> 
>     1. The `AttributeError` being caught was raised by `get_view_urlpattern` and specifically in cases where the view/viewset doesn't define a `urlpattern()` method. Sound familiar @newswangerd ?
> 
>     2. The OrphanCleanupView is one of those views and it would need a `urlpattern()` in order for us to RBAC it. After everything does that we probably could remove the AttributeError being caught here again.

I would keep catching it and just raise a refined version of the exception with an annotation of the programming error we already identified.