Adds `PULP_API_ROOT` support to `make html`
pulp/pulpcore pull request #2236
Opened 2022-02-16 16:54 UTC by bmbouter

[noissue]

2022-02-16 16:58 UTC, bmbouter commented
@fao89 @mdellweg can you both review this plz?

2022-02-16 16:59 UTC, fao89 approved these changes
LGTM

2022-02-17 08:16 UTC, mdellweg requested changes

2022-02-17 08:16 UTC, mdellweg commented on docs/Makefile
> +PULP_V3_API_ROOT    ?= /pulp/api/v3/
```suggestion
PULP_API_ROOT    ?= /pulp/api/v3/
```

2022-02-17 17:10 UTC, mdellweg approved these changes

2022-02-17 17:51 UTC, merged