Fix delete repository version causing "duplicate key" error
pulp/pulpcore pull request #2261
Opened 2022-02-24 08:17 UTC by hao-yu

Add_and_remove task might fail with "duplicate key value violates
unique constraint" error after deleting a repository version.

closes #2047

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2022-02-24 11:28 UTC, mdellweg commented
If i read this correctly, this is also fixing an unreported bug where content was deleted from the version being deleted, added back in the next one and then redeleted at some later version. I think, i want to see a test for this.

Draft:
- Setup versions like:
  - v0:  -- pulp always starts that way
    - add: ABCDE
  - v1: ABCDE
    - delete: BCDE; add: FGHJ 
  - v2: AFGHJ -- to be deleted
    - delete: GJ; add: CD
  - v3: ACDFH  -- to be squashed into
    - delete: DH; add: EJ
  - v4: ACEFJ
- delete version 2 (to be squashed into 3)
- check the version content did not change

Do you think this covers all cases?

2022-02-25 05:41 UTC, hao-yu commented
@mdellweg yeah. you are right. Fixing that will prevent the duplicate key error when "add/remove" contents. So far, this is what I tested https://bugzilla.redhat.com/show_bug.cgi?id=2044631#c6

2022-02-25 14:26 UTC, mdellweg commented
I turned your hidden bug into it's own issue: https://github.com/pulp/pulpcore/issues/2267

2022-02-25 18:39 UTC, mdellweg commented
I added the transaction guarding the `_squash` operation with a slightly increased scope in this other PR (sill unmerged):
https://github.com/pulp/pulpcore/pull/2264/files#diff-29bc9ed3cae158e3a508ec8cfa3c61538c4ddf9c88d77f033b61005d0af9019cR949

Can you confirm that it solves your constraint issues?

2022-02-28 07:08 UTC, hao-yu commented
Hmm...what do you mean the "solves the constraints issues"? Do you mean the duplicate key error this PR? That error is happened when user "add_and_remove" contents to the repo after hitting this bug.

If you added a transaction in the "delete" routine, I think I can delete mine in the "_squash" routine since I don't think we need an inner transaction here.

Btw, select_for_update in the line below won't work. For more information please refer to https://bugzilla.redhat.com/show_bug.cgi?id=2021406#c10  read from comment 10 and https://code.djangoproject.com/ticket/33516 which is filed by @ggainey 

https://github.com/pulp/pulpcore/pull/2264/files#diff-29bc9ed3cae158e3a508ec8cfa3c61538c4ddf9c88d77f033b61005d0af9019cR952

2022-02-28 08:49 UTC, mdellweg commented
> Hmm...what do you mean "solves your constraints issues"? Do you mean the duplicate key error this PR is trying to prevent? That error is happened when user "add_and_remove" contents to the repo after hitting this bug.

I see. Thanks for that clarification.

> If you added a transaction in the "delete" routine, I think I can delete mine in the "_squash" routine since I don't think we need an inner transaction here.

That's what i wanted to say, yes.

> Btw, select_for_update in the line below won't work. For more information please refer to https://bugzilla.redhat.com/show_bug.cgi?id=2021406#c10 read from comment 10 and https://code.djangoproject.com/ticket/33516 which is filed by @ggainey
> 
> https://github.com/pulp/pulpcore/pull/2264/files#diff-29bc9ed3cae158e3a508ec8cfa3c61538c4ddf9c88d77f033b61005d0af9019cR952

I think, what you are referring to here is specific to the operation of `skip_locks=True` which we do not want to use here. The postgres row locks will still be set on the transaction level.

2022-02-28 09:00 UTC, hao-yu commented
>I think, what you are referring to here is specific to the operation of skip_locks=True which we do not want to use here. The postgres row locks will still be set on the transaction level.

Not really. Both with and without the skip_locks operation won't work. The workaround is to use the raw statement.

2022-02-28 10:55 UTC, mdellweg commented
I went ahead and wrote the test.
Can you please squash this commit into your PR and remove the xfail mark?

https://github.com/mdellweg/pulpcore/tree/test_delete_version

2022-02-28 12:37 UTC, mdellweg commented
> > I think, what you are referring to here is specific to the operation of skip_locks=True which we do not want to use here. The postgres row locks will still be set on the transaction level.
> 
> Not really. Both with and without the skip_locks operation won't work. The workaround is to use the raw statement.
> 
> One way you can test it is to run "filter(...).select_for_update().update(...)" and check the postgres log. You won't see the execution of "select for update" query

Thank you for pointing this out. Going to read to docs again now...

2022-03-01 03:51 UTC, dralley commented
@mdellweg Thank you for the test, I think it's a good one.  I have some suggestions but I think I'll just submit them as a followup PR rather than block this one

2022-03-01 04:47 UTC, hao-yu commented
Sure. Thanks for writing the test. I will try to squash the commit today or tomorrow.

2022-03-01 05:38 UTC, hao-yu commented
```
In [9]: with transaction.atomic():
   ...:     print(FileContent.objects.filter(relative_path="A").select_for_update().all()[0])
   ...:     sleep(5)
```

The documentation says "When the queryset is evaluated (for entry in entries in this case)". In the above case, it is the limit but we don't really want to return the objects.

2022-03-01 10:08 UTC, mdellweg approved these changes
Thank you for this fix.
(Without the indentation change, it is so much easier to understand.)

2022-03-01 11:53 UTC, mdellweg commented
> @mdellweg Thank you for the test, I think it's a good one. I have some suggestions but I think I'll just submit them as a followup PR rather than block this one

I agree, that we maybe can improve the logic of the queries here (Had my own share of still unsuccessful experiments...). But keep in mind that whatever we want backported probably needs to go into this PR.

2022-03-01 11:54 UTC, mdellweg commented on pulpcore/app/models/repository.py
>          # use list() to force the evaluation of the queryset, otherwise queryset is affected
This list thing is not true anymore, as you reordered update and delete.

2022-03-01 13:53 UTC, ggainey commented
> > I think, what you are referring to here is specific to the operation of skip_locks=True which we do not want to use here. The postgres row locks will still be set on the transaction level.
> 
> Not really. Both with and without the skip_locks operation won't work. The workaround is to use the raw statement.
> 
> One way you can test it is to run "filter(...).select_for_update().update(...)" and check the postgres log. You won't see the execution of "select for update" query

I am late to this party, apologies - was on PTO.

 I opened django-33516 for my problem trying to get select_for_update() to work for a bulk_update operation. The Django Team corrected my approach in https://code.djangoproject.com/ticket/33516#comment:1 (which I used to gleefully replace my raw-sql). In the use I see here, select_for_update() should work fine.

One note: we need to make sure to order_by() before select_for_update(). Otherwise,  select_for_update() will lock rows in arbitrary order; in heavy-concurrency contexts with overlapping content, this can (and will!) lead to deadlocks.  We prob want an issue/fix for this (assuming I'm reading the code correctly, which I may not be...)

(Note for clarity: I'm talking about the s_f_u() here : https://github.com/pulp/pulpcore/pull/2264/files#diff-29bc9ed3cae158e3a508ec8cfa3c61538c4ddf9c88d77f033b61005d0af9019cR955 )

2022-03-01 14:23 UTC, dralley commented
>One note: we need to make sure to order_by() before select_for_update(). Otherwise, select_for_update() will lock rows in arbitrary order; in heavy-concurrency contexts with overlapping content, this can (and will!) lead to deadlocks. We prob want an issue/fix for this (assuming I'm reading the code correctly, which I may not be...)

@ggainey That shouldn't be the case - it was the case for content because multiple tasks can work w/ them at the same time, but that should not be true for repository versions.  There's external locking in place that should prevent that.

2022-03-01 14:39 UTC, hao-yu commented
Hmm... Good to know this approach https://code.djangoproject.com/ticket/33516#comment:1 but I am still feel that it is still not quite handy for chaining methods. :)

2022-03-01 19:50 UTC, ggainey commented
> > One note: we need to make sure to order_by() before select_for_update(). Otherwise, select_for_update() will lock rows in arbitrary order; in heavy-concurrency contexts with overlapping content, this can (and will!) lead to deadlocks. We prob want an issue/fix for this (assuming I'm reading the code correctly, which I may not be...)
> 
> @ggainey That shouldn't be the case - it was the case for content because multiple tasks can work w/ them at the same time, but that should not be true for repository versions. There's external locking in place that should prevent that.

If there's external locking, then what are we accomplishing with the select_for_update()? Is it possible for us to collide while doing different kindsof-things on the same repo (eg, sync and copy-into and add-content all at the same time) (yes, this would be Weird, but users have done stranger things)

I've spent a lot of time recently debugging odd ways that bulk-operations on postgres can cause deadlocks in very non-obvious ways.

2022-03-01 20:07 UTC, ggainey commented
> Also i see a bunch of RowShareLock instead of AccessShareLock without the select_for_update. I do not understand why it results in shared row locks though. @ggainey do you know more?

RowShareLock isn't actually a row lock - it's a lock-mode on the affected table, with an unfortunate name "for historical reasons". Alas. See https://www.postgresql.org/docs/12/explicit-locking.html#LOCKING-TABLES for commentary.

However - I don't know that this answers your question (or matches what you're seeing?) If this is still a problem, peruse the docs on locks, and if what you're seeing still doesn't match, let's look at the logging together to see what's going on.

2022-03-01 20:07 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +            version_removed_id_content_id_map.setdefault(repo_rel.version_removed_id, []).append(
This would be much more readable to be if `version_removed_id_content_id_map` were defined as `version_removed_id_content_id_map = defaultdict(list)`.

2022-03-01 20:08 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +        for repo_rel in repo_relations.filter(
This would be more readable if the qs was defined on the line above and given a name.

2022-03-01 20:10 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +        for repo_rel in repo_relations.filter(
Also `repo_rel` tells me the object type but not really what is issssss. Naming is hard, but I think another name here would be helpful.

2022-03-01 20:11 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +        for version_removed_id, content_ids in version_removed_id_content_id_map.items():
A single comment above this line would be helpful describing the overall for-loop updating.

2022-03-01 20:12 UTC, bmbouter commented on pulpcore/app/models/repository.py
>          # use list() to force the evaluation of the queryset, otherwise queryset is affected
+1 and +1 to doing it later

2022-03-01 20:14 UTC, bmbouter requested changes
I ran this code via its test locally and overall it's great. I'm asking for some reworking only for readability. This code is in a complicated area so I'm striving to have it be as readable as possible. If these requests don't make sense or aren't clear about what do to please comment and let me know. I'm hoping each of the changes is straightforward and easy.

2022-03-02 15:03 UTC, bmbouter approved these changes
This addresses my concerns, thanks!

2022-03-02 15:07 UTC, mdellweg requested changes
Let's request adding that changelog.
Sorry for the inconvenience.

2022-03-02 16:52 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
> +@pytest.mark.parallel
@mdellweg @bmbouter  Will it need manual backports because of this?

2022-03-02 17:40 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
> +@pytest.mark.parallel
No I expect it will just run linearly with the other tests instead if the older test-runner isn't parallel-aware.

2022-03-02 20:14 UTC, dralley approved these changes
Thanks for the investigation and the fix @hao-yu !

2022-03-03 08:51 UTC, mdellweg approved these changes

2022-03-03 08:54 UTC, mdellweg commented
The failed test is unrelated. I see 3 approvals. We are good to merge.

2022-03-03 08:55 UTC, merged

2022-03-03 09:39 UTC, mdellweg commented
The cherry-picking fails, because we do have the pytest fixtures on these old branches. I am not going to rewrite the test, so the question is should we backport without the test, or should we make the pytest things available on the old release branches? I think we will encounter this problem with more bugfixes (that should always be accompanied by tests) in the future.
@bmbouter ?