Fix new-task-system migration to clean up task and taskreservedresource.
pulp/pulpcore pull request #2295
Opened 2022-03-02 21:16 UTC by ggainey

fixes #2101
[nocoverage]

2022-03-02 21:19 UTC, ggainey commented
This is a WIP while I try to coerce a dev-env to start at core/3.7, with entries in core_task and core_taskreservedresource, and then upgrade to core/3.14 with this change. Early eyes are appreciated, however.

2022-03-03 09:06 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
>          task.save()
If i didn't write this migration long ago, I would have used `batch_update` here. XD

2022-03-03 09:06 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.filter(state__in=TASK_FINAL_STATES).delete()
Should we keep tasks that are some kind of recent?

2022-03-03 09:06 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
>  def noop(apps, schema_editor):
I know now: There is a `migrations.RunPython.noop`...

2022-03-03 09:06 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +        migrations.RunPython(
If you really want to gain something from this operation, you should do it before the `copy_reserved_resource_record` (the one that happened to take >= 1h on loaded systems).

2022-03-03 13:06 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.filter(state__in=TASK_FINAL_STATES).delete()
Good question. In this instance, it's only an issue if you were running pre-3.14 (old task system), and are now upgrading to 3.14 (or later) and the new tasking system. I don't have a strong opinion one way or another. Maybe "complete and older than 10 days"?

2022-03-03 13:07 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +        migrations.RunPython(
Yes - I actually moved these ahead of the Alter... stmts, just haven't pushed the change yet. GMTA! :)

2022-03-03 13:44 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.filter(state__in=TASK_FINAL_STATES).delete()
Of course, if we keep most-recent, then in a very common usecase (core/3.7 used to do 2to3 migration followed immediately by upgrade to core/3.14), we won't have much impact on the number of tasks - since many/most of them will have been created "recently". Thoughts?

2022-03-03 14:38 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.filter(state__in=TASK_FINAL_STATES).delete()
Right. The reason for this is to keep the migration time low. So a number of tasks to keep would do that but that does not sound like the thing we should do unless that number is zero.
Let's keep it that way.

2022-03-03 20:16 UTC, dralley approved these changes

2022-03-04 08:12 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            reverse_code=noop,
```suggestion
            reverse_code=migrations.RunPython.noop,
```

2022-03-04 08:15 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
>          task.save()
If the mass deletion of tasks is not working, this is really the data migration where we can gain a lot of performance by performing the update in batches.

2022-03-04 15:54 UTC, ggainey commented
@mdellweg @dralley Rather than delete task-entries, I've moved to bulk_update to try and address the performance issue. More eyes again, please.

2022-03-04 16:18 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in tasks_qs:
Set `.only("reserved_resources_record")` on the `tasks_qs` so you're only extracting the data you want to work with.  

And I think if you want to just use the queryset directly you can use `.update()` instead of `.bulk_update()`.

If the list of tasks is too massive you might want to use `.iterator()` and stick with `.bulk_update()` but do the batching manually.  I'm not sure how big it is, it would probably have to be >100k for that to start making sense.

2022-03-04 16:52 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in tasks_qs:
"reserved_resources_record" is a ManyToMany, not a field, and can't be used for only(). Tasks are also pretty small, so I don't think this saves us much.

My understanding of update() vs bulk_update(), is that update() is going to do one db-update per entity, where bulk_update() is going to do one db call per-batch.

2022-03-04 17:31 UTC, dralley approved these changes

2022-03-04 18:06 UTC, ggainey commented
I'm un-drafting this - still needs more eyes, tho

2022-03-07 09:49 UTC, mdellweg requested changes

2022-03-07 09:49 UTC, mdellweg commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.bulk_update(tasks_qs, ["_reserved_resources_record"], 1000)
I don't think, that is, how it works. You would need to collect the updated task objects from line 20 and pass those to bulk_update. Also i would do the batching in python to have a cap on memory consumption.
See example here: https://github.com/pulp/pulpcore/blob/main/pulpcore/app/migrations/0086_task_json_fields.py#L26

2022-03-08 18:59 UTC, dralley commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    for task in tasks_qs:
I don't think that's correct, the difference is that `update()` does its work entirely in the database so there's less marshalling, but it's also less flexible because of that, you can't update using complex python logic like you can with `.bulk_update()`

The docs actually mention that `.bulk_update()` uses `.update()` internally.

https://docs.djangoproject.com/en/4.0/ref/models/querysets/#bulk-update

2022-03-09 19:07 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.bulk_update(tasks_qs, ["_reserved_resources_record"], 1000)
You are correct, current version does the deed and updated 1K tasks in ~4s for the entire migrate-invocation.

2022-03-09 19:08 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +            reverse_code=noop,
:+1:

2022-03-09 19:08 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
>          task.save()
Changed to use batch-update

2022-03-09 19:09 UTC, ggainey commented on pulpcore/app/migrations/0064_add_new_style_task_columns.py
> +    Task.objects.filter(state__in=TASK_FINAL_STATES).delete()
batch-update addresses the performance-issue, and means we don't have to "guess" how many tasks to leave around.

2022-03-09 20:17 UTC, dralley approved these changes

2022-03-10 07:04 UTC, mdellweg approved these changes
I still don't get, what kind of data migration you can mix with schema migrations, and where it breaks, but future me will try to always separate data from schema migrations.

Thanks for working on this!

2022-03-10 07:07 UTC, merged