Adds TASK_DIAGNOSTIC setting and docs
pulp/pulpcore pull request #2331
Opened 2022-03-11 17:44 UTC by bmbouter

closes #2329

2022-03-11 17:53 UTC, bmbouter commented
It produces image files like this one:

![memory](https://user-images.githubusercontent.com/180319/157922980-f57ea58c-beda-4018-9ccc-bdaa197621ef.png)

2022-03-11 17:58 UTC, bmbouter commented
@pulp/core FYI here's one of the next-steps that came out of the memory PoC.

2022-03-11 19:47 UTC, dralley commented on pulpcore/plugin/stages/api.py
> +    taskdata_dir = Path("/var/tmp/pulp") / str(current_task.pulp_id)
We should make `/var/tmp/pulp/` into a constant somewhere.

I'm not sure we should put it here, it kind of makes sense that this should be enabled for *all* tasks and not just sync tasks yes?  It would be cleaner to make it part of the heartbeat.

2022-03-11 20:17 UTC, mdellweg commented on docs/configuration/settings.rst
> +    If ``True``, have each task will record various diagnostics (listed below) to files in the dir
```suggestion
    If ``True``, each task will record various diagnostics (listed below) to files in the dir
```

2022-03-11 20:18 UTC, mdellweg commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +    plot "memory.datum"
Can we add names and units to the axes here?

2022-03-11 20:20 UTC, mdellweg commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +3) Open your png chart saved at memory.datum
```suggestion
3) Open your png chart saved at memory.png .
```
If you don't "set output", you might end up with an interactive plot window, even. Why do you think we should do?

2022-03-14 14:26 UTC, bmbouter commented on pulpcore/plugin/stages/api.py
> +    taskdata_dir = Path("/var/tmp/pulp") / str(current_task.pulp_id)
I'm moving it to a constant. Also yes I do think this should be for all tasks. I'm going to rework it. Yes I think it will need to be part of the worker machinery. I'll look around and revise it. Suggestions are welcome.

2022-03-14 14:28 UTC, bmbouter commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +3) Open your png chart saved at memory.datum
I'll try it without the `set output`. I know very little about gnuplot lol. This work was inspired by your herminig plots.

2022-03-14 15:27 UTC, bmbouter commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +3) Open your png chart saved at memory.datum
It errored on my dev environment which makes sense because it does not have a window manager env. I'll leave it in for now.

2022-03-14 15:36 UTC, bmbouter commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +    plot "memory.datum"
done.

2022-03-14 15:37 UTC, bmbouter commented on pulpcore/tasking/pulpcore_worker.py
> +    if settings.TASK_DIAGNOSTICS:
This runs in the child process and the memory reporting includes all threads.

2022-03-15 08:46 UTC, mdellweg commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +3) Open your png chart saved at memory.datum
That's actually the big question: Would you pull the data or the image processed from the data off of your server.
In production, i would probably not have gnuplot installed on the box. Then again, you may not want to do such a thing on a production box...
In the end the data to some file processing the most flexible solution.

2022-03-15 08:49 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +            file.write(f"{current_mb_in_use:.2f}\t\n")
Can we write two columns with timestamp and memory use?

2022-03-15 08:52 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +        normal_thread.start()
Can we signal that thread after the work is done to write one last record and quit?
So we get at least 2 records from tasks running in less than 5 sec.

Also i was wondering whether we could monitor the memory from the other process in `supervise_task`. But at least for more detail information than just memory we probably need to be _in_ the child task.

2022-03-15 15:48 UTC, bmbouter commented
With the most recent revisions it now has a data format like this:

```
# Seconds       Memory in MB
0       102.22
5       133.05
10      133.82
15      135.88
20      136.39
25      142.64
30      142.90
35      143.16
40      143.16
```

And the charting now looks like this:
![memory](https://user-images.githubusercontent.com/180319/158416982-5be5a1c9-8e3c-4187-abd2-ea050e9f89ca.png)

2022-03-15 15:58 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    if settings.TASK_DIAGNOSTICS:
Including the one doing the reporting. Very quantum this ...

2022-03-15 16:03 UTC, mdellweg requested changes

2022-03-15 16:03 UTC, mdellweg commented on docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
> +3) Open your png chart saved at memory.datum
The suggested change is still pending, thou.

Shouldn't ask two things in one email.

2022-03-15 16:06 UTC, bmbouter commented on pulpcore/tasking/pulpcore_worker.py
> +        normal_thread.start()
In this case the error I don't think is significant enough to make spending additional time on it a  good use of time relative to the many other things we are supposed to do.

2022-03-15 16:06 UTC, bmbouter commented on pulpcore/tasking/pulpcore_worker.py
> +        normal_thread.start()
I hear you though.

2022-03-15 17:14 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +        normal_thread.start()
I can live with that, but lets go ahead and  at least

A) file an issue for that limitation
B) leave a TODO in the code mentioning it

It would suck if this bit someone and it wasn't immediately obvious from the code why that was the case

2022-03-15 17:15 UTC, dralley approved these changes
Approve in principle, although I do strongly prefer we closed the hole which @mdellweg mentioned.  See comment about marking this issue at miminum

2022-03-15 17:24 UTC, bmbouter commented
I filed this to capture the concern https://github.com/pulp/pulpcore/issues/2337

I'll push the TODO now

2022-03-15 22:37 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    if settings.TASK_DIAGNOSTICS:
The other thing that makes me a bit wary is that we introduce another notion of concurrency here. (We already use subprocess for the task itself, which may use the async loop and at the same time we have adhoc asynchronicity non-blockability in the main pulp_worker process. `supervise_task` already returns regular-ish to heartbeat, it is probably easy to add some subtask diagnostic there too.

2022-03-15 22:38 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    if settings.TASK_DIAGNOSTICS:
I've seen you opened an issue about that: https://github.com/pulp/pulpcore/issues/2337

2022-03-15 22:41 UTC, mdellweg approved these changes

2022-03-16 00:27 UTC, merged

2022-03-16 00:28 UTC, dralley commented
@bmbouter I'm merging this to be able to use it in testing your other PR, hope you don't mind!