Update the auth docs
pulp/pulpcore pull request #2399
Opened 2022-03-23 18:58 UTC by bmbouter

closes #2260

2022-03-23 20:39 UTC, gerrod3 approved these changes
Looks good, but I guess this means by default RBAC won't be supported for users using external authentication databases and wishing to not duplicate the users in the Pulp DB. We should probably discuss this some more in RTFM and decide on further action, but getting this docs out for currently affected users would be helpful.

2022-03-24 07:05 UTC, mdellweg requested changes

2022-03-24 07:05 UTC, mdellweg commented on docs/authentication/webserver.rst
> +    ]"
This too should be in the how to use dynaconf section.

https://docs.pulpproject.org/pulpcore/configuration/applying.html

2022-03-24 11:35 UTC, ipanova commented on docs/authentication/overview.rst
> +        'guardian.backends.ObjectPermissionBackend',  # Django-guardian based obj level permissions
+1 to leave a note that with 3.20 we're removing guardian form the stack

2022-03-24 11:43 UTC, ipanova commented on docs/authentication/webserver.rst
> +set the ``DEFAULT_PERMISSION_CLASSES`` to check permissions differently or not at all. To only
maybe worth mentioning that the default is `AccessPolicyFromDB` and it needs to be changed ( as you've already stated)

2022-03-24 15:53 UTC, bmbouter commented on docs/authentication/webserver.rst
> +    PULP_AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.RemoteUserBackend']
I have mixed feelings on it too. Yes I'll remove these on this PR at least and maybe we can improve the dynaconf section later.

2022-03-24 15:55 UTC, bmbouter commented on docs/authentication/webserver.rst
> +    PULP_AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.RemoteUserBackend']
OK but here's the tricky part, the thing I'd be removing would be the "config-file" based one because ultimately the env var approach is the only real default for Pulp.

2022-03-24 17:33 UTC, bmbouter commented
@ipanova @mdellweg Thanks for all the input. wdyt of the revised version?

2022-03-24 17:36 UTC, bmbouter commented
Also here's the link to the docs issue to improve the config dynaconf stuff with examples: https://github.com/pulp/pulpcore/issues/2417  I can probably work on that here soon too.

2022-03-25 09:51 UTC, mdellweg commented on docs/authentication/overview.rst
> +        'guardian.backends.ObjectPermissionBackend',  # Django-guardian based obj level permissions
If we go all sale on roles, there would be no permissions assigned directly to users, and the ModelBackend will have nothing left to report, as far as I understand.

2022-03-25 10:18 UTC, mdellweg approved these changes

2022-03-25 10:58 UTC, bmbouter commented on docs/authentication/overview.rst
> +        'guardian.backends.ObjectPermissionBackend',  # Django-guardian based obj level permissions
Mmmm perhaps that will happen then. Anyways when it happens we can change it then.

2022-03-25 10:58 UTC, merged