Enable bypassing DB encryption [#2466]
pulp/pulpcore pull request #2469
Opened 2022-03-31 21:49 UTC by dannysauer

Alter behavior of field-level encryption such that a false value in DB_ENCRYPTION_KEY results in bypassing the encryption and decryption of "encrypted" text field data

Fixes #2466

PR is initially expecting to solicit input.  In particular, I'd like to know if this approach seems like the most reasonable approach (it seemed like the least invasive way to mess with the code), and I'd like to know if it's appropriate to leave without a "decrypt migration".  Presumably it would be possible to add a `old_encryption_key` parameter or something like that which could be used as a one-off to decrypt the DB with a migration if someone decided to turn off encryption.  Perhaps addressing the logic to decrypt would help resolve #2048; there's just be a two-step process where the current key is moved to the old key, and then the DB is reencrypted with the new key (which could be empty in this case, or a new key in that case).  In any event, I'm not sure how to do a conditional migration or if migration is the right facility - I guess it'd have to be based on 1) old key parameter is present and 2) the value of the old key hasn't already been subjected to a migration.

2022-03-31 22:09 UTC, dannysauer commented
Also exciting that the test case seems to at least catch some kind of error (whether it's in the case or the code being tested, though...). :D

2022-04-01 08:36 UTC, mdellweg commented on pulpcore/tests/unit/models/test_remote_unencrypted.py
> +        settings.DB_ENCRYPTION_KEY = False
I think, i've seen a decorator before to mock a setting for a single test.

2022-04-01 08:50 UTC, mdellweg commented on pulpcore/tests/unit/models/test_remote_unencrypted.py
> +        settings.DB_ENCRYPTION_KEY = False
I do not understand how it is supposed to work there (as it does not seem to be a unittest), but here it should just do the trick:
https://github.com/pulp/pulpcore/blob/main/pulpcore/tests/functional/api/test_status.py#L112

2022-04-01 15:17 UTC, dannysauer commented on pulpcore/tests/unit/models/test_remote_unencrypted.py
> +        settings.DB_ENCRYPTION_KEY = False
Well, that didn't have the intended result.
https://docs.djangoproject.com/en/4.0/topics/testing/tools/#overriding-settings has several options.  Either way, I should really just follow the directions and set up local testing instead of burning all of the project's Github Actions minutes. :D

Thinking about it, I also probably should have just added another test in the test_remote.py instead of creating a whole new file. 🤦

2022-04-04 12:12 UTC, ipanova commented on docs/configuration/settings.rst
> +  If this parameter is set to boolean false or 0, the encryption is bypassed and values are stored
i'd add a separate boolean config option to not overload already existing DB_ENCRYPTION_KEY.
We'd need to also update our repair command @dralley has added to check whether the pulp encryption is on/off https://github.com/pulp/pulpcore/blob/main/pulpcore/app/management/commands/datarepair-2327.py

2022-04-04 12:12 UTC, ipanova commented on docs/configuration/settings.rst
> +  in plain test. Warning: values which are already encrypted are not decrypted if this setting is
s/test/text

2022-04-04 12:21 UTC, ipanova commented
@dannysauer for  the existing installation that would want to turn off the encryption we could provide management command similar to the repair that would be decrypting the fields based on what's the settings

2022-04-04 12:33 UTC, dannysauer commented on docs/configuration/settings.rst
> +  in plain test. Warning: values which are already encrypted are not decrypted if this setting is
Hah. Plain test. 🤦‍♂️

2022-04-04 18:08 UTC, bmbouter commented on pulpcore/app/settings.py
> +    or (not DB_ENCRYPTION_KEY)
JFYI, check out this PR also, which will probably merge conflict with this. If this merged I think that's fine otherwise it'll need some conflict resolution. https://github.com/pulp/pulpcore/pull/2453

2022-04-04 18:13 UTC, bmbouter commented
Overall I'm ok with users to have the option to disable the encryption, so +1 whenever the other reviewer's comments are addressed. @dannysauer ty for opening this!

2022-04-04 18:37 UTC, dannysauer commented
FWIW, I'm on vacation this week, so may or may not get a chance to promptly address all that good feedback. Just sharing so no one thinks It's been dropped on the floor. :)

2022-04-19 13:46 UTC, goosemania commented
@dannysauer , would you have a moment to look at this PR?

2022-04-19 20:52 UTC, dannysauer commented
> @dannysauer , would you have a moment to look at this PR?

Vacation took longer than I thought. ;)

I'm back on figuring this out this week. Thanks for following up.

2022-05-03 13:21 UTC, dralley commented
@dannysauer Ping, status update?

2022-08-22 07:27 UTC, attenuation commented
Hi, i will take over this pr, So anyone can help me to active this PR from the draft status?

2022-08-22 09:34 UTC, dannysauer commented
> Hi, I will take over this pr, So Can anyone help me to active this PR from the draft status?

There you go. :)

(sorry; I changed jobs and don't use pulp now - and haven't had time to work on it. Thanks for picking it back up, @attenuation)

2022-08-22 18:10 UTC, bmbouter commented
@dannysauer I totally understand. Thank you just the same.

@attenuation welcome, there are some linting issues. Please squash your commits to one migration, and also look at the flake8 and/or black errors. I'll also leave some comments now. Please ask any questions you have; we want to make this as easy a contribution process as possible! FYI we have a [new dev env](https://github.com/pulp/oci_env) in case that is helpful.

2022-08-22 18:12 UTC, bmbouter commented on docs/configuration/settings.rst
> +  If this parameter is set to boolean false or 0, the encryption is bypassed and values are stored
```suggestion
If ``False`` the at-rest database encryption is not used and values are stored
```

2022-08-22 18:13 UTC, bmbouter commented on docs/configuration/settings.rst
> +  If this parameter is set to boolean false or 0, the encryption is bypassed and values are stored
Also please state that the default is True (with True surrounded by double backticks which is needed for RST escaping in Sphinx.

2022-08-22 18:13 UTC, bmbouter commented on docs/configuration/settings.rst
> +  in plain text. Warning: values which are already encrypted are not decrypted if this setting is
This warning can become it's own line below and use the RST directive for it. See this example https://github.com/pulp/pulpcore/blob/5c84ab71928aef83a37bc97b5eda7d2a60463807/docs/configuration/settings.rst#L119

2022-08-22 18:15 UTC, bmbouter commented on pulpcore/app/models/fields.py
> +        self.skipencryption = not settings.DB_ENCRYPTION
I'd prefer to not set this and instead have the if statements below use: `if not settings.DB_ENCRYPTION` to keep fewer moving parts.

2022-08-22 18:17 UTC, bmbouter commented on pulpcore/app/settings.py
> +    or (not DB_ENCRYPTION or not DB_ENCRYPTION_KEY)
:+1:

2022-08-22 18:18 UTC, bmbouter commented on pulpcore/tests/unit/models/test_remote.py
> +    @override_settings(DB_ENCRYPTION=False)
nice test. :+1:

2022-08-23 08:09 UTC, mdellweg commented on CHANGES/2466.feature
> +Note: does not decrypt already encrypted values
We do have a management command to repair these fields when a certain bug encrypted them an unpredictable amount of times. Do you think we can come up with another management command that allows for encrypting/decrypting/re-encrypting them?
cc @dralley

2022-08-23 08:22 UTC, ipanova commented on docs/configuration/settings.rst
> +  in plain text. Warning: values which are already encrypted are not decrypted if this setting is
@bmbouter I feel uneasy to leave existing fields encrypted. We basically say for existing/upgraded installations there is no way to turn off the encryption consistently, unless this is a brand new fresh install. Is this the message we're sending?

2022-08-23 13:49 UTC, dralley commented on CHANGES/2466.feature
> +Note: does not decrypt already encrypted values
We probably could, yes.

2022-08-23 18:49 UTC, bmbouter commented on docs/configuration/settings.rst
> +  in plain text. Warning: values which are already encrypted are not decrypted if this setting is
With this being a driven entirely by community contribution, to me, it's kind of up to them how much they want to do. My perspective is that if a community contributor only wants to go so far, it's up to the next community user who wanted it to go further to make their contribution at a later time.

That being said I hear where you're coming from. There is a judgement call from project maintainers for what we think is responsible to accept on behalf of the user base. For me, I'd be willing to accept this without commands to fix it on existing in-use installations because it's clearly labeled as such. The best case is @attenuation is willing to make commands to handle that case too. If not though, I'll defer to you (happily) on whether to accept or not. If you want to require more I would understand. Use the required changes I think to indicate your desires there and I would +1 it.

2022-08-24 15:43 UTC, ipanova commented on docs/configuration/settings.rst
> +  in plain text. Warning: values which are already encrypted are not decrypted if this setting is
@bmbouter looking at it this way i am comfortable to not have a repair command. Thank you for sharing your perspective!

2022-08-29 07:21 UTC, attenuation commented
@bmbouter I just squash my commit, but the first commit is too old, I can't squash it.

2022-08-29 08:28 UTC, mdellweg commented
> @bmbouter I just squash my commit, but the first commit is too old, I can't squash it. And about the repair command, I am sorry I can not do this because I am not very familiar with this project.

You probably need to rebase then.
And the added management command is an additional idea for sure. Don't bother about it. We can have that as a followup piece.

2022-08-30 09:14 UTC, mdellweg requested changes

2022-08-30 09:14 UTC, mdellweg commented on pulpcore/app/settings.py
> +    or (not DB_ENCRYPTION or not DB_ENCRYPTION_KEY)
is this the same as `if not (...) and DB_ENCRYPTION and DB_ENCRYPTION_KEY`?
Should we maybe instead validate that `DB_ENCRYPTION_KEY` must be set if `DB_ENCRYPTION` and then just have `... and DB_ENCRYPTION` here?

2022-08-30 09:14 UTC, mdellweg commented on pulpcore/app/management/commands/datarepair-2327.py
> +                                field_value = force_str(fernet.decrypt(force_bytes(field_value)))
This will lead to in infinite loop.
I think we should exit the repair command right away it encryption is disabled.

2022-09-13 13:51 UTC, dkliban commented
@attenuation Are you still working on this? How can we help you move this work forward?

2022-10-18 13:49 UTC, closed without merging