Make tests independant
pulp/pulpcore pull request #2479
Opened 2022-04-04 19:57 UTC by bmbouter

To avoid errors the pulpcore tests have been updated to leave to objects
except FileContent and Tasks behind. Also all tests are now independant.

[noissue]

2022-04-04 20:01 UTC, bmbouter commented
@pulp/core This PR attempts to:

1. Combine tests that depend on the changes made by other tests into one test. Do this by leaving the individual tests as function calls and make a new "workflow" style test that is longer and calls them. This hopefully will allow us to later break them down into smaller tests possible

2. Move all stateful data out of `setUpClass` and into `setUp` and similarly 

3. Add actual cleanup handlers for all objects, so now all pulpcore tests leave behind only orphans and task records. This was verified locally using the pytest snippet here https://discourse.pulpproject.org/t/making-tests-totally-independent/412 That isn't going into the code right now so it's not part of this PR.

Please review and I hope to merge soon because I need this in order to have the pulp_file tests run after the pulpcore tests (separate PR to follow for that part).

2022-04-05 14:22 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_content_cache.py
> +            monitor_task(task_href)
Miss cleaning up the distros in `self.distro2`.

2022-04-05 14:36 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
> +        self.assertEqual(exc.exception.response.status_code, 400)
Weird that this wasn't raising an exception before.

2022-04-05 15:10 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_content_cache.py
> +            monitor_task(task_href)
That's handled [here](https://github.com/pulp/pulpcore/pull/2479/files#diff-9570e781202e07282a657bd3316b2badb8b1a0b4e71964828f26b313a528631cR135). This is one of the confusing things about these long workflow tests it's like um did I get them all? Also that's the great thing about [this tool](https://discourse.pulpproject.org/t/making-tests-totally-independent/412).

2022-04-05 15:18 UTC, ggainey requested changes

2022-04-05 15:18 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
> +    def _setup_repositories(self):
FilesystemExport tests need to sync the target-repos once - needs to be "workflow'd", to avoid syncing for every test.

2022-04-05 15:18 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
> +    def _setup_repositories(self):
est_pulpexport needs a workflow just like pulpimport - otherwise we'll run the repo-setup-sync for every test, which is horribly inefficient.

2022-04-05 15:18 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_purge.py
> +    def tearDown(self):
purge as it exists is def order-dependent, and doesn't want to sync more than once. However, the sync is on-demand of a small(ish) repo, and I think this particular suite prob needs to just be refactored to take better advantage of the workflow-infra. I don't know that that needs to happen as part of this PR.

2022-04-05 15:23 UTC, bmbouter commented on pulpcore/tests/functional/api/using_plugin/test_distributions.py
> +        self.distribution = self.client.get(distribution["pulp_href"])
fixed in my next change, ty

2022-04-05 17:45 UTC, bmbouter commented
My eventual goal is to reduce runtime, so I was happy to workflow-ize these. @ggainey the latest version does that. I also ran a few experiments to see how much this request benefited us (or how much not doing it would have slowed us down).

I ran those specific test classes with `pytest -v -r sx --color=yes devel/pulpcore/pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py devel/pulpcore/pulpcore/tests/functional/api/using_plugin/test_pulpexport.py devel/pulpcore/pulpcore/tests/functional/api/using_plugin/test_pulpimport.py -x`

against pulp/main @ 0b7c22ca99bebaa3af8506cc8a039f21ed95734b - `it was 35 passed, 1 skipped, 30 warnings in 98.67s (0:01:38)`

before ggainey's requested changes @ d421d37d51d02707629020f3adee6e22f9c81e9b   -  `23 passed, 1 skipped, 30 warnings in 198.27s (0:03:18)`

after ggainey's requested changes @ 42f7429c3bf6872ba7e699e21faece6315d83160 - `5 passed, 30 warnings in 94.00s (0:01:33)`

2022-04-05 17:52 UTC, ggainey approved these changes

2022-04-05 17:56 UTC, gerrod3 approved these changes

2022-04-05 18:19 UTC, merged