Loosened import version-restriction to x.y instead of x.y.z.
pulp/pulpcore pull request #2497
Opened 2022-04-08 13:54 UTC by ggainey

closes #2269

2022-04-09 10:48 UTC, mdellweg commented on docs/workflows/import-export.rst
> +been synchronized using ``policy=on_demand``. :term:`Artifacts<Artifact>` must actually
and "streamed"

2022-04-11 10:22 UTC, ipanova commented on pulpcore/app/tasks/importer.py
> +            if version.split(".")[:2] != component["version"].split(".")[:2]:
maybe this is a bit more readable? `version[:version.rfind(".")]`

2022-04-11 17:34 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +            if version.split(".")[:2] != component["version"].split(".")[:2]:
> maybe this is a bit more readable? `version[:version.rfind(".")]`

Can't use rfind() - dev-versions look like 3.19.0.dev. I ha dseveral attempts, they were all ugly. How about I just add comment describing what we're doing?

2022-04-11 18:25 UTC, ipanova commented on pulpcore/app/tasks/importer.py
> +            if version.split(".")[:2] != component["version"].split(".")[:2]:
I see. Then yeah leaving a lone line comment would do.

2022-04-11 18:28 UTC, ipanova approved these changes

2022-04-11 18:31 UTC, ipanova requested changes
Actually,  I am removing my approval before @ggainey  starts to  yell at me. I will wait until suggestions are pushed :D

2022-04-12 02:03 UTC, dralley commented
Does this need backports to 3.15, 3.14?

2022-04-12 04:19 UTC, dralley commented
Adding this as a 3.19 blocker

2022-04-12 07:54 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +            if version.split(".")[:2] != component["version"].split(".")[:2]:
Also the logic is slightly different. With rfind we'd compare "all but the last segment", with split we compare "the two most significant ones".

2022-04-12 09:51 UTC, ipanova commented on pulpcore/app/tasks/importer.py
> +            if version.split(".")[:2] != component["version"].split(".")[:2]:
For the production installation both logic would be interchangeable.

2022-04-12 13:18 UTC, ggainey commented
> Does this need backports to 3.15, 3.14?

Currently only requested for 3.16 by stakeholder.

2022-04-12 16:06 UTC, dralley commented on docs/workflows/import-export.rst
> +all the only way for the Downstream Pulp instance to gain access to them!
Strictly speaking this is only true if the downstream Pulp is disconnected.  I think that is probably the most common case though.

2022-04-12 16:07 UTC, dralley commented on docs/workflows/import-export.rst
> +These default to empty, if not explicitly set attempts to import or export will fail
This flows a little strangely, do you think this would be an improvement

> These default to empty - if they are not explicitly set, to import or export will fail

2022-04-12 16:15 UTC, dralley commented on docs/workflows/import-export.rst
> +all the only way for the Downstream Pulp instance to gain access to them!
What I mean though is that there's no law that says you're only allowed to import / export if you have a disconnect systems.

2022-04-12 16:20 UTC, ggainey commented on docs/workflows/import-export.rst
> +all the only way for the Downstream Pulp instance to gain access to them!
Export absolutely will fail if a piece of content doesn't have an Artifact, because the overarching use-case for this feature is "the downstream has no internet access and therefore requires all the Artifacts be imported".

2022-04-12 16:33 UTC, dralley commented on docs/workflows/import-export.rst
> +all the only way for the Downstream Pulp instance to gain access to them!
I see now that there's some clarification about the use case a bit further up in the docs, but maybe we should make it clear that this isn't really intended to be a general backup solution either (along with not being related to pulp-to-pulp sync).

I just noticed a typo though.

> **i** :term:`Artifacts<Artifact>`

2022-04-12 17:21 UTC, dralley approved these changes

2022-04-12 17:23 UTC, merged