Add pulpcore pytest fixtures from pulp-smash
pulp/pulpcore pull request #2562
Opened 2022-04-19 18:35 UTC by bmbouter

The pulpcore fixtures are moving from pulp-smash to pulpcore so that
they can be versioned properly with pulpcore.

Required PR: https://github.com/pulp/pulp-smash/pull/1291

[noissue]

2022-04-20 12:25 UTC, mdellweg requested changes

2022-04-20 12:25 UTC, mdellweg commented on setup.py
> +        "pytest11": ["pulpcore = pulpcore.tests.functional"],
Let's not make this a pytest plugin but load the fixtures explicitely.

2022-04-20 12:25 UTC, mdellweg commented on pulpcore/tests/functional/__init__.py
> +@pytest.fixture(scope="session")
This should probably go into conftest.

2022-04-20 13:29 UTC, bmbouter commented on setup.py
> +        "pytest11": ["pulpcore = pulpcore.tests.functional"],
Yes that is what we talked about yesterday. After thinking it over some though, having 100% of plugins have to add a line when we could do it here once didn't seem like the best option. That being said, we may have to do it as you suggest because the CI is failing due to the unexpected import-time reaching its way to pulp-smash. Perhaps what you're suggesting will resolve that actually. I'm continuing to work on it and once I know more of which options could work we can talk it over some.

2022-04-20 13:31 UTC, bmbouter commented
@mdellweg do you think I should also move the --no-pulp-leftovers flag here too? I think I should, but I had some practical issues doing so, so I started moving things in parts in this PR. Anyways, that feature 100% uses pulpcore bindings so I thought moving it made sense. What do you think?

2022-04-20 16:10 UTC, mdellweg commented on setup.py
> +        "pytest11": ["pulpcore = pulpcore.tests.functional"],
It's more than that one line repeated on all plugins. I expect pulp_file and pulp_certguard to require themselves in a similar way. And at that point i value the expliciteness of saying "we need those fixtures".

2022-04-20 16:11 UTC, mdellweg commented
> @mdellweg do you think I should also move the --no-pulp-leftovers flag here too? I think I should, but I had some practical issues doing so, so I started moving things in parts in this PR. Anyways, that feature 100% uses pulpcore bindings so I thought moving it made sense. What do you think?

That feature is implemented as a hook. So we could keep the flag with the hook definition in smash and just move the hook implementation using pulpcore facilities here.

2022-04-20 17:14 UTC, bmbouter commented on pulpcore/tests/functional/conftest.py
> +pytest_plugins = "pulpcore.tests.functional"
Kind of ironic, but it needed this too. :rofl:

2022-04-20 17:21 UTC, mdellweg commented on pulpcore/tests/functional/conftest.py
> +pytest_plugins = "pulpcore.tests.functional"
Not if we put the fixtures in conftest.py i'd say.
Fixtures can either live in the _same_ python module, or on any conftest.py up in the directory tree.

If conftest.py does not work for inclusion of the fixtures in other plugins, can we have them in `pulpcore.tests.functional.fixtures`?

2022-04-20 19:29 UTC, bmbouter commented on pulpcore/tests/functional/conftest.py
> +pytest_plugins = "pulpcore.tests.functional"
If I'm reading your words right, you're suggesting I move everything from `__init__.py` to `conftest.py` in this PR and then have plugins declare their dependency with `pytest_plugins = "pulpcore.tests.functional.conftest"`. Is that right?

If ^ is right, the only downside is that now all plugins dependent on pulpcore will receive everything in conftest, but perhaps that's always correct. I can't think of a case where that isn't true.

I wanted to check before I go reworking the PRs once more. Ty!

2022-04-21 09:35 UTC, mdellweg commented on pulpcore/tests/functional/conftest.py
> +pytest_plugins = "pulpcore.tests.functional"
Assuming, that it actually works, that is what i'm suggesting. Using the `...functional.fixtures` module would be my second preferred solution.
One interesting question then is still, whether plugins will receive the hook implementations alongside the fixtures (pytest docs are not so explicit about that).

2022-04-21 18:09 UTC, mdellweg approved these changes

2022-04-21 19:43 UTC, dkliban approved these changes

2022-04-21 19:44 UTC, merged