Ensure download has fresh file on retry
pulp/pulpcore pull request #2571
Opened 2022-04-20 22:06 UTC by gerrod3

[noissue]

Not sure if this has an issue already or not. Related to https://issues.redhat.com/browse/AAH-1202 and test found in: https://github.com/pulp/pulp_file/pull/689

Our downloaders really need to be refactored and will be (https://discourse.pulpproject.org/t/downloader-refactor-sig/393/4), so not sure how useful this fix is. Also, I only fixed this on the http downloader, base and file are unaffected, and if any other downloaders override the `_run` method then this fix won't occur.

2022-04-21 09:07 UTC, fao89 reviewed
I feel it needs a changelog entry

2022-04-21 09:14 UTC, mdellweg requested changes
Thank you! I must have been dumb. I reset both the size counter and the hashes, but i forgot about the actual data. :facepalm: 
But we still need an issue and a changelog.

2022-04-21 13:38 UTC, bmbouter approved these changes
+1 to the comments from @mdellweg the issue and changelog are needed. @mdellweg can be the final lgtm. Thanks @gerrod3 this is great!

I'll review the test separately.

2022-04-21 20:40 UTC, dralley approved these changes

2022-04-22 11:28 UTC, mdellweg approved these changes

2022-04-22 11:28 UTC, merged

2022-04-25 10:59 UTC, ipanova commented
@gerrod3 given that most of the plugins override _run() this change will not fix https://issues.redhat.com/browse/AAH-1202 unless we make a direct change in ansible and containers plugins, if i read things correctly.

2022-04-25 13:46 UTC, gerrod3 commented
OK I checked ansible, rpm and container and they all override the `_run()` method so this fix won't fix the issue for their plugins. However, all the plugins don't override the `run()` method, so I think I can just move the call to the new method, `_ensure_fresh_file()` to be inside `run()` and then the fix should apply to all plugins.

2022-04-25 13:48 UTC, dralley commented
@gerrod3 Add this to the list of things we'd really like the downloader refactor to improve if possible.