Removes i8ln from log messages and adds docs
pulp/pulpcore pull request #2577
Opened 2022-04-21 20:57 UTC by bmbouter

i8ln should only be for using facing strings. This updates the code as
best as I could tell the difference, and also documents that expectation
for plugin writers.

closes #2477

2022-04-22 08:16 UTC, lubosmj commented on CHANGES/2477.bugfix
> +untranslated is best for everyone. All user facing strings are still expected to be i8ln.
```suggestion
Removed i18n from the logs written so they will always show up in English. It's a debatable point,
but after feedback from multi-language speakers, since the logs aren't user facing, having them
untranslated is best for everyone. All user facing strings are still expected to be i18n.
```

It is "i18n", not "i8ln" (see https://docs.python.org/3/library/gettext.html).

Also, I do not like the idea of expressing a subjective judgment in a changelog entry (`It's a debatable point`). The reasoning should be rather advertised in a release announcement on discourse.

2022-04-22 11:26 UTC, mdellweg commented on CHANGES/2477.bugfix
> +untranslated is best for everyone. All user facing strings are still expected to be i8ln.
Good call. We did that change. We state so. There is no need to argue anymore.

2022-04-28 15:51 UTC, bmbouter commented on CHANGES/2477.bugfix
> +untranslated is best for everyone. All user facing strings are still expected to be i8ln.
I agree, I've revised this.

2022-04-28 16:03 UTC, lubosmj commented on docs/plugins/plugin-writer/concepts/index.rst
> +internationalized will remain in English. This expectation was was formed after feedback from
```suggestion
internationalized will remain in English. This expectation was formed after feedback from
```

2022-04-28 16:03 UTC, lubosmj commented on pulpcore/app/management/commands/handle-artifact-checksums.py
> +    help = "Handle missing and forbidden checksums on the artifacts"
I am not quite sure if this is the type of string we do not want to translate.

2022-04-28 16:05 UTC, mdellweg requested changes

2022-04-28 16:05 UTC, mdellweg commented on docs/plugins/plugin-writer/concepts/index.rst
> +internationalized will remain in English. This expectation was was formed after feedback from
```suggestion
internationalized will remain in English. This expectation was formed after feedback from
```

2022-04-28 18:52 UTC, bmbouter commented on pulpcore/app/management/commands/handle-artifact-checksums.py
> +    help = "Handle missing and forbidden checksums on the artifacts"
Yeah it's generally pretty confusing. This one faces the administrator (not the user) so I left it un-il8n.

2022-04-28 18:54 UTC, bmbouter commented on docs/plugins/plugin-writer/concepts/index.rst
> +internationalized will remain in English. This expectation was was formed after feedback from
@mdellweg I fixed this if you could re-review plz. Thanks!

2022-04-28 19:35 UTC, mdellweg approved these changes

2022-04-28 20:47 UTC, gerrod3 approved these changes
Looks good. Looking at our logs we format our strings using `format` and `%`, but no `f strings`. :disappointed: . Don't have to change them now, but we can finally start to use `f strings`!

2022-04-29 08:18 UTC, merged

2022-04-29 13:48 UTC, bmbouter commented
> Looks good. Looking at our logs we format our strings using `format` and `%`, but no `f strings`. disappointed . Don't have to change them now, but we can finally start to use `f strings`!

I agree!