Adds docs on how to enable DEBUG logging
pulp/pulpcore pull request #2641
Opened 2022-04-29 18:57 UTC by bmbouter

closes #1944

2022-04-29 19:02 UTC, bmbouter commented on docs/troubleshooting.rst
> +    PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
@rochacbruno I tried maybe 5-6 variations to get this working and I wasn't able to. It doesn't seem to merge, it always overwrites. Got any pointers for me?

2022-05-02 14:00 UTC, rochacbruno commented on docs/troubleshooting.rst
> +    PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
The challenge there is the empty string `''` being used as the dictionary key.
merge operates by key and the current implement is not able to work with empty/false keys.

If the logger was for example calles `root`

```py
PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'root': {'handlers': ['console'], 'level': 'DEBUG'}}}
```

Or

```bash
PULP_LOGGING__loggers__root__level=DEBUG
```

I don't know right a workaround, we need changes on dynaconf to have some aditional syntax to work on empty keys.

2022-05-02 14:05 UTC, bmbouter commented on docs/troubleshooting.rst
> +    PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
@rochacbruno thanks for the reply! Is there a bug or something I can follow? I'd like to document the limitation in a straightforward way for our users as it works towards a resolution.

2022-05-02 16:49 UTC, rochacbruno commented on docs/troubleshooting.rst
> +    PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
@bmbouter this is not being tracked anywhere, the issue never happened before.

2022-05-03 14:56 UTC, bmbouter commented on docs/troubleshooting.rst
> +    PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
@rochacbruno I added it here so I could at least reference the issue. I don't expect it to be fixed unless it's easy. https://github.com/rochacbruno/dynaconf/issues/747

2022-05-03 17:48 UTC, ggainey requested changes
Just some minor wordsmithing tweaks, looks great otherwise!

2022-05-03 17:48 UTC, ggainey commented on docs/troubleshooting.rst
> +    ``'level': 'DEBUG'`` in addition to your current config show with ``dynaconf list``.
^show^shown

2022-05-03 17:48 UTC, ggainey commented on docs/troubleshooting.rst
> +Designating a Python based settings file, and putting the DEBUG logging configuration there::
^Python based^Python-based

2022-05-03 17:48 UTC, ggainey commented on docs/troubleshooting.rst
> +you can read more about :ref:`viewing-settings`. If configured correctly you should see::
^command which you can read more about:ref:`viewing-settings`.^command (for more information, see :ref:`viewing-settings`).

2022-05-03 17:58 UTC, bmbouter commented
@ggainey all pushed if you could re-review plz.

2022-05-03 18:01 UTC, ggainey approved these changes
:+1:

2022-05-03 18:05 UTC, dkliban reviewed
Should we include anything about setting 'DJANGO_SETTINGS_MODULE' before calling into dynaconf?

2022-05-03 18:06 UTC, bmbouter commented
> Should we include anything about setting 'DJANGO_SETTINGS_MODULE' before calling into dynaconf?

Good idea, let me add that now.

2022-05-03 18:12 UTC, dkliban approved these changes

2022-05-03 19:29 UTC, merged

2022-07-11 20:22 UTC, curiositycasualty commented
`PULP_LOGGING='@json {"dynaconf_merge": true, "loggers": {"": {"handlers": ["console"], "level": "DEBUG"}}}'`
~ https://github.com/rochacbruno/dynaconf/issues/747