Upgrade Django and ensure compat with it
pulp/pulpcore pull request #2651
Opened 2022-05-02 19:10 UTC by bmbouter

[noissue]

(cherry picked from commit c06ed6d)

2022-05-03 08:29 UTC, mdellweg approved these changes

2022-05-03 10:25 UTC, ipanova requested changes
This change does not suffice for container plugin https://github.com/pulp/pulp_container/pull/745#issuecomment-1114800086
https://github.com/pulp/pulp_container/runs/6271437401?check_suite_focus=true#step:14:399

2022-05-03 15:03 UTC, bmbouter commented
We're going to wait and see if those using 3.7 are aware that even after fixing this they will be using an unsupported version of Django. If they still want us to release the fixes we'll have to evaluate all plugins (like pulp_container) and likely release several fixes. So we're waiting for now to see what is best.

2022-05-11 10:38 UTC, ipanova approved these changes

2022-05-11 12:16 UTC, ipanova commented on requirements.txt
> -Django~=2.2.16  # LTS version, switch only if we have a compelling reason to
@bmbouter I think we actually don't even need this PR. Means that we also don't need to release pulpcore 3.7
once pulp-container 2.1 is released with this change https://github.com/pulp/pulp_container/pull/745/files i think we are good to go.

2022-05-11 12:38 UTC, bmbouter commented on requirements.txt
> -Django~=2.2.16  # LTS version, switch only if we have a compelling reason to
Yeah I think you are right. I'll close the pulpcore PR w/ a similar comment.

2022-05-11 12:39 UTC, bmbouter commented on requirements.txt
> -Django~=2.2.16  # LTS version, switch only if we have a compelling reason to
Oh ha, this is on that very PR. Closing!

2022-05-11 12:39 UTC, closed without merging