Enable admins to specify a custom GnuPG directory or keyring
pulp/pulpcore pull request #2653
Opened 2022-05-03 16:24 UTC by lubosmj

In this commit, the validation procedure triggered before saving signing services was refactored. As of this commit, users will no longer experience problems with missing keys or improperly configured GnuPG home directory. Public keys are imported to a temporary GnuPG directory where everything is correctly staged for validation purposes.

Also, redundant validation checks in the AsciiArmoredDetached's validate() method were removed as well.

closes https://github.com/pulp/pulpcore/issues/2476

2022-05-04 08:58 UTC, mdellweg reviewed
Thank you for this.
Does the validation work with all types of signatures (inline/detatched ; armored/text) ?

2022-05-04 08:58 UTC, mdellweg commented on pulpcore/app/util.py
> +            raise RuntimeError("Exactly one key must be imported.")
@quba42 Is this limitation useful? Can there be situations where you would check against one of multiple keys?

2022-05-04 08:58 UTC, mdellweg commented on pulpcore/app/util.py
> +            )
This seems superfluous. The keyring generated only contains the single key imported, so there's no room for ambiguity anymore. Also this function is about verification. It should not contain any trace of a signing service.

2022-05-04 08:58 UTC, mdellweg commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
I am wondering if we should throw a new subclass of `RuntimeError` or just return the result of the verification.

2022-05-04 08:58 UTC, mdellweg commented on pulpcore/app/models/content.py
> +        with tempfile.NamedTemporaryFile() as temp_file:
We should keep the temp directory wrapper too.

2022-05-04 08:58 UTC, mdellweg commented on pulpcore/app/util.py
> +    with tempfile.TemporaryDirectory() as temp_directory_name:
```suggestion
    with tempfile.TemporaryDirectory(dir=".") as temp_directory_name:
```
This can be run inside tasks and they need to use the current working directory for temporary stuff.

2022-05-04 10:14 UTC, lubosmj commented on pulpcore/app/util.py
> +            )
The check is a left-over from the old validation method. I was hesitant to remove it completely or move it to the `validate` method of `SigningService`. We would need to initialize a new GnuPG instance two times when considering the second option.

Regarding the ambiguity, there is still room for that. Administrators are passing fingerprints and public keys separately while creating signing services. In the check, we are testing whether the provided fingerprints match the fingerprints of the imported public keys.

We can try to compute fingerprints from passed public keys before saving objects to the database. Then, administrators would not have to deal with fingerprints by themselves since everything would be computed on the fly. With this, we lower requirements for the administrators. However, computing the fingerprint may not be as simple as it sounds.

2022-05-04 10:17 UTC, lubosmj commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
I am in favour of mentioning that this function raises `RuntimeError` once the verification was not successful in the docstring.

2022-05-04 10:20 UTC, ipanova commented on CHANGES/2476.feature
> +creation of a signing service. The introduced options ``--gnupghome`` and ``--keyring`` are
s/options/optional arguments/

2022-05-04 10:20 UTC, ipanova commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
s/The file '{filepath}' has not got/The file '{filepath}' does not have/

2022-05-04 10:20 UTC, ipanova commented on pulpcore/plugin/util.py
> +from pulpcore.app.util import verify_signature  # noqa
you should add changelog entry for plugin_api too

2022-05-04 10:21 UTC, mdellweg commented on pulpcore/app/util.py
> +            )
That is not true if we consider the pulpcore-manager command as the interface for the admin. They specify a key id and that's it.
I'd say, remove this check _and_ the `pubkey_fingerprint` argument.
Remember, `verify_signature` is meant to be used not only in the creation of signing services.

2022-05-04 10:25 UTC, lubosmj commented on pulpcore/app/util.py
> +            )
You can still create a signing service without `pulpcore-manager`, can't you? Do we want to end up in a non-consistent state? I still think that this check should be running somewhere. Maybe, this ^ is not the right place to run it, I agree.

2022-05-04 10:36 UTC, mdellweg commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
If you subclass RuntimeError, you can still catch it as a RuntimeError. But it allows to pin the reason for failure more granulary.

2022-05-04 10:38 UTC, mdellweg commented on pulpcore/app/util.py
> +            )
What is the other way? The one i know of is using the orm directly in `pulpcore-manager shell` (one that i would consider inherently unsafe).

2022-05-04 11:49 UTC, lubosmj commented on pulpcore/app/util.py
> +            )
Yes, there are two standard ways of saving signing services: 1. `pulpcore-manager shell_plus` (dangerous), 2. `pulpcore-manager add-signing-service` (fine). But, what prevents plugin writers from adding a new endpoint for managing their signing services? I am removing the check if we believe that administrators will always use `pulpcore-manager add-signing-service` and plugin writers will never think of validating fingerprints.

In the documentation, we suggest using `pulpcore-manager shell_plus`. It should be then described as one of the non-recommended ways of creating signing services (https://docs.pulpproject.org/pulpcore/workflows/signed-metadata.html?highlight=signing%20service).

2022-05-10 19:51 UTC, lubosmj commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
This suggestion is debatable because we also deal with detached signatures.

2022-05-11 08:16 UTC, lubosmj commented
@mdellweg, yes, the validation works for both detached and inlined signatures.

2022-05-11 08:34 UTC, mdellweg requested changes

2022-05-11 08:34 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
> -   .. code-block:: python
[not a ReST expert here] Do we want this to be a `.. code-block:: bash/shell/sh/whatever`?

2022-05-11 08:34 UTC, mdellweg commented on docs/workflows/signed-metadata.rst
We could add to this note something like:
"The public key must be available on the callers keyring or on a keyring provided via the `--gpghome` or `--keyring` parameters."

2022-05-11 08:34 UTC, mdellweg commented on pulpcore/plugin/util.py
> +from pulpcore.app.util import verify_signature  # noqa
Also we need to export the Exception `InvalidSignatureError` too.

2022-05-11 12:40 UTC, lubosmj commented on docs/workflows/signed-metadata.rst
> -   .. code-block:: python
I used `code-block:: bash` instead.

2022-05-11 12:41 UTC, lubosmj commented on docs/workflows/signed-metadata.rst
I removed a bunch of unnecessary sentences and added the suggested statement.

2022-05-12 10:27 UTC, mdellweg approved these changes

2022-05-23 12:24 UTC, ipanova approved these changes

2022-05-23 12:27 UTC, ipanova commented on pulpcore/app/util.py
> +                raise RuntimeError(f"The file '{filepath}' has not got a valid signature.")
this suggestion was mostly about english grammar :D

2022-05-23 12:27 UTC, merged