Adds docs cleaning up the PR walkthrough
pulp/pulpcore pull request #2712
Opened 2022-05-10 19:03 UTC by bmbouter

closes #1852

2022-05-10 19:24 UTC, ggainey commented on docs/contributing/pull-request-walkthrough.rst
> +If you fixing a bug that needs to also be backported to another brancher than ``main``, add the
```suggestion
If you are fixing a bug that should also be backported to another branch than ``main``, add the
```

2022-05-10 19:26 UTC, ggainey requested changes
A few suggestions, really glad to see this page reflecting relaity again!

2022-05-10 20:41 UTC, bmbouter commented on docs/contributing/pull-request-walkthrough.rst
> +If you fixing a bug that needs to also be backported to another brancher than ``main``, add the
this fix was pushed, ty

2022-05-11 09:07 UTC, mdellweg commented on docs/contributing/pull-request-walkthrough.rst
> +If you are fixing a bug that should also be backported to another branche than ``main``, add the
```suggestion
If you are fixing a bug that should also be backported to another branch than ``main``, add the
```

2022-05-11 09:08 UTC, mdellweg commented on docs/contributing/pull-request-walkthrough.rst
> +"Needs Cherry Pick" label to the PR. PR authors can also add or remove this label if they have write
Actually we have `backport-3.20` like labels now.

2022-05-11 09:19 UTC, lubosmj commented on CHANGES/1852.doc
> +Added docs cleaning up the pull request checklist and page.
```suggestion
Cleared out some of the paragraphs from the Pull Request Walkthrough section.
```

2022-05-11 15:55 UTC, bmbouter commented on docs/contributing/pull-request-walkthrough.rst
> +"Needs Cherry Pick" label to the PR. PR authors can also add or remove this label if they have write
I switched this language.

2022-05-11 16:20 UTC, bmbouter commented
@ggainey @mdellweg can you re-review this?

2022-05-11 16:53 UTC, ggainey approved these changes
lg2m!

2022-05-12 10:01 UTC, mdellweg approved these changes

2022-05-12 13:01 UTC, merged