Create missing repositories automatically
pulp/pulpcore pull request #2713
Opened 2022-05-10 19:39 UTC by lubosmj

As of this commit, repositories are identified as standard import/export resource objects. It allows the automatic creation of importing repositories that were not created beforehand or do not exist.

closes #1920

2022-05-23 14:17 UTC, ipanova reviewed
can you make a showcase with pulp_container plugin for this feature?

2022-05-23 14:17 UTC, ipanova commented on docs/workflows/import-export.rst
> +    POST request.
"..that will create missing repos on the fly"

2022-05-30 13:58 UTC, mdellweg commented
Can you add "on import" to both the PR and the commit message first line?

2022-05-31 18:06 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
>              content = Content.objects.filter(pk__in=resulting_content_ids)
No, the said two are different things. `repo_mapping` is used for mapping repositories (a dictionary passed via the REST API as the mapping between repositories' names) whilst `mapping` "probably" represents the mapping retrieved from the `content_mapping.json` file (the mapping between content units and repositories (https://docs.pulpproject.org/pulpcore/plugins/plugin-writer/concepts/subclassing/import-export.html#content-mapping)) that is included within an exported tarball.

2022-06-07 18:46 UTC, ipanova commented
> can you make a showcase with pulp_container plugin for this feature?

This PR is waiting on ^

2022-06-10 11:20 UTC, ipanova commented on docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
> +    IMPORT_ORDER = [FileContentResource, FileRepositoryResource]
One could have a completely different assumption that first we need to import repository to have a place to place content into.
@ggainey can you confirm what's the correct order here?

2022-06-10 11:47 UTC, lubosmj commented on docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
> +    IMPORT_ORDER = [FileContentResource, FileRepositoryResource]
Actually, the order of repositories does not matter. When we export repositories, we do not include any additional references to related objects (no remotes, no content units, ...). In comparison, in pulp_container, we export tags that reference manifests that reference blobs - so, in this case, we need to take care of the order.

2022-06-10 12:13 UTC, ipanova commented on docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
> +    IMPORT_ORDER = [FileContentResource, FileRepositoryResource]
so what you're saying is - if we put repos as first in the order it would not make any difference.

2022-06-10 16:12 UTC, ggainey commented on docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
> +    IMPORT_ORDER = [FileContentResource, FileRepositoryResource]
IMPORT_ORDER is, in fact, ordered, because some resources are dependent on the existence of others before they can be created. However, the act of adding content to a repo is a separate step that happens only after we've imported All The Things, so it's perfectly fine to create the repo last in the list.

2022-06-15 14:14 UTC, ipanova commented
@lubosmj how do we plan to create on the fly a repo which would be different type from the source repo?
Something we'd need to add in plugin or?

2022-06-15 15:02 UTC, ggainey requested changes
I did a quick patch to pulp_rpm modelresource and saw the whole process Just Work, was definitely easy to implement at the plugin side.

I'd like to see the doc expanded to cover the "why repo-mapping and this switch aren't compatible" question.

2022-06-16 17:41 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> -                with repo.new_version() as new_version:
I think we can't move this - has to be done per-entity-in-mapping, inside this loop, to pick up subrepos (like, say, RPM kickstart repositories)

2022-06-17 17:20 UTC, ggainey approved these changes
Reviewed, exercised in pulp_rpm via https://github.com/pulp/pulp_rpm/pull/2592 . Looks good to me!

2022-06-20 09:56 UTC, mdellweg commented on docs/workflows/import-export.rst
> +    POST request that will force Pulp to create missing repositories on the fly.
This comment has not been processed yet.

2022-06-20 09:56 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = []
I think, we still need to lock on the newly created repository.
Either we create it here before we subtask is dispached, or we find a way to sneak the newly created repository in the exclusive_resources of the running task in the same transaction as we create it (this is unprecedented).

2022-06-20 11:06 UTC, mdellweg commented on docs/workflows/import-export.rst
> +    is initialized. Thus, the repository has to be already created in advance.
Do we have validation for this in the serializer?

2022-06-21 10:32 UTC, lubosmj commented on docs/workflows/import-export.rst
> +    is initialized. Thus, the repository has to be already created in advance.
No, I should add it.

2022-06-21 11:21 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = []
We can't lock it "in advance", it doesn't exist until "at some point" in the processing of import-records we run the (Detail)RepositoryResource file through _import_file()

2022-06-21 12:14 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = []
Lubos can you try if this would solve the problem?
https://github.com/pulp/pulpcore/pull/2881/files

2022-06-21 13:01 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = []
@mdellweg, yes, it seems like a repository can be locked in that way.

Below is an example with 2 imported repositories:
```
(pulp) [vagrant@pulp3-source-fedora35 exports]$ http :24817/pulp/api/v3/importers/core/pulp/58df31e2-9ca9-4333-bf01-92b8c11fe494/imports/ create_repositories=True path=/tmp/exports/export-e0398973-e809-49ca-8a61-f52d6c2fc4a4-20220617_0912.tar.gz
HTTP/1.1 202 Accepted
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, POST, HEAD, OPTIONS
Connection: close
Content-Length: 79
Content-Type: application/json
Correlation-ID: a6e8728d9cde4cf184a2db6aee4fecd2
Date: Tue, 21 Jun 2022 12:56:26 GMT
Referrer-Policy: same-origin
Server: gunicorn
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "task_group": "/pulp/api/v3/task-groups/0c37dfe7-bdcf-4957-85c5-347b066174d0/"
}


(pulp) [vagrant@pulp3-source-fedora35 exports]$ http :24817/pulp/api/v3/task-groups/0c37dfe7-bdcf-4957-85c5-347b066174d0/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, HEAD, OPTIONS
Connection: close
Content-Length: 1502
Content-Type: application/json
Correlation-ID: 43eaf18954fd479aa20ad7950f95849f
Date: Tue, 21 Jun 2022 12:56:34 GMT
Referrer-Policy: same-origin
Server: gunicorn
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "all_tasks_dispatched": true,
    "canceled": 0,
    "canceling": 0,
    "completed": 3,
    "description": "Import of /tmp/exports/export-e0398973-e809-49ca-8a61-f52d6c2fc4a4-20220617_0912.tar.gz",
    "failed": 0,
    "group_progress_reports": [
        {
            "code": "import.repo.versions",
            "done": 2,
            "message": "Importing repository versions",
            "suffix": null,
            "total": 2
        }
    ],
    "pulp_href": "/pulp/api/v3/task-groups/0c37dfe7-bdcf-4957-85c5-347b066174d0/",
    "running": 0,
    "skipped": 0,
    "tasks": [
        {
            "finished_at": "2022-06-21T12:56:26.960056Z",
            "name": "pulpcore.app.tasks.importer.pulp_import",
            "pulp_created": "2022-06-21T12:56:26.619315Z",
            "pulp_href": "/pulp/api/v3/tasks/d0c062c5-5ac2-45ed-a065-edfea494e8ed/",
            "started_at": "2022-06-21T12:56:26.662507Z",
            "state": "completed",
            "worker": "/pulp/api/v3/workers/fc68cff5-cad7-45ca-afb9-40b3cbea41b0/"
        },
        {
            "finished_at": "2022-06-21T12:56:28.069882Z",
            "name": "pulpcore.app.tasks.importer.import_repository_version",
            "pulp_created": "2022-06-21T12:56:26.928973Z",
            "pulp_href": "/pulp/api/v3/tasks/5cbbec24-4947-4a0d-8e88-bcb6e8393612/",
            "started_at": "2022-06-21T12:56:26.963631Z",
            "state": "completed",
            "worker": "/pulp/api/v3/workers/2a5f93cc-68a2-4bac-b1e8-04e69f0e8cec/"
        },
        {
            "finished_at": "2022-06-21T12:56:28.284207Z",
            "name": "pulpcore.app.tasks.importer.import_repository_version",
            "pulp_created": "2022-06-21T12:56:26.942847Z",
            "pulp_href": "/pulp/api/v3/tasks/d764aebf-5451-48ff-9c92-be01e2d84384/",
            "started_at": "2022-06-21T12:56:26.994319Z",
            "state": "completed",
            "worker": "/pulp/api/v3/workers/fc68cff5-cad7-45ca-afb9-40b3cbea41b0/"
        }
    ],
    "waiting": 0
}


(pulp) [vagrant@pulp3-source-fedora35 exports]$ http :24817/pulp/api/v3/tasks/5cbbec24-4947-4a0d-8e88-bcb6e8393612/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, PATCH, DELETE, HEAD, OPTIONS
Connection: close
Content-Length: 992
Content-Type: application/json
Correlation-ID: 2b5d33927ef5425c82822d475176a9b4
Date: Tue, 21 Jun 2022 12:56:41 GMT
Referrer-Policy: same-origin
Server: gunicorn
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "child_tasks": [],
    "created_resources": [
        "/pulp/api/v3/repositories/container/container-push/721b4126-f844-440d-9233-a7f37ba52627/versions/1/"
    ],
    "error": null,
    "finished_at": "2022-06-21T12:56:28.069882Z",
    "logging_cid": "a6e8728d9cde4cf184a2db6aee4fecd2",
    "name": "pulpcore.app.tasks.importer.import_repository_version",
    "parent_task": "/pulp/api/v3/tasks/d0c062c5-5ac2-45ed-a065-edfea494e8ed/",
    "progress_reports": [
        {
            "code": "import.repo.version.content",
            "done": 5,
            "message": "Importing content for pulp/fixture",
            "state": "completed",
            "suffix": null,
            "total": 5
        }
    ],
    "pulp_created": "2022-06-21T12:56:26.928973Z",
    "pulp_href": "/pulp/api/v3/tasks/5cbbec24-4947-4a0d-8e88-bcb6e8393612/",
    "reserved_resources_record": [
        "/pulp/api/v3/repositories/container/container-push/721b4126-f844-440d-9233-a7f37ba52627/"
    ],
    "started_at": "2022-06-21T12:56:26.963631Z",
    "state": "completed",
    "task_group": "/pulp/api/v3/task-groups/0c37dfe7-bdcf-4957-85c5-347b066174d0/",
    "worker": "/pulp/api/v3/workers/2a5f93cc-68a2-4bac-b1e8-04e69f0e8cec/"
}


(pulp) [vagrant@pulp3-source-fedora35 exports]$ http :24817/pulp/api/v3/tasks/d764aebf-5451-48ff-9c92-be01e2d84384/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, PATCH, DELETE, HEAD, OPTIONS
Connection: close
Content-Length: 979
Content-Type: application/json
Correlation-ID: c10013e0651d44d98b6e80267265b705
Date: Tue, 21 Jun 2022 12:56:59 GMT
Referrer-Policy: same-origin
Server: gunicorn
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "child_tasks": [],
    "created_resources": [
        "/pulp/api/v3/repositories/container/container/6668db36-ae79-409d-97b1-01bd382c2893/versions/1/"
    ],
    "error": null,
    "finished_at": "2022-06-21T12:56:28.284207Z",
    "logging_cid": "a6e8728d9cde4cf184a2db6aee4fecd2",
    "name": "pulpcore.app.tasks.importer.import_repository_version",
    "parent_task": "/pulp/api/v3/tasks/d0c062c5-5ac2-45ed-a065-edfea494e8ed/",
    "progress_reports": [
        {
            "code": "import.repo.version.content",
            "done": 12,
            "message": "Importing content for lubosmj",
            "state": "completed",
            "suffix": null,
            "total": 12
        }
    ],
    "pulp_created": "2022-06-21T12:56:26.942847Z",
    "pulp_href": "/pulp/api/v3/tasks/d764aebf-5451-48ff-9c92-be01e2d84384/",
    "reserved_resources_record": [
        "/pulp/api/v3/repositories/container/container/6668db36-ae79-409d-97b1-01bd382c2893/"
    ],
    "started_at": "2022-06-21T12:56:26.994319Z",
    "state": "completed",
    "task_group": "/pulp/api/v3/task-groups/0c37dfe7-bdcf-4957-85c5-347b066174d0/",
    "worker": "/pulp/api/v3/workers/fc68cff5-cad7-45ca-afb9-40b3cbea41b0/"
}

```

2022-06-21 14:29 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                if task := Task.current():
Does not matter it is all in the same transaction.

2022-06-21 14:34 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = []
> django-import-export has an after_import_instance() method that can be overridden. In the workflow, a row in an import-file is turned into an instance and saved; perhaps we can figure out the right way to get involved at this point in the process, and lock the created/updated repository at that point? Perhpas in https://github.com/lubosmj/pulpcore/blob/da635ebf6a445b20ed14ee8658cac0a482e6046b/pulpcore/app/modelresource.py#L50 ?

Would that come inside a transaction? We definitely need that. The current approach kind of assumes that whenever a task, for what ever reason creates a repository, it will own it until finished.

2022-06-21 14:36 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
@bmbouter @dkliban
Since i drafted this, i really want both of you to sign off this change.

2022-06-21 15:20 UTC, mdellweg requested changes

2022-06-21 15:20 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                dest_repo = Repository.objects.get(name=repo_name)
Ok, i see a new problem now: If the Repository was created between the dispatching of the subtask and here, the task will not have a lock on the repository. So we need to change the logic a little bit. I think we need to tell the task (in it's args) whether it is supposed to _use_ an existing repository.

2022-06-21 15:20 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +    importer_pk, destination_repo_name, source_repo, tar_path, create_repositories
If i'm not mistaken, this function is meant to be executed as task. So existing repositories must be passed by pk and not by name. The name should only be used for nonexistent repositories.
Reason: The resources are locked by their url (containing the pk which is unique and cannot be reused). However on the other hand, "the repository with the name 'foo'" could be a different thing when dispatching a task and when executing it.

2022-07-14 08:14 UTC, lubosmj commented on pulpcore/app/models/repository.py
> +                    task.save()
Can this be addressed now, please?

2022-07-14 08:30 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
can we do `task.save(update_fields=["reserved_resources_record"])`?

2022-07-15 10:09 UTC, mdellweg requested changes

2022-07-15 10:09 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +        task.save()
Where did that come from? This cannot be. A task cannot just claim that it has the lock on certain resources.

2022-07-15 13:05 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> +        task.save()
What is the proper way of locking a resource from within a task?

2022-07-15 16:11 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +        task.save()
There is no way. This breaks all the assumptions of the tasking system. Resources must be requested when the task is dispatched.
The only viable exception is a resource newly created by that task if added withing the same transaction. That way, no other task could have claimed that new resource earlier.

2022-07-27 14:41 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
To add some context: This is the only way we can safely create a repository in one task and manipulate it further in the same one.

2022-07-29 08:24 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
```suggestion
                if task := Task.current():
                    task.reserved_resources_record.append(get_url(self))
                    task.save(update_fields=["reserved_resources_record"])
```

2022-07-30 01:22 UTC, dralley commented on pulpcore/app/models/repository.py
> +                    task.save()
I'm not sure I understand why that is the case - this task is creating the repository, and repository pk's are UUIDs, so how would another task get a reference to it to manipulate it?  Are tasks fighting over the same work?

2022-07-31 20:30 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
No, but the moment the repository appears in the database, a new task can be dispatched to modify it. We must ensure this other task is waiting until our task is finished.
The only way to do it is to add it to reserved resources.

2022-08-23 12:49 UTC, bmbouter commented on pulpcore/app/tasks/importer.py
> +        source_repo (dict): Repository in the export.
Unless we need to handle N dest_repos (which I think we don't) then these args should be unpacked to not be dictionaries, but instead be like: `dest_repo_pk` and `dest_repo_name`. Similar with `source_repo`.

2022-08-23 12:49 UTC, bmbouter commented on pulpcore/app/tasks/importer.py
> +        source_repo (dict): Repository in the export.
One reason is that the more we made arg data complex it becomes more complicated and harder to later add things like type checking support (because now you'd have to assert on the dict and its contents not just simple python primitives).

2022-08-23 12:50 UTC, bmbouter commented on pulpcore/plugin/modelresources.py
> +from pulpcore.app.modelresource import RepositoryResource  # noqa
:+1:

2022-08-23 12:53 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +                    task.save()
I think it would be safer if it used the `update_fields` use. What if in between the `task := Task.current():` and the `save()` something else modifies it? I don't have an example of how, but if it did then there would be a race condition here.

2022-08-23 12:55 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +                    task.save()
Other than the request to make the save() call a little safer, I'm ok with this. At some point later I think we need to standardize the lock generation for all objects in Pulp. It's possible not all dispatchers for repositories are using `get_url()` as the string. That's a problem not for this PR thought.

@dralley @mdellweg @dkliban ^ this future improvement for the tasking system.

2022-08-24 08:23 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
I don't quite follow. All dispatchers must agree on the same lock-string for the same resource. And we agreed to use the pulp_href. Yes, we should probably do the actual `get_url` call somewhere in the tasking code for a nice separation of concerns. But the result must be the same for proper locking of the resources.

2022-08-24 13:21 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
AFAIK we never use the plain uuid (or worse pk). But we allow for arbitrary strings to be used (for abstract resources not in the pulp_db).
I'd be happy to discuss your suggestion in a coded example.

2022-08-24 13:36 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +                    task.save()
I just did a quick audit and almost all usage of `exclusive_resources` is uses the db object itself, e.g. `exclusive_resources=[repository]`. Is that the result of `get_url()`?

2022-08-24 13:51 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    task.save()
Yes, this will be translated by dispatch.

2022-08-24 13:55 UTC, bmbouter commented on pulpcore/app/models/repository.py
> +                    task.save()
@mdellweg thanks, then I think we're in a good spot then. As a side curiosity, where does that translation happen in the code?

2022-08-25 12:59 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +    def lock_within_task(self):
Can we not make this a method? It really absolutely _needs_ to be called from within the transaction of `save`. Making it a function will lead future us to think it's safe to be called.

2022-08-26 09:19 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                )
```suggestion
                repository_url = get_url(self)
                update_func = Func(
                    F("reserved_resources_record"), Value(repository_url), function="ARRAY_APPEND"
                )
```
Feel free to ignore. Just a feeling the `F` and `Value` are kind of a similar thing.

2022-08-26 09:19 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                Task.objects.filter(pk=task_id).update(reserved_resources_record=update_func)
Do you think we can use the return value to determine that one task was actually updated and raise an error if not?
Trying to make this really bullet proof.

2022-08-26 10:06 UTC, lubosmj commented on pulpcore/app/models/repository.py
> +                Task.objects.filter(pk=task_id).update(reserved_resources_record=update_func)
Resolved.

2022-08-26 10:36 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +                    raise RuntimeError(f"The repository '{self.name}' could not be locked")
:+1:

2022-08-29 12:07 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> -            )
@ggainey, @mdellweg, I removed this check completely because we will still raise an error (in the set_content method) in another place when we try to import content of an unknown type to a particular repository (e.g., rpm content to a file repository). Are you fine with that?

The actual problem is that we do not have the facility to get subclassed repository resources when running the export procedure from pulpcore. We do not use typed exports (similarly to: /repositories/container/container/) and we handle the generic repository export here: https://github.com/pulp/pulpcore/blob/c19d083aa86062cb581dc9a7252d38916b4c8ce1/pulpcore/app/importexport.py#L120. It is not possible to determine the type of repository resource at this time (Models (queryset) are not associated with import/export resources). As a result, even though I override the behaviour from pulp_container (where we export one repository type as another one; https://github.com/pulp/pulp_container/pull/826/files#diff-ad03c3a610de949dd025b92b32ea7684c7526e598829dbe85210b8520d98b16eR37-R49), it will be ignored because we always instantiate the generic repository resource (RepositoryResource). So, I am not able to export one repository type as another one because it will fail on the highlighted check during the import.

What this check does is that it halts the import procedure in case the types of repositories do not match before importing the actual files. Without this check, the halt will occur later.

2022-08-29 12:33 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> -            )
I am just not an expert on import-export... But what i do not understand: If we always handle Repositories by means of the pulpcore RepositoryResource, how can we serialize detail-specific extra fields?

2022-08-29 12:44 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> -            )
to take advantage of this functionality, the plugins need to define their detail-repositories as model-resources - like this : https://github.com/pulp/pulp_rpm/pull/2592

2022-08-29 14:34 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> -            )
Exactly, and we basically export the same thing two times. Once as "RepositoryResource.json" in the root directory of a tarball. And, another time we export it as "PluginRepositoryResource.json". We do not know the name of a repository resource beforehand from the current mechanism.

2022-08-29 14:38 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> -            )
I would probably opt for opening a new task called "Making import/export a typed system" where we would refactor the whole machinery in order to allow plugin-based definitions and possible overrides (like we do for repositories, remotes, etc.). Because it is impossible to do that right now without extensively touching the pulpcore's code. Funny that I noticed these kinds of limitations at the end of testing the pulp_container import/export workflow - where first, I exported a push repo, removed it, created a new sync repo, and tried to import the exported push repo.

2022-08-29 14:43 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> -            )
What is the path I should take - (1) leave it as it is, (2) outsource the import/export capabilities to concrete plugins where we are aware of exact import/export types for the whole time, (3) store the import/export resource classes in the database to be able to read resource types even from pulpcore?

2022-08-29 21:28 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> -            )
What we have now works with the import/export machinery as defined - "core handles the engine and knows the repos, the plugins handle the details of their objects". The disadvantage is, Repositories exist twice, once at root (so "the engine" can know what its doing) and again in the repo-directories (because that's where the plugin-exported-files live).  This is a little ugly, but that happens sometimes in plugin-architectures with cross-cutting features.

Is there an actual *problem* here that I'm missing? Because I don't see one other than "this could be more elegant", which is not a good reason to start refactoring machinery that is already in-use.

2022-08-30 06:32 UTC, lubosmj commented on pulpcore/app/tasks/importer.py
> -            )
The only problem is that by removing the highlighted "pre-condition", we are losing the possibility to detect invalid repository types before running the actual import procedure (where we save content to the database). So, we will import a bunch of files and after that we will realize: "oopsie, this type of content cannot be added to such a repository, halt".

2022-09-01 16:14 UTC, ggainey approved these changes
It's possible there are Odd Edge Cases we haven't imagined - but it's because they'd all be plugin-specific. I am good with this modification to the engine; we'll learn more as we go.

2022-09-01 16:14 UTC, ggainey commented on pulpcore/app/models/repository.py
> +                    raise RuntimeError(f"The repository '{self.name}' could not be locked")
:+1:

2022-09-01 16:14 UTC, ggainey commented on pulpcore/app/serializers/importer.py
> +                    _("The option 'create_repositories' is not compatible with 'repo_mapping'.")
:+1:

2022-09-01 16:14 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> -            )
So if I am imagining this correctly - the failure-mode we're removing here, is only "the user has  created a destination-repo of one type, that doesn't match the type of the src-repo of the same name (or that is in a mapping as pointing-to the mismatched destination)". Current-code shortcircuits that failure, with this PR it has to wait until content-import. 

The major time-bottleneck for PIE is the Artifact step, which happens well before this. The actual content-load into django-importexport, is quite fast, even for large repositories (**memory utiilzation** is another issue,of course :) ). I think I'm OK with having a delayed failure here, given the gain in user-experience of this feature.

2022-09-01 16:15 UTC, mdellweg approved these changes
LGTM

2022-09-01 19:23 UTC, merged