Add ?for_object_type to roles API
pulp/pulpcore pull request #2748
Opened 2022-05-19 18:27 UTC by newswangerd

fixes: #2747

Example usage: http://localhost:8080/pulp/api/v3/roles/?for_object_type=/pulp/api/v3/groups/

Returns roles that only have permissions on the `/pulp/api/v3/groups/` resource type.

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2022-05-19 19:04 UTC, newswangerd commented
I don't think the CI failure is related to this PR

2022-05-31 14:07 UTC, bmbouter commented on pulpcore/tests/functional/__init__.py
> +def gen_role(roles_api_client, gen_object_with_cleanup):
@mdellweg is this the right place to introduce this fixture?

2022-05-31 14:31 UTC, newswangerd commented on pulpcore/tests/functional/__init__.py
> +def gen_role(roles_api_client, gen_object_with_cleanup):
wasn't sure if they should go in `__init__.py` or `conftest.py`. I put it here because that's where all the other fixtures are. LMK if I should move it.

2022-05-31 14:39 UTC, newswangerd commented on pulpcore/app/viewsets/base.py
> +                resource and not an instance of it.
Done.

2022-05-31 17:14 UTC, bmbouter commented on pulpcore/app/viewsets/base.py
> +            raise DRFValidationError(detail=_("URI not valid: {u}").format(u=uri))
Maybe just let the initial 404 bubble up? Either way is fine w/ me.

2022-05-31 17:18 UTC, bmbouter commented on pulpcore/app/viewsets/user.py
> +                    "Filter roles that only have permissions" " for the specified object HREF."
```suggestion
                    "Filter roles that only have permissions for the specified object HREF."
```

2022-05-31 17:19 UTC, bmbouter commented on pulpcore/tests/functional/__init__.py
> +def gen_role(roles_api_client, gen_object_with_cleanup):
After thinking more on it, I think this is the right place because the `roles_api_client` is offered from pulpcore itself. @mdellweg lmk if you think differently.

@newswangerd I'm trying to get our factory pattern usage to have `_factory` in it so can this be 
```suggestion
def role_factory(roles_api_client, gen_object_with_cleanup):
```

2022-05-31 17:20 UTC, bmbouter commented on pulpcore/tests/functional/__init__.py
> +    yield _gen_role
```suggestion
    return _gen_role
```

If there isn't cleanup work to do after having it return is more efficient by not having the generator resumed later only to return.

2022-05-31 17:21 UTC, bmbouter requested changes
I requested a few small changes. Thanks!

2022-05-31 17:25 UTC, newswangerd commented on pulpcore/app/viewsets/base.py
> +            raise DRFValidationError(detail=_("URI not valid: {u}").format(u=uri))
@bmbouter I wanted to keep it consistent with `get_resource`.

2022-06-01 05:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_role.py
> +        name="role_with_perms_for_multiple_objects",
We usually give them uuid4 names to be able to avoid conflicts.

2022-06-01 05:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_role.py
> +    assert roles.count == 0
This is interesting. It means we only return "pure" roles. I would have expected differently. But a good test reads like a specification. Well done!

How about adding roles with names
`"<uuid4>_multi_type"`: `["core.add_group", "core.view_task"]` (like yours)
`"<uuid4>_single_type"`: `["core.add_group", "core.view_group"]` (with more than one perm, just to be sure)
`"<uuid4>_empty"`: `[]` (should this be returned or not?)
and list them by `<...>.list(for_object_type=group_href, name__startswith="<uuid4>")` ?

2022-06-01 05:59 UTC, mdellweg commented on pulpcore/tests/functional/api/test_role.py
> +    assert roles.count == 0
I think the test would qualify for `@pytest.mark.parallel` at that point.

2022-06-01 16:17 UTC, bmbouter commented on pulpcore/tests/functional/api/test_role.py
> +    assert returned_roles == set([single_type.name, single_type2.name])
please add a newline at the end (the CI should be checking for this but currently isn't)

2022-06-01 19:03 UTC, mdellweg commented on pulpcore/tests/functional/api/test_role.py
> +    assert roles.count == 0
The docs are fine. I just didn't read it properly and assumed.

2022-06-01 19:05 UTC, mdellweg commented on pulpcore/tests/functional/api/test_role.py
> +    prefix = uuid.uuid4()
```suggestion
    prefix = str(uuid.uuid4())
```
Sorry i keep forgetting that...

2022-06-02 13:50 UTC, bmbouter approved these changes
This looks great. Thank you!

2022-06-02 13:50 UTC, merged