Define a custom API root endpoint class
pulp/pulpcore pull request #2793
Opened 2022-06-01 14:54 UTC by lubosmj

closes #2340

2022-06-14 13:26 UTC, mdellweg approved these changes

2022-06-14 13:39 UTC, bmbouter commented on pulpcore/app/urls.py
> +class PulpDefaultRouter(routers.DefaultRouter):
Could a test also be written that forms the URL and requesting it with aiohttp with no auth. Here are some similar tests I've written for this.

https://github.com/pulp/pulpcore/pull/2656/files#diff-4ba773aa1c5a9462bf450deb5056971d3bd6609dd44b6c8b11733cd4c27dc670R50-R51

https://github.com/pulp/pulpcore/pull/2656/files#diff-4ba773aa1c5a9462bf450deb5056971d3bd6609dd44b6c8b11733cd4c27dc670R33-R35

2022-06-14 13:40 UTC, bmbouter commented on pulpcore/app/urls.py
> +class PulpDefaultRouter(routers.DefaultRouter):
Actually this comment was for the `PulpAPIRootView` instead.

2022-06-14 13:40 UTC, bmbouter requested changes
Would you be willing to write a pytest test?

2022-06-14 15:16 UTC, lubosmj commented on pulpcore/app/urls.py
> +#: The Pulp Platform v3 API router, which can be used to manually register ViewSets with the API.
I wanted to have the variable definition close to the code that is actually using the variable.

2022-06-14 15:17 UTC, lubosmj commented on pulpcore/app/urls.py
> +class PulpDefaultRouter(routers.DefaultRouter):
Sure thing!

2022-06-15 14:19 UTC, bmbouter commented on pulpcore/tests/functional/utils.py
> +class NoAuth(requests.auth.AuthBase):
We're actually trying to not have requests as a test dependency and instead consolidate on aiohttp.client. Could you use that to make the requests instead please?

2022-06-15 15:04 UTC, bmbouter commented on pulpcore/tests/functional/__init__.py
> +def pulp_api_v3_root_endpoint(pulp_cfg, pulp_api_v3_path):
```suggestion
def pulp_api_v3_url(pulp_cfg, pulp_api_v3_path):
```

This is a tricky one to name, but this name made more sense to me.

2022-06-16 15:52 UTC, bmbouter commented on pulpcore/tests/functional/api/test_root_endpoint.py
> +@pytest.mark.from_pulpcore_for_all_plugins
I'm not sure plugins running this test also created additional value. I don't think their code is in a position to modify pulpcore's routers.

2022-06-16 15:52 UTC, bmbouter approved these changes
I think removing that one mark (see comment) would be good, but otherwise this is :100:

2022-06-20 10:34 UTC, merged