Allow uploads to be turned into content directly
pulp/pulpcore pull request #2795
Opened 2022-06-02 11:10 UTC by mdellweg

This is needed to prevent creating orphans in the meantime.

fixes #2786

2022-06-07 11:48 UTC, mdellweg commented
The test will come in a pulp_file PR pulp/pulp_file#733 .

2022-06-09 15:44 UTC, gerrod3 requested changes
By the way, this change implies that artifacts will eventually also be scoped like content, right?

2022-06-09 15:44 UTC, gerrod3 commented on pulpcore/plugin/serializers/content.py
> +            raise ValidationError(_("One of 'file', 'artifact' ad 'upload' must be specified."))
Can this be simplified to:
```python
if len({"file", "upload", "artifact"}.intersection(data.keys())) != 1:
    raise ValidationError(...)
```
Also, I think it should be *or* instead of *and* for the error message.

2022-06-09 15:44 UTC, gerrod3 commented on pulpcore/plugin/serializers/content.py
> +                raise RuntimeError("This validation should only be called in the task context.")
I'm confused, what does `"request" not in self.context` mean? I was under the impression the check is there for when the validate method is called outside of a request, aka in task code.

2022-06-09 15:44 UTC, gerrod3 commented on pulpcore/plugin/serializers/content.py
>      locks the Artifact and when specified, the repository.
The help text needs to be updated for the additional `upload` field.

2022-06-09 16:25 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +                raise RuntimeError("This validation should only be called in the task context.")
This check signifies a bug. When the serializer is called outside of a viewset (==without request context) the file field should already be translated into an artifact. So in the deferred validation, you either have an artifact, or an upload. Without the deferred validation, you cannot rely on an information about the uploaded file.
I will reformulate the error.

2022-06-09 17:04 UTC, gerrod3 requested changes
Found some more things to change. Keeping track of how each field in this serializer changes to become an artifact for the upload task is really hard...

2022-06-09 17:04 UTC, gerrod3 commented on pulpcore/plugin/serializers/content.py
> +    touches the Artifact and locks the Upload and Repository when specified.
You are going to need to add the resource locks on Upload objects in the generic upload viewsets in `/plugin/viewsets/content.py`.

2022-06-10 07:11 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +        the artifact.
:shrug:

2022-06-10 07:16 UTC, mdellweg commented
> Found some more things to change. Keeping track of how each field in this serializer changes to become an artifact for the upload task is really hard...

The interesting part is that an (immediately) uploaded file must be turned into an artifact before dispatching the task, while the upload will only be turned in the task code later. Maybe we could make these cases more alike by using a `PulpTemporaryFile` in the former case, but i don't see this being much of an improvement.

2022-06-10 07:24 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
This is in the deferred validation code, so we intend to use the artifact right away. No need to touch it.

2022-06-10 15:32 UTC, gerrod3 commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
Hmmph, thought that was the reason why we had to touch it, to make sure it doesn't disappear on us before we use it again.

2022-06-10 16:07 UTC, gerrod3 approved these changes
Looks good.

2022-06-15 12:58 UTC, ipanova commented on pulpcore/plugin/serializers/content.py
> +        the artifact.
we just need to document that this might be a breaking change

2022-06-15 12:58 UTC, ipanova commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
for the readability sake also - we usually whether create new artifact/content or if using the existing ones we touch it right after we have 'found' it

2022-06-15 16:32 UTC, bmbouter commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
Without a touch I think it's possible for orphan cleanup to remove it, even if its a very small window. I think it should `touch()`.

2022-06-15 16:32 UTC, bmbouter commented on pulpcore/plugin/viewsets/content.py
> +            serializer.validated_data["artifact"].touch()
I guess I see the `touch()` here?

2022-06-16 09:13 UTC, ipanova commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
I get what @mdellweg  is saying - here in the viewset we touch it right away so the window is minimal https://github.com/pulp/pulpcore/blob/cca12bcbc2f1af74d8e21955ac33aa4133f4fbe2/pulpcore/plugin/viewsets/content.py#L121
What I am saying is - when i read code and i see:
```
try:
    a = Artifact.objects.get()
except:
    a.save()
```
I start looking where is  the `touch` so i need to go and trace it in other parts of the code to be sure it was not 'forgotten'
versus I read this code and  it is my clear and explicit:
```
try:
    a = Artifact.objects.get()
    a.touch()
except:
    a.save()
```

2022-06-17 09:33 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
So this deferred validation is happening in the same tasking code that will _use_ the artifact milliseconds later. When we find the artifact in the viewset and expect to wait for the task to start, however, we perform the touch as pointed out in another comment below. So it's unclear to me whether you want me to add touch (an additional db call) here.
Do you think we can expect plugins to add validation that will take a significant amount of time before creating the content?

2022-06-17 09:38 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +        the artifact.
added a removal changelog.

2022-06-17 09:38 UTC, mdellweg commented on pulpcore/plugin/viewsets/content.py
> +            serializer.validated_data["artifact"].touch()
See answer above.

2022-06-17 11:38 UTC, ipanova commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
I am pitching for adding this db call just here and not in the deferred validation. Mostly because of readability, because it will be us who will be reading this code. I am not concerned about the milliseconds.

2022-06-17 12:23 UTC, mdellweg commented on pulpcore/plugin/serializers/content.py
> +                    artifact = Artifact.objects.get(sha256=file.hashers["sha256"].hexdigest())
This _is_ in the deferred_validate code. Hence all the argumentation. But i will add it anyway. I convinced myself, that shoving the artifact through some external validation may take an unprecedented amount of time before actually turning it into a content unit.

2022-06-17 14:50 UTC, ipanova approved these changes
Thank you!

2022-06-17 14:58 UTC, merged