Improve content app performance on head requests
pulp/pulpcore pull request #2925
Opened 2022-07-04 12:06 UTC by fao89

closes #2924

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2022-07-04 18:41 UTC, bmbouter commented on pulpcore/content/handler.py
> +            return HTTPOk(headers={"Content-Type": "text/html"})
Does it even need the header specified?

2022-07-05 13:50 UTC, bmbouter requested changes
Would you be willing to write some docs on how users can check if a specific content app is alive by issuing a `HEAD /pulp/content/` call (or whatever [CONTENT_PATH_PREFIX](https://docs.pulpproject.org/pulpcore/configuration/settings.html#content-path-prefix) is set to).

I think it would make sense as a new section called "Availability" in this area https://docs.pulpproject.org/pulpcore/components.html (or wherever it makes sense to you).

2022-07-05 16:55 UTC, bmbouter approved these changes
Thank you!

2022-07-05 19:48 UTC, bmbouter commented
FWIW I don't think this is worth backporting

2022-07-06 13:20 UTC, mdellweg approved these changes

2022-07-06 13:20 UTC, merged