Enable telemetry for users
pulp/pulpcore pull request #3116
Opened 2022-08-22 20:08 UTC by bmbouter

By default Pulp systems will now submit anonymous telemetry information
to https://analytics.pulpproject.org/. It documents exactly what is
submitted, and introduces the `TELEMETRY` setting which can be used to
disable anonymous telemetry submission entirely.
    
closes #3115

2022-08-22 20:09 UTC, bmbouter commented
We're going to merge the first commit as part of this PR: https://github.com/pulp/pulpcore/pull/3025/

2022-08-23 08:42 UTC, ipanova requested changes

2022-08-23 08:42 UTC, ipanova commented on pulpcore/app/apps.py
> +    if settings.TELEMETRY and "core_taskschedule" in connection.introspection.table_names():
you want to leave the logic in place for when the setting was ON then OFF so the task schedule gets deleted.

2022-08-24 15:21 UTC, ipanova approved these changes
looks good!

2022-08-25 06:45 UTC, mdellweg approved these changes

2022-08-25 13:44 UTC, merged