Switch to a UUIDv7 (draft 04) implementation as the UUID generator
pulp/pulpcore pull request #3136
Opened 2022-08-25 04:43 UTC by dralley

UUIDv7 was designed to be lexicographically sortable and
database-index friendly.

closes #3117

2022-08-25 04:43 UTC, dralley commented on requirements.txt
> +uuid6==2022.06.25
irony

2022-08-25 04:44 UTC, dralley commented on pulpcore/app/models/base.py
> +from uuid6 import uuid7
irony

2022-08-26 02:05 UTC, dralley commented
Looks like we cannot make this change until 3.25.  It ends up creating migrations in any plugin that has models which inherit from `BaseModel` directly rather than going through a master-detail model.

2022-08-26 09:01 UTC, mdellweg commented on pulpcore/app/migrations/0095_auto_20220826_0201.py
> +            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
Looks like we need all plugins to move to this individually and create their migrations for it.
It probably does not hurt if they don't though.

2022-08-26 12:56 UTC, dralley commented on pulpcore/app/migrations/0095_auto_20220826_0201.py
> +            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
I'm not 100% sure about that, we'll need to see

2022-08-31 20:47 UTC, dralley commented on pulpcore/app/migrations/0095_auto_20220826_0201.py
> +            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
@mdellweg You're right, I tested both ways (applying the migration to pulpcore but not the plugin, and applying it to the plugin but not pulpcore) and it works fine.

2022-08-31 20:53 UTC, dralley commented on pulpcore/app/migrations/0095_auto_20220826_0201.py
> +            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
I'm curious whether the CI for some plugins will start complaining about unapplied migrations though, it might force it to be adopted sooner rather than later to avoid issues.

It's good to be reminded that we have some abstract model inheritance going on still... should probably address that.

2022-09-01 19:31 UTC, dralley commented on pulpcore/app/migrations/0095_auto_20220826_0201.py
> +            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
>I'm curious whether the CI for some plugins will start complaining about unapplied migrations though, it might force it to be adopted sooner rather than later to avoid headache.

On the flip side, for developers using a newer plugin with an older version of pulpcore, makemigrations would try to revert the UUID patch.  But that's rare and not particularly consequential.

The real issue here is that we've still got plugins inheriting from a core-provided abstract model.  It's not as bad a situation as `BaseDistribution` but it's not great.

2022-09-01 19:46 UTC, dralley commented
Moving to draft pending discussion in the pulpcore meeting on Tuesday

2022-09-06 18:23 UTC, bmbouter commented on CHANGES/plugin_api/3117.feature
> +Created a wrapper type for UUID generation so that the implementation can potentially be switched in the future.  UUIDs are just 128-bit integers so as long as they don't overlap there is no explicit
This needs to be line wrapped to 98 chars.

2022-09-06 18:35 UTC, bmbouter commented on pulpcore/plugin/models/__init__.py
> +    pulp_uuid,
nitpick: this needs to be alphabetized

2022-09-06 18:36 UTC, bmbouter commented on requirements.txt
> +uuid6==2022.06.25
Can we have broader compatibility than this? What if some other dependency wants another version of `uuid6` for example.

2022-09-06 18:37 UTC, bmbouter commented on pulpcore/app/models/base.py
> +
```suggestion
    """
    Abstract wrapper for UUID generator.

```

2022-09-06 18:37 UTC, bmbouter commented on pulpcore/app/models/base.py
> +
```suggestion
    """
    Abstract wrapper for UUID generator.

```

2022-09-06 18:38 UTC, bmbouter requested changes
Overall this is looking good to me. I left a bunch of little requests.

2022-09-07 03:07 UTC, dralley commented on pulpcore/app/models/base.py
> +
I could do this, but it wouldn't match any of the existing docstrings in this file.  Do you want me to change all of them?

This file does seem inconsistent with other files FWIW.

2022-09-07 03:10 UTC, dralley commented on requirements.txt
> +uuid6==2022.06.25
Tricky since they don't use semantic versioning : /

2022-09-07 03:32 UTC, dralley commented
This new strategy eliminates the need for any plugins to ever import `uuid6` directly, which is great.

It does still cause some plugins (ones with models that inherit from `BaseModel` directly) to want a new migration.  However, it will prevent that from ever being necessary again in the future - and it's also not abnormal, any plugin that ever wants to use a new pulpcore feature would need to do this, and we have a few such features in 3.21 anyway like the new field on `RepositoryVersion` requested by Atix.  So it feels like this wouldn't really be a significant problem for anyone.

But actually we could eliminate that problem too - the only thing it cares about is the existence of a function by that name - we could just copy the function to older pulpcore branches (without changing anything functionally, and without actually using it anywhere in Pulpcore), and we would basically have no compatibility concerns at all.

```Python
def pulp_uuid():
    return uuid.uuid4()
```

Matthias / Grant, I'd be happy enough to just get the first commit in if you still have concerns about `uuid7`

2022-09-07 09:12 UTC, mdellweg commented
I still believe that we will have all the plugins to want a migration and once they have it, they depend hard on the pulpcore version introducing this. So it is really all the way the `BaseDistribution` reloaded.
The question that we need to ask ourselves is, are we confident with shipping plugins that want a migration and don't get it for a while.

2022-09-07 15:47 UTC, dralley commented on CHANGES/plugin_api/2998.feature
> +Added new field ``info`` to the ``RepositoryVersion``. This will allow to store additional
No, though I can move it out if you want.  You asked for the lines to be truncated to the character limit but this one went over.

2022-09-07 15:57 UTC, bmbouter commented on CHANGES/plugin_api/3117.feature
> +there is no explicit need to stick with any particular implementation. Plugin writers may
If plugin writers may need to create a migration doesn't this have to wait until 3.25? Currently a forward compatible plugin wouldn't have those changes is what I was thinking.

2022-09-07 15:58 UTC, bmbouter commented
How can I learn more about the database indexing benefits? I think that is key on reaching agreement on the acceptance of this.

2022-09-07 15:59 UTC, dralley commented on CHANGES/plugin_api/3117.feature
> +there is no explicit need to stick with any particular implementation. Plugin writers may
They don't *need* to, it will work fine without it.

2022-09-07 16:00 UTC, bmbouter commented on CHANGES/plugin_api/3117.feature
> +need to create migrations to adopt this.
```suggestion
want to create migrations to adopt this, although it is optional.
```

2022-09-07 16:01 UTC, dralley commented
@bmbouter The IETF document is a good place to start https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format#section-1

2022-09-07 16:04 UTC, bmbouter commented on requirements.txt
> +uuid6==2022.06.25
True, but couldn't we just `uuid6<=2022.06.25`. Even though it's a date it's still a semver compatible number I believe. I looked at their changelog and since all we do is call `uuid6` I think this is safe. I'm preparing a PR that recommends similar approaches be taken (I've had [this issue](https://github.com/pulp/pulpcore/issues/2997) assigned for a long time).

2022-09-08 07:49 UTC, mdellweg commented on CHANGES/plugin_api/3117.feature
> +there is no explicit need to stick with any particular implementation. Plugin writers may
But our plugin ci will complain until they do, right?

2022-09-08 12:31 UTC, dralley commented on CHANGES/plugin_api/3117.feature
> +there is no explicit need to stick with any particular implementation. Plugin writers may
> Also we will be in a situation where users may start generating migrations on site (i think we had this issue with migrations that were dependent on configurations).

Hmmm, that's interesting.  When did that happen?  I'm not sure I am familiar with the background.

On a separate note, I had this idea to try to make it easier for plugins to just adopt the new migration without impacting their compatibility with previous versions of pulpcore too badly: https://github.com/pulp/pulpcore/pull/3136

2023-01-18 19:55 UTC, dralley commented
It's waiting for the 3.25 update cycle

2023-05-03 08:10 UTC, mdellweg commented on pulpcore/app/models/base.py
> +    pulp_id = models.UUIDField(primary_key=True, default=pulp_uuid, editable=False)
Label is scheduled to go away in 3.25. ;)

2023-05-03 12:49 UTC, dralley commented on pulpcore/app/models/base.py
> +    pulp_id = models.UUIDField(primary_key=True, default=pulp_uuid, editable=False)
I assume this means you'd like to drop that model first?

2023-05-03 15:19 UTC, mdellweg commented on pulpcore/app/models/base.py
> +    pulp_id = models.UUIDField(primary_key=True, default=pulp_uuid, editable=False)
Well, honestly it does not matter much. Maybe the migration will use a few microseconds less on each new installation.

2023-05-04 13:50 UTC, mdellweg approved these changes
One necessary change (i believe should be caught by the CI) pending.

2023-05-04 13:50 UTC, mdellweg commented on requirements.txt
> +uuid6>=2023.5.2
I think this needs an upper bound.

2023-05-04 13:52 UTC, dralley commented on requirements.txt
> +uuid6>=2023.5.2
How I wish semver was mandatory

2023-05-04 13:57 UTC, mdellweg commented on requirements.txt
> +uuid6>=2023.5.2
Hell yeah!

2023-05-04 14:01 UTC, decko approved these changes

2023-05-04 14:30 UTC, merged