Add `write_only_fields` to RemoteSerializer
pulp/pulpcore pull request #3167
Opened 2022-09-02 10:19 UTC by jerabekjiri

fixes: [pulp#2825](https://github.com/pulp/pulpcore/issues/2825)

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2022-09-05 09:20 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +        # returns false if field is "" or None
This is not entirely true. It returns whatever evaluates to boolean `False`. This includes `[]`, `{}` and `set()`. Should we check explicitly for `""` and `None`?

2022-09-05 12:39 UTC, jerabekjiri commented on pulpcore/app/serializers/repository.py
> +        # returns false if field is "" or None
@mdellweg I think in theory, we could check just for `""` and `None` since in `RemoteSerializer` the `write_only` is used only for `CharField`

2022-09-05 13:01 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +        # returns false if field is "" or None
We should do in practice. As this also affects all future fields and maybe unknown subclasses. They may have a write-only bool field. And in that case `False` is a real set value.

2022-09-12 15:26 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_repository.py
> +        serializer = RemoteSerializer(Remote, data=data, partial=True)
Ha! I believe the serializer should not accept "write_only_fields" for writing. Being a SerializerMethodField it should be read_only anyway. Maybe the serializer just ignores this?

2022-09-12 15:26 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_repository.py
> +        fields = serializer.get_write_only_fields(Remote, extra_data)
I think, we don't need to call that directly, but instanciate a serializer from a Remote object serialize that and check the output for the "write_only_fields".

2022-09-14 13:45 UTC, ipanova commented on pulpcore/app/serializers/repository.py
> +        for field_name in fields:
this is dict right? you can use items() instead

2022-09-14 14:07 UTC, ipanova commented on pulpcore/app/serializers/repository.py
> +    write_only_fields = serializers.SerializerMethodField(
The initial feature request was not scoped only to the remote serializer but  to all the write_only fields. There is for example user serializer that has password as write only, i think it should also benefit from this feature.

Thoughts?

2022-09-20 13:49 UTC, dkliban commented
@jerabekjiri Are you still working on this?

2022-09-20 16:38 UTC, jerabekjiri commented on pulpcore/app/serializers/repository.py
> +    write_only_fields = serializers.SerializerMethodField(
Good idea, I'll look into that

2022-09-20 16:44 UTC, jerabekjiri commented
@dkliban yes, but I was busy with finishing stuff for 2.3

2022-09-21 16:08 UTC, gerrod3 commented on pulpcore/tests/unit/serializers/test_repository.py
> +        fields = serializer.get_write_only_fields(Remote, extra_data)
```suggestion
        serializer = RemoteSerializer(Remote, data=extra_data, partial=True)
        serializer.is_valid(raise_exception=True)
        fields = serializer.write_only_fields
```

2022-09-21 16:14 UTC, gerrod3 commented on pulpcore/app/serializers/repository.py
> +    def get_write_only_fields(serializer, obj, extra_data=None):
```suggestion
    def get_write_only_fields(self, obj):
```
This is a method on the serializer so it should use `self`. Also, since this method is a `SerializerMethodField` it should follow their API which only accepts one argument (besides `self`): https://www.django-rest-framework.org/api-guide/fields/#serializermethodfield

2022-09-21 16:57 UTC, gerrod3 commented on pulpcore/tests/unit/serializers/test_repository.py
> +        fields = serializer.get_write_only_fields(Remote, extra_data)
Ok my suggestion doesn't work. Maybe this should be a functional test, but if you want to test the method directly then what you are doing now is fine, although I think the `extra_data` param is incorrect (see my comment above). 

Another way to do this test:
```python
from pulp_file.app.models import FileRemote
        ...
        remote = FileRemote.objects.create(**self.minimum_data)
        # Maybe just include extra data in the remote creation
        serializer = RemoteSerializer(remote, data=extra_data, context={"request": None})
        serializer.is_valid(raise_exception=True)
        fields = serializer.data["write_only_fields"]
```

2022-09-27 07:24 UTC, mdellweg commented on pulpcore/app/serializers/exporter.py
> +
I think i do not quite like this pattern. Can we add these as a mixin?

2022-09-30 10:35 UTC, mdellweg commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
Now this is interesting. The write-only fields here are as far as i a can see only used to create the exports, and probably never persisted on the model. I don't see the logic for adding this facility for them.

However is see that we have two semantics for "write_only":
1. Used to create a thing but no persistent meaning thereafter.
2. Used to hide the value of a field.

We should only introduce this technology for the latter.
WDYT? @pulp/core

2022-09-30 10:35 UTC, mdellweg commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
Maybe the right terminus here is "hidden fields".

2022-09-30 13:29 UTC, bmbouter commented on pulpcore/tests/unit/serializers/test_repository.py
> +class TestPublicationSerializer(unittest.TestCase):
If this change causes you to have to also change any test code leave it as is since this is not the goal of your PR.

2022-09-30 13:31 UTC, bmbouter commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
My understanding is also that it's only for hiding the value of a saved field. The issue you're describing though is already present regardless of this PR is that right?

2022-09-30 13:44 UTC, ggainey commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
We're using write_only in PulpExport serializer for the django usage/definition: "Set this to True to ensure that the field may be used when updating or creating an instance, but is not included when serializing the representation.". As @mdellweg notes, in this class it denotes things you pass in, but which are not persisted.

2022-10-03 13:11 UTC, jerabekjiri commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
I have added `write_only_fields` to all serializers with `write_only` fields, which wasn't a great idea. 

I also see `write_only` fields in `SingleArtifactContentUploadSerializer`, `UploadSerializerFieldsMixin`, `SingleArtifactContentSerializer`, `UploadChunkSerializer`. Can we decide on which of these serializers should have the `write_only_fields` field?

2022-10-03 20:26 UTC, ipanova commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
I think it should be just UserSerializer

2022-10-05 07:25 UTC, mdellweg requested changes

2022-10-05 07:25 UTC, mdellweg commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
This question needs to be resolved.

2022-10-05 09:42 UTC, jerabekjiri commented
@mdellweg from [Ina's comment](https://github.com/pulp/pulpcore/pull/3167#discussion_r986191275), I was planning to revert changes and use serializer just for `RemoteSerializer` and `UserSerializer`?

2022-10-05 11:52 UTC, ipanova commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
@mdellweg will renaming WriteOnlyFieldsMixin to WriteOnlyHiddenFieldsMixin( to better describe its nature)  and adding that mixing to remote and user serializer suffice to address your question, given that I am correctly understating it.

2022-10-05 12:05 UTC, mdellweg commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
That might work today. Should we call the field `hidden_fields` too?

In general, i cannot see that we will never have a serializer having both types of fields. At that point we would need a more explicit interface or a better heuristic.

2022-10-05 12:06 UTC, mdellweg commented
> @mdellweg from [Ina's comment](https://github.com/pulp/pulpcore/pull/3167#discussion_r986191275), I was planning to revert changes and use serializer just for `RemoteSerializer` and `UserSerializer`?

Keep the mixin intact please.

2022-10-05 12:09 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +    )
What is the openapi spec that is generated for this field?

2022-10-05 12:13 UTC, ipanova commented on pulpcore/app/serializers/exporter.py
> +class PulpExportSerializer(ExportSerializer, WriteOnlyFieldsMixin):
Since there is not a usecase of such situation to be addressed today, i will leave this until we have one and solve it in future. Today we want to have mixing for write_only fields that have a purpose to be hidden - lets' call it so and apply only to those serializers that need it. my 2c

2022-10-06 12:16 UTC, jerabekjiri commented on pulpcore/app/serializers/base.py
> +    )
Currently: `"write_only_fields": "string"`. I'll change this to match the actual response :+1:

2022-10-06 12:30 UTC, mdellweg submitted a review, later dismissed

2022-10-06 12:30 UTC, mdellweg commented on pulpcore/app/serializers/__init__.py
> +    WriteOnlyFieldsMixin,
Can we decide not to call this "write_only" but "hidden"?
@pulp/core

2022-10-06 13:09 UTC, jerabekjiri commented on pulpcore/app/serializers/base.py
> +    List of dictionaries is containing `name` and `field_is_set`
@mdellweg I followed this https://github.com/pulp/pulpcore/issues/2825#issuecomment-1169906703, should I revert it to just `is_set`?

2022-10-06 13:17 UTC, jerabekjiri commented on pulpcore/app/serializers/__init__.py
> +    WriteOnlyFieldsMixin,
I think I misread the last discussion, so should this be `HiddenFieldsMixin` and the serializer field just `hidden_fields`?

2022-10-06 14:00 UTC, ipanova commented on pulpcore/app/serializers/__init__.py
> +    WriteOnlyFieldsMixin,
I am down with that

2022-10-06 14:05 UTC, ggainey commented on pulpcore/app/serializers/__init__.py
> +    WriteOnlyFieldsMixin,
HiddenFieldsMixin works for me as well

2022-10-06 15:29 UTC, jerabekjiri commented on pulpcore/tests/unit/serializers/test_repository.py
> +class TestPublicationSerializer(unittest.TestCase):
hmm, I thought I had to switch to using `unitest.TestCase` for `TestRemoteSerializer` because it was causing
```
E       RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```
and then adding `@pytest.mark.django_db` didn't seem to help and it was throwing `Overriding pulp_container access policy` warning, but testing it now it's working fine with the `django_db` mark. 

So would be a better idea to keep unittest and add `@pytest.mark.django_db` just to my `test_write_only_fields` and `test_read_only_write_only_fields` tests?

2022-10-06 17:00 UTC, jerabekjiri commented on pulpcore/app/serializers/__init__.py
> +    WriteOnlyFieldsMixin,
done, thanks :)

2022-10-11 11:42 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +    List of dictionaries is containing `name` and `is_set`
```suggestion
    Adds a list field of hidden (write only) fields and whether their values are set
    so clients can tell if they are overwriting an existing value.
    For example this could be any sensitive information such as a password, name or token.
    The list contains dictionaries with keys `name` and `is_set`.
```

2022-10-11 11:46 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +    )
Can you paste the verbatim content of the spec for this parameter?

`pulp debug openapi schema --name UserResponse | jq '.properties.hidden_fields'`

2022-10-13 10:03 UTC, jerabekjiri commented on pulpcore/app/serializers/base.py
> +    )
I finally figured out I had to switch to pulp's UserSerializer and I'm not able to run pulp debug with `oci_env`, but this should work
```
➜  oci_env git:(main) curl http://localhost:5001/api/automation-hub/pulp/api/v3/docs/api.json | jq '.components.schemas.UserResponse.properties.hidden_fields'
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "is_set": {
        "type": "boolean"
      }
    }
  },
  "readOnly": true,
  "description": "List of hidden (write only) fields"
}
```
and just in case here's RemoteSerializer
```
➜  oci_env git:(main) curl http://localhost:5001/api/automation-hub/pulp/api/v3/docs/api.json | jq '.components.schemas.RemoteResponse.properties.hidden_fields'
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "is_set": {
        "type": "boolean"
      }
    }
  },
  "readOnly": true,
  "description": "List of hidden (write only) fields"
}

```

2022-10-13 14:21 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +    ) -> List[TypedDict("hidden_fields", {"name": str, "is_set": bool})]:
Yay! This looks great!

2022-10-17 11:25 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_repository.py
> +        serializer = RemoteSerializer(remote, data=data, context={"request": None})
```suggestion
        remote = FileRemote(**data)
        serializer = RemoteSerializer(remote, data=data, context={"request": None})
```

I think, this is what is trying to talk to the database. And for testing the serializer, there should be no need for. So with this suggested change, i believe we can all safely go back to just using unittest.

2022-10-17 16:37 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_repository.py
> +        serializer = RemoteSerializer(remote, data=data, context={"request": None})
Is the "SimpleNamespace" approach not working here?

2022-10-17 17:38 UTC, jerabekjiri commented on pulpcore/tests/unit/serializers/test_repository.py
> +        serializer = RemoteSerializer(remote, data=data, context={"request": None})
no, afaiu `hidden_fields` doesn't get serialized, because it's missing attributes
```
self = DetailIdentityField(view_name_pattern='remotes(-.*/.*)-detail')
obj = namespace(name='test', proxy_password='pass', proxy_url='http://whatever', proxy_username='user', url='http://whatever')

    def _view_name(self, obj):
        # this is probably memoizeable based on the model class if we want to get cachey
        try:
>           obj = obj.cast()
E           AttributeError: 'types.SimpleNamespace' object has no attribute 'cast'
```

2022-10-18 07:42 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_repository.py
> +        serializer = RemoteSerializer(remote, data=data, context={"request": None})
Ok, there's the second attempt to get to the database then. Can we mock `_view_name` here?

I kind of don't want this "easy" test to trigger the whole django create a test database machinery. And at the same time i don't want to invest too much into unittest style unit tests. (We have an ongoing test rewriting effort from unittest to pytest.)

2022-10-20 10:54 UTC, mdellweg approved these changes

2022-10-21 08:56 UTC, merged