Added pulpcore-manager command for removing signing services
pulp/pulpcore pull request #3182
Opened 2022-09-08 12:05 UTC by MichalPysik

The pulpcore-manager now supports command 'remove-signing-service' which allows for removing signing services specified by name and class.

closes #2967

2022-09-08 16:18 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +        available_signing_services = {ss.name for ss in SigningService.objects.all()}
```python
service = SigningService.objects.get(name=name)
service.delete()
```
Should have been sufficient. You'd catch both `IntegrityError` and `DoesNotExist`.

2022-09-09 09:25 UTC, MichalPysik commented on pulpcore/app/management/commands/remove-signing-service.py
> +        available_signing_services = {ss.name for ss in SigningService.objects.all()}
That sounds good, I will change that for the deletion code. Although I will keep the lines you selected (38-41), since their purpose is mainly to show the user the list of all available services when he selects a non-existent one.

2022-09-09 10:41 UTC, mdellweg commented on pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
> +        "core:AsciiArmoredDetachedSigningService",
:+1: Thank you for not forgetting this!

2022-09-09 10:41 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +                    "For more information, please refer to the detailed error message below:"
I would rephrase this to `raise CommandError("Signing service {name} of class {} does not exist.").
Reason: Let's not start to speculate for the user. The name could have been a typo and never existed anyway. Also the exception tells us "The thing de not exist". That is all the information the user ever wants to hear. There is no point in rerasining it.

2022-09-09 10:41 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +            raise e
Same here. Don't generate too much information: `raise CommandError("SingingService could not be removed because it is still in use.")`

2022-09-09 10:41 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +            )
Let's not do this. The user didn't ask for it. There's an api to list signing services.

2022-09-09 10:44 UTC, MichalPysik commented on pulpcore/app/management/commands/remove-signing-service.py
> +                    "For more information, please refer to the detailed error message below:"
The problem with this is that it could not have been a typo, since if the service didn't exist, it wouldn't get found in the list of all available services above. But I can still shorted the message tho

2022-09-09 12:03 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +                    "For more information, see the detailed error message below:"
Can you give an example of the "more information" please?

2022-09-09 12:03 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +                ).format(name)
I really do not expect more information here. The thing does not exist. That is it.

2022-09-14 09:39 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +            raise e
```suggestion
            raise CommandError(
                _("Signing service '{}' could not be removed because it's still in use.").format(
                    name
                )
            )
```

2022-09-14 09:41 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +            raise e
```suggestion
            raise CommandError(_("Signing service '{}' of class '{}' does not exists.").format(name))
```

2022-09-14 09:42 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +
Can we add a check here that the class is a subclass of the signing service base class?

2022-09-14 11:05 UTC, MichalPysik commented
Should I maybe rewrite the stdout writes to raises of CommandError instead? @mdellweg

2022-09-14 11:51 UTC, mdellweg commented on pulpcore/app/management/commands/remove-signing-service.py
> +        if SigningService.__base__ is not BaseSigningService:
there's a builtin `issubclass`.
Also can you add the same check to the other management command?

2022-09-14 12:04 UTC, MichalPysik commented on pulpcore/app/management/commands/remove-signing-service.py
> +        if SigningService.__base__ is not BaseSigningService:
I tried that, but it didn't work, maybe I did it incorrectly so I will try it again. What other command do you mean, ``add-signing-service`` ?

2022-09-14 12:57 UTC, mdellweg approved these changes

2022-09-14 12:58 UTC, mdellweg commented on CHANGES/2967.feature
> +Added pulpcore-manager command called remove-signing-service for removing specified signing services.
```suggestion
Added pulpcore-manager command called ``remove-signing-service`` for removing specified signing services.
```

2022-09-14 15:29 UTC, bmbouter commented on pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
> -        "shell",
:+1:

2022-09-14 15:45 UTC, bmbouter commented on pulpcore/app/management/commands/remove-signing-service.py
> +            self.stdout.write(_("Signing service '{}' has been successfully removed.").format(name))
This could move out of the try block entirely or to an `else` clause.

2022-09-14 15:51 UTC, bmbouter requested changes
@MichalPysik right now we have fixtures that use these commands, but can you add a test in pulpcore that creates and deletes a `core:AsciiArmoredDetachedSigningService` signing service. I just did an audit in pulpcore and pulp_file and I don't see any test that actually uses these fixtures in either repo. Since the signing service and fixture are in pulpcore, I think it can just live in pulpcore.

What do you think? If this doesn't make sense, please ask. Thanks!

2022-09-20 11:54 UTC, mdellweg commented on pulpcore/tests/functional/api/test_signing_service.py
> +    assert service.pulp_href.isascii()
I thought that you'd check that the pulp_href contains the string "ascii". And maybe it doesn't...

2022-09-20 19:18 UTC, bmbouter commented on pulpcore/tests/functional/api/test_signing_service.py
> +def test_crud_signing_service(ascii_armored_detached_signing_service):
:heart_eyes:

2022-09-20 19:18 UTC, bmbouter approved these changes
Thank you!!

2022-09-20 19:19 UTC, bmbouter commented
I see two approvals so I'm going to merge.

2022-09-20 19:19 UTC, merged

2022-09-20 19:54 UTC, MichalPysik commented on pulpcore/tests/functional/api/test_signing_service.py
> +    assert service.pulp_href.isascii()
The pulp_href doesn't contain the word 'ascii', I checked the format of the href.

2022-11-22 15:14 UTC, tjmullicani commented
Any idea when this feature will be integrated into the pulpcore release schedule? I didn't see it in 3.21.3.

2022-11-22 15:16 UTC, dralley commented
It'll be in the next released, probably 1-2 weeks from now.