Fs exporter correctly handles hardlink across partitions
pulp/pulpcore pull request #3188
Opened 2022-09-09 03:34 UTC by parthaa

Fixed the fs exporter to handle the case where hardlink method was requested but pulp and export locations are in different partitions so can't share the same inode.

2022-09-09 03:40 UTC, parthaa commented
fixes #3187

2022-09-09 03:47 UTC, dralley commented on pulpcore/app/tasks/export.py
> +        raise RuntimeError(_("Unsupported export method '{}'.").format(method))
The serializer layer ought to be handling this already, right?

2022-09-09 03:50 UTC, dralley commented on pulpcore/app/tasks/export.py
> +                pass
Is this related to https://github.com/pulp/pulpcore/issues/1949 ?

2022-09-09 04:21 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +        raise RuntimeError(_("Unsupported export method '{}'.").format(method))
Thats a good point!. Will remove that check

2022-09-09 05:43 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +                pass
Interesting. Guess this might fix that too :)
I just added it because there was a precedent to this pattern here -> https://github.com/pulp/pulp-2to3-migration/blob/main/pulp_2to3_migration/app/plugin/content.py#L163-L170

2022-09-09 14:00 UTC, dralley commented on pulpcore/app/tasks/export.py
> +                pass
If you do fix that one too, just mark it fixed in the commit message :)

2022-09-09 17:23 UTC, parthaa commented on pulpcore/app/tasks/export.py
>              os.symlink(src, dest)
That's a good point copy vs symlink. I am not sure which is better :). Writes are probably better if its across an nfs share.

2022-09-09 17:59 UTC, parthaa commented on pulpcore/app/tasks/export.py
>              os.symlink(src, dest)
oh wait you are asking a diff question :). Yes `os.symlink` fails if file already exists

2022-09-09 18:02 UTC, dralley commented on pulpcore/app/tasks/export.py
>              os.symlink(src, dest)
Yup, different question - let's make sure the behavior is consistent regardless of whether the user hardlinks or softlinks, if it doesn't fail if the file already exists for one then it shouldn't fail or the other.

2022-09-16 18:16 UTC, dralley commented
@parthaa Could you write a changelog entry to make the CI happy?

2022-09-23 18:19 UTC, dralley commented on pulpcore/app/tasks/export.py
> +                pass
Is there a cheap way to verify that it's the same file being pointed to by the symlink?

2022-09-23 18:21 UTC, dralley commented on pulpcore/app/tasks/export.py
> +        and os.stat(settings.MEDIA_ROOT).st_dev != os.stat(path).st_dev
I would break this out into a separate variable

```Python
export_on_same_filesystem = os.stat(settings.MEDIA_ROOT).st_dev != os.stat(path).st_dev

if method == FS_EXPORT_METHODS.HARDLINK and export_on_same_filesystem:
    # ....
```

2022-09-29 02:52 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +                pass
What  about removing the dest symlink and then symlinking ?

2022-09-29 14:58 UTC, dralley commented on pulpcore/app/tasks/export.py
> +                pass
That works too

2022-09-30 02:07 UTC, dralley approved these changes

2022-09-30 02:08 UTC, dralley commented
@parthaa If there are BZs for these issues then please link them so we can make sure they get tagged appropriately

2022-09-30 02:45 UTC, parthaa commented
> If there are BZs for these issues then please link them so we can make sure they get tagged appropriately


https://bugzilla.redhat.com/show_bug.cgi?id=2125444  . Not sure what I need to do.

2022-09-30 02:46 UTC, parthaa commented
I am also not sure why the unit tests are failing :(

2022-10-04 13:36 UTC, dralley commented
@parthaa Try rebasing on the latest main branch

2022-10-06 18:36 UTC, ggainey approved these changes
Looks good, please rebase to main and repush, should clear up the test-failures.

2022-10-12 12:27 UTC, ggainey commented
@parthaa the failing tests are telling us that the on-same-filesystem check doesn't work when you're on a block-storage device like, say, s3. See https://github.com/pulp/pulpcore/actions/runs/3219721871/jobs/5265485591#step:13:8493 for the specific point of failure. We need to figure out the right way to accomplish this.

2022-10-12 12:28 UTC, ggainey requested changes
Fails on block-storage devices - need to figure out the right way to ask this question in that scenario.

2022-10-12 18:12 UTC, ggainey requested changes

2022-10-12 18:12 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +    export_on_same_filesystem = (
```suggestion
    export__not_on_same_filesystem = (
```

2022-10-12 18:12 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +    if method == FS_EXPORT_METHODS.HARDLINK and export_on_same_filesystem:
```suggestion
    if method == FS_EXPORT_METHODS.HARDLINK and export__not_on_same_filesystem:
```

2022-10-12 19:28 UTC, ggainey approved these changes
Changes look great - approved!

2022-10-12 19:29 UTC, merged

2022-10-12 19:30 UTC, dralley commented on pulpcore/app/tasks/export.py
>          and method != FS_EXPORT_METHODS.WRITE
@parthaa Move the check to a separate line

```Python
local_filesystem = settings.DEFAULT_FILE_STORAGE == "pulpcore.app.models.storage.FileSystem"
if not local_filesystem and method != FS_EXPORT_METHODS.WRITE:
    raise RuntimeError(_("Only write is supported for non-filesystem storage."))
    
os.makedirs(path)
if method == FS_EXPORT_METHODS.HARDLINK:
    # hardlink method is not permitted if not on a local filesystem
    if os.stat(settings.MEDIA_ROOT).st_dev != os.stat(path).st_dev:
        log.info(_("Hard link cannot be created, file will be copied."))
        method = FS_EXPORT_METHODS.WRITE
```