[POC] Add new multi-tenancy feature: domains
pulp/pulpcore pull request #3190
Opened 2022-09-11 00:23 UTC by gerrod3

Lots of changes to add domains: an **_opt-in_** namespace feature to allow for multi-tenancy. This is a POC and doesn't contain all the necessary changes for pulpcore (maybe 70%). The goal of this PR is for discussion and feedback and hopefully show a feature of this scale can be added in the next Y release without breaking plugins and existing users.

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +        unique_together = ("name", "domain")
Would this uniqueness hold if the default domain was saved as `None`?

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/app/models/role.py
> +    domain_id = models.TextField(null=True)
Foreign key?

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +        self.check_cross_domains({"repository": repository, "remote": remote})
Is this check not done by the `ValidateFieldsMixin`?

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/app/util.py
> +    return models.Domain.objects.get(name="default", storage_class="default").pk
```suggestion
@lru_cache(maxsize=1)
def get_default_domain():
    return models.Domain.objects.get(name="default", storage_class="default").pk
```

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/app/viewsets/access_policy.py
> +    # There is probably more locked roles needed for a feature like this
I don't even think so. It should be rather simple for this central object. The complexity is added to all the objects contained by it.
The thing we may need is another permission `can_manage_domain_roles` to allow setting domain wide roles.

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/backends.py
> +        # Not sure how or if I need to get this function to work with domains...
I think yes. If you receive a permission for the `obj` via a domain, it should be listed too.

2022-09-12 08:31 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
I had envisioned that there would be the name of the domain. But this looks interesting too.

2022-09-12 12:58 UTC, gerrod3 commented on pulpcore/app/models/publication.py
> +        unique_together = ("name", "domain")
No, this is why I am using a default_domain. Null fields can not be used for a uniqueness constraint since null != null in SQL.

2022-09-12 13:29 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +        unique_together = ("name", "domain")
Too sad...

2022-09-12 15:20 UTC, gerrod3 commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
If I make `domain.name` unique then yes it could be.

2022-09-12 15:22 UTC, gerrod3 commented on pulpcore/app/models/role.py
> +    domain_id = models.TextField(null=True)
Yeah, roles logic is kind of messed up right now. I was testing if the uniqueness constraint was about null values or the type of data (Text vs ForeignKey)

2022-09-12 15:28 UTC, gerrod3 commented on pulpcore/app/serializers/repository.py
> +        self.check_cross_domains({"repository": repository, "remote": remote})
It is called, but not with all the fields filled in to be valid as repository isn't a field, it's part of the url. I think I might need to create a second method like `prepare_fields` that `check_cross_domains` calls so that it can get each field for the cross check for serializers like this.

2022-09-12 15:30 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
The question is whether we _want_ to see the domain as a kind of namespace.

2022-09-12 15:49 UTC, gerrod3 commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
Oh, are you saying instead of `/pulp/domain/...` it should be `/pulp/{domain_pk}/...`? Otherwise I don't know how to differentiate requests to the content-app now that `base_path` is not unique.

2022-09-13 08:54 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
No what i was saying is i always thought the domain would give us a namespace like `/pulp/content/{domain.name}/{base_path}` or (because that ship has sailed...) `/pulp/domain/{domain.name}/{base_path}`. And yes the domain name must be unique then, just as the username.
I'm not sure anymore and we need to get more information from potential users here.

2022-09-14 13:12 UTC, mdellweg commented
Collapsing into one domain is probably not going to work due to _all_ the uniqueness constraints that contain the domain pk now (e.g. names that are unique in a domain/namespace).

2022-09-14 15:52 UTC, bmbouter commented
> Collapsing into one domain is probably not going to work due to _all_ the uniqueness constraints that contain the domain pk now (e.g. names that are unique in a domain/namespace).

Agreed and I think pulp needs a startup check that refuses to start if > 1 domain and yet you have `ENABLE_DOMAIN=False`.

2022-09-15 09:57 UTC, ipanova commented
> > Collapsing into one domain is probably not going to work due to _all_ the uniqueness constraints that contain the domain pk now (e.g. names that are unique in a domain/namespace).
> 
> Agreed and I think pulp needs a startup check that refuses to start if > 1 domain and yet you have `ENABLE_DOMAIN=False`.

+1 to refuse to start

2022-09-15 11:12 UTC, ipanova commented
I noticed that few models do not have domain as fk like signing service, labels, export, taskgroup, etc. should we add it?

2022-09-15 15:32 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
We had some more discussions about the url schema:
1. We want the domain name (to be unique and) be part of hrefs.
2. If we can make it so the openapi spec does not change, we can user the rerouting feature present in current client tooling to interact with different domains.
3. Suggested url schemas: `/pulp/<domain-name>/api/v3/tasks/`, `/pulp/<domain-name>/content/<base-path>/`

2022-09-15 17:28 UTC, bmbouter commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
I thought some more about that and I think we should consider `/pulp/api/v3/<domain-name>/` instead. The issue with the `/pulp/<domain-name>/api/v3/` approach is that it forces all objects to be domain namespaced even where there aren't any. We have some objects that just aren't, e.g. Workers, Users, etc. One might think, "oh well let's just put them into the default namespace" but that becomes very inconvenient (and likely inappropriate) when it comes to authorization of those calls into the default namespace because in practice all users now need permissions for that domain in some way.

This inconvenience stems from us namespacing an object that really shouldn't be namespaced, so the way to avoid it is not to do that, which brings us back to `/pulp/api/v3/<domain-name>/` for objects that are domain enabled and `/pulp/api/v3/` for those that aren't.

I think we are doing this mostly out of convenience for the CLI (which was a fine idea) but these practical problems I think outweight that. That CLI and bindings, and openAPI schema need a `domain` setting I think which will be used when needed for those object types.

What do you think about ^?

2022-09-16 08:24 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
Actually I was thinking (and not writing it down) that workers, users, groups and other non-domain entities would only be routed via the `/pulp/api/v3/` path that would map into the default domain right away. But that might add a lot of complexity.

`/pulp/api/v3/<domain-name>/` does not work for me, because it collides with paths we already have, and we keep adding interfaces at that level. We cannot prevent a domain to be named `keys` e.g. if we intend to add an api for `keys` in the future. Thinking about client tooling, i'd say for the cli it's easy to add another path parameter and use that if the openapi spec declares it properly. The CLI consumes that spec on the fly. The published bindings will have a hard time though (reason to stop publishing them?).

What would work for me [SPOILER]: `/pulp/api/v3/status` and all that jazz continues to work (and maybe just use the default domain for domained entities; that's why we call it "default" in the first place.). `/pulp/api/v4/<domain-name>/repositories/` and the like will be used for domained entities only. At this point we can inject the domain at the router level.

2022-09-16 08:27 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    app.add_routes([web.get("/pulp/domain/{domain_pk}/{path:.+}", Handler().stream_content)])
We might think about specifying locked resources differently then: `<app-label>:<class-name>:<uuid>` instead of the now rather unstable `<href>`.
We can still translate to href's in the serializer.

2022-09-16 14:55 UTC, chris1984 commented
@gerrod3 I think I saw you yesterday at the transfer hall, were you in town for pulpcon?

2022-10-26 15:11 UTC, lubosmj commented on pulpcore/app/tasks/purge.py
> +    tasks_qs = Task.objects.filter(finished_at__lt=finished_before, state__in=states, domain=domain)
Would it be possible to facilitate the retrieval of domains under the hood so that plugin writers will not be required to adjust affected filtering queries?

For instance, is it achievable to create a new manager that will handle the filtering by first running `queryset.filter(domain=Task.current().domain)` (https://docs.djangoproject.com/en/3.2/topics/db/managers/) before executing the actual queries? All models that are associated with domains should then have this manager attached to them.

2022-10-26 20:38 UTC, gerrod3 commented on pulpcore/app/tasks/purge.py
> +    tasks_qs = Task.objects.filter(finished_at__lt=finished_before, state__in=states, domain=domain)
This is a good idea, I'll look into it. We use querysets in many different spots so knowing how to get the domain from each context might be a bit challenging.

2022-10-27 07:41 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +    tasks_qs = Task.objects.filter(finished_at__lt=finished_before, state__in=states, domain=domain)
We determine the domain in the middleware, right? We could even set a context variable (like set_guid) so we can access it from all custom managers.

2022-10-27 07:56 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/domains/domains_compatibility.rst
> +        domain = models.ForeignKey("core.Domain", default=get_default_domain, on_delete=models.PROTECT)
Have you looked into constraints to make the unique across inherited properties work? I'd really prefer to see the domain on the base class.
https://docs.djangoproject.com/en/3.2/ref/models/options/#constraints

2022-10-27 08:31 UTC, mdellweg reviewed
Sorry for being late with this idea. But seeing all the many cases where you inject the domain in function signatures may be handled by having the domain as a context var.

I think of them as the call stack having class attributes.
https://docs.python.org/3.7/library/contextvars.html

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +    def check_cross_domains(self, data):
I would see this in a simpler way: The request (or task) must be attached to a single domain, and every field that references any object must check against that domain.

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +def get_domain(self):
Is this function meant to be a method for some class?

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +        # abstract = True
Abstract in a serializer? I think this can go away. ;)

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/app/viewsets/orphans.py
> +        uri = "/pulp/api/v3/orphans/cleanup/"
Since the api root is something we can reconfigure, this is not even safe the way we use it today. Or put another way: In order to reconfigure the API-ROOT, you should really drain your task queue first.
Ideally we would refer to things by another (stable) identifier.

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/middleware.py
> +        setattr(request, "domain", domain)
Can we set the hydrated object here? (`request.user` is handled that way.)
And maybe we set it as a context var here (or in the `__call__` part).

2022-10-27 08:31 UTC, mdellweg commented on pulpcore/middleware.py
> +        log.info(f"{domain=}")
This will be quite verbose. I think it should at least be debug in the final version.

2022-10-28 21:11 UTC, gerrod3 commented on pulpcore/app/serializers/base.py
> +from dynaconf import settings
It should be `django.conf`, thanks for catching this.

2022-10-28 21:12 UTC, gerrod3 commented on pulpcore/app/serializers/base.py
> +    def check_cross_domains(self, data):
Good point, I'll refactor this to be simpler.

2022-10-28 21:20 UTC, gerrod3 commented on pulpcore/app/serializers/base.py
> +def get_domain(self):
It was a part of the `ModelSerializer` class, but I factored it out because I thought I might need to use this in other serializers that don't inherit from the `ModelSerializer`. There isn't any other serializers in pulpcore that use this method, but I do have it exposed in the plugin api currently for potential future use.

2022-10-28 21:21 UTC, gerrod3 commented on pulpcore/middleware.py
> +        log.info(f"{domain=}")
Whoops, leftover print statement when I was first debugging.

2022-11-04 07:53 UTC, mdellweg reviewed
Next round of ideas.

2022-11-04 07:53 UTC, mdellweg commented on pulpcore/app/global_access_conditions.py
> +        return request.user.has_perm(permission, obj=request.domain)
:+1:

2022-11-04 07:53 UTC, mdellweg commented on pulpcore/app/response.py
> +            args.insert(0, request.domain.name)
can this be like for task groups below?

```
        kwargs = {"pk": task_group.pk}
        if settings.DOMAIN_ENABLED:
            kwargs["domain_path"] = request.domain  # This should be the task_group's domain
            kwargs["domain_path"] = request.domain.name  # This should be the task_group's domain
        resp = {"task_group": reverse("task-groups-detail", kwargs=kwargs, request=None)}
        super().__init__(data=resp, status=202)
```

2022-11-04 07:53 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +def get_domain(self):
Should we name it's argument "serializer" then? It's not meant to be used as a class method as far as i see.

2022-11-04 07:53 UTC, mdellweg commented on pulpcore/plugin/viewsets/content.py
> +                    artifact = Artifact.objects.get(sha256=artifact.sha256, domain=request.domain)
This sounds even safer!

2022-11-04 07:53 UTC, mdellweg commented on pulpcore/app/migrations/0097_add_domain.py
> +                ('name', models.TextField(unique=True)),
Sorry for being late again.
This is dangerous, because we intend to use that name as part of a url. I think we should use a slug field. Or, We keep a nice name because company names do not necessarily contain hyphens and add a `SlugField` called "slug" to be used in the url.

https://docs.djangoproject.com/en/3.2/ref/models/fields/#slugfield

2022-11-04 16:44 UTC, gerrod3 commented on pulpcore/app/response.py
> +            args.insert(0, request.domain.name)
Yes, forgot to switch this over to using kwargs instead.

2022-11-04 16:47 UTC, gerrod3 commented on pulpcore/app/migrations/0097_add_domain.py
> +                ('name', models.TextField(unique=True)),
Good point, I'll switch it. I was wondering if `SlugField` was the correct option after switching the name to be unique + part of the url.

2022-11-07 08:20 UTC, mdellweg commented on pulpcore/app/migrations/0097_add_domain.py
> +        migrations.RunPython(create_default_domain, reverse_code=migrations.RunPython.noop),
Seeding of data should be in a post migrate signal.

2022-11-08 04:29 UTC, gerrod3 commented on pulpcore/app/migrations/0097_add_domain.py
> +        migrations.RunPython(create_default_domain, reverse_code=migrations.RunPython.noop),
I just realized this was your first comment on the first commit. What is the reasoning for this? This feature can not function without the default domain, with future migrations relying on the default being present, so having it be created outside a migration feels hacky IMO.

2022-11-08 10:50 UTC, mdellweg commented on pulpcore/app/migrations/0097_add_domain.py
> +        migrations.RunPython(create_default_domain, reverse_code=migrations.RunPython.noop),
Basically `pulpcore-manager flush`.
If any subsequent migration needs the default domain, it needs to create it in an idempotent way the same way as the post-migrate signal needs to. Just make sure that after successfully running all the migrations (or flush which will only trigger the post_migrate), it is there.

2022-11-23 12:04 UTC, lubosmj reviewed
I went only through the documentation and added a few suggestions. Personally, I think we should move some parts of the `docs/workflows/domains-multi-tenancy.rst` documentation to the plugins themselves.

2022-11-23 13:11 UTC, mdellweg commented on pulpcore/app/apps.py
> +    domain_compatible = True
This is the pulpcore config. And it anables domains, so `True` is correct here.

2022-11-23 13:32 UTC, mdellweg commented on pulpcore/app/apps.py
> +        get_default_domain()  # Cache the default domain
This will create the default domain, right?

2022-11-23 13:32 UTC, mdellweg commented on pulpcore/app/global_access_conditions.py
> +    domain is present then return False.
This text is outdated.

2022-11-23 13:32 UTC, mdellweg commented on pulpcore/app/global_access_conditions.py
> +    )
Is this a change in behaviour?

2022-11-23 13:32 UTC, mdellweg commented on pulpcore/app/util.py
> +                kwargs["pulp_domain"] = domain.name
Does this mean, a domain "lives" inside itself?

2022-11-23 13:32 UTC, mdellweg commented on pulpcore/app/util.py
> +    return domain.pk if return_pk_only else domain
Polymorphic return values are dangerous. Can we just have `get_domain` and `get_domain_pk` if there is a need for it?

2022-11-23 15:51 UTC, gerrod3 commented on pulpcore/app/apps.py
> +        get_default_domain()  # Cache the default domain
Nope. The default domain is created within the migration (Through the default field on the new relations). This is no longer needed now that we are using a Domain ContextVar.

2022-11-23 15:57 UTC, gerrod3 commented on pulpcore/app/util.py
> +                kwargs["pulp_domain"] = domain.name
No, this function is set up so that you can pass in a domain to use for the reverse call besides "default" or the domain on the object. If you where to call this function with a domain as the first arg (model), then it would use "default" since the domain object doesn't  have domain relation.

2022-11-23 16:04 UTC, gerrod3 commented on pulpcore/app/util.py
> +    return domain.pk if return_pk_only else domain
The need is from the default on the `pulp_domain` field being set to `get_domain`, it expects the return value to be a `PK`. I can break this into two separate methods.

2022-11-23 16:32 UTC, gerrod3 commented on pulpcore/app/global_access_conditions.py
> +    )
Yes, I realized the previous behavior was incorrect on update actions. For update the serializer should be instantiated with the object instance to perform correct validation.

2022-11-23 19:17 UTC, gerrod3 commented on docs/plugin_dev/plugin-writer/concepts/rbac/permissions.rst
> +Model-Level, Domain-level (if domains are enabled) or Object-Level.
An Oxford comma fan.

2022-11-23 20:27 UTC, gerrod3 commented on pulpcore/app/apps.py
> +        get_default_domain()  # Cache the default domain
Update: The answer is actually yes & no. If you are upgrading, then the new migrations will cause the default method, `get_domain_pk`, (which in turn calls `get_default_domain`) to be ran when adding the new `pulp_domain` relation to your existing models.  If you are creating a brand new Pulp instance, then this post migrate hook will be the one to create the default domain.

2022-11-23 20:31 UTC, mdellweg commented on pulpcore/app/apps.py
> +        get_default_domain()  # Cache the default domain
Great! That is exactly what i needed to hear.

2022-11-28 14:00 UTC, ipanova commented on docs/workflows/domains-multi-tenancy.rst
> +Current Domain Compatible Plugins:
is it worth adding this info to the status endpoint?

2022-11-28 14:00 UTC, ipanova commented on docs/workflows/domains-multi-tenancy.rst
> +Once domains are enabled all URLs in Pulp will require the domain name in the path after the
Can you remind me whether it is possible to disable domains once enabled them?

2022-11-28 15:22 UTC, gerrod3 commented on docs/workflows/domains-multi-tenancy.rst
> +Once domains are enabled all URLs in Pulp will require the domain name in the path after the
Yes, the other domains will become inaccessible and the URLs will go back to normal.

2022-11-28 15:23 UTC, ipanova commented on docs/workflows/domains-multi-tenancy.rst
> +Once domains are enabled all URLs in Pulp will require the domain name in the path after the
Awesome thanks!

2022-12-01 15:52 UTC, gerrod3 commented on docs/workflows/domains-multi-tenancy.rst
> +Current Domain Compatible Plugins:
Possibly. I added a `domain_enabled` field to the status endpoint that reflects the setting `DOMAIN_ENABLED`. I'll look at adding it.

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/models/domain.py
> +class Domain(BaseModel, AutoAddObjPermsMixin):
so you've written the trigger that will be watching for deletion at the DB level but does it make sense to also add a pre_delete hook  that will be checking removal of default domain? it will produce a more user friendly output

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/models/content.py
> +        artifact_file = temp_file.file.open()
should not the file be closed?

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/models/content.py
> +            domain_pk = get_domain()
get_domain_pk or rename the var

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/models/content.py
> +            pk__in=content_pks,
why we are not getting the domain here?

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/role_util.py
>      try:
let's not shorten 'Object'

2022-12-02 13:53 UTC, ipanova commented on pulpcore/app/role_util.py
> +        domains = list(
because otherwise this is a queryset object
```
In [33]: Remote.objects.all().values_list("name", flat=True).extend
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [33], in <cell line: 1>()
----> 1 Remote.objects.all().values_list("name", flat=True).extend

AttributeError: 'QuerySet' object has no attribute 'extend'
```

2022-12-02 14:21 UTC, gerrod3 commented on pulpcore/app/models/domain.py
> +class Domain(BaseModel, AutoAddObjPermsMixin):
Sure, I'll add one. The hook will still be bypassed if the default domain is deleted in bulk, but it'll prevent individually trying to delete it.

2022-12-02 14:24 UTC, ipanova commented on pulpcore/app/models/domain.py
> +class Domain(BaseModel, AutoAddObjPermsMixin):
yes, i remember that bulk delete caveat

2022-12-02 14:25 UTC, gerrod3 commented on pulpcore/app/apps.py
> +    if "core_domain" in table_names:
Yes, migrations can be ran up or down and the post migrate signal is always sent, so this can be called without the domain table existing in the db anymore. Actually most (all?) of our post migrate hooks might break from backwards migrations, although you probably can't go back that far in migrations since some of them are irreversible.

2022-12-02 14:28 UTC, gerrod3 commented on pulpcore/app/models/content.py
> +            pk__in=content_pks,
I'm under the assumption that if you are specifying `content_pks` then you have already filtered by domain.

2022-12-02 14:33 UTC, gerrod3 commented on pulpcore/app/role_util.py
> +        domains = list(
My comment was originally for a different error for using the domains queryset in another queryset filter `qs.filter(pulp_domain_id__in=domains)`. I had the user and group role queries separate and was adding them as two different Q objects, but I found that filtered query wasn't working unless I cast the domains query to a list. Since I was casting to a list it made sense to combine the user and group queries into one list.

2022-12-02 14:37 UTC, ipanova commented on pulpcore/app/apps.py
> +    if "core_domain" in table_names:
right, i keep forgetting running the migration down

2022-12-12 10:17 UTC, mdellweg commented on pulpcore/app/apps.py
> +def _ensure_default_domain(sender, apps, verbosity, **kwargs):
```suggestion
def _ensure_default_domain(sender, **kwargs):
```
... unless you want to add some verbosity...

2022-12-12 10:37 UTC, mdellweg commented on pulpcore/app/models/fields.py
> +class EncryptedJSONField(JSONField):
I'm unsure if it is useful to derive this field from a JSON field if all we store is an encrypted string. Can't we just have it a text field and call json.loads and json.dumps in the db transformations? Or we could even derive from the existing `pulpcore.EncryptedField`!?

2022-12-12 10:40 UTC, mdellweg commented on pulpcore/app/models/storage.py
> +# This is currently not used by anyone, probably should deprecate and remove from plugin api
yes, let's do it!

2022-12-12 10:45 UTC, mdellweg commented on pulpcore/app/serializers/acs.py
> +        validator = UniqueValidator(
We could implement a `UniquePerDomainValidator`, wdyt? Can we add validators for the domain field too?

This can be followup work.

2022-12-12 10:47 UTC, mdellweg commented on pulpcore/app/serializers/base.py
> +                            _("Objects must be all of the same domain.")
It's more like one objects domain does not match the requests domain now. Right?

2022-12-12 10:55 UTC, mdellweg commented on pulpcore/app/serializers/domain.py
> +class DomainSettingsSerializer(serializers.Serializer):
Should this be called `StorageSettingsSerializer` ?

Does is reflect it's polymorphy correctly in the openapi spec?

 https://swagger.io/specification/#discriminator-object

2022-12-12 10:59 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +        self.check_cross_domains({"repository": repository, "remote": remote})
Another crazy idea: Should we change the Manager on all domained models to add the filter for domains already? We would get 404s instead of "Hey you are trying to use something from the other domain!". But i think this is even better in terms of protecting other tenants.

2022-12-12 11:03 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +    domain = Task.current().pulp_domain
We should set the domain in the tasking stack so that we can use `util.get_domain()`.

2022-12-12 11:13 UTC, mdellweg commented on pulpcore/backends.py
> +        elif isinstance(obj, Domain) and "domain" not in perm:
shouldn't we check against `util.get_domain` as provided by the middleware?

2022-12-12 11:17 UTC, mdellweg commented on pulpcore/openapi/__init__.py
> +        result["info"]["x-pulp-domain-enabled"] = settings.DOMAIN_ENABLED
:+1:

2022-12-12 11:21 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +    task = Task.objects.select_related("pulp_domain").get(pk=task_pk)
:+1:

2022-12-12 11:22 UTC, mdellweg commented on pulpcore/tests/functional/__init__.py
> -
These may be in use by plugin tests. At the very least i would keep the factory.

2022-12-12 11:26 UTC, mdellweg requested changes
This is a BIG PR. Maybe i didn't see it, but i think the support for "REDIRECT_TO_OBJECT_STORAGE" feature is missing. Should this setting not move to the domains settings?

2022-12-13 04:36 UTC, gerrod3 commented on pulpcore/app/models/fields.py
> +class EncryptedJSONField(JSONField):
I modified the field to encrypt each value instead of encrypting the whole field as a string. I could have made this an `EncryptedField` using json.loads and json.dumps, but we would lose the extra functionality of the JSONField.

2022-12-13 04:39 UTC, gerrod3 commented on pulpcore/app/serializers/acs.py
> +        validator = UniqueValidator(
`UniquePerDomainValidator` is possible, I can look into it, but it should probably be done later as to not delay any further. What do you mean about validators for the domain field? There is no domain field on these serializers.

2022-12-13 04:41 UTC, gerrod3 commented on pulpcore/app/serializers/domain.py
> +class DomainSettingsSerializer(serializers.Serializer):
Renamed it. Polymorphy is not correctly reflected in the spec. I couldn't figure out how to get the auto-gen spec code to recognize this serializer's polymorphic nature. Any ideas?

2022-12-13 04:44 UTC, gerrod3 commented on pulpcore/backends.py
> +        elif isinstance(obj, Domain) and "domain" not in perm:
This check is for when you are assigning a permission on a domain object, i.e. `core.view_domain`. This is how the backend knows if the permission is being assigned on a domain-level vs being assigned on a domain object. Checking against `get_domain` wouldn't provide any information.

2022-12-13 04:45 UTC, gerrod3 commented on pulpcore/responses.py
> +            self._artifact = await sync_to_async(_get_artifact)(self._artifact_pk)
Yes, they are identical.

2022-12-13 12:00 UTC, mdellweg commented
> > This is a BIG PR. Maybe i didn't see it, but i think the support for "REDIRECT_TO_OBJECT_STORAGE" feature is missing. Should this setting not move to the domains settings?
> 
> Per domain, yes the feature is missing. Right now all domains would follow the global setting for `REDIRECT_TO_OBJECT_STORAGE`. I can add it to the domain's settings if we want domains to be able to control this setting.

I think, we need to. Some storages do not allow redirecting.

2023-03-03 16:21 UTC, dkliban commented on docs/plugin_dev/plugin-writer/concepts/rbac/access_policy.rst
> +            "condition": "has_model_domain_or_obj_perms:file.view_fileremote",
s/model_domain/model_or_domain/

2023-03-03 16:29 UTC, dkliban commented on docs/workflows/domains-multi-tenancy.rst
> +    http POST :24817/pulp/boo/api/v3/repositories/file/file/ name="boo"
s/boo/foo/

2023-03-03 16:36 UTC, dkliban commented on docs/workflows/domains-multi-tenancy.rst
> +There are three notable objects in Pulp, ``AccessPolicies``, ``Roles`` and ``Users/Groups``, that
s/three/four/ and split Users/Groups to be comma separated.

2023-03-03 16:49 UTC, dkliban commented on pulpcore/app/global_access_conditions.py
> +def has_model_domain_or_obj_perms(request, view, action, permission):
s/model_domain/model_or_domain/

2023-03-03 16:51 UTC, dkliban commented on pulpcore/app/global_access_conditions.py
> +# 'Remote' parameter checks, should I deprecate the current model_or_obj checks?
Remove this question.

2023-03-03 18:44 UTC, dkliban commented on pulpcore/app/models/fields.py
> +            raise ImproperlyConfigured("EncryptedTextField does not support primary_key=True.")
s/EncryptedTextField/EncryptedJSONField/

2023-03-03 18:48 UTC, dkliban commented on pulpcore/app/models/publication.py
> +                    base_keys = [f"{self.pulp_domain.name}:{base_path}" for base_path in base_paths]
Let's refactor this to not duplicate code.

2023-03-03 19:29 UTC, dkliban commented on pulpcore/app/serializers/base.py
> +            field = fields[field_name]
Let's not worry about introspecting the write_only fields and keep the existing behavior.

2023-03-03 19:30 UTC, dkliban commented on pulpcore/app/serializers/domain.py
> +    ("storages.backends.gcloud.GoogleCloudStorage", "Use Google Cloud as storage"),
Please comment out the the google storage backend.

2023-03-03 19:41 UTC, dkliban commented on pulpcore/app/serializers/domain.py
> +    ("pulpcore.app.models.storage.PulpSFTPStorage", "Use SFTP server as storage"),
We should hold off on having PulpSFTPStorage supported for now. Its future is uncertain.

2023-03-03 19:44 UTC, dkliban commented on pulpcore/app/serializers/publication.py
> +    def validate_base_path(self, value):
let's change this parameter back to path.

2023-03-03 19:57 UTC, dkliban commented on pulpcore/app/settings.py
> +settings.set("V3_DOMAIN_API_ROOT", settings.API_ROOT + "<pulp_domain>/api/v3/")
should be this be the slug for the domain?

2023-03-03 20:11 UTC, dkliban commented on pulpcore/app/util.py
> +            f"The value settings.DEFAULT_FILE_STORAGE={artifact_domain.storage_class} "
Let's add a condition check on domain enablement to determine what the error message should be. If domains are disabled it should give the old message.

2023-03-03 20:13 UTC, dkliban commented on pulpcore/app/views/orphans.py
> +            uri = f"/{request.pulp_domain.name}/api/v3/orphans/cleanup/"
Maybe use string substitution?

2023-03-03 20:24 UTC, dkliban commented on pulpcore/app/viewsets/domain.py
> +            raise NotAcceptable(_("Default domain can not be updated."))
Let's switch this to a bad request.

2023-03-06 11:44 UTC, mdellweg commented
I have another issue, that i think may have been lost in the discussion. When switching on the domain feature in an existing system, the href's of a lot of objects change. I think, this is not reflected in the `reserved_resources` of the tasks. Do we have a plan for this?

2023-03-06 20:18 UTC, gerrod3 commented on pulpcore/app/migrations/0100_add_domain.py
> +DROP TRIGGER IF EXISTS protect_default ON core_domain;
@ggainey Do you know how these triggers are stored/associated in the database. I was under the impression the trigger is unique per table, so unique on the domain table.

2023-03-07 05:19 UTC, gerrod3 commented on pulpcore/app/models/fields.py
> +class EncryptedJSONField(JSONField):
No, it only encrypts the values in the dictionary. The keys remain unencrypted. We get the benefit of using the has_keys and contains filtering methods: https://docs.djangoproject.com/en/4.1/topics/db/queries/#querying-jsonfield

2023-03-07 05:23 UTC, gerrod3 commented on pulpcore/app/models/storage.py
> +# This is currently not used by anyone, probably should deprecate and remove from plugin api
No, it hasn't been deprecated yet. Should be done in another PR.

2023-03-07 05:33 UTC, gerrod3 commented on pulpcore/app/serializers/base.py
> +            if isinstance(instance, Mapping):
Not sure, I was copying the the internal code that DRF uses for its serializer fields when grabbing their values. I'm reverting this back as the extra complexity is not worth the tiny feature gain.

2023-03-07 06:33 UTC, gerrod3 commented on pulpcore/app/models/storage.py
> +    __class__ = Storage
Yes, if you talking about the `__class__ = Storage`  line, this is to bypass the isinstance check that Django does when instantiating a FileField. 

No, if you are talking about the `DomainStorage` class as a whole. This is just one of the many ways to implement the dynamic storage backend for the FileField. I particularly like this one for how clean it looks / simplicity, but if you look through the commit history you can see the other ways I've attempted before.

2023-03-07 15:05 UTC, mdellweg requested changes
You have a discontinuity in the naming of the setting "DOMAIN_ENABLED" and "DOMAINS_ENABLED". Which one is it?

2023-03-07 16:40 UTC, gerrod3 commented
> You have a discontinuity in the naming of the setting "DOMAIN_ENABLED" and "DOMAINS_ENABLED". Which one is it?

DOMAIN_ENABLED. Fixed.

2023-03-08 14:02 UTC, mdellweg commented on pulpcore/app/settings.py
> +settings.set("V3_DOMAIN_API_ROOT", settings.API_ROOT + "<slug:pulp_domain>/api/v3/")
Ha, it really is type:name...

2023-03-09 16:19 UTC, dkliban approved these changes

2023-03-09 16:36 UTC, merged

2023-03-09 16:37 UTC, bmbouter commented
![image](https://user-images.githubusercontent.com/180319/224090923-3a02db46-3b46-40e7-b502-8f5d9ae4a865.png)