Prod telemetry site only receives production data
pulp/pulpcore pull request #3224
Opened 2022-09-19 19:57 UTC by bmbouter

This commit fixes a bug where installations with at least one pre-release plugin installed were posting to the production telemetry site instead of the developer telemetry site.

closes #3213

2022-09-19 20:05 UTC, bmbouter commented
This is to handle plugins with pre-release names that don't end in `.dev`, e.g. `pulp-ostree 2.0.0a6`.

2022-09-19 20:12 UTC, ggainey requested changes

2022-09-19 20:12 UTC, ggainey commented on pulpcore/app/tasks/telemetry.py
>      for app in pulp_plugin_configs():
Can we get a comment in here with an example of what broke us and/or what assumptions we're making?

2022-09-19 20:21 UTC, bmbouter commented on pulpcore/app/tasks/telemetry.py
>      for app in pulp_plugin_configs():
I pushed a change, wdyt?

2022-09-19 20:29 UTC, ggainey commented on pulpcore/app/tasks/telemetry.py
>      for app in pulp_plugin_configs():
:+1: 

I can imagine scenarios that will break this - but they'd all result in aiming at dev-url, which is better than dev-installs aiming at prod-url. I'm good w/ this change to fix the current problem.

2022-09-19 20:29 UTC, ggainey approved these changes
lg2m

2022-09-19 23:37 UTC, merged

2022-09-20 07:11 UTC, mdellweg commented
Can we please accompany this with a server-side change so the telemetry site does not choke on invalid input?

2022-09-20 14:39 UTC, bmbouter commented
Yes that got put in place first actually, but all it can do is drop the data. https://github.com/pulp/analytics.pulpproject.org/commit/b29eed4bcf88dd2ce8336fb97597e8b4410ddab5