Separated the user plugin vs plugin writer docs
pulp/pulpcore pull request #3261
Opened 2022-09-29 16:11 UTC by bmbouter

closes #3260

2022-09-29 16:15 UTC, dralley commented on docs/glossary.rst
> +        :ref:`plugin_api`. It is :term:`plugin`-based and manages :term:`Content`.
Should we say more?  The pulpcore API also helps with managing repository versions and so forth.

2022-09-29 16:20 UTC, dralley approved these changes

2022-09-29 17:00 UTC, bmbouter commented on docs/glossary.rst
> +        :ref:`plugin_api`. It is :term:`plugin`-based and manages :term:`Content`.
We should, but in another piece of work. I'm hoping to spend more time with our docs as part of my contribution.

2022-09-29 17:33 UTC, ggainey requested changes
One minor tweak, otherwise this is great!

2022-09-29 17:33 UTC, ggainey commented on docs/index.rst
> +Anyone interested in writing a plugin should reference the :ref:`plugin_development`.
```suggestion
Anyone interested in writing a plugin should reference :ref:`plugin_development`.
```

2022-09-29 17:58 UTC, ggainey approved these changes
lg2m!

2022-10-06 11:48 UTC, mdellweg commented
Please rebase onto the latest CI fixes.

2022-10-06 13:59 UTC, merged