Added reserved_resources filters to task list
pulp/pulpcore pull request #3282
Opened 2022-10-05 13:28 UTC by mdellweg

These new filters search for both shared and exclusive resources.

fixes #3280

2022-10-06 18:52 UTC, ggainey requested changes
Doc change needed (I believe). Can we get a pulp_file PR to add tests for this?

2022-10-06 18:52 UTC, ggainey commented on pulpcore/app/viewsets/custom_filters.py
> +            value (string): href containing a reference to a reserved resource
This can now be str or [str,...] yes?

2022-10-11 11:03 UTC, mdellweg commented on pulpcore/app/viewsets/custom_filters.py
> +            value (string): href containing a reference to a reserved resource
Yes, it can. It will be `str` if the filter is used as is, and `List[str]` if mixed with `BaseInFilter`.
The docstring of this function is kind of questionable, as it is not meant to be called directly at all, but only as a callback for the filtering backend. Will adjust it anyway.

2022-10-11 14:32 UTC, ggainey approved these changes
lg2m

2022-10-11 14:34 UTC, dkliban commented
@mdellweg what do you think about adding some tests to `pulp_file` for this feature?

2022-10-12 13:48 UTC, dkliban approved these changes

2022-10-13 13:25 UTC, merged