Convert tests to use bindings & pytest style
pulp/pulpcore pull request #3293
Opened 2022-10-08 01:33 UTC by gerrod3

[noissue]

2022-10-10 14:31 UTC, bmbouter commented on pulpcore/tests/functional/api/test_api_docs.py
> +* `Pulp Smash #893 <https://github.com/pulp/pulp-smash/issues/893>`_
Stylistically we don't keep links to issues in the test docstrings anymore.

2022-10-10 14:32 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +    # Should I clean up the temporary file?
No pytest does this for you.

2022-10-10 14:33 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
@lubosmj @mdellweg @gerrod3 @dkliban I think we need to bring over the ability to `get_pulp_setting` to pulpcore natively. I believe the assumption now and going forward is that is on the local system also so the implementation moved to pulpcore only needs to consider that. Is that you expectation as well?

2022-10-10 14:54 UTC, bmbouter commented on pulpcore/tests/functional/api/test_upload.py
> +from pulp_smash.pulp3.bindings import monitor_task
@gerrod3 @dkliban @lubosmj @mdellweg we should move `monitor_task` over to pulpcore also I think as a utility function in https://github.com/pulp/pulpcore/blob/main/pulpcore/tests/functional/utils.py

2022-10-10 14:57 UTC, bmbouter commented on pulpcore/tests/functional/api/test_workers.py
> +    worker = _test_01_read_all_workers(workers_api_client)
Not a required change, but stylistically we've been making this one long test and using single-line comments blocking out each separate section. Here is an example of that:  https://github.com/pulp/pulp_file/pull/830/files#diff-6c2b39e46a76f777fb2a3c2fe06d98e8654db70525351c5a9d136f889107ef67R94

2022-10-10 14:58 UTC, bmbouter requested changes
@gerrod3 ty so much for working on this! This is all looking really good. What do you think about the requested change I've written in comments?

2022-10-10 15:00 UTC, lubosmj commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
We should move both the `get_pulp_setting` and `monitor task` functions (and many others) to pulpcore. However, I am not sure if it needs to be done in this PR.

2022-10-10 15:12 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
A test should just `from pulpcore.app import settings` to check pulp settings.

2022-10-10 15:30 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
@gerrod3 then please just move the `monitor_task` fixture to pulpcore. Does that sound ok?

2022-10-10 15:40 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
Ok, I'll move `monitor_task` to pulpcore. I'll also try using `from pulpcore.app import settings`, but I'm not sure it will work.

2022-10-10 16:17 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_api_docs.py
> +* `Pulp Smash #893 <https://github.com/pulp/pulp-smash/issues/893>`_
Removed.

2022-10-10 16:19 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
`monitor_task` and `monitor_task_group` is now in pulpcore. Importing settings directly from pulpcore did not work as not all the settings were initialized.

2022-10-10 20:05 UTC, lubosmj commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
@dkliban, @gerrod3, importing the settings directly from pulpcore works in pulp_file (because the pulpcore module is correctly initialized before executing the test?): https://github.com/pulp/pulp_file/pull/842/files#diff-d40a0ce852ae1c631a07c83021e5d9e9be0b4de32c98b7d2bb34a9aff4922824R13.

2022-10-10 20:15 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
I think everything importing settings should be using `from django.conf import settings` which allows dynaconf to hook in as expected and layer, validate, etc.

Also could the issue be that django.setup() hasn't been called yet? We have `django.setup()` called by all the various entrypoints of Pulp, e.g. WSGI, the tasking system, etc, but maybe we don't have one for the test suite currently....

2022-10-11 15:29 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
To recap our RTFM working group call from earlier, we're going to leave `get_pulp_setting` provided by pulp_smash for now. We can move that later.

2022-10-11 15:35 UTC, bmbouter commented on pulpcore/tests/functional/api/test_upload.py
> +        finish_task = uploads_api_client.commit(upload.pulp_href, {"sha256": sha256}).task
Is it that it's not `post` it's `commit` and `gen_object_with_cleanup` doesn't know that?

2022-10-11 15:37 UTC, bmbouter approved these changes
I asked one question mainly for my understanding, but this is looking great. Thank you!

2022-10-11 19:08 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
the following diff worked for me

```diff 
diff --git a/pulpcore/tests/functional/api/test_crd_artifacts.py b/pulpcore/tests/functional/api/test_crd_artifacts.py
index 79a24536e..5712ab63e 100644
--- a/pulpcore/tests/functional/api/test_crd_artifacts.py
+++ b/pulpcore/tests/functional/api/test_crd_artifacts.py
@@ -5,8 +5,8 @@ import os
 import uuid
 import pytest
 
-from pulp_smash.utils import get_pulp_setting
 from pulp_smash.exceptions import CalledProcessError
+from pulpcore.app import settings
 from pulpcore.client.pulpcore import ApiException
 
 
@@ -141,10 +141,11 @@ def test_upload_mixed_attrs(artifacts_api_client, pulpcore_random_file):
 
 def test_all(artifacts_api_client, pulpcore_random_file, cli_client):
     """Delete an artifact, it is removed from the filesystem."""
-    storage = get_pulp_setting(cli_client, "DEFAULT_FILE_STORAGE")
+    from pulpcore.app import settings
+    storage = settings.DEFAULT_FILE_STORAGE
     if storage != "pulpcore.app.models.storage.FileSystem":
         pytest.skip("this test only works for filesystem storage")
-    media_root = get_pulp_setting(cli_client, "MEDIA_ROOT")
+    media_root = settings.MEDIA_ROOT
 
     artifact = artifacts_api_client.create(pulpcore_random_file["name"])
     cmd = ("ls", os.path.join(media_root, artifact.file))
```

2022-10-11 19:13 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
If we do go down this road I think we should `from django.conf import settings`. @gerrod3 if you want to do this in this PR that's fine, or if not also fine (to me).

2022-10-11 19:16 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
@dkliban Did you test on a system using a non-file system backend? I’m pretty sure the default value is the file system so that value is already set in the module before `django.setup` is ran.

2022-10-11 19:22 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_upload.py
> +        finish_task = uploads_api_client.commit(upload.pulp_href, {"sha256": sha256}).task
`commit` takes an `upload` object and turns it into an `artifact`, deleting the `upload` object in the process. Since this api creates an object of another api, `gen_object `has no idea how delete the created object.

2022-10-11 19:25 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
@gerrod3 yes, i added `DEFAULT_FILE_STORAGE='storages.backends.s3boto3.S3Boto3Storage'` to `/etc/pulp/settings.py` and the test started being skipped. 

@bmbouter `from django.conf import settings` works just the same. I don't feel strongly about one way or another.

2022-10-11 20:02 UTC, dkliban commented on pulpcore/tests/functional/__init__.py
> +        is_redis_connected = status_response["redis_connection"]["connected"]
This is not working as you suspect it is. The status_read() method returns a StatusResponse[0]. This object is not subscriptable so you are always getting an exception trying to access `"redis_connection"`.

[0] https://docs.pulpproject.org/pulpcore_client/StatusResponse/

2022-10-11 20:14 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +    1. Upload a file and provide both an ``sha256`` and a ``size``. Let one
one is valid and the other is invalid.

2022-10-11 20:17 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +    cli_client.run(cmd, sudo=True)
you can just use Python to check the existence of the file.
```python
from os.path import exists

path_to_file = os.path.join(media_root, artifact.file)
file_exists = exists(path_to_file)
```

2022-10-11 20:19 UTC, dkliban commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +def test_all(artifacts_api_client, pulpcore_random_file, cli_client):
The test name seems inappropriate. Maybe just `test_delete_artifact` ?

2022-10-11 20:47 UTC, dkliban approved these changes
This looks great! Thank you!

2022-10-12 00:42 UTC, dkliban commented on pulpcore/tests/functional/api/test_api_docs.py
> +def test_valid_credentials(pulpcore_client, pulp_docs_url):
This test can be marked as parallel.

2022-10-12 00:42 UTC, dkliban commented on pulpcore/tests/functional/api/test_api_docs.py
> +def test_no_credentials(pulpcore_client, pulp_docs_url, anonymous_user):
This one can be parallel also.

2022-10-12 00:43 UTC, dkliban commented on pulpcore/tests/functional/api/test_api_docs.py
> +def test_http_method(pulpcore_client, pulp_docs_url):
This one can be parallel also.

2022-10-12 00:44 UTC, dkliban requested changes
All the tests in this PR seem like they can be run in parallel. Please mark them as such with `@pytest.mark.parallel`

2022-10-12 15:13 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +from pulp_smash.utils import get_pulp_setting
It works the same, but it's not DRY. We specify the settings location when we configure django and to specify it here also puts that configuration in yet one more place.

2022-10-12 16:18 UTC, dkliban approved these changes

2022-10-12 16:47 UTC, merged