Fix the number of parameters passed to UnexportableArtifactException
pulp/pulpcore pull request #3312
Opened 2022-10-14 07:35 UTC by lubosmj

[noissue]

2022-10-14 10:25 UTC, mdellweg requested changes
I assume this is fixing a bug. So we need an issue for all the downstream trackers.

2022-10-14 11:29 UTC, mdellweg approved these changes
A suggestion for the Changelog wording.
Fine for me anyway.

2022-10-14 11:29 UTC, mdellweg commented on CHANGES/3313.bugfix
> +Fixed an error raised when initializing ``UnexportableArtifactException``.
```suggestion
Fixed an error when raising ``UnexportableArtifactException``.
```

2022-10-14 12:08 UTC, ggainey reviewed
lg2m

2022-10-14 12:09 UTC, ggainey approved these changes

2022-10-14 13:28 UTC, merged

2023-03-28 15:00 UTC, ggainey commented
Adding backports to support released downstream products