Fixes the worker__in filter for the Tasks API
pulp/pulpcore pull request #3347
Opened 2022-10-21 19:42 UTC by decko

Closes #3235

Co-authored-by: dkliban <dkliban@redhat.com>

2022-10-24 10:56 UTC, mdellweg requested changes

2022-10-24 10:56 UTC, mdellweg commented on pulpcore/app/viewsets/task.py
> +            "worker": ["exact"],
My experiment shows that this is superfluous too.

2022-10-24 18:05 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    search_results = tasks_api_client.list(worker__in=[task.worker])
`TaskViewSet` is ordered by `-pulp_created`.

2022-10-24 18:10 UTC, decko commented on pulpcore/app/viewsets/task.py
> +            "worker": ["exact"],
Removed in the latest commit.

2022-10-24 18:54 UTC, mdellweg requested changes

2022-10-24 18:54 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +            time.sleep(1)
you need to fetch the task again from the api.

2022-10-24 19:08 UTC, mdellweg approved these changes

2022-10-25 07:24 UTC, mdellweg requested changes

2022-10-25 07:24 UTC, mdellweg commented on pulpcore/app/viewsets/task.py
> +    worker__in = HyperlinkRelatedFilter(field_name="worker", lookup_expr="in")
After reading it again, i realized, we need to make the `filter` function of `HyperlinkRelatedFilter` capable to consume a list of strings.

2022-10-26 13:51 UTC, decko commented on pulpcore/app/viewsets/task.py
> +    worker__in = HyperlinkRelatedFilter(field_name="worker", lookup_expr="in")
It can consume a list of strings with the latest changes

2022-10-28 07:41 UTC, mdellweg requested changes

2022-10-28 07:41 UTC, mdellweg commented on pulpcore/app/viewsets/task.py
> +    worker__in = HyperlinkRelatedInFilter(field_name="worker", lookup_expr="in")
Can you try this?
```suggestion
    worker__in = HyperlinkRelatedInFilter(field_name="worker")
```

2022-10-28 07:41 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +def test_filter_tasks_using_worker__in_filter(task, tasks_api_client, dispatch_task):
Instead of creating tasks differently, let's just use the `dispatch_task` fixture twice here.

2022-10-28 07:41 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    second_task = tasks_api_client.read(second_task_href)
just call `monitor_task` on both tasks.

2022-10-28 13:35 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    assert task in search_results.results
Good. With this we could avoid any race conditions.

2022-10-28 14:53 UTC, decko commented on pulpcore/app/viewsets/task.py
> +    worker__in = HyperlinkRelatedInFilter(field_name="worker", lookup_expr="in")
Tried and it works! The example in the docs explicitly uses the parameter. 
Removed.

2022-10-31 08:42 UTC, mdellweg requested changes

2022-10-31 08:42 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    assert task1_href and task2_href in [task.pulp_href for task in search_results.results]
```suggestion
    task_hrefs = [task.pulp_href for task in search_results.results]
    assert task1_href in task_hrefs
    assert task2_href in task_hrefs
```

2022-10-31 08:42 UTC, mdellweg commented on pulpcore/app/viewsets/custom_filters.py
> +            self.lookup_expr = "isnull"
I meant that it may be unsafe to change the object attribute `lookup_expr`. This would change the filter and I do not know how long lived that thing is.

2022-10-31 12:40 UTC, decko commented on pulpcore/app/viewsets/custom_filters.py
> +            self.lookup_expr = "isnull"
Got it

2022-11-02 08:56 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    assert task1_href and task2_href in [task.pulp_href for task in search_results.results]
I don not see this applied. In the current state we are not checking the inclusion of `task1_href`. Only that it does not evaluate to `False`.

2022-11-02 13:02 UTC, mdellweg approved these changes

2022-11-08 13:08 UTC, dkliban approved these changes

2022-11-08 13:08 UTC, merged