Adds postgresql version analytics collection
pulp/pulpcore pull request #3397
Opened 2022-11-11 15:01 UTC by bmbouter

Adds an analytics entry like: `{'postgresqlVersion': '13.7'}`

closes #3396

2022-11-15 14:20 UTC, ggainey commented
@bmbouter would love to see this in core/3.22 - how close are we to having this be not-draft?

2022-11-15 14:52 UTC, bmbouter commented
> @bmbouter would love to see this in core/3.22 - how close are we to having this be not-draft?

Close, I expect it to undraft today/tomorrow and merge by end of week. It's entirely waiting on https://github.com/pulp/analytics.pulpproject.org/pull/62, technically this PR is ready to be undrafted already. Protobuf allows us to merge and release this ahead of the server side even knowing about it. :)

2022-11-18 07:28 UTC, mdellweg approved these changes

2022-11-18 16:14 UTC, dkliban requested changes
We should be collecting the raw value returned from Postgresql. In case we are converting the version string incorrectly, we will have an opportunity to fix the conversion if we perform it on the analytics server.

2022-11-18 17:22 UTC, mdellweg approved these changes

2022-11-18 17:28 UTC, dkliban approved these changes

2022-11-18 17:35 UTC, merged