Renames TELEMETRY setting to ANALYTICS.
pulp/pulpcore pull request #3423
Opened 2022-11-22 15:38 UTC by dkliban

fixes: #3417

2022-11-22 15:55 UTC, mdellweg commented on pulpcore/app/util.py
> +    name = "Post Anonymous Analytics Periodically"
This will leave the old schedule lying around. Can you write an elidable migration to delete it?

2022-11-22 15:56 UTC, mdellweg commented on pulpcore/app/settings.py
> +ANALYTICS = True
To make this change not breaking today, can you deprecate but still use the old setting (if set)? I'd say (if set) the new setting ought to take precedence.

2022-11-22 15:57 UTC, mdellweg commented on CHANGES/3417.bugfix
> +Renamed `TELEMETRY` setting to `ANALYTICS`. This is a necessary, but backwards incompatible change.
This should come with a removal changelog entry.

2022-11-22 16:00 UTC, ipanova commented on CHANGES/3417.bugfix
> +Renamed `TELEMETRY` setting to `ANALYTICS`. This is a necessary, but backwards incompatible change.
Imagine user had set the telemetry to False and not we just replace it with analytics which is enabled by defaults. it means once the user will upgrade to next pulpcore version the data will be collected again, even if he previously marked the setting to False.

2022-11-22 16:06 UTC, dkliban commented on pulpcore/app/settings.py
> +ANALYTICS = True
How long will we support the old setting? I  would like to drop it in a future release.

2022-11-22 16:08 UTC, dkliban commented on CHANGES/3417.bugfix
> +Renamed `TELEMETRY` setting to `ANALYTICS`. This is a necessary, but backwards incompatible change.
I'll add one.

2022-11-22 16:09 UTC, dkliban commented on pulpcore/app/util.py
> +    name = "Post Anonymous Analytics Periodically"
Yes, I'll add a migration.

2022-11-22 16:13 UTC, dkliban commented on pulpcore/app/settings.py
> +ANALYTICS = True
I propose remove `TELEMETRY` in 3.23.

2022-11-22 16:18 UTC, dkliban commented on CHANGES/3417.bugfix
> +Renamed `TELEMETRY` setting to `ANALYTICS`. This is a necessary, but backwards incompatible change.
We don't have a deprecation policy for settings/user features. I propose that we deprecate in 3.22 and remove in 3.23.

2022-11-22 20:48 UTC, dkliban commented
After some discussion with @mdellweg on Matrix I left the `TELEMETRY` setting in place and introduced a new `ANALYTICS` setting. I also added a migration to remove the old TaskSchedule.

2022-11-23 08:24 UTC, mdellweg commented
> After some discussion with @mdellweg on Matrix I left the `TELEMETRY` setting in place and introduced a new `ANALYTICS` setting. I also added a migration to remove the old TaskSchedule.

To sum up my contribution to that discussion: Leaving the setting around as an alias forever is a small price payed for not upsetting users.

2022-11-23 08:27 UTC, mdellweg approved these changes
One optional suggestion...

2022-11-23 08:27 UTC, mdellweg commented on pulpcore/app/migrations/0097_remove_telemetry_task_schedule.py
> +            remove_telemetry_task_schedule, reverse_code=migrations.RunPython.noop
```suggestion
            remove_telemetry_task_schedule, reverse_code=migrations.RunPython.noop, elidable=True
```

2022-11-23 08:34 UTC, mdellweg requested changes

2022-11-23 08:34 UTC, mdellweg commented on pulpcore/app/settings.py
> +
Actually i doubt that this works as desired. After executing this module, `ANALYTICS` will be `True` and not "the value of `TELEMETRY`".

2022-11-23 13:19 UTC, dkliban commented on pulpcore/app/settings.py
> +
I'll try to add a unit test around this.

2022-11-23 13:40 UTC, ipanova commented on CHANGES/3417.bugfix
> +Renamed `TELEMETRY` setting to `ANALYTICS`. This is a necessary, but backwards incompatible change.
that's fine with me as long as we don't delete that setting right away, first deprecate it and introduce a new analytics settings, basically this https://github.com/pulp/pulpcore/pull/3423#discussion_r1029522070

2022-11-28 19:31 UTC, daviddavis commented
> To sum up my contribution to that discussion: Leaving the setting around as an alias forever is a small price payed for not upsetting users.

We have to set `TELEMETRY` to false in some of our environments for security reasons so maintaining it as an option until the next major release of pulp would make us happy. Also, my hope would be that settings would be covered by Pulp's semver policy.

Thanks 👍

2022-11-28 22:11 UTC, bmbouter commented
I can agree to maintain this setting until the next major version change. It's not my first choice, but that's the feedback we got from users, so let's work with that.

Also I think the new setting should be called `PULP_ANALYTICS`. I'm thinking all Pulp specific new settings should be prepended with `PULP_` to allow Pulp to be safely combined with any other random Django project which is a deployment scenario we allow.

2022-11-29 12:31 UTC, mdellweg commented
> Also I think the new setting should be called `PULP_ANALYTICS`. I'm thinking all Pulp specific new settings should be prepended with `PULP_` to allow Pulp to be safely combined with any other random Django project which is a deployment scenario we allow.

When translating to environment variables, they will automatically be prefixed with "PULP_". In plugins is saw variables being prefixed by the plugin name. I'm kind of against `PULP_PULP_ANALYTICS=true` and I'm not sure if `PULP_CORE_ANALYTICS=true` would carry the meaning we want.

2022-12-01 14:11 UTC, bmbouter commented
> When translating to environment variables, they will automatically be prefixed with "PULP_". In plugins is saw variables being prefixed by the plugin name. I'm kind of against `PULP_PULP_ANALYTICS=true` and I'm not sure if `PULP_CORE_ANALYTICS=true` would carry the meaning we want.

This is a great point, let's not prepend settings with `PULP_`, having a user specify an env var as `PULP_PULP_ANALYTICS` sounds not good. So given that discussion, Having the original setting name of `ANALYTICS` is what makes the most sense to me.

2022-12-01 19:02 UTC, dkliban commented on pulpcore/app/settings.py
> +ANALYTICS = True
We are keeping it around until 4.0

2022-12-01 20:17 UTC, bmbouter commented on CHANGES/3417.deprecation
> +`TELEMETRY` setting got deprecated in favor of `ANALYTICS`.
```suggestion
``TELEMETRY`` setting was deprecated in favor of ``ANALYTICS``.
```

It needs double backticks.

2022-12-01 20:17 UTC, bmbouter commented on CHANGES/3417.feature
> +The new `ANALYTICS` setting replaced the `TELEMETRY` setting to avoid confusion with application metrics that will be exposed using `OpenTelemetry`.
```suggestion
The new ``ANALYTICS`` setting replaced the ``TELEMETRY`` setting to avoid confusion with application metrics that will be exposed using Open Telemetry.
```

2022-12-01 20:17 UTC, bmbouter commented on CHANGES/3417.feature
> +The new `ANALYTICS` setting replaced the `TELEMETRY` setting to avoid confusion with application metrics that will be exposed using `OpenTelemetry`.
Also I think this could be line wrapped maybe.

2022-12-01 20:20 UTC, bmbouter approved these changes
I left some small formatting/language requests, but this is looking good. Thanks!

2022-12-01 20:20 UTC, bmbouter commented on pulpcore/app/util.py
> +    if settings.get("TELEMETRY") is not None:
A 1-liner comment in this if block for our future selves would be nice.

2022-12-01 23:12 UTC, mdellweg approved these changes
Now we confuse our own CI. (The deprecation check still works...)

2022-12-02 14:07 UTC, merged