Adds dates to the distribution listing pages
pulp/pulpcore pull request #3431
Opened 2022-11-30 19:15 UTC by dkliban

Distributions serving Publications display the date the published artifact was created. Distributions serving pass through Publications display the date the repository version was created. Distributions serving repositiory versions display the date the repository version was created.

closes: #2054

2022-11-30 20:22 UTC, dkliban commented
Here is what the results look like:

![image](https://user-images.githubusercontent.com/294339/204900220-ad59de63-b1c0-4e00-ba42-26a6e97872ab.png)

2022-12-01 15:26 UTC, gerrod3 commented on pulpcore/content/handler.py
> +        html = Handler.render_html(directory_list, path=path)
Can this also include the `pulp_created` of the distributions for dates as well?

2022-12-01 15:26 UTC, gerrod3 commented on pulpcore/content/handler.py
> +<body bgcolor="white">
Does this need `<!DOCTYPE html>` at the top? Also, can indentation be added back to the template?

2022-12-01 16:58 UTC, daviddavis commented
I tested this out and it works great but there's a problem for our use case (and perhaps the original reporter's use case too). 

The dates being shown for packages are when the published artifact is created but what we care about is the package first gets added to (or rather published in) a repo. In other words, just because a repo gets published again, the timestamp for a package that is already in the repo shouldn't change. This is similar to how if you were using createrepo + a web server: running createrepo to publish/re-publish the repo wouldn't change the timestamp on the package.

I don't know how feasible it is to do this though?

2022-12-01 17:19 UTC, daviddavis commented on pulpcore/content/handler.py
>                      )
Maybe allow `content_handler_list_directory` to return dates?

```suggestion
                    vals = await sync_to_async(distro.content_handler_list_directory)(rel_path)
                    if isinstance(vals, set):
                        dir_list.update(vals)
                    else:
                        dir_list.update(vals[0])
                        dates.update(vals[1])          
```

2022-12-01 18:15 UTC, dkliban commented
@daviddavis I believe you are interested in the date that the content was added to the repository version. Am I understanding correctly?

2022-12-01 18:17 UTC, daviddavis commented
@dkliban ideally, we'd have the date that the content was first published (ie exposed to the world). However, the date that the content was added to the repo might suffice. Let me doublecheck.

2022-12-01 19:21 UTC, daviddavis commented
@dkliban so I got a response and it sounds like the content creation time is what we want.

2022-12-01 19:23 UTC, dkliban commented
@daviddavis that makes sense to me. i'll update the PR.

2022-12-01 20:43 UTC, dkliban commented on pulpcore/content/handler.py
> +        html = Handler.render_html(directory_list, path=path)
I was not sure how much value that would provide. Maybe the pulp_last_updated would be better?

2022-12-01 20:46 UTC, dkliban commented
@mdellweg I changed which date is now displayed. It will always show the date that the content was created in Pulp. Please re-review.

2022-12-01 20:55 UTC, daviddavis approved these changes

2022-12-01 21:14 UTC, dkliban commented on pulpcore/content/handler.py
> +        html = Handler.render_html(directory_list, path=path)
Actually, I would prefer to not make that decision now and leave off the dates on the list of distributions.

2022-12-01 23:15 UTC, mdellweg commented on pulpcore/content/handler.py
> +                    dates.update({name: pa.content_artifact.pulp_created})
Should this be the artifact or the content?

2022-12-02 00:53 UTC, daviddavis commented on pulpcore/content/handler.py
> +                    dates.update({name: pa.content_artifact.pulp_created})
Hmm. What would be the tradeoffs between using artifact over content or content over artifact?

To be honest, as everyday Pulp users, we never interact with artifacts. The endpoints we use are the one-shot upload endpoints, content list/show, and then the repository modify endpoint. So artifacts are completely obscure to us as we don't even expose artifacts to our users. And so I think content creation timestamp is probably more useful to us.

2022-12-02 09:22 UTC, mdellweg commented on pulpcore/content/handler.py
> +                    dates.update({name: pa.content_artifact.pulp_created})
I agree. Just because two content units happen to use the same bits should not determine their date.

Also great feedback, as with our RBAC story we assume exactly that (less privileged) users may not interact with artifacts or orphaned content directly.

2022-12-02 12:04 UTC, daviddavis commented on pulpcore/content/handler.py
> +                    dates.update({name: pa.content_artifact.pulp_created})
So what @dkliban has here works then? I assume that the `content_artifact.pulp_created` would be the same as the content `pulp_created`?

2022-12-02 13:58 UTC, mdellweg commented on pulpcore/content/handler.py
> +                    dates.update({name: pa.content_artifact.pulp_created})
I believe so.

2022-12-02 13:59 UTC, mdellweg approved these changes
Reinstating my approval.

2022-12-02 14:16 UTC, bmbouter requested changes
Please add a test for this.

2022-12-02 18:08 UTC, dkliban commented on pulpcore/content/handler.py
> +<body bgcolor="white">
@gerrod3 I am torn about this. You are basing your suggestions on what Apache serves up when it lists directories. My changes to the template make it look like the page that is served up by nginx. I used https://fixtures.pulpproject.org as my example.

2022-12-02 20:34 UTC, bmbouter approved these changes
Thank you!

2022-12-02 20:39 UTC, merged