Redirects user to a path that ends in /
pulp/pulpcore pull request #3434
Opened 2022-12-02 20:44 UTC by dkliban

This patch returns a 301 redirect when a requested path does not end in a / but should end in a /.

fixes: #3363

2022-12-02 20:47 UTC, dralley commented
@dkliban Does this fix https://github.com/pulp/pulpcore/issues/3173 ?

2022-12-02 21:48 UTC, dkliban commented
@dralley yes it does.

2022-12-02 21:50 UTC, dralley commented
Great, would you mind making sure both get closed and updating the BZ?

2022-12-03 05:01 UTC, dralley commented
adding an extra fixes / closes tag to the commit, or marking duplicate, whichever you prefer

2022-12-05 13:32 UTC, mdellweg requested changes

2022-12-05 13:32 UTC, mdellweg commented on .ci/ansible/settings.py.j2
> -TELEMETRY = False
This needs to be `ANALYTICS=False`.
But we should solve it in the template.

2022-12-05 13:37 UTC, daviddavis commented
I tested this and it works great 👍 

I found [one other issue that the dates change apparently introduced](https://github.com/pulp/pulpcore/issues/3436) but it's relatively minor I think and can be fixed in a z-stream.

2022-12-05 13:39 UTC, daviddavis approved these changes

2022-12-05 15:58 UTC, gerrod3 commented on pulpcore/content/handler.py
> +            raise HTTPMovedPermanently(f"{settings.CONTENT_PATH_PREFIX}{path}/")
What is going on here? Should this not be covered by the above `try/except` block?

2022-12-05 16:50 UTC, dkliban commented on pulpcore/content/handler.py
> +            raise HTTPMovedPermanently(f"{settings.CONTENT_PATH_PREFIX}{path}/")
Your observation is correct. I'll update my PR to always raise PathNotResolved on line 308 (without checking if the path ends in a slash).

2022-12-05 19:04 UTC, dralley commented on pulpcore/content/handler.py
> +            ends_in_slash = rel_path == "" or rel_path[-1] == "/"
Why do we need to perform this check twice?  Can the redirect happen earlier?

Can we use `.endswith()` consistently instead of using `[-1]` here

2022-12-05 21:30 UTC, dkliban commented on pulpcore/content/handler.py
> +            ends_in_slash = rel_path == "" or rel_path[-1] == "/"
I'll update to use .endswith(). 

The redirect can't happen earlier because we don't know if there is an index.html until later.

2022-12-06 12:55 UTC, mdellweg commented on pulpcore/content/handler.py
> +                rel_path = rel_path[:-1]
So this is un-doing the thing from before?
So i understand correctly, that for every request inside a publication we first try to find `f"{url/index.html"` and only then attempt to serve the proper published artifact?
I think this index thing should be a fallback basically halfing the number of accesses to the `published_artifact` table.

2022-12-06 13:54 UTC, dkliban commented on pulpcore/content/handler.py
> +                rel_path = rel_path[:-1]
yes, it is undoing the path manipulation from above. I believe you have identified a performance regression that this code introduces. I will move the search for index.html and directory listing to be after we try looking for published artifacts.

2022-12-07 11:35 UTC, mdellweg approved these changes

2022-12-07 19:13 UTC, dralley commented on pulpcore/content/handler.py
>          base_paths = cls._base_paths(path)
This lookup should be unaffected by the transformation, yes?

2022-12-07 21:25 UTC, merged

2022-12-13 13:46 UTC, ipanova commented on pulpcore/content/handler.py
>          base_paths = cls._base_paths(path)
In pulp-container base_paths are treated completely differently, they should not end with /, hence we are overriding this method.
This change breaks the plugin because there is an assumption that every plugin uses base_bath in the same way.