Not finished...
pulp/pulpcore pull request #3448
Opened 2022-12-07 20:29 UTC by bmbouter

2022-12-12 09:45 UTC, mdellweg requested changes

2022-12-12 09:45 UTC, mdellweg commented on CHANGES/plugin_api/3368.doc
> +Adds docs that plugin writers tasks must be backwards compatible until Pulp 4.0. This practice will
Can you wrap this line at 98 characters?
Towncrier will add two spaces eventually.

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +cause all Pulp code to take on two new requirements:
```suggestion
cause all Pulp code to take on new requirements:
```
I'm almost sure this list wlll expand...

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +* Migrations cannot break earlier versions of running code.
```suggestion
* Migrations must not break earlier versions code possibly still running during an upgrade.
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +* Task code must be backwards compatible until Pulp 4.0
```suggestion
* Task code must be backwards compatible until the next major version of Pulp.
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +1. Run the migrations while old pulp code is online. Old code, new data format
```suggestion
1. Run the migrations while old pulp code is online. Old code, is using the new data format.
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +be made. This would break all previous code which expects the previous column name.
```suggestion
be renamed. After renaming the field, Django would generate a migration that renames the specifiied
column. This would break all previous code which expects the previous column name.
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +1. Avoid it. Is this rename really that important? Is it worth the effort?
Really just a suggestion...
```suggestion
1. Avoid it. Is this rename really that important? Is it worth the trouble?
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +   the `db_column <https://docs.djangoproject.com/en/3.2/ref/models/fields/#db-column>`_.
This is almost impossible due to semver on the api anyway, right? But it could be some other api requesting it from us.

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +4. For data migrations that would normally use table-locks, break these up into chunks.
I do not see this as an individual solution to any problem. When you do chunked updates of data, the old code would only see the not yet migrated items, while the new code would only see the already migrated chunks.
It does not sound right to me.

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +  This allows the new code to read/write exclusively with `bar` and the old code to deal with `foo`.
```suggestion
  This allows the new code to read/write exclusively with `new` and the old code to deal with `old`.
```

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +  treated as deleted without deleting it.
I was wondering if we would keep the column around in the ORM layer and later delete it from there.
I believed this would be much easier with the Django generated migrations.

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +* Remove the column ``old`` and the database trigger.
Probably the other way around...

2022-12-12 09:45 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +code until Pulp 4.0.
I think at some point it should be ok to cancel a very old task with an appropriate error message.

2023-01-05 18:16 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +* Migrations cannot break earlier versions of running code.
I removed the `possibly` since we'll be able to know for sure if its' running or not from the db.

2023-01-05 18:19 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +1. Avoid it. Is this rename really that important? Is it worth the effort?
+1 it's more than just effort it's also uncertainty and support over time. Change made.

2023-01-05 18:24 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +   the `db_column <https://docs.djangoproject.com/en/3.2/ref/models/fields/#db-column>`_.
Agreed. Based on that, I removed the `and serializers` words since there could be attributes on models we don't expose or expose directly. In those cases I think this idea makes sense. If you think we should modify this more, please lmk.

2023-01-05 18:32 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +code until Pulp 4.0.
I modified to be `the next major version of Pulp.`. Yes we may need to at some point, but I'd prefer to not add that into the toolbox as an option right from the start if that's ok. Let me know if you still want to.

2023-01-05 18:38 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +  treated as deleted without deleting it.
I agree, I rewrote this part so let me know what you think. Also I realized I never told developers to actually copy the data from `old` to `new` so I added that step in here too.

2023-01-10 12:29 UTC, mdellweg requested changes
Please look for "may" or "maybe" if you think some suggestions are not required...

2023-01-10 12:29 UTC, mdellweg commented on CHANGES/plugin_api/3368.doc
> +will eventually enable zero-downtime upgrades.
Actually, this is an issue even without zero-downtime. Maybe just scrap that last sentence, or stat that it provides more stable upgrades in general.

2023-01-10 12:29 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +  upgrade to a version pulp_file>=1.10,<1.13.0.
The sentence structure is a little unclear to me. How about:
```suggestion
  pulp_file < 1.10.0. If there are, abort running the migration and notify the user they need to
  upgrade to a version pulp_file>=1.10,<1.13.0.
```

2023-01-10 12:29 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +  table-lock.
With the trigger in place it may suffice to "update" the old columns.

2023-01-10 12:29 UTC, mdellweg commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +be forever backwards compatible until Pulp 4.0. For example, you cannot have a breaking signature
... the next major version ...

I always try to avoid explicit versions in docs. You will most definitely miss updating them properly in the future.

2023-01-13 07:23 UTC, mdellweg approved these changes

2023-01-13 15:30 UTC, ipanova commented on CHANGES/plugin_api/3368.doc
> +Adds docs that plugin writers tasks must be backwards compatible until Pulp 4.0.
until the next Pulp major version

2023-01-13 15:30 UTC, ipanova commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +cause all Pulp code to take on new requirements:
I am having troubles to understand the goal of these 2 sentences. Is this a future promise but we are still not there? "will likely start allowing" does not give much of the info to the users. How can we re-phrase this better?

2023-01-13 15:30 UTC, ipanova commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +older codebases could be runnable on newer, upgraded workers. To ensure this always works tasks must
`could run` otherwise `they should be runnable` as "-able" points to ability not to the possibility.

2023-01-13 17:53 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +cause all Pulp code to take on new requirements:
I rewrote this paragraph to more clearly state what is hapening. What do you think?

2023-01-16 19:23 UTC, bmbouter commented
@ipanova can I have one more review when you get a chance please?

2023-01-16 20:40 UTC, ipanova approved these changes

2023-01-16 20:40 UTC, ipanova commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +To work towards that goal, developers of ``pulpcore`` and ``pulp_file`` should take on the following
I am not sure whether it's worth specifically accentuating on the pulp-file as a plugin, I think every plugin will need to adhere to this requirements.

2023-01-16 21:02 UTC, bmbouter commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +To work towards that goal, developers of ``pulpcore`` and ``pulp_file`` should take on the following
I revised this a bit more. With "should" remaining in the sentence, having it stated generally as a requirement for all plugins is in-line with the original thinking. +1

2023-01-17 10:36 UTC, ipanova commented on docs/plugin_dev/plugin-writer/concepts/index.rst
> +To work towards that goal, developers of ``pulpcore`` and ``pulp_file`` should take on the following
yes, thank you.

2023-01-17 10:36 UTC, merged

2023-01-17 14:08 UTC, bmbouter commented
Thanks for the reviews!