Enables one to incrementally export rpms
pulp/pulpcore pull request #3511
Opened 2023-01-13 23:13 UTC by parthaa

It accepts a start repository version and calculates what content artifacts need to get copied over.

2023-01-16 21:21 UTC, ggainey commented
This PR currently supports `start_repository_version` **only if** you have specified `repository_version`. `publication=` is a major workflow for users of this functionality, but if you specify `start_repository_version=` and `publication=`, you get a 500. Rude. :)

I think we should always accept `publication=`. Actually, more strongly - I contend that we should support a `start_publication=` param as well. You can only specify one of publication/repository_version, and only one of start_publication/start_repository_version, and the combinatorics should all work.

(Also - we prob need some error-checking at the view-level, you should **not** be able to specify a delta that "goes back in time" - once we have start and end repo-version, we should insure that start < end...)

The other thing I'm noting is, if I start with a repo, remove some RPMs to create version-N, add them back in to create version-M, and export start_repository_version=N/repository_version=M, I get an empty export. I expect somewhere in the "find the content for a version" is making An Assumption that may not be valid.

Testing/investigation continues.

2023-01-16 22:10 UTC, parthaa commented
> This PR currently supports `start_repository_version` **only if** you have specified `repository_version`. `publication=` is a major workflow for users of this functionality, but if you specify `start_repository_version=` and `publication=`, you get a 500. Rude. :)

Interesting -  Katello only uses publication. Wonder why  `start_repository_version=` and `publication=` is failing for you. I used that combination for all my tests :). 

> I think we should always accept `publication=`. Actually, more strongly - I contend that we should support a `start_publication=` param as well. You can only specify one of publication/repository_version, and only one of start_publication/start_repository_version, and the combinatorics should all work.

I wonder if we should limit the scope of this PR to only publication and start_publication and leave the version compare to a different PR? Katello really only needs this combination to work. That would potentially mean small set of changes.


> The other thing I'm noting is, if I start with a repo, remove some RPMs to create version-N, add them back in to create version-M, and export start_repository_version=N/repository_version=M, I get an empty export. I expect somewhere in the "find the content for a version" is making An Assumption that may not be valid

I will look into this case

2023-01-16 22:19 UTC, sjha4 commented
We may not create "new" publications if our contents_changed dynflow middleware detects nothing has changed in which case we reuse the previous version's publication. Every repo version however will have a publication URL which could be used here I think with the catch that the publication may not be unique between versions.

2023-01-16 22:27 UTC, ianballou commented
Here's the publication logic: https://github.com/Katello/katello/blob/69d4da4767ea71810a4323c02ff0ce3969418289/app/lib/actions/pulp3/orchestration/repository/generate_metadata.rb#L15

2023-01-20 20:14 UTC, parthaa commented
> This PR currently supports `start_repository_version` **only if** you have specified `repository_version`. `publication=` is a major workflow for users of this functionality, but if you specify `start_repository_version=` and `publication=`, you get a 500. Rude. :)

```bash
$ curl --cert /home/vagrant/foreman-certs/client_cert.pem --key /home/vagrant/foreman-certs/client_key.pem \
   -X POST -H 'Content-Type: application/json' \
   -d '{"publication":"/pulp/api/v3/publications/rpm/rpm/62b3af46-d059-4d2b-a898-1dd7955ec531/", "start_repository_version":"/pulp/api/v3/repositories/rpm/rpm/6c98c027-53ff-440e-a5ce-ba68cc0833cc/versions/4/"}' \
    https://centos8-katello-devel-stable.example.com/pulp/api/v3/exporters/core/filesystem/8f7a1139-5153-4e54-9e9d-994152379d01/exports/
```

Works well - `journalctl` output

```
Jan 20 20:06:28 centos8-katello-devel-stable.example.com pulpcore-api[15405]: pulp [0ed95cc8205048eca7cf18c134bf3b94]:  - - [20/Jan/2023:20:06:28 +0000] "POST /pulp/api/v3/exporters/core/filesystem/8f7a1139-5153-4e54-9e9d-994152379d01/exports/ HTTP/1.1" 202 67 "-" "curl/7.61.1"
Jan 20 20:06:28 centos8-katello-devel-stable.example.com pulpcore-worker-4[23566]: pulp [0ed95cc8205048eca7cf18c134bf3b94]: pulpcore.tasking.pulpcore_worker:INFO: Starting task 7b7d754c-771b-4c51-a443-dd5402be20da
Jan 20 20:06:28 centos8-katello-devel-stable.example.com pulpcore-worker-4[23566]: pulp [0ed95cc8205048eca7cf18c134bf3b94]: pulpcore.app.tasks.export:INFO: Exporting: file_system_exporter=open_Export-Library-SYNCABLE_2.0-67, publication=62b3af46-d059-4d2b-a898-1dd7955ec531, start_repo_version=e5e32d67-0e8c-455a-9c65-eb9cb5242ac7, path=/var/lib/pulp/exports/open/Export-Library-SYNCABLE/2.0/2023-01-20T18-27-51-00-00/custom/goals/auto
Jan 20 20:06:28 centos8-katello-devel-stable.example.com pulpcore-worker-4[23566]: pulp [0ed95cc8205048eca7cf18c134bf3b94]: pulpcore.tasking.pulpcore_worker:INFO: Task completed 7b7d754c-771b-4c51-a443-dd5402be20da
Jan 20 20:07:10 centos8-katello-devel-stable.example.com pulpcore-api[15405]: pulp [6d519aaaad01486bbfdda21d9685c6b5]:  - - [20/Jan/2023:20:07:10 +0000] "GET /pulp/api/v3/tasks/7b7d754c-771b-4c51-a443-dd5402be20da/ HTTP/1.1" 200 744 "-" "Pulp-CLI/0.14.0"

```

2023-01-20 22:19 UTC, ianballou commented
> I wonder if we should limit the scope of this PR to only publication and start_publication and leave the version compare to a different PR? Katello really only needs this combination to work. That would potentially mean small set of changes.

I'm still digging into this myself, but it sounds like Katello only really needs to give the start repo version and the end publication to get what we want -- if that's the case then I'm with Partha in that perhaps the start publication could be added later. I'd be curious to hear though if Pulp folks think we might be missing something and do need a start publication.

2023-01-23 10:30 UTC, mdellweg commented
Can we phrase this feature around "content" instead of "rpms"?

2023-01-23 13:35 UTC, parthaa commented
> Can we phrase this feature around "content" instead of "rpms"?

I think only Yum/File repos are supported for FS Exporter at this point. Where do you see this being specific to rpms?

2023-01-24 08:20 UTC, mdellweg commented
> > Can we phrase this feature around "content" instead of "rpms"?
> 
> I think only Yum/File repos are supported for FS Exporter at this point. That being said where do you see this PR being specific to rpms?

I meant the docs and changelog. Sorry for not being specific enough.

2023-01-24 20:28 UTC, ggainey requested changes
Some minor wordsmithing, and one bugfix :)

2023-01-24 20:28 UTC, ggainey commented on pulpcore/app/viewsets/exporter.py
> +                request.data["repository_version"], RepositoryVersion
Has to be

```suggestion
                request.data["start_repository_version"], RepositoryVersion
```

2023-01-24 20:28 UTC, ggainey commented on CHANGES/3413.feature
> +Also made it incrementally export rpms that differed between
```suggestion
If specified, it will export only rpms that differed between 
```

2023-01-24 20:28 UTC, ggainey commented on pulpcore/app/serializers/exporter.py
> +        help_text=_("A URI of the last-exported-repo-version."),
```suggestion
        help_text=_("The URI of the last-exported-repo-version."),
```

2023-01-25 11:19 UTC, mdellweg reviewed
Some formatting and what i meant by agnostic in the changelog...

2023-01-25 11:19 UTC, mdellweg commented on CHANGES/3413.feature
> +2 repository versions
```suggestion
Added a ``start_repository_version`` parameter to the file system exporter.

If specified, it will export only content units that differed between two repository versions.
```

2023-01-27 05:42 UTC, dralley commented
@parthaa Can you rebase and squash commits?

2023-01-27 05:45 UTC, dralley commented on pulpcore/app/tasks/export.py
> +            start_repo_version is None or pa.content_artifact in difference_content_artifacts
`difference_content_artifacts` appears to be a queryset, do we know that this isn't going to be re-evaluated every time in a loop?

2023-01-27 16:21 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +            start_repo_version is None or pa.content_artifact in difference_content_artifacts
Thats a good point I am curious about that :). How would I be able to check if its getting re evaluated ?

2023-01-27 18:45 UTC, dralley commented on pulpcore/app/tasks/export.py
> +            start_repo_version is None or pa.content_artifact in difference_content_artifacts
You could explicitly cast to a set

2023-01-27 22:04 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +            start_repo_version is None or pa.content_artifact in difference_content_artifacts
updated!

2023-01-31 18:41 UTC, ggainey approved these changes
Looks like all current comments are responded to. Tested with an RPM repo in my test env, worked like a champ. Looks good to me!

2023-01-31 20:56 UTC, chris1984 commented
Tested it here locally with Katello and was able to export incrementally and import without any issues

2023-01-31 21:01 UTC, dralley commented on pulpcore/app/tasks/export.py
> +        ):
How does this work with the metadata e.g. RPM metadata?  

`difference_content_artifacts` is derived from the repository version, not the publication, so how does this not filter out all the RPM metadata from the newest publication?

2023-01-31 21:03 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +        ):
It exports the full metadata, always, but only the delta for artifacts.

2023-01-31 21:04 UTC, parthaa commented on pulpcore/app/tasks/export.py
> +        ):
Oh it always picks the latest metadata from the repo publication (I thought that was the same way regular incremental export worked? ). It is only doing a diff for rpms

2023-01-31 22:19 UTC, dralley commented on pulpcore/app/tasks/export.py
> +        ):
@ggainey I agree that's what it should do, but where is the separate codepath for metadata?  It looks like it's all treated as `Content`, and `PublishedMetadata` inherits from `Content` so that can work, but unlike any other kind of content it's not part of any repositories.

2023-01-31 22:51 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +        ):
We're looking at the diff between a start_repo-version and a publication - "only export things that are in the publication, and are NOT in the start_repo_version". So the publication's metadata is always "found".

@parthaa does that match your expectation?

2023-01-31 23:04 UTC, dralley commented on pulpcore/app/tasks/export.py
> +        ):
Ok, never mind, that sounds correct.   Line 119 starts from the publication.

I think my brain flipped around the order of the sets.

2023-01-31 23:04 UTC, dralley approved these changes

2023-01-31 23:28 UTC, ggainey commented on pulpcore/app/tasks/export.py
> +        ):
> Ok, never mind, that sounds correct. Line 119 starts from the publication.
> 
> I think my brain flipped around the order of the sets.

No worries - the flow is complicated, deltas make it moreso, and responding to your question made me go over the whole thing again so I actually understand it better now myself :)

2023-02-01 19:18 UTC, ggainey commented
@parthaa OK, please rebase this on top of current-main to address the lint-issues, and resubmit.

2023-02-02 12:22 UTC, merged

2023-02-02 16:42 UTC, parthaa commented
@dralley  - I'll request it if needed and if customers are desperate for it.

2023-03-02 17:06 UTC, dralley commented
@parthaa It looks like there is a request for this to go into 3.18 (6.12.z), could you investigate which other patches are necessary to backport it?