Repeat to kill the process of a canceled task
pulp/pulpcore pull request #3540
Opened 2023-01-31 10:54 UTC by mdellweg

fixes #3407

2023-01-31 19:05 UTC, ggainey requested changes
A change and a question - def on the right track tho

2023-01-31 19:05 UTC, ggainey commented on pulpcore/tasking/pulpcore_worker.py
> +                    if self.task_grace_timeout:
If task_grace_timeout ever goes negative (somehow), this ends up being "true" when we prob don't want it to - safer to make this check <0, like the check at line 349

2023-01-31 19:05 UTC, ggainey commented on pulpcore/tasking/pulpcore_worker.py
> +                        os.kill(task_process.pid, signal.SIGUSR1)
Are we sure that sending USR1 again is guaranteed to kill the task-process? Do we need a "no really, shoot it in the head" w/ SIGKILL if it's somehow still around?

2023-02-01 05:17 UTC, dralley commented
Do we have a theory on "why" this happens?  I don't object to the approach necessarily

2023-02-01 05:50 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +# Number of heartbeats between attemts to kill the subprocess (approx)
typo "attemts"

2023-02-01 05:52 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +                if cancel_state == TASK_STATES.CANCELED:
Do we expect that it could possibly be in a different state here or are we just being explicit?  Curious about this change.

2023-02-01 05:55 UTC, dralley commented on pulpcore/app/tasks/test.py
> +    """A sleep task that is really reluctant to being killed."""
reluctant -> resistant?  Also it would be good to expand a bit on the mechanics of it

2023-02-01 08:21 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                    if self.task_grace_timeout:
If it can ever go negative, it can also go infinitely negative and produce an overflow. I think i should prevent it from ever getting there in the first place. I will adjust the ticking down part.

2023-02-01 08:25 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                        os.kill(task_process.pid, signal.SIGUSR1)
The test in place is showing that it is sufficient, as long as the subprocess is "only" ignoring python exceptions. I would keep it that way until we hear from the field that it's not sufficient.
I remember vaguely that i had troubles sending SIGTERM where the worker (for whatever reason) terminated itself.

2023-02-01 08:27 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                if cancel_state == TASK_STATES.CANCELED:
This is a consequence of the worker shutdown code path being able to signal multiple times too. It would set the `cancel_state` to `FAILED` instead.

2023-02-01 08:28 UTC, mdellweg commented on pulpcore/app/tasks/test.py
> +    """A sleep task that is really reluctant to being killed."""
```suggestion
    """A sleep task that tries to avoid being killed by ignoring all exceptions."""
```

2023-02-01 08:28 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +# Number of heartbeats between attemts to kill the subprocess (approx)
```suggestion
# Number of heartbeats between attempts to kill the subprocess (approx)
```

2023-02-01 08:30 UTC, mdellweg commented
> Do we have a theory on "why" this happens? I don't object to the approach necessarily

We never got the requested log steam around the failed cancel, so no. When i see the cli test in our CI failing to properly cancel a task, there seems to be a backoff involved. But i could never reproduce it.

2023-02-01 09:08 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +                if cancel_state == TASK_STATES.CANCELED:
Actually i reworked the killing process in the worker shutdown to take this route too. Looks like this now:

```
pulp [70ba56f0-3532-4965-8ca7-c3697ca6b90c]: pulpcore.tasking.pulpcore_worker:INFO: Starting task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2
^Cpulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 51070@8bd82e0b7d01 was requested to shut down.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker shutdown requested, waiting for task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2 to finish.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker shutdown requested, waiting for task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2 to finish.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Aborting current task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2 due to worker shutdown.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Aborting current task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2 due to cancelation.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Cleaning up task d1d42cf9-90c1-4416-9a3c-a647eeb0dca2 and marking as failed. Reason: Aborted during worker shutdown.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 51070@8bd82e0b7d01 was shut down.
```

2023-02-01 13:43 UTC, ggainey commented
> Do we have a theory on "why" this happens? I don't object to the approach necessarily

I spent a fair amount of time trying to reproduce the reported behavior in a variety of ways with no success. My current hypothesis is that, somehow, the USR1 handling threw an exception before reaching the os.kill() stmt - but I couldn't convince myself I could see how that might happen. Without logs, we're just guessing.

2023-02-01 16:14 UTC, dralley commented on pulpcore/tasking/pulpcore_worker.py
> +                    if self.task_grace_timeout:
FYI, there is effectively no such thing as an integer overflow in Python, when it overflows 64 bits the payload type gets promoted to an implementation of "big integers"

2023-02-01 19:46 UTC, dralley commented
Do we have sufficient logging to ensure that we would be able to make use of the log stream if we had it?

2023-02-02 12:25 UTC, mdellweg commented
We log when the worker (outerprocess) received the cancel notification. And we log when the worker is killing the child process. So it should at least be sufficient to see, where in the process we get lost.
And that is the very line I desparately want to see in the logs. Also for the case this fix is tailored for you would see some logging from backoff.

2023-02-02 14:02 UTC, dralley approved these changes

2023-02-03 14:28 UTC, ggainey approved these changes

2023-02-03 14:28 UTC, ggainey commented on pulpcore/tasking/pulpcore_worker.py
> +            if self.task_grace_timeout > 0:
:+1:

2023-02-03 14:28 UTC, ggainey commented on pulpcore/tasking/pulpcore_worker.py
> +                    if self.task_grace_timeout > 0:
:+1:

2023-02-03 14:35 UTC, merged