Fixes a possible N+1 issue within reclaim_space task
pulp/pulpcore pull request #3557
Opened 2023-02-08 16:43 UTC by decko

Closes #3404

2023-02-08 17:38 UTC, dralley approved these changes

2023-02-08 18:12 UTC, lubosmj commented on CHANGES/3404.bugfix
> +Fixes a possible N+1 issue within reclaim_space task.
Could this be translated into a more user-friendly message with a past simple tense?

2023-02-09 20:54 UTC, gerrod3 commented on pulpcore/app/tasks/reclaim_space.py
> +    ca_qs = ContentArtifact.objects.select_related("content").filter(
Should this also include `"artifact"`? The loop below accesses the pk of the artifact. I know accessing `artifact_id` wouldn't trigger a db lookup, but I'm not sure if you access the pk off of the artifact object if that triggers a lookup as well.

2023-02-09 20:56 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
> +    ca_qs = ContentArtifact.objects.select_related("content").filter(
Good question - I *think* it's smart enough to avoid an extra query, maybe 90% sure, but not 100%

2023-02-10 12:46 UTC, mdellweg commented
Am i right, that this change is not changing behaviour, but only performance?

2023-02-10 13:35 UTC, dralley commented
@mdellweg  Yes

2023-02-10 13:38 UTC, mdellweg commented
Then let's put the work "performance" in the changelog. ;)

2023-02-10 18:33 UTC, dralley commented on pulpcore/app/tasks/reclaim_space.py
>          ca_qs = ca_qs.filter(remoteartifact__isnull=False)
The error makes sense but tbh I wonder why it wasn't triggering before?

TL;DR since your queryset is using .values(), the objects returned are dictionaries rather than objects.  On line 60 you need to use something like `ca["content__pulp_type"]`

2023-02-10 20:49 UTC, decko commented on CHANGES/3404.bugfix
> +Fixes a possible N+1 issue within reclaim_space task.
How could I write this in a better way? :thinking:

2023-02-10 20:56 UTC, ggainey commented on CHANGES/3404.bugfix
> +Fixes a possible N+1 issue within reclaim_space task.
```suggestion
Addressed a possible N+1 performance issue within reclaim_space task.
```

wdyt?

2023-02-10 21:04 UTC, ggainey requested changes

2023-02-10 21:04 UTC, ggainey commented on CHANGES/3404.performance
> +Fixes a possible N+1 issue within reclaim_space task.
We don't have a "performance" section of towncrier, so .bugfix it is. (Maybe we *should* have "performance" as an option - but that's a separate discussion/fix, elsewhere :) )

2023-02-10 21:12 UTC, decko commented on CHANGES/3404.performance
> +Fixes a possible N+1 issue within reclaim_space task.
I was using `misc` in a previous iteration of this PR, but seems that a `bugfix` is applicable here. What do you think @mdellweg ?

2023-02-10 21:14 UTC, ggainey commented on CHANGES/3404.performance
> +Fixes a possible N+1 issue within reclaim_space task.
I like bugfix because it's good to let ppl know we're looking into performance issues. I believe .misc is "not visible to enduser" - and performance issues absolutely can be noticeable.

2023-02-13 10:29 UTC, mdellweg commented on CHANGES/3404.performance
> +Fixes a possible N+1 issue within reclaim_space task.
+1 To all of this. Sorry, i meant to use the word "performance" in the actual changelog line.

2023-02-13 10:31 UTC, mdellweg commented on CHANGES/3404.bugfix
> +Addressed a possible N+1 performance issue within reclaim_space task.
I'm still a bit unsure about the "N+1" part. I assume you mean N+1 db calls instead of one. But at lease we tell our users that they can expect better perf with this fix and what was slow.

2023-02-13 10:31 UTC, mdellweg approved these changes

2023-02-13 11:38 UTC, decko commented on CHANGES/3404.bugfix
> +Addressed a possible N+1 performance issue within reclaim_space task.
I changed it to "N+1 query performance issue" to be specific about the piece we worked on.

2023-02-13 16:04 UTC, dralley approved these changes

2023-02-13 16:05 UTC, dralley commented
@ggainey Could you +1?

2023-02-13 16:31 UTC, ggainey approved these changes

2023-02-13 17:11 UTC, merged