Enables replicating distributions/repositories from another Pulp.
pulp/pulpcore pull request #3568
Opened 2023-02-13 21:54 UTC by dkliban

This patch adds a new Upstream Pulps API. This API enables the user to provide REST API credentials for an upstream Pulp. The user is then able to make a POST request to the Upstream Pulp 'replicate' API to dispatch a task that will look for all distributions that are available on the upstream Pulp. This task will then create remotes that can sync from those distributions. It will also create repositories and distributions that have the same base paths as on the upstream Pulp. It will then sync from all the distributions. The task then removes any distributions that are no longer present on the upstream Pulp, but exist on the Pulp running the replication task. The user is able to limit which distributions are replicated by specifying a 'labels' attribute on the Upstream Pulp config.

This patch provides an abstract class of a Replicator that each plugin is expected to implement. The replication task will only replicate content for plugins that implement a Replicator.

closes: #3566

2023-02-14 10:52 UTC, mdellweg commented on pulpcore/app/models/replica.py
> +    labels = models.TextField(null=True)
This is meant to encode criteria for replicating, right?
Do we want to invent a DDL that can filter by labels, name patterns, relpath prefixes?

labels are key[-value] in Pulp. How do you expect this to be represented?

If this was just for a list of label keys, should we not make it an ArrayField?

2023-02-14 10:54 UTC, mdellweg commented on pulpcore/app/replica.py
> +        self.app_label = None
At least these could be class attributes.

2023-02-14 10:56 UTC, mdellweg commented on pulpcore/app/replica.py
> +            offset += list_size
:thinking: This iterator could be a _thing_ on the context model.

2023-02-14 10:57 UTC, mdellweg commented on pulpcore/app/replica.py
> +        self.distribution_ctx = None
If is understand correctly, you intend to put the context class here. In pulp-cli land this variable is always used as an instance. This would confuse me.

2023-02-14 11:00 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        user_agent="pulpcore-3.22",
Can we find a way to let this not be outdated easily?

2023-02-14 11:02 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +        )
This is exclusive in the way that you can only replicate one upstream at a time?

2023-02-14 11:07 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +        user_agent="pulpcore-3.22",
Yes, this was just a placeholder. I'll get the version string from __version__ of pulpcore.

2023-02-14 11:07 UTC, dkliban commented on pulpcore/app/viewsets/replica.py
> +        )
yes. I am open to discussion about this.

2023-02-14 11:10 UTC, dkliban commented on pulpcore/app/models/replica.py
> +    labels = models.TextField(null=True)
Here is the help text I provided on the serializer: "One or more pulp_labels that will be used to filter distributions on the upstream Pulp. E.g.  '"foo=bar,key=val" or "foo,key"'

2023-02-14 11:12 UTC, dkliban commented on pulpcore/app/replica.py
> +        self.distribution_ctx = None
Yes, these are classes, not instances. I'll update the names to better reflect that.

2023-02-14 11:13 UTC, dkliban commented on pulpcore/app/replica.py
> +            offset += list_size
I would very much like it if it was.

2023-02-14 11:44 UTC, mdellweg commented on pulpcore/app/models/replica.py
> +    labels = models.TextField(null=True)
"foo=bar,bar" is also possible?

2023-02-14 11:49 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +        )
Well what would it even mean if you replicate multiple pulps? Would the last one remove all the former ones? What if the collide on a distribution name?

2023-02-14 14:02 UTC, dkliban commented on pulpcore/app/models/replica.py
> +    labels = models.TextField(null=True)
Yes, it is possible. However, 'bar' only matches keys 'bar'.

2023-02-14 21:51 UTC, dkliban commented
@mdellweg  What do you think about changing the 'labels' attribute of UpstreamPulp to 'pulp_label_select' to match the query parameter name from the REST API for distributions?

2023-02-14 21:53 UTC, dkliban commented on pulpcore/app/viewsets/replica.py
> +        )
yeah ... Multiple Pulp's should not be replicated onto the same Pulp. Only if you decide that you want to replace the repositories with this other Pulp.

2023-02-15 13:26 UTC, dkliban commented on pulpcore/app/replica.py
> +        self.app_label = None
I updated these to be class attributes. Thanks for the suggestion.

2023-02-16 14:54 UTC, mdellweg commented
> @mdellweg What do you think about changing the 'labels' attribute of UpstreamPulp to 'pulp_label_select' to match the query parameter name from the REST API for distributions?

If it follows the very same syntax, that sounds like a fine idea.

2023-02-21 19:14 UTC, ggainey requested changes

2023-02-21 19:14 UTC, ggainey commented on pulpcore/app/models/__init__.py
> +# Moved here to avoid a circular import with
"...avoid circular import with"...what?

2023-02-21 19:14 UTC, ggainey commented on pulpcore/app/models/replica.py
> +    name = models.TextField(db_index=True, unique=True)
Do we need to handle the proxy usecases here as well?

2023-02-22 11:39 UTC, mdellweg commented on pulpcore/app/migrations/0100_upstreampulp.py
> +                ('client_cert', models.TextField(null=True)),
This should be encrypted.

2023-02-22 11:50 UTC, mdellweg requested changes

2023-02-22 11:50 UTC, mdellweg commented on requirements.txt
> +pulp-glue>=0.17.1,<1.0
There is no such guarantee.
```suggestion
pulp-glue>=0.17.1,<0.18
```

2023-02-22 11:50 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        background_tasks=False,
This looks like a task is going to wait on another task. We cannot safely do this. This is the on think that can make our tasking system deadlock.

2023-02-22 12:41 UTC, mdellweg commented on pulpcore/app/migrations/0100_upstreampulp.py
> +                ('client_cert', models.TextField(null=True)),
I see the key is protected. Maybe we should add support for API tokens...

2023-02-22 12:43 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        background_tasks=False,
Is this a misconception on my side? We only use glue to question the upstream server, right? I still would feel better if we made these calls non-blocking (well they still wait on an http response, but at least not on pulp tasks.).

2023-02-22 12:47 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +def user_agent():
Where are you using this?

2023-02-22 12:54 UTC, mdellweg requested changes

2023-02-22 12:54 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +            repository = replicator.create_or_update_repository(remote=remote)
It feels like i'm missing something. Is this a blocking (waiting on another pulp task) call?

2023-02-22 12:54 UTC, mdellweg commented on pulpcore/app/replica.py
> +            repository.save()
We cannot do that if we do not have the resource reserved.

2023-02-22 12:54 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +            replicator.create_or_update_distribution(repository, distro)
This one seems fine. We dispatch a task, but we don't wait on it.

2023-02-22 12:54 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +            replicator.sync(repository)
This also seems fine.

2023-02-22 12:54 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        replicator.remove_missing(distro_names)
For this we miss all the resource locks again.

2023-02-22 13:56 UTC, dkliban commented on pulpcore/app/models/replica.py
> +    name = models.TextField(db_index=True, unique=True)
We do, but I don't think pulp-glue currently supports that. @mdellweg please correct me if I am wrong.

2023-02-22 14:01 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +        background_tasks=False,
We use pulp-glue to look up distributions and for some plugins we look up repositories and/or publications. We don't perform any tasks using pulp-glue.

2023-02-22 14:02 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +            repository = replicator.create_or_update_repository(remote=remote)
No, this is not blocking. THe current implementation only dispatches tasks for updating/creating distributions.

2023-02-23 11:41 UTC, mdellweg commented on pulpcore/app/models/replica.py
> +    name = models.TextField(db_index=True, unique=True)
We inherit the proxysupport from requests. So i guess by manipulating the environment of the process we could inject proxy information. But that is not a solution beyond a cli too.
So we should add passing proxy information to requests there.

2023-02-23 11:44 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        background_tasks=False,
I know. So we don't _ever_ make a call that will even check for this condition. Still for the sake of future us, please make it `True`, so we see immediate failures when someone starts to introduce dangerous calls.
Remember, you could configure this to replicate from itself (maybe a different domain). Having this task waiting on a pulp_task in the same box is a recipe for deadlocks.

2023-02-23 11:45 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +        replicator.remove_missing(distro_names)
But we may redo this to dispatch delete tasks.

2023-02-23 11:47 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +            repository = replicator.create_or_update_repository(remote=remote)
Yes so the issue is that we must not update an existing repository in this task, yet we cannot wait for a dispatched task to do it for us.

2023-02-23 13:14 UTC, dkliban commented on pulpcore/app/replica.py
> +            repository.save()
Yeah ... I'll refactor this  to dispatch a task.

2023-02-28 21:01 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +        background_tasks=False,
I will update it to True.

2023-02-28 21:02 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +            repository = replicator.create_or_update_repository(remote=remote)
I am going to dispatch a task for updating a repository. We don't have to wait on it because the task will have an exclusive lock on the repository which will prevent the sync task from running first.

2023-03-01 01:08 UTC, dkliban commented
@mdellweg I added tasks for remote and repository updates. I also now dispatch tasks to delete distributions.

2023-03-01 08:39 UTC, mdellweg commented on pulpcore/app/tasks/replica.py
> +            repository = replicator.create_or_update_repository(remote=remote)
Can you check that the sync task will not have the previous remote taken at "POST" time from the repository?

2023-03-01 11:53 UTC, mdellweg approved these changes

2023-03-01 11:53 UTC, mdellweg commented on pulpcore/app/replica.py
> +    def get_upstream_distributions(self, labels=None):
```suggestion
    def upstream_distributions(self, labels=None):
```
As being an iterator this can be considered to _be_ the upstream distributions.

2023-03-01 11:53 UTC, mdellweg commented on pulpcore/app/replica.py
> +            exclusive_resources=[repository],
And now i know, (again) why we cannot rely on the remote attribute of the repository in the task. It would not do the locking properly.

2023-03-01 19:19 UTC, dkliban commented on pulpcore/app/models/__init__.py
> +# Moved here to avoid a circular import with
GroupProgressReport ... i updated the comment.

2023-03-01 19:20 UTC, dkliban commented on pulpcore/app/tasks/replica.py
> +        replicator.remove_missing(distro_names)
I updated it to dispatch general_delete tasks.

2023-03-01 20:31 UTC, ggainey reviewed
I think I'm good here (modulo the discussions ongoing RE async/locking)

2023-03-01 20:31 UTC, ggainey commented on pulpcore/app/models/replica.py
> +    name = models.TextField(db_index=True, unique=True)
@mdellweg @dkliban so if I'm understanding this - if the downstream-pulp-machine is set up to use a proxy in the general case (e.g. via /etc/environments or whatever) then that gets used when talking to the upstream-pulp (and is managed externally). These validation-methods are to be used by downstream **once it's contacted upstream**, correct?

If that's so, then I'm good. Being able to "override" proxy-settings per-call becomes a nice-to-have, instead of a can't-get-there-from-here.

2023-03-01 20:43 UTC, ggainey approved these changes
Looks good to me!

2023-03-02 08:50 UTC, mdellweg commented on pulpcore/app/models/replica.py
> +    name = models.TextField(db_index=True, unique=True)
That is my assumption. But also it may not be the same syntax / semantic as glue is using requests, while remotes e.g. use aiohttp. We may still need to add better proxy support to glue. Proxy usage should be configurable per profile in the cli.

2023-03-02 14:41 UTC, merged

2023-03-09 14:28 UTC, ipanova commented on pulpcore/app/replica.py
> +    def remote_extra_fields(self, upstream_distribution):
@dkliban can you add same for distributions?

2023-03-09 14:43 UTC, dkliban commented on pulpcore/app/replica.py
> +    def remote_extra_fields(self, upstream_distribution):
yes, let's do that.