Fixed import/export in the face of Domains.
pulp/pulpcore pull request #3664
Opened 2023-03-17 19:40 UTC by ggainey

We can't export entities' domain-info.

fixes #3663.
[nocoverage]

2023-03-17 21:39 UTC, gerrod3 reviewed
Seems simple enough, but more greedily can we get a pulp_file PR with more export/import tests that properly test this.

2023-03-17 21:39 UTC, gerrod3 commented on CHANGES/3663.bugfix
> +Fixed import/export in the presence on the domains work.
Do you mean s/on/of/ ?

2023-03-17 21:39 UTC, gerrod3 commented on pulpcore/plugin/importexport.py
> +        exclude = ("pulp_domain", "pulp_id", "pulp_created", "pulp_last_updated")
Are `UserRole` and `GroupRole`s exported/imported? They are the only objects that have a domain relation that is not named pulp_domain.

2023-03-17 23:21 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +        exclude = ("pulp_domain", "pulp_id", "pulp_created", "pulp_last_updated")
They are not (very deliberately) - so we're good (so far)

2023-03-20 14:40 UTC, ggainey commented
> Seems simple enough, but more greedily can we get a pulp_file PR with more export/import tests that properly test this.

Testing the problem requires a sync, an export, and a complete db-reset before importing (because if the db you import-into contains the same default-org as the one you exported-from, you won't be testing anything at import - that's how this was missed originally). Pretty sure we *can* do so, but I wanted to get the fix out ASAP. Can you open a pulp_file issue to remind us/me to create such a test #soon?

2023-03-21 10:16 UTC, mdellweg reviewed
Do we need to / can we exclude "_pulp_domain" for all the content exported, too?

2023-03-21 12:30 UTC, ggainey commented
> Can we mark db fields to exclude exportation on the models where we define them? (Just a crazy thought.)

The models know nothing about import/export, and I'd like to keep it that way.

2023-03-21 12:30 UTC, ggainey commented
> Do we need to / can we exclude "_pulp_domain" for all the content exported, too?

We can - but I don't see that anywhere. Where does it show up as a field?

2023-03-21 13:55 UTC, ggainey commented
> This field is going to be present on every child Content model, it's the field they will use for changing their `unique_together`. pulp_file example: https://github.com/pulp/pulp_file/blob/main/pulp_file/app/models.py#L41

Ah! I missed that. Yeah, will do.

2023-03-22 14:39 UTC, mdellweg requested changes

2023-03-22 14:39 UTC, mdellweg commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
Maybe i'm mistaken. But row is what we get from the file imported, right? So as far as i understand this should never include the domain. So should the check not be somthing like:
`if hasattr(self.model, "_pulp_domain")`?

Should we account for `__pulp_domain` too in case we have content that is subclassed multiple times?

2023-03-22 14:39 UTC, mdellweg commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
Also would it not be a good idea to populate `pulp_domain` on all models that have it too?

Whould this maybe _just_ make import export domains compatible?

2023-03-22 14:42 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
> Should we account for `__pulp_domain` too in case we have content that is subclassed multiple times?

It *has to* inclulde _pulp_domain, because that's become part of the natural-key of content. So it has to be exported, and then replaced on-import with the approapriate domain we're importing-into.

2023-03-22 14:46 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
> Also would it not be a good idea to populate `pulp_domain` on all models that have it too?
> 
> Whould this maybe _just_ make import export domains compatible?

That's a good question, `pulp_domain` (as opposed to `_pulp_domain`) lives in Artifact and Content.  @gerrod3 , what happoens w/ artifact/content is pulp_domain isn't specified?

2023-03-22 14:52 UTC, mdellweg commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
We don't export across domains, right? All repos of one export need to be in the same domain.

2023-03-22 14:52 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
See https://docs.pulpproject.org/pulpcore/plugin_dev/plugin-writer/concepts/domains/domains_compatibility.html#add-domain-relation-to-plugin-models - I read that as "you only add _pulp_domain if you subclass directly from Content"

2023-03-22 14:57 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
> We don't export across domains, right? All repos of one export need to be in the same domain.

One could *export* across-domains - but one *imports* into a single domain. What we're doing/have to do here, is replace whatever domain-uuid the exported content has/with the appropriate "current" domain on import.

The reason we choose to export a domain-field that we're just going to replace, is to make it so the import side doesn't have to make any decisions around "should I add a current-domain UUID into every row" - if the field exists, replace it, otherwise skip.

Currently in this PR we're "getting away with" not-exporting "pulp_domain" from the modelresources that carry it, but I'm thinking we probably want to do this replacement to that field (if at exists) as well. @gerrod3 , wdyt?

2023-03-22 15:05 UTC, mdellweg commented on pulpcore/plugin/importexport.py
> +            row["_pulp_domain"] = get_domain_pk()
I mean, a single export can only include repositories of one domain, no? And the import of it goes into a single (maybe different) domain, also. I believe that is what we agree on.
So if we could make sure, the domain_field will never make it into an exported file, will pulp not populate that field automatically with `current_domain_pk`? Maybe that is too late for finding existing entities.
To me the logic is still: Does my model have a pulp_domain field? Then i need to populate it on import.

2023-03-22 15:10 UTC, ggainey commented
pulp_rpm and pulp_ansible override before_import_row(), without calling super(). We have to fix that, for this to work.

I'm going to Draft this PR while I consider.

2023-03-22 20:20 UTC, ggainey commented
Commentary from another discussion w/ @gerrod3 : we need to add `pulp_domain` to the **import-id-fields** of Artifact and Repository to get them to behave correctly, at import-time, in the face of multiple domains.

2023-03-22 21:29 UTC, ggainey commented
OK, this incarnation appears to do the deed. More eyes please, folks.

2023-03-23 10:40 UTC, mdellweg approved these changes

2023-03-23 14:02 UTC, merged