Reworked the task purge feature
pulp/pulpcore pull request #3709
Opened 2023-04-05 10:08 UTC by MichalPysik

When an object could not be deleted, the purge task would fail. This has been reworked  so that the purge continues to delete other tasks and informs the user about tasks that could not be deleted.

noissue

2023-04-14 12:16 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +                print(f"Details of the object: {e.protected_objects}")
It's either logging or adding to a progress report, but never print.

2023-04-14 13:10 UTC, MichalPysik commented on pulpcore/app/tasks/purge.py
> +                print(f"Details of the object: {e.protected_objects}")
It was somewhat of a placeholder, I'm currently working on real solution that incorporates both logging and a new progress report for objects that couldn't be deleted

2023-04-14 14:08 UTC, MichalPysik commented on pulpcore/app/tasks/purge.py
> +                log.info(e)
This should really be sufficient, I initially wanted to parse the exception manually but it's quite painful and the default text seems okay to me.

2023-04-14 14:16 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +        message=_("Failed to purge task-objects"),
"Tasks failed to purge" sounds better do me.

2023-04-14 14:18 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +                log.info(e)
Can we please keep the bulk delete and only do one-by-one as a fallback?

2023-04-19 07:18 UTC, mdellweg requested changes

2023-04-19 07:18 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +            # loop though the candidate objects and delete them one-by-one
```suggestion
            # loop through the candidate objects and delete them one-by-one
```

2023-04-19 07:18 UTC, mdellweg commented on pulpcore/app/tasks/purge.py
> +        units_deleted = 0
That logic does not work. If you failed to delete the whole batch, there may still be tasks left.
Can we rewrite this to use a batch iterator?

2023-04-20 11:33 UTC, mdellweg commented on CHANGES/3530.bugfix
> +Task purge now continues when encountering a task that could not be deleted. The user is informed about any such tasks.
Please line wrap this at 98 characters.

2023-04-21 21:34 UTC, dralley approved these changes

2023-04-26 08:28 UTC, mdellweg approved these changes

2023-04-26 08:28 UTC, merged