Redirects user to a path that ends in /
pulp/pulpcore pull request #3795
Opened 2023-05-04 17:14 UTC by mdellweg

This patch returns a 301 redirect when a requested path does not end in a / but should end in a /.

Changes the order in which pulpcore-content looks for published artifacts The handler now looks for a published artifact before it tries to look for an index.html or listing the directory.

fixes: #3173
fixes: #3459

2023-05-04 18:20 UTC, mdellweg commented
Is this in any way close to what was requested on those two issues?
(I'm a bit lost on what behaviour should be opted in/out).

2023-05-04 20:32 UTC, daviddavis commented on CHANGES/plugin_api/3459.feature
> +Added a flag `REDIRECT_ON_MISSING_SLASH` for plugin distrubution models to opt out of automatic
```suggestion
Added a flag `REDIRECT_ON_MISSING_SLASH` for plugin distribution models to opt out of automatic
```

2023-05-04 20:33 UTC, daviddavis commented
> Is this in any way close to what was requested on those two issues?
> (I'm a bit lost on what behaviour should be opted in/out).

I believe it is. I think the behavior is supposed to be opt-out.

2023-05-08 17:38 UTC, bmbouter commented
> I believe it is. I think the behavior is supposed to be opt-out.

The default today is enabled-for-all right? If so, +1 to opt-out.

2023-05-08 17:39 UTC, bmbouter commented on CHANGES/plugin_api/3459.removal
> +where this is in appropriate.
```suggestion
where this is inappropriate.
```

2023-05-08 17:39 UTC, bmbouter commented on CHANGES/plugin_api/3459.feature
> +Added a flag `REDIRECT_ON_MISSING_SLASH` for plugin distribution models to opt out of automatic
```suggestion
Added a flag ``REDIRECT_ON_MISSING_SLASH`` for plugin distribution models to opt out of automatic
```

2023-05-08 17:39 UTC, bmbouter commented on CHANGES/plugin_api/3459.removal
> +A plugin must set `REDIRECT_ON_MISSING_SLASH=False` on distribution models for content types
```suggestion
A plugin must set ``REDIRECT_ON_MISSING_SLASH=False`` on distribution models for content types
```

2023-05-08 17:39 UTC, bmbouter commented on CHANGES/plugin_api/3459.removal
> +Starting with this release, pulpcore will default to redirect clients of the content app when
Didn't it do this before?

2023-05-08 17:40 UTC, bmbouter commented on pulpcore/app/models/publication.py
> +    REDIRECT_ON_MISSING_SLASH = True
Maybe the plugin writer guide should get a 1 paragraph on this? (this is an optional idea)

2023-05-08 17:40 UTC, daviddavis commented
> The default today is enabled-for-all right? If so, +1 to opt-out.

I think the original change (to redirect slash-less index paths to slash paths) was enabled-for-all but was reverted because it caused issues for pulp_container. So this new change would enable it for all except those that opt out.

2023-05-08 17:42 UTC, daviddavis commented on CHANGES/plugin_api/3459.removal
> +Starting with this release, pulpcore will default to redirect clients of the content app when
No, it was reverted in https://github.com/pulp/pulpcore/pull/3465 because the behavior broke pulp_container.

2023-05-08 17:42 UTC, bmbouter commented
I'm not feeling confident enough to review the code so I'm avoiding being the formal review. Let's see if we can get reviewers at tomorrow's pulpcore meeting. If we often can't find enough reviewers maybe we should adjust the review required count from 2 to 1.

2023-05-08 17:43 UTC, daviddavis commented on CHANGES/plugin_api/3459.removal
> +Starting with this release, pulpcore will default to redirect clients of the content app when
Or I guess it might've been pulp_python? Maybe @gerrod3 knows.

2023-05-08 17:44 UTC, daviddavis commented
> 
I'm not feeling confident enough to review the code so I'm avoiding being the formal review. Let's see if we can get reviewers at tomorrow's pulpcore meeting. If we often can't find enough reviewers maybe we should adjust the review required count from 2 to 1.

FWIW, I worked with @dkliban on this change and from a high level it looks good to me. I can't speak to things like performance though.

2023-05-08 23:26 UTC, dralley commented on CHANGES/3173.feature
> +Content app now redirects requests without a trailing slash to a path with the trailing slash.
By default

2023-05-09 04:44 UTC, dralley approved these changes

2023-05-09 07:27 UTC, mdellweg commented on CHANGES/3173.feature
> +Content app now redirects requests without a trailing slash to a path with the trailing slash.
I'm not sure this would be helpful. For the users perspective, pulpcore is just doing it. They cannot configure it. It's just certain content types that don't want it in their distribution paths.

2023-05-09 09:46 UTC, gerrod3 requested changes
This can not be merged in its current state. I'm thinking we should try the refactor first before making changes as the behavior will be easier to follow.

2023-05-09 09:46 UTC, gerrod3 commented on pulpcore/content/handler.py
> +                raise ObjectDoesNotExist(request.path)
Is this the right exception? This looks like a Django exception, so wouldn't this report a 500 error if it got raised?

2023-05-09 09:46 UTC, gerrod3 commented on pulpcore/content/handler.py
> +                    raise
Have you tested this to see what the response is when a bad path is given?

2023-05-09 09:46 UTC, gerrod3 commented on pulpcore/content/handler.py
>                  index_path = "{}index.html".format(rel_path)
This is part of the reason for the refactor I am doing. All of this new logic has to be repeated twice for distro's serving repository versions.

2023-05-09 09:46 UTC, gerrod3 commented on pulpcore/content/handler.py
> +                await publication.published_artifact.aget(relative_path=index_path)
BTW, moving this logic downward has probably broke the normal behavior for plugins that create their own index.html pages in a publication. We don't use the result from this `aget` we just check if it exists and then the logic from L585-L599 would actually serve the artifact. Moving this down will break current functionality. (We don't see breaks in tests probably because pulp_file uses the dynamic generated listing.)

2023-08-22 13:24 UTC, closed without merging