Vendor the aiohttp instrumentation code and add it to the aiohttp middleware list
pulp/pulpcore pull request #3828
Opened 2023-05-15 14:52 UTC by decko

[noissue]

2023-05-15 15:39 UTC, bmbouter commented
Can a feature be filed for this and a user facing release note added associated with that feature also please? Thanks!

2023-05-15 20:13 UTC, bmbouter commented on CHANGES/3829.misc
> +Adds a vendor version of the OpenTelemetry Aiohttp-server instrumentor to instrument pulp-content app.
Can we put this into user terms? I think that would be `3829.feature` and it would add open telemetry support for the pulp-content app.

2023-05-15 20:30 UTC, bmbouter approved these changes
This looks great to me! I agree with vendoring this given the upstream timeline does not seem on the order of days or maybe even weeks.

2023-05-15 20:35 UTC, ggainey approved these changes
Looks good, I'm good w/ us carrying until it appears in an upstream release.

2023-05-15 20:35 UTC, ggainey commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
:+1:

2023-05-16 07:28 UTC, lubosmj commented on CHANGES/3829.feature
> +Add OpenTelemetry support and enable pulp-content app tracing and metrics.
```suggestion
Implemented OpenTelemetry support and enabled tracing and metrics for the pulp-content app.
```

2023-05-16 10:07 UTC, ipanova requested changes
Apologies for bringing in last minutes changes requests, but would it be possible to add docs? This is an important feature pulp is adding and users will not see it a word about it except for this one liner changelog. 
Can at least a docs paragraph be added? In a similar fashion we have mentions about analytics https://github.com/pulp/pulpcore/blob/main/docs/components.rst#analytics-collection

2023-05-16 12:08 UTC, mdellweg commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
Let's be honest. Instead of calling this an effective copy of a PR (that may or may not be accepted in the current state), let's own this code, make it officialy a part of Pulp and talk about upstreaming it from there.

2023-05-16 12:09 UTC, mdellweg requested changes
Can this work be tested in any reasonable way?

2023-05-16 14:35 UTC, decko commented
> Can this work be tested in any reasonable way?

If you're talking about the instrumentation code we have it on the upstream package. I couldn't see a reason to vendor the tests too.
If you're talking about our instance of the aiohttp-server I've found no tests for the authentication middleware or any kind of test that test those pieces together.

Would make sense to have tests for it?

2023-05-16 16:20 UTC, decko commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
I don't think it's possible @mdellweg since we're only part of the authors of that code.

2023-05-16 16:21 UTC, decko commented on CHANGES/3829.feature
> +Add OpenTelemetry support and enable pulp-content app tracing and metrics.
Thanks for the suggestion @lubosmj. Way better this way

2023-05-16 16:51 UTC, bmbouter commented
> > Can this work be tested in any reasonable way?
> 
> If you're talking about the instrumentation code we have it on the upstream package. I couldn't see a reason to vendor the tests too. If you're talking about our instance of the aiohttp-server I've found no tests for the authentication middleware or any kind of test that test those pieces together.
> 
> Would make sense to have tests for it?

I agree with this. This isn't really Pulp code, it's just being included here so we can start using it because the upstream is very slow to respond. Given that the only actual Pulp part is the part enabling it. We'd add tests here just to then remove them when we remove it in favor of the upstream release also.

2023-05-16 17:38 UTC, decko commented
> Apologies for bringing in last minutes changes requests, but would it be possible to add docs? This is an important feature pulp is adding and users will not see it a word about it except for this one liner changelog. Can at least a docs paragraph be added? In a similar fashion we have mentions about analytics https://github.com/pulp/pulpcore/blob/main/docs/components.rst#analytics-collection

I "drafted" a first version of it @ipanova. Can you check and left more suggestions?

2023-05-16 18:13 UTC, bmbouter commented on CHANGES/3829.feature
> +Implemented OpenTelemetry support and enabled tracing and metrics for the pulp-content app.
An additional release note can be added indicating that the docs for open telemetry configuration were added. This can be in the file `CHANGES/3829.doc`.

2023-05-16 18:23 UTC, decko commented on CHANGES/3829.feature
> +Implemented OpenTelemetry support and enabled tracing and metrics for the pulp-content app.
Done

2023-05-16 18:29 UTC, bmbouter commented on docs/components.rst
> +New Pulp installations can obtain telemetry data, like the number of requests, active connections and latency response for both `pulp-api` and `pulp-content` using OpenTelemetry. You can read more ab
```suggestion
Pulp can produces OpenTelemetry data, like the number of requests, active connections and latency response for both `pulp-api` and `pulp-content` using OpenTelemetry. You can read more about `OpenTelemetry here <https://opentelemetry.io>`_.
```

These docs should also be line wrapped at 100 chars.

2023-05-16 18:31 UTC, bmbouter commented on docs/components.rst
> +* ``PULP_OTEL_ENABLED`` set to ``True``.
I think this needs to become it's own paragraph expanding on it. What this actually does is run the workers with a different prefix so these docs should give an example of running `pulp-api` and `pulp-content` with and without open telemetry support. Then after explaining that we can state that the `pulp-oci-images` automatically handles that if the `PULP_OTEL_ENABLED` is set.

2023-05-17 05:10 UTC, dralley commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
Make sure that if the license requires a copyright / license notice in copies of the code, that we're complying with that.

2023-05-17 05:15 UTC, dralley commented on pulpcore/content/instrumentation.py
> +    """TODO: is this useful??"""
I assume this is awaiting comment on the upstream PR side?

2023-05-17 07:02 UTC, mdellweg commented
> > > Can this work be tested in any reasonable way?
> > 
> > 
> > If you're talking about the instrumentation code we have it on the upstream package. I couldn't see a reason to vendor the tests too. If you're talking about our instance of the aiohttp-server I've found no tests for the authentication middleware or any kind of test that test those pieces together.
> > Would make sense to have tests for it?
> 
> I agree with this. This isn't really Pulp code, it's just being included here so we can start using it because the upstream is very slow to respond. Given that the only actual Pulp part is the part enabling it. We'd add tests here just to then remove them when we remove it in favor of the upstream release also.

Well, it is surely not upstream code. Hence my ask to really own it here. If we do not make it Pulp code, it's nobody's code. Whatever may or may not be merged upstream eventually, nobody can say. And what is not tested, must be considered broken. Adding all of this to pulp is supposed to generate some side effects. If those are not observable, it's not a feature. Maybe for clarification, I am talking about pulp tests, not unittests for the otel library. However, the latter should also come with the code.

2023-05-17 08:44 UTC, mdellweg commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
I should probably elaborate: With owning i don't mean claiming the authorship, but taking the responsibility.

2023-05-17 13:23 UTC, bmbouter commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
re licensing: it's unmerged upstream so I think it's actually not even licensed. When it is merged the upstream will be apache V2.

re owning it: we are owning it since we're contributing it upstream and the vendored version here. The thing I'm trying to avoid is to have it adhere to the standards of the Pulp community when it's actual destination is a contribution to the open-telemetry community which has different standards, norms, and expectations. If there's an issue though, I expect we'll fix that both here and in the upstream for example.

2023-05-17 13:46 UTC, mdellweg commented on pulpcore/content/instrumentation.py
> +# gets merged into opentelemetry-python-contrib
re licensing: It's easy then. The original contribution, which we adopt here, was made under the Apache V2 license. So it is that one.

2023-05-17 14:43 UTC, decko commented on docs/components.rst
> +New Pulp installations can obtain telemetry data, like the number of requests, active connections and latency response for both `pulp-api` and `pulp-content` using OpenTelemetry. You can read more ab
Done

2023-05-17 15:47 UTC, ipanova commented on CHANGES/3829.doc
> +Adds the Telemetry section to the docs with information about OpenTelemetry and its usage on Pulp.
added. keep it past simple

2023-05-17 15:47 UTC, ipanova commented on docs/components.rst
> +Pulp can produces OpenTelemetry data, like the number of requests, active connections and latency response for
s/like/such as

2023-05-17 15:47 UTC, ipanova commented on docs/components.rst
> +* ``PULP_OTEL_ENABLED`` set to ``True``.
@bmbouter is it pulp-oci-images that handles this automatically? that means not only single container  but also operator should be well set here too as well.

2023-05-17 15:47 UTC, ipanova commented on docs/components.rst
> +Pulp can produces OpenTelemetry data, like the number of requests, active connections and latency response for
Pulp can produce

2023-05-17 16:21 UTC, bmbouter commented
@ipanova yes it's pulp-oci-images that does it [with this](https://github.com/pulp/pulp-oci-images/commit/2976e33e442bd987d6f2c75eb46a456431fcde91). I also expect that to work correctly for the operator too.

2023-05-21 17:39 UTC, decko commented
> Given that there is not an agreement on the testing requirements for this code, I think we should split the docs into their own PR.
> 
> This PR was designed to save time for the upstream to accept and release the work. I believe if we need to write tests also here it will take more time than it saves. We can just let the upstream contribution process work it out and close this PR.

I'm closing this PR until further decision about how we should deal with this kind of situation.
And I'm opening another PR just for the documentation.

2023-05-21 17:39 UTC, closed without merging

2023-05-22 09:13 UTC, mdellweg commented
> If you're talking about our instance of the aiohttp-server I've found no tests for the authentication middleware or any kind of test that test those pieces together.

We do test the authentication middleware, because it's purpose is to set the `user` attribute on the `request` object. We test the domain middleware, because without the domain set, pulp would not work properly. So I read that the otel middleware is supposed to generate some data that is to be collected somewhere. Why is it so hard to assert that this happens according to some expectations?

> This PR was designed to save time for the upstream to accept and release the work. I believe if we need to write tests also here it will take more time than it saves. We can just let the upstream contribution process work it out and close this PR.

If closing this PR was meant to prevent writing any tests at all, I must still say functional test that read like a specification for what kind of collected data we expect are still a requirement in my not so humble opinion.

2023-05-23 13:46 UTC, bmbouter commented
This is a different situation from those examples. In those examples the features provided by dependencies are consumed by Pulp and because of that they are able to be asserted on via the Pulp APIs. In this case this feature is offered from the opentelemetry dependency and consumed directly by the user. There is no Pulp API that we can actually make an API assertion on.

That's "why its so hard". There isn't a Pulp API that we can call to intercept this data. We'd be spending time and effort adding this capability to the CI and then assertions to a component other than Pulp. Additionally, consider that we are only temporarily carrying this code until it's available upstream. That info together means we'd be doing a lot of work just to throw it away, and that isn't something we can afford to do.

My ask is the same as it was. Think over my claim that this is not "pulp code".  Allow this code to be temporarily carried as-is, and let the actual test contribution happen upstream. [That PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1800/files) does have tests. This is the #1 request from a large upstream user and I'd like us to let them test it prior to the upstream accept + release timeline.