Extensions to give plugins a chance to set specific content-headers.
pulp/pulpcore pull request #3893
Opened 2023-05-31 17:34 UTC by ggainey

Added Distribution.content_headers_for() and call it from inside Handler.response_headers().

This is in support of https://github.com/pulp/pulp_rpm/issues/2947

[noissue]

2023-05-31 17:36 UTC, ggainey commented on pulpcore/app/models/publication.py
> +    def content_headers_for(self, path):
Distribution "feels like" the right place to know-things about specific files being served.

2023-06-01 12:07 UTC, mdellweg commented on pulpcore/content/handler.py
> +            distribution(Distribution) : Disitrbution detail that might want to add headers for path
```suggestion
            distribution(Distribution) : Distribution detail that might want to add headers for path
```

2023-06-01 12:12 UTC, mdellweg commented on pulpcore/content/handler.py
> +        headers = self.response_headers(rel_path, distro)
Are the headers supposed to be dependent on the content identified?
If `content_handler_result` was populated from the plugin 3 lines up, do we expect the headers to be there already?

2023-06-01 12:19 UTC, ggainey commented on pulpcore/content/handler.py
> +        headers = self.response_headers(rel_path, distro)
Yes - look at the issue, the specific problem is "repomd.xml needs to not-cache". Headers specific to specific files is pretty common (and if you want to set them for Everything, you do that in the webserver configs)

content_handler_result is the output of the current protocol, where the handler says "if you give me a result back I am not touching it - you (the plugin) did what needed doing". I would actually have preferred to do this "inside" that existing protocol, but there wasn't any way to take advantage of all of the machinery that happens next without just doing a giant copy/paste into the plugin.

conten-handling needs a serious refactor - but this ask isn't the place to do it.

2023-06-03 16:57 UTC, mdellweg commented on CHANGES/3897.feature
> +Added Distribution.content_headers-for() to let plugins affect content-app responses.
I think this belongs in CHANGES/plugin ...

2023-06-05 06:26 UTC, dralley commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
Do we need to be concerned with casing?

2023-06-05 06:28 UTC, dralley approved these changes
This is fairly reasonable - I agree that we need to overhaul content serving completely but yes, that's out of scope.

2023-06-05 07:58 UTC, mdellweg commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
Assuming, you meant casting, it is already the detail model:
https://github.com/pulp/pulpcore/pull/3893/files#diff-453fdf3a6e81f92ff5391cf65f9c6154852133a656d82082021e3beaa887776fR300

2023-06-05 11:08 UTC, dralley commented
No casing as in lowercase.  Updating sets with potentially different-but-the-same keys.

2023-06-05 12:05 UTC, ggainey commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
This is a good point, that also uncovers "what if the Distribution wants to return Content-Type"? Let me make some adjustments here.

2023-06-05 14:44 UTC, dralley commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
Copying my comment since github mobile put it in the wrong place:

> No casing as in lowercase. Updating sets with potentially different-but-the-same keys.

2023-06-06 12:18 UTC, ipanova commented on pulpcore/content/handler.py
> +        headers = self.response_headers(rel_path, distro)
What about this code path? https://github.com/pulp/pulpcore/blob/a18d5b861011de33b7305a22d267e8f32e48f350/pulpcore/content/handler.py#L578

2023-06-06 12:44 UTC, ipanova commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
HTTP headers names are case insensitive, aiohttps responses like File/StreamResponse use CIMultiDict which take care exactly of this problem so we can just ignore this.
The only problematic place I see is here https://github.com/pulp/pulpcore/blob/main/pulpcore/content/handler.py#L869. We could just CIMultiDict instead of casefolding.

2023-06-06 12:45 UTC, ipanova commented on pulpcore/content/handler.py
> +            headers.update(distribution.content_headers_for(path))
```
In [1]: from multidict import CIMultiDict

In [2]: x=CIMultiDict()

In [3]: x['Ina']=1

In [4]: x['ina']=2

In [5]: x
Out[5]: <CIMultiDict('ina': 2)>

```

2023-06-06 13:19 UTC, ipanova requested changes
please check my comments :)

2023-06-08 15:54 UTC, ggainey commented on pulpcore/content/handler.py
> +        headers = self.response_headers(rel_path, distro)
That's the "get  index.html" (only) path; I guess I "assumed" nobody would care about it. You are correct, tho, there's no reason to **prevent** a plugin from having some control there as well.

2023-06-08 17:50 UTC, ipanova approved these changes

2023-06-08 17:57 UTC, ipanova requested changes
per our matrix chat we've decided to use `CIMultiDict`

2023-06-13 11:04 UTC, ipanova approved these changes

2023-06-13 11:06 UTC, merged