Add version information to tasks
pulp/pulpcore pull request #3930
Opened 2023-06-16 15:27 UTC by mdellweg

Workers will refuse to pick up a task caliming a version of a plugin to be higher than their own. The corresponding plugin an it's version will be inferred from the task import path, unless the task function provides a __versions__ attribute.

fixes #3369

2023-07-04 14:55 UTC, MichalPysik commented on CHANGES/3369.feature
> +than their own.
```suggestion
Added version information to tasks. Workers will refuse to pick up tasks with a version higher
than their own.
```

2023-07-10 15:32 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_tasking.py
> +    task_href = dispatch_task("pulpcore.app.tasks.test.sleep", args=(0,))
Interestingly we are losing the ability to run outside python functions as tasks with this change. Are we sure that no plugin has been using this behavior already? (I think this is a better design and we should only allow running pulpcore/plugin code)

2023-07-10 16:33 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    task_href = dispatch_task("pulpcore.app.tasks.test.sleep", args=(0,))
Yes, I agree, we never made any such statement. But i'd be happy to call it undefined behaviour. Back in the days celery tasks needed to be decorated, and i think that is not the worst design. Actually I would want to be even much stricter about what a task can be. But that is for another day. (sneak preview: https://github.com/pulp/pulpcore/pull/3997)

2023-07-11 13:57 UTC, gerrod3 approved these changes

2023-07-11 18:54 UTC, ggainey commented
Would it be desirable for the tasking-system to recognize that none of the available tasks can be picked up due to version-incompatibility and log warnings?

Is there any way to have a test-case that places an incompatible-task-entry into the queue and then sees it not-get-picked-up?

2023-07-11 19:28 UTC, mdellweg commented
> Would it be desirable for the tasking-system to recognize that none of the available tasks can be picked up due to version-incompatibility and log warnings?

The distributed nature of the tasking system makes it kind of hard (without a lot of overhead including db queries) to identify that no available worker is compatible with the task at hand. Do we want that? This change is designed to help prevent bad to happen in a system that does rolling upgrades. So is suspect that the moment you spin up a new api worker you probable spin up a new worker too (maybe in the same container). And when you don't, you are in a half upgraded system and expect some quirks. It's not that the system is in an undefined state. The task will be picked up once at least one sufficiently recent worker is started.

> 
> Is there any way to have a test-case that places an incompatible-task-entry into the queue and then sees it not-get-picked-up?

Possibly. Not quite sure if we want that. The CI would probably not care that there will be a task waiting forever. Other development systems, idk.

2023-07-12 10:11 UTC, mdellweg commented
I added a test, and also changed the semantics a little bit. A worker is now still able to cancel a task even if the versions are not met. I believe this is necessary to be able to clean up e.g. when an upgrade needed rollback or a plugin was removed.

@gerrod3 you may want to take a second look.

2023-07-12 11:59 UTC, decko commented on pulpcore/tasking/pulpcore_worker.py
> +            _logger.info(
What about using a `_logger.warn` here?

2023-07-12 12:00 UTC, decko approved these changes

2023-07-12 12:02 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +            _logger.info(
I had it warn first but wasn't sure. In case of an ongoing rolling upgrade this can get quite verbose. I was even thinking about debug.
We have conflicting suggestions here:
@ggainey > "I'd make it INFO. We def want to leave traces - esp if/when the task-queue is full of nothing but New Tasks but the only workers running are running Olde Code"

2023-07-12 13:01 UTC, ggainey approved these changes

2023-07-12 13:38 UTC, gerrod3 requested changes

2023-07-12 13:38 UTC, gerrod3 commented on pulpcore/tasking/pulpcore_worker.py
> +            f"task: {label}>={version} worker: {self.versions.get(label)}"
```suggestion
            f"task: {label}>={version} worker: {self.versions.get(label, 'None')}"
```

2023-07-12 13:38 UTC, gerrod3 commented on pulpcore/tasking/pulpcore_worker.py
> +            or parse_version(self.versions[label]) < parse_version(version)
I am not sure about this condition check. I think it should be `!=`. Maybe if plugin writers passed in the min required version for their tasks then we could use the this check, but if this is filled out by default we have no guarantee that a plugin's task is compatible with its previous version.

2023-07-12 14:04 UTC, ggainey commented on pulpcore/tasking/pulpcore_worker.py
> +            or parse_version(self.versions[label]) < parse_version(version)
Then we'd basically be saying "you have to cancel all waiting tasks when you upgrade". A task can't declare future-compatibility, so by definition every time you update core or a plugin, existing tasks could never be handled.

Example: I have 200 waiting tasks issued by core/3.25. I upgrade to core/3.28. Using '!=' means now nothing can ever pick up those tasks.

zero-downtime-upgrade requires that new-task-code continue to be able to handle old-tasks; if we can't do that, we can't have ZDU.

2023-07-12 14:40 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +            f"task: {label}>={version} worker: {self.versions.get(label)}"
Can you elaborate? My experiment (and it is part of the tests too) is that the stringinterpolation works just fine here.

2023-07-12 14:42 UTC, mdellweg commented on pulpcore/tasking/pulpcore_worker.py
> +            or parse_version(self.versions[label]) < parse_version(version)
No, the rule is whenever a worker has a version greater or equal than the api dispatching the task, it needs to be able to handle it. You cannot assume there will be an old worker around to handle all the old tasks.
We have that rule already. Plugins must always be able to handle old tasks. This is not even ZDU related.

2023-07-12 14:47 UTC, gerrod3 commented on pulpcore/tasking/pulpcore_worker.py
> +            f"task: {label}>={version} worker: {self.versions.get(label)}"
Actually I don't think this is needed after checking the string interpolation. `f"{None}" == "None"`.

2023-07-12 14:50 UTC, gerrod3 commented on pulpcore/tasking/pulpcore_worker.py
> +            or parse_version(self.versions[label]) < parse_version(version)
Very well then, I guess this is a requirement I need to be cognizant of when reviewing plugin code as I was not aware of this before.

2023-07-12 14:51 UTC, gerrod3 approved these changes

2023-07-12 14:59 UTC, merged