Taught FileDownloader to correctly handle on-demand remotes.
pulp/pulpcore pull request #4031
Opened 2023-07-12 21:02 UTC by ggainey

fixes #4109.

2023-07-12 21:02 UTC, ggainey commented
Needs a test, getting it up to get some clean test runs and more eyes.

2023-07-13 08:55 UTC, mdellweg commented on pulpcore/download/file.py
> +            self.headers_ready_callback = kwargs.get("headers_ready_callback")
It looks like it's perfectly safe to have `headers_ready_callback==None` (also `get` defaults to `None` anyway).
```suggestion
        self.headers_ready_callback = kwargs.get("headers_ready_callback")
```

2023-07-25 13:53 UTC, ggainey commented
Status: writing a test discovered that there is more work to be done.

2023-08-08 18:26 UTC, ggainey commented on pulpcore/download/file.py
> +            self.headers_ready_callback = kwargs.get("headers_ready_callback")
That code turned out to not be the actual issue (alas)

2023-08-09 11:11 UTC, mdellweg requested changes

2023-08-09 11:11 UTC, mdellweg commented on pulpcore/content/handler.py
> +                await response.prepare(request)
The result of preparing a request is that you cannot add headers anymore (as far as I remember).
Is handle_response_headers not executed in the use case you are fixing here? Or is there a chance it didn't finish yet?
Can we use a `asyncio.Event` to make this function wait until it is set by `handle_response_headers` after the `prepare` call?

2023-08-09 12:43 UTC, ggainey commented on pulpcore/content/handler.py
> +                await response.prepare(request)
The path for returning an on-demand artifact, from a file: entity, through the content-app, is tortuous. handle_response_headers never gets invoked. If you've gotten to handle_data(), the content-app "assumes" prepare() has completed. If you are in this call, you're about to start writing, and will fail if prepare() hasn't happened.

This change makes it at least possible to serve on_demand file: artifacts. A better answer would be rearchitecting/rewriting the content-app to not be a mass of barbed wire - but fixing this use-case isn't the place for that.

2023-08-09 13:53 UTC, mdellweg commented on pulpcore/content/handler.py
> +                await response.prepare(request)
OK, I understand now. This is the `FileDownloader` not even knowing about `headers_ready_callback` and therefore never bothering to call it. With the `HttpDownloader` on the other hand, we can always assume that `headers_ready_callback` is awaited before `handle_data` is ever invoked.
Please leave a description like this in a comment there.

2023-08-10 10:17 UTC, mdellweg requested changes

2023-08-10 10:17 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_content_access.py
> +)
Please don't use pulp-smash.
There's a `file_distribution_factory` for this.

2023-08-10 20:26 UTC, mdellweg approved these changes

2023-08-14 18:36 UTC, dkliban approved these changes

2023-08-14 18:37 UTC, merged