Fixes a bug in the Upstream Pulp Replicate API
pulp/pulpcore pull request #4120
Opened 2023-07-24 17:28 UTC by dkliban

This bug was only present when domains were enabled.

fixes: #4119

2023-07-24 18:31 UTC, ipanova approved these changes

2023-07-24 18:39 UTC, ipanova commented
any versions we want to backport this to?

2023-07-25 01:40 UTC, dkliban commented
we should backport to 3.23, 3.28, 3.29

2023-07-25 01:42 UTC, dkliban commented
I added a test and that required fixing another bug as part of the same PR.

2023-07-25 05:58 UTC, mdellweg requested changes

2023-07-25 05:58 UTC, mdellweg commented on pulpcore/tests/functional/__init__.py
> +def non_default_domain(domains_api_client, pulp_settings, gen_object_with_cleanup):
Why don't we make this a domain_factory right away?

2023-07-25 05:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_replication.py
> +    response = upstream_pulp_api_client.replicate(upstream_pulp.pulp_href)
So this is really the first time we sync from one pulp into itself, right?

2023-07-25 12:23 UTC, dkliban commented on pulpcore/tests/functional/__init__.py
> +def non_default_domain(domains_api_client, pulp_settings, gen_object_with_cleanup):
i was going to convert it on my next PR, but I'll do it now.

2023-07-25 12:23 UTC, dkliban commented on pulpcore/tests/functional/api/test_replication.py
> +    response = upstream_pulp_api_client.replicate(upstream_pulp.pulp_href)
yes, i believe so.

2023-07-25 12:40 UTC, mdellweg approved these changes

2023-07-25 13:12 UTC, merged