Taught import to throttle at 25% of available workers.
pulp/pulpcore pull request #4160
Opened 2023-07-26 20:08 UTC by ggainey

When we expose  IMPORT_WORKERS_PERCENT, this becomes a configurable percentage.

fixes #4068.

2023-07-26 20:09 UTC, ggainey commented
Tested and works. In draft because I want some eyes on this before we decide it's the Right Way to go.

Note that we are separating this from actually adding IMPORT_WORKERS_PERCENT to settings.py to facilitate backporting the actual fix, from the Y-version of "added a config-option".

2023-07-26 23:25 UTC, dralley commented
>Tested and works. In draft because I want some eyes on this before we decide it's the Right Way to go.

If we can provide it as a hotfix for the one user that really needs it, we can take a bit more time with choosing the correct approach.  Since the first import is obviously the biggest and most problematic, they should be freed up once they're through it.

2023-07-27 10:55 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +        import_workers_percent = int(settings.get("IMPORT_WORKERS_PERCENT", 25))
This _is_ adding it as a setting.
Also i was wondering if we should add it to the import viewset so you can make the admin (only persona to use imports) decide on a case by case basis.

2023-07-27 11:00 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                worker_rsrc = f"import-worker-{index % import_workers}"
So this is a global worker limit. (Sounds fine...)
But all import tasks will start with dispatching "import-worker-0". Can we add some random offset here?

2023-07-27 11:02 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +                        exclusive_resources = [worker_rsrc]
Let's move this out of the "if" statement. And change the one below to `exclusive-resources.append(dest_repo)`

2023-07-27 12:33 UTC, dralley commented on pulpcore/app/tasks/importer.py
> +        import_workers_percent = int(settings.get("IMPORT_WORKERS_PERCENT", 25))
I agree, also it is better to keep defaults all in one place.  We're basically putting the default in the code here.

2023-07-27 12:36 UTC, mdellweg commented on pulpcore/app/tasks/importer.py
> +        import_workers_percent = int(settings.get("IMPORT_WORKERS_PERCENT", 25))
What i was saying is that i thought we didn't want to make it a setting in this backportable hotfix, no?

2023-07-27 13:02 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +                worker_rsrc = f"import-worker-{index % import_workers}"
Is it worth the complication? It's an issue exactly and only if you start multiple imports at the same time, which is a never-happen case for the admin.

2023-07-27 13:25 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +        import_workers_percent = int(settings.get("IMPORT_WORKERS_PERCENT", 25))
> What i was saying is that i thought we didn't want to make it a setting in this backportable hotfix, no?

With the code looking for a setting (that we haven't advertised yet), we make it at least possible for installations with the fix to adjust their worker-use if absolutely necessary. Without it, Support has to tell customers "upgrade or patch the python code", which is...rude.

Is this a perfect solution? No. It's a pragmatic one that is trying to thread the needle of "fix a problem, while still making it possible for users to still give import All The Workers, in a way that can be backported to (very) previous versions of pulpcore."

2023-07-27 13:27 UTC, ggainey commented on pulpcore/app/tasks/importer.py
> +        import_workers_percent = int(settings.get("IMPORT_WORKERS_PERCENT", 25))
> Also i'm not sure if we want a setting in the end at all.

Honestly, we do. In a lot of import-use-cases, when you're importing, you're importing All The Things, and aren't doing anything else in your system. In that workflow, maximum-concurrency is desirable.

2023-07-27 14:42 UTC, mdellweg commented
So with this way of accessing the setting, you say we are free to delete/change it later?
I think the same goes for a setting in settings.py but not in the docs, making it particularly "undocumented".

2023-07-28 09:02 UTC, mdellweg approved these changes
One last ask.
Feel free to merge.

2023-07-28 09:20 UTC, lubosmj approved these changes

2023-07-28 10:36 UTC, ipanova commented
> > So with this way of accessing the setting, you say we are free to delete/change it later? I think the same goes for a setting in settings.py but not in the docs, making it particularly "undocumented".
> 
> Yeah, I think adding it to settings.py in this PR is the right way to go. Working on updates now.

I am not sure I feel comfortable with this approach. Once backported this setting even if undocumented will be available in the settings.py file accessible for manipulation and changes.
@ggainey  sorry for back and forth but can we in this PR drop this change https://github.com/pulp/pulpcore/pull/4160/files#diff-4e1146f075426039ac8e1350e88fe5736a3e50872a42d101bfc8bc1b7f483574R306 and this line hardcode to number 25 https://github.com/pulp/pulpcore/pull/4160/files#diff-06badc442eb525dc6f2de7f4e19a7762ce20a972b79b6a90cf1ee80211053ab5R516 and in separate followup PR bring back the setting  https://github.com/pulp/pulpcore/pull/4160/files#diff-4e1146f075426039ac8e1350e88fe5736a3e50872a42d101bfc8bc1b7f483574R306 and this line https://github.com/pulp/pulpcore/pull/4160/files#diff-06badc442eb525dc6f2de7f4e19a7762ce20a972b79b6a90cf1ee80211053ab5R516 + document setting+ in CHANGES/.feature

2023-07-28 10:36 UTC, ipanova requested changes
per my comment

2023-07-28 11:02 UTC, mdellweg commented
As i tried to explain: Having it in the settings file is not what makes the setting officially available. And there is absolutely no difference between having the default in the settings.py or buried deep in the code.
My worry is that we make it there-to-stay even if not official the moment we tell an support person to use it.

2023-07-28 11:16 UTC, ipanova commented
> As i tried to explain: Having it in the settings file is not what makes the setting officially available. And there is absolutely no difference between having the default in the settings.py or buried deep in the code. It is till "undocumented". My worry is that we make it there-to-stay even if not official the moment we tell an support person to use it.

Given that I understood your reply, that's why I am asking to not have the setting here at all - neither in settings.py nor burried in the code, so simply sticking to `import_workers_percent = 25` will do for the backport purpose. And in follow up PR will come the rest.

2023-07-28 14:17 UTC, ggainey commented
Great discussion all, thanks!

Changing percent-used-by-default, based on this summing-up from matrix:

"I'm a big fan of what I think your discussion leads to - "default to all-workers, allow users to set a percentage if they want/need to"."

2023-07-28 14:24 UTC, ipanova commented on CHANGES/4068.bugfix
> +Taught pulp-import to never use more than 25% of available worker-threads.
needs update >.>

2023-07-28 14:25 UTC, ggainey commented on CHANGES/4068.bugfix
> +Taught pulp-import to never use more than 25% of available worker-threads.
It is updated - github isn't showing us the last thing I pushed. Yay Friday?

2023-07-28 14:25 UTC, ipanova commented on CHANGES/4068.bugfix
> +Taught pulp-import to never use more than 25% of available worker-threads.
dejavu!

2023-07-28 14:26 UTC, ggainey commented on CHANGES/4068.bugfix
> +Taught pulp-import to never use more than 25% of available worker-threads.
There we go - I updated title/1st-comment to match the updated commit-msg

2023-07-28 14:31 UTC, ipanova approved these changes
Thank you!

2023-07-28 15:02 UTC, ipanova commented
> If you give me a hotfix on top of 6.12.4.1, I'll be able to test in the LAB Satellite of my current CU.

That's the next step to get it downstream.

2023-07-28 17:54 UTC, merged