Add records for Api app status
pulp/pulpcore pull request #4249
Opened 2023-08-03 10:32 UTC by mdellweg

fixes #3175

2023-08-03 21:28 UTC, mdellweg commented
The current version of the change required, that gunicorn is started with "--worker-class pulpcore.app.gunicorn_worker.PulpApiWorker`.

2023-08-09 13:25 UTC, mdellweg commented
I redesigned and pulpcore will now provide a `pulpcore-api` entrypoint that is basically a preloaded gunicorn.
How much of the options should we move there? E.g. how about the logging-format?
Also any way we do it requires a change to the startup files in the oci images.

2023-08-11 08:52 UTC, mdellweg commented on pulpcore/api_gunicorn.py
> +    PulpcoreApiApplication("%(prog)s [OPTIONS]").run()
I need confirmation that we want to start running our components this way.
So if two @pulp/core devs could ack this specific part please?

2023-08-14 18:34 UTC, ggainey commented on pulpcore/api_gunicorn.py
> +    PulpcoreApiApplication("%(prog)s [OPTIONS]").run()
"confirmation that we want to start running our components this way."

I guess my only real question is, is there some **downside** to this? I can't think of one, but I'm prob just being dense.

2023-08-15 07:29 UTC, mdellweg commented on pulpcore/api_gunicorn.py
> +    PulpcoreApiApplication("%(prog)s [OPTIONS]").run()
Maybe that it's another layer of abstraction. But that goes on the plus side as well. When i think about our plan to redesign the content app, it will be much easier to just change the gunicorn worker type used in the entrypoint than telling people to modify their service files.
And exactly that thought brings me to the next question: How much should our entrypoint mimick the gunicorn commandline? Should we just override some parameters internally, or should we explicitely proxy only some parameters?

2023-08-15 13:24 UTC, dkliban commented
We need to make sure that users can still specify gunicorn timeout, number of workers, and logging format.

2023-09-01 17:38 UTC, gerrod3 requested changes

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/app/entrypoint.py
> +                self.api_app_status.delete()
Is it possible we could close/kill the worker and not delete the record?

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/app/entrypoint.py
Can you link the appropriate gunicorn documentation for the classes we import and options we are allowed to pass in?

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/app/models/status.py
>          ``settings.CONTENT_APP_TTL`` from now.
```suggestion
        ``self.model.APP_TTL`` from now.
```

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/app/models/status.py
> +        defined here as longer than the ``settings.WORKER_TTL``, or you can specify age as a
```suggestion
        defined here as longer than the ``self.model.APP_TTL``, or you can specify age as a
```
Might want to consider rewriting this doc-string to change 'worker' to 'object' since this method now refers to the content app, pulpcore-api & task workers.

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/content/__init__.py
> +    heartbeat_task.cancel()
Nifty, this should remove the asyncio Error 'Task was destroy but it is pending' from the logs when restarting the content app?

2023-09-01 17:38 UTC, gerrod3 commented on pulpcore/app/models/status.py
>              bool: True if the content app is considered online, otherwise False
s/content app/app. Also, you need to change the docstring for the `missing` property as well.

2023-09-01 20:36 UTC, mdellweg commented on pulpcore/content/__init__.py
> +    heartbeat_task.cancel()
I hope so...

2023-09-01 20:37 UTC, mdellweg commented on pulpcore/app/models/status.py
> +        defined here as longer than the ``settings.WORKER_TTL``, or you can specify age as a
We call them api workers and content workers... And gunicorn talks a lot about workers too. I think we are probably fine...

2023-09-01 20:50 UTC, mdellweg commented on pulpcore/app/entrypoint.py
> +                self.api_app_status.delete()
Why should we? Also there was a request from @bmbouter when implementing the hearbeating for pulpcore-workers to clean up on exiting. And this PR tries to apply these rules to all types of workers.

And btw we never cleaned up the content api status before. I guess there are some db's around where that table became humongous by now.

2023-09-01 20:52 UTC, mdellweg commented on pulpcore/app/entrypoint.py
> +                    self.api_app_status.save(update_fields=["versions"])
In theory yes. The name is composed of `<pid>@<hostname>` when you restart that computer, and the boot process is very consistent, you will end up with the same name again.

2023-09-01 20:54 UTC, gerrod3 commented on pulpcore/app/entrypoint.py
> +                self.api_app_status.delete()
Oh sorry, I worded my question wrong. I was asking is it possible the worker could be kill and not have its record cleaned up. Looking later down in the code, it seems that the task worker code would clean up any missing worker records.

2023-09-01 21:14 UTC, mdellweg commented on pulpcore/app/entrypoint.py
> +                self.api_app_status.delete()
The cleanup happens after a week (or so). But yes, it's always possible that the application is killed in a way that no cleanup procedures will be executed anymore. OOM, kill -9, segfault, you name it...

2023-09-01 21:26 UTC, gerrod3 commented on pulpcore/app/wsgi.py
> +    raise RuntimeError("This app must be executed using pulpcore-api endpoint.")
```suggestion
    raise RuntimeError("This app must be executed using pulpcore-api entrypoint.")
```

2023-09-05 18:31 UTC, gerrod3 approved these changes

2023-09-05 19:40 UTC, ggainey approved these changes

2023-09-06 07:52 UTC, merged