WIP POC Expression filter
pulp/pulpcore pull request #4270
Opened 2023-08-11 08:41 UTC by mdellweg

fixes #2480
fixes #3914

2023-08-11 20:32 UTC, gerrod3 commented on pulpcore/filters.py
> +                        "order You the query filter. cannot the inside q"
Is this error message a pun? Kind of funny even if not intentional.

2023-08-13 12:32 UTC, mdellweg commented on pulpcore/filters.py
> +                        "order You the query filter. cannot the inside q"
Intentional for the time being. See the todo above. Currently these errors bubble up as 500, while they should be 400 or 422.

2023-08-15 15:43 UTC, newswangerd commented
@jamestalton does this work for the ansible ui?

2023-08-16 13:07 UTC, ggainey requested changes
I'd like to see doc with examples of how-to-use - it's pretty opaque to the end-user just looking at the REST API, yeah?

2023-08-16 13:52 UTC, mdellweg commented
> I'd like to see doc with examples of how-to-use - it's pretty opaque to the end-user just looking at the REST API, yeah?

Should we just take the queries from the tests as examples?

2023-08-16 13:56 UTC, ggainey commented
> > I'd like to see doc with examples of how-to-use - it's pretty opaque to the end-user just looking at the REST API, yeah?
> 
> Should we just take the queries from the tests as examples?

That would work fine - just put them where REST users don't have to dig into code to understand how to use this.

2023-08-17 12:10 UTC, ggainey approved these changes

2023-08-17 12:10 UTC, ggainey commented on docs/workflows/advanced-filtering.rst
:+1:

2023-08-17 17:44 UTC, lubosmj commented on docs/workflows/advanced-filtering.rst
> +
You should use the `q` parameter, like so:
```
http :5001/pulp/api/v3/tasks/?q='name__contains=a AND (NOT state="failed")'
```

I also had a hard time understanding it in the first place. Overall, the functionality is very promising to me. 👍🏻

2023-08-17 18:26 UTC, lubosmj reviewed
From the functional perspective, I adore this change. Everything is working as expected. Longer and more complex queries take some time to complete but this is fine, e.g.:
```
# valid
http :5001/pulp/api/v3/tasks/?q="(((((NOT name__contains='Horror' OR (NOT name__contains='Thriller')) AND (name__contains='Suspense' OR name__contains='Mystery')) AND ((name__contains='Detective' OR name__contains='Crime') AND (NOT name__contains='Action'))) OR (name__contains='Intrigue' AND (NOT name__contains='Suspense'))) OR ((name__contains='Dilemma' OR name__contains='Tension') AND (NOT name__contains='Conflict' OR name__contains='Resolution'))) AND (name__contains='Climax' OR (NOT name__contains='Conclusion'))"
```
```
# invalid
http :5001/pulp/api/v3/tasks/?q="((((((NOT name__contains='Adventure' OR (NOT name__contains='Mystery')) AND (name__contains='Suspense' OR name__contains='Detective')) AND ((name__contains='Crime' OR name__contains='Intrigue') AND (NOT name__contains='Action'))) OR (name__contains='Enigma' AND (NOT name__contains='Suspense'))) OR ((name__contains='Dilemma' OR name__contains='Tension') AND (NOT name__contains='Puzzle' OR name__contains='Resolution'))) AND (name__contains='Climax' OR (NOT name__contains='Conclusion'))"
```

Are regular users the ones who can invoke such a complex query? Is this limited to admins? The filtering could block the API worker, right? Is the worry about DoS in place?

2023-08-17 18:41 UTC, ggainey commented
> Are regular users the ones who can invoke such a complex query? Is this limited to admins? The filtering could block the API worker, right? Is the worry about DoS in place?

It's just another parameter on the list-endpoints. Yes, 'regular' users can call those endpoints. Yes, that might be a problem. That's an artifact of enabling this kind of reporting/searching. Given the requirements for this feature, it can't reasonably be limited to admin-only (and would need to be a separate endpoint if we wanted to do so).

2023-08-17 19:11 UTC, lubosmj commented
Cool. Then, a small warning in the docs might be the only missing thing.

2023-08-21 09:52 UTC, mdellweg commented
I have issues writing a warning with absolutely no hint what to do about it. It's not like the admin has any choice here.

2023-08-23 07:02 UTC, mdellweg commented
> > Are regular users the ones who can invoke such a complex query? Is this limited to admins? The filtering could block the API worker, right? Is the worry about DoS in place?
> 
> It's just another parameter on the list-endpoints. Yes, 'regular' users can call those endpoints. Yes, that might be a problem. That's an artifact of enabling this kind of reporting/searching. Given the requirements for this feature, it can't reasonably be limited to admin-only (and would need to be a separate endpoint if we wanted to do so).

Yes this is a feature for users. By design. I do not see any value in it if you cannot use it.

2023-08-23 10:33 UTC, mdellweg commented
I added a complexity limit to address all the remaining concerns.

2023-08-23 18:22 UTC, ggainey requested changes

2023-08-23 18:22 UTC, ggainey commented on pulpcore/filters.py
> +            if result.complexity > 8:
:+1:  I think this is a good compromise between "usefulness" and "protect the pulp instance from inadvertent DDoS". I def want to see a mention in the doc for this along the lines of " "to provide some protection from overly-complex queries stalling the database, the Q() filter limits query-complexity to 8 AND/OR/NOT combinations"

2023-08-23 21:05 UTC, mdellweg commented on docs/workflows/advanced-filtering.rst
> +
@ggainey Isn't this the mention you requested?

2023-08-23 21:37 UTC, ggainey commented on docs/workflows/advanced-filtering.rst
> +
The code is specific, the docs should be as well. It's rude to force users to do things like "well, *that* expression was OK, but *this* one isn't - what makes something 'too complex'?"

2023-08-24 06:40 UTC, lubosmj approved these changes
I am giving the approval from the functional perspective. 🧑‍🍳 Please, address the comment from @ggainey.

2023-08-24 09:47 UTC, mdellweg commented on docs/workflows/advanced-filtering.rst
> +
I wanted to be a bit unspecific, because we may decide to change the way we compute complexity while we learn more from the field. But I'll add a sketch of the calculation.

2023-08-24 13:26 UTC, ggainey requested changes
Documentation nitpicks only, consistency to avoid some amount of user-confusion.

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND(   name__icontains=gh OR name__contains="naïve")
```suggestion
    pulp_type="core.rbac" AND (name__icontains="gh" OR name__contains="naïve")
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type__in='core.rbac'
```suggestion
    pulp_type__in="core.rbac"
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type__in=core.rbac,core.content_redirect
```suggestion
    pulp_type__in="core.rbac","core.content_redirect"
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND name__contains=GGGG
```suggestion
    pulp_type="core.rbac" AND name__contains="GGGG"
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND name__iexact={prefix}-gGgG
```suggestion
    pulp_type="core.rbac" AND name__iexact="{prefix}-gGgG"
```

This one's a little unclear to me, what is `{prefix}`?

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND name__icontains=gg AND NOT name__contains=HH
```suggestion
    pulp_type="core.rbac" AND name__icontains="gg" AND NOT name__contains="HH"
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    NOT (pulp_type="core.rbac" AND name__icontains=gGgG)
```suggestion
    NOT (pulp_type="core.rbac" AND name__icontains="gGgG")
```

2023-08-24 13:26 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" OR name__icontains=gh OR name__contains="naïve"
```suggestion
    pulp_type="core.rbac" OR name__icontains="gh" OR name__contains="naïve"
```

2023-08-24 13:33 UTC, mdellweg commented on docs/workflows/complex-filtering.rst
> +    pulp_type__in=core.rbac,core.content_redirect
That one is not going to work.

2023-08-24 13:34 UTC, mdellweg commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND(   name__icontains=gh OR name__contains="naïve")
We demonstrate that whitespace is not changing the query.

2023-08-24 13:35 UTC, mdellweg commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND name__iexact={prefix}-gGgG
This one is actually bad.

2023-08-24 13:59 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type="core.rbac" AND(   name__icontains=gh OR name__contains="naïve")
:+1:

2023-08-24 13:59 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type__in=core.rbac,core.content_redirect
Heh, ok then :)

2023-08-24 14:00 UTC, ggainey commented on docs/workflows/complex-filtering.rst
> +    pulp_type__in='core.rbac'
Ah, understood. I still think we may get questions on "why is the documentation inconsistent", but that's a good answer. (And if anyone goes digging, they'll find this discussion and be Enlightened...)

2023-08-24 14:02 UTC, ggainey approved these changes

2023-08-24 14:25 UTC, merged