Adds RBAC for UpstreamPulp API
pulp/pulpcore pull request #4336
Opened 2023-08-25 19:39 UTC by dkliban

fixes: #3994

2023-08-29 01:14 UTC, gerrod3 commented on pulpcore/app/viewsets/replica.py
> +                "condition": ["has_model_or_domain_or_obj_perms:core.manage_roles_upstreampulp"],
Should a `view_upstreampulp` check also be here?

2023-08-29 01:14 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_replication.py
> +def test_replicate_rbac(
Since this test is already requiring domains to run, can we use two new domains for the test so that we can mark this parallel?

2023-08-29 08:19 UTC, mdellweg commented on pulpcore/tests/functional/api/test_replication.py
> +    try_action(bob, upstream_pulp_api_client, "replicate", 202, upstream_pulp.pulp_href)
After sucessfully replicating, do we have any content in the replica domain that we need to clean so the fixture can clean up the domain?

2023-09-05 20:53 UTC, dkliban commented on pulpcore/tests/functional/api/test_replication.py
> +def test_replicate_rbac(
yes, let's make it a parallel test.

2023-09-06 13:08 UTC, dkliban commented on pulpcore/tests/functional/api/test_replication.py
> +    try_action(bob, upstream_pulp_api_client, "replicate", 202, upstream_pulp.pulp_href)
I am going to update the test to ensure that there is no content remaining in the domain which is serving as the replica.

2023-09-06 19:49 UTC, dkliban commented on pulpcore/app/viewsets/replica.py
> +                "condition": ["has_model_or_domain_or_obj_perms:core.manage_roles_upstreampulp"],
I didn't see any other viewsets that have view_<model> conditions for the roles actions. Am I misunderstanding?

2023-09-08 12:44 UTC, mdellweg commented on pulpcore/app/models/replica.py
> +            ("manage_roles_upstreampulp", "Can manage roles on upstream pulps"),
```suggestion
            ("manage_roles_upstreampulp", "Can manage roles on upstream pulp"),
```

2023-09-08 12:45 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +                "action": ["update", "partial_update"],
Are there labels on upstream pulp?

2023-09-08 12:55 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +                "condition": ["has_model_or_domain_or_obj_perms:core.manage_roles_upstreampulp"],
That is a good point.
Is the view permission not implied by the queryset filtering anyway? Would that not also apply to update and delete actions?

2023-09-08 12:55 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +        ],
How about a role that can only trigger the replication, not change it?

2023-09-08 12:55 UTC, mdellweg commented on pulpcore/tests/functional/api/test_replication.py
> +def test_replicate_rbac(
The ask here was to make the "serving" domain ephemeral too.
What if other tests constantly create and delete distributions?
I think with the label_select we still have a rather stable test here?

2023-09-08 12:55 UTC, mdellweg commented on pulpcore/tests/functional/api/test_replication.py
> +    try_action(bob, upstream_pulp_api_client, "replicate", 202, upstream_pulp.pulp_href)
So this intentionally does not replicate a single repository?
Do we have another test for this? Wouldn't it be better (faster) to combine these tests into one?
1. Setup two distributions with content and different labels.
2. Replicate with label_select matching one of them.
3. Verify one repo.
4. replicate again with label_select matching nothing (to cleanup)
5. verify deletion of repo

2023-09-08 13:16 UTC, dkliban commented on pulpcore/tests/functional/api/test_replication.py
> +def test_replicate_rbac(
yeah, the label_select guarantees that no distributions get actually discovered for replication.

2023-09-08 13:17 UTC, dkliban commented on pulpcore/tests/functional/api/test_replication.py
> +    try_action(bob, upstream_pulp_api_client, "replicate", 202, upstream_pulp.pulp_href)
This test intentionally doesn't do any replication. I am going to open a PR against Pulp file that does what you describe.

2023-09-08 13:20 UTC, dkliban commented on pulpcore/app/viewsets/replica.py
> +                "action": ["update", "partial_update"],
Not at this time.

2023-09-08 13:53 UTC, dkliban commented on pulpcore/app/viewsets/replica.py
> +        ],
Hmm ... maybe. Do we have such roles for syncing repos?

2023-09-08 14:20 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +        ],
Yes, but replicate is a bit more complex. Also you can sync using a remote without being able to modify it's proxy credentials... Similar we'd have a way to separate the upstream credentials from the ability to use the upstream pulp. I think it'd be useful.

2023-09-19 08:13 UTC, mdellweg requested changes

2023-09-19 08:13 UTC, mdellweg commented on pulpcore/app/viewsets/replica.py
> +                    "has_model_or_domain_or_obj_perms:core.view_upstreampulp",
I think this view perm is still superfluous.

2023-09-19 17:35 UTC, gerrod3 approved these changes

2023-09-19 20:16 UTC, merged