fix: social urls from config
pulp/pulpcore pull request #4512
Opened 2023-09-28 01:24 UTC by jeff350

Addresses #4511  by using required config option `SOCIAL_AUTH_URL_NAMESPACE`

2023-09-28 15:37 UTC, dkliban requested changes
please add a changelog file to the CHANGES directory. I would say that this is a new feature. So it should be called `4511.feature`.

Your commit message needs to also state 'fixes: #4511' or 'closes: #4511'

2023-09-28 16:02 UTC, jeff350 commented
@dkliban requested updates have been made, please let me know if I need to change all commit messages to 'fixes: #4511'  or if just the latest is sufficient.

2023-09-28 16:03 UTC, dkliban commented
@jeff350 please squash the changes into a single commit

2023-09-28 16:26 UTC, jeff350 commented
@dkliban all commits have been squashed into a single commit, looks like this should be good to go when all tests pass.

2023-09-28 16:36 UTC, dkliban commented
@jeff350 The CI is showing the following error:

` AttributeError: 'HookableSettings' object has no attribute 'SOCIAL_AUTH_URL_NAMESPACE'`

You need to ensure that the setting is present before checking the value.

2023-09-28 16:47 UTC, jeff350 commented
@dkliban I missed that case... I am starting to wonder if checking that specific setting directly may not the best approach. A possible alternative would be to check if social_django is in the list of installed apps, that maybe a cleaner way to do this.

 do you have an option on what would be preferred?

2023-09-28 16:56 UTC, dkliban commented
@jeff350 You should check that `django_social` is in the installed apps. If it is installed, you should then check that `SOCIAL_AUTH_URL_NAMESPACE` is set. Then the value of `SOCIAL_AUTH_URL_NAMESPACE` should be used as the value of `namespace` when adding the You also want to make sure that the value of `namespace` in the urlpattern being added.

2023-09-28 17:43 UTC, jeff350 commented
@dkliban This should be fixed now. I also added the SOCIAL_AUTH_URL_NAMESPACE as a default in the settings.py file as I understand that will always need to be a custom namespace and 'social' is what django_social always recommends to use. 

This also helped to further simplify the docs.

2023-09-28 17:52 UTC, dkliban commented on pulpcore/app/urls.py
> +    if settings.SOCIAL_AUTH_URL_NAMESPACE == "social":
I don't believe that we want to only include the urlpattern when the SOCIAL_AUTH_URL_NAMESPACE is 'social'. If 'social_django' is installed we want to include the urlpattern with the `namespace` specified by `SOCIAL_AUTH_URL_NAMESPACE`.  So like this:

```python
if "social_django" in settings.INSTALLED_APPS:
    urlpatterns.append(path("", include("social_django.urls", namespace=settings.SOCIAL_AUTH_URL_NAMESPACE)))
```

2023-09-28 18:28 UTC, jeff350 commented on pulpcore/app/urls.py
> +    if settings.SOCIAL_AUTH_URL_NAMESPACE == "social":
Change has been mande

2023-09-29 11:02 UTC, mdellweg commented on pulpcore/app/urls.py
> +    if settings.SOCIAL_AUTH_URL_NAMESPACE == "social":
Thank you. I was about to request the exact same.

2023-09-29 11:04 UTC, mdellweg requested changes

2023-09-29 11:04 UTC, mdellweg commented on pulpcore/app/settings.py
> +
Please add a section to the settings part of the docs, too.

2023-09-29 11:05 UTC, mdellweg commented on docs/authentication/keycloak.rst
> -
By now providing a default value, can we still keep this step as an optional one?

2023-09-30 14:52 UTC, jeff350 commented on docs/authentication/keycloak.rst
> -
My understanding is that this is not a setting anyone will want to change. Reading the Django docs (https://docs.djangoproject.com/en/4.2/topics/http/urls/#url-namespaces) the namespace is designed for reserving url patterns. I would equate django_social having the namespace of 'social' to their example of the django admin having a namespace of 'admin'.

additionally  django_social also recommends setting this to 'social' if a custom namespace is going to be used.  https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#urls-entries

2023-09-30 14:57 UTC, jeff350 commented on pulpcore/app/settings.py
> +
If this is not something that is intended for users to change does it need a section in the settings documentation? looking at the documentation it seems that the settings there are ones that are intended fore users to change as needed. 

See for context on why this does not need to be a user configurable setting https://github.com/pulp/pulpcore/pull/4512#discussion_r1341971011

2023-10-02 06:49 UTC, mdellweg commented on docs/authentication/keycloak.rst
> -
> additionally django_social also recommends setting this to 'social' if a custom namespace is going to be used. https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#urls-entries

Actually, i read it the other way around. You only need to set it if it's _not_ the default (and their example is not helping much). Having said that, the url-namespace is not changing the included paths. So, I think we are fine always using "social".

2023-10-02 06:51 UTC, mdellweg commented on docs/authentication/keycloak.rst
>      SOCIAL_AUTH_JSONFIELD_CUSTOM = 'django.db.models.JSONField'
We are always using Postgres. You can move these settings too and remove the step from the docs.

2023-10-02 12:51 UTC, jeff350 commented on docs/authentication/keycloak.rst
>      SOCIAL_AUTH_JSONFIELD_CUSTOM = 'django.db.models.JSONField'
Requested changes have been made

2023-10-02 12:58 UTC, dkliban commented on pulpcore/app/settings.py
> +SOCIAL_AUTH_JSONFIELD_CUSTOM = 'django.db.models.JSONField'
black is complaining about use of single quotes. Please use " instead of '.

2023-10-02 13:03 UTC, jeff350 commented on pulpcore/app/settings.py
> +SOCIAL_AUTH_JSONFIELD_CUSTOM = 'django.db.models.JSONField'
fixed

2023-10-02 13:58 UTC, mdellweg approved these changes

2023-10-02 14:11 UTC, dkliban approved these changes

2023-10-02 14:11 UTC, merged