Add a HeaderContentGuard.
pulp/pulpcore pull request #4534
Opened 2023-10-05 16:54 UTC by decko

Closes #4518

2023-10-12 13:00 UTC, dkliban commented on pulpcore/app/models/publication.py
> +            ("download_headercontentguard", "Can Download Content"),
you don't need this permission. this is only needed for the rbac content guard.

2023-10-13 13:35 UTC, bmbouter commented on pulpcore/app/models/publication.py
> +                "Access not allowed - Header value not encoded in a proper format."
```suggestion
                "Access not allowed - Header is not Base64 encoded."
```

2023-10-13 13:37 UTC, bmbouter commented
This is looking good!

2023-10-16 15:17 UTC, dkliban commented on pulpcore/tests/unit/test_content_guard.py
> +    # header_content = {
Did you mean to leave this all commented out?

2023-10-16 23:28 UTC, dkliban approved these changes
Thank you!

2023-10-17 06:53 UTC, mdellweg requested changes
jq can filter regex, so there's no need to add that on the value. :+1:

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +from binascii import Error as Base64DecodeError
I wonder if this could be imported from base64 instead?

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +                "Can manage role assignments on RBAC content guard",
```suggestion
                "Can manage role assignments on header content guard",
```

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +    value = serializers.CharField(help_text=_("The valued that is used to check against."))
```suggestion
    value = serializers.CharField(help_text=_("The value used to check against."))
```

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +    header_name = serializers.CharField(help_text=_("The header that the guard will check on."))
```suggestion
    header_name = serializers.CharField(help_text=_("The header the guard will check on."))
```

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +    )
Should we call this a jq-filter? Because we filter the value before comparing it.

2023-10-17 06:53 UTC, mdellweg commented on CHANGES/4518.feature
> +Add a HeaderContentGuard to allow a specific header and its content to guard the content app.
```suggestion
Added a ``HeaderContentGuard`` to allow a content access based on a value provided by a specific header. The header can optionally be filtered through a ``jq`` expression.
```

2023-10-17 06:53 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +            raise PermissionError("Access not allowed. Header not found.")
We should just access deny here but log (debug?) a bit more verbose.
```suggestion
            raise PermissionError("Access denied.")
            log.debug(_("Access denied. Header {header_name} not found in request.").format(header_name))
```
The same with all raise below.

2023-10-17 13:00 UTC, decko commented on pulpcore/app/models/publication.py
> +from binascii import Error as Base64DecodeError
The `base64` module doesn't define any special exception and uses the `binascii` under the hood to decode base64 values.

2023-10-17 17:12 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +    )
Sure, but i don't think the issue tells us how to name things. But the name chosen will stick with us forever.

2023-10-18 15:51 UTC, decko commented on pulpcore/app/serializers/publication.py
> +    )
Oh, not the issue issue. But the card/ticket/issue. #4518

2023-10-18 21:26 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +    )
I get, that the issue introduced that name, but i see that more of a suggestion / guideline. And `json_accessor` does not quite express the concept to me.

2023-10-18 23:30 UTC, dkliban commented on pulpcore/app/serializers/publication.py
> +    )
The jq documentation refers to this string as a filter[0]. Let's call it a `jq_filter`.

[0] https://jqlang.github.io/jq/tutorial/

2023-10-19 13:11 UTC, decko commented on pulpcore/app/serializers/publication.py
> +    )
`jq_filter` then.

2023-10-20 14:10 UTC, bmbouter commented on CHANGES/4518.feature
> +Added a ``HeaderContentGuard`` to allow a content access based on a valued provided by a specific header. The header can optionally be filtered through a ``jq`` expression.
Can this be wrapped to one line. Sorry for the nitpick.

2023-10-20 14:12 UTC, bmbouter commented on pulpcore/app/models/publication.py
> +            raise PermissionError("Access denied.")
What about wrapping all the `PermissionErrors` strings with `gettext`? Generally in Pulp we i8ln the user facing string (but not the logs).

2023-10-20 14:12 UTC, bmbouter commented on pulpcore/app/serializers/publication.py
> +    header_name = serializers.CharField(help_text=_("The header the guard will check on."))
```suggestion
    header_name = serializers.CharField(help_text=_("The header name the guard will check on."))
```

2023-10-20 14:13 UTC, bmbouter commented on pulpcore/app/serializers/publication.py
> +    value = serializers.CharField(help_text=_("The valued used to check against."))
```suggestion
    value = serializers.CharField(help_text=_("The valued that will authorize the request."))
```

2023-10-20 14:14 UTC, bmbouter commented on pulpcore/app/serializers/publication.py
> +                "not be filtered yet it still try to decode it."
```suggestion
                "only be Base64 decoded and checked as an explicit string match."
```

2023-10-20 14:16 UTC, bmbouter approved these changes
I left a string/language comments. Fix those if you agree. Functionally speaking this is ready to go. Thank you!

2023-10-20 15:12 UTC, ipanova commented on CHANGES/4518.feature
> +Added a ``HeaderContentGuard`` to allow a content access based on a valued provided by a specific header. The header can optionally be filtered through a ``jq`` expression.
s/valued/value

2023-10-20 15:17 UTC, ipanova commented on pulpcore/app/models/publication.py
> +            raise PermissionError("Access denied.")
does it make sense to provide more info instead log.debug directly in the error? i.e `Access denied. Content guard header not provided`. Similarly, other  PermissionError occurrences down in the code

2023-10-20 15:18 UTC, ipanova commented on pulpcore/app/models/publication.py
> +    value = models.TextField()
if you use header_name then use header_value, or drop `header` completely

2023-10-20 15:20 UTC, ipanova commented on pulpcore/app/viewsets/publication.py
> +    Content guard to protect the content app using a specific header and its content.
`Content guard to protect the content app using a specific header.`

2023-10-20 15:21 UTC, ipanova commented on pulpcore/app/viewsets/publication.py
> +    endpoint_name = "header"
please use plural

2023-10-20 15:23 UTC, ipanova commented on pulpcore/app/viewsets/publication.py
> +    endpoint_name = "header"
maybe it will be even better to be more explicit - header_contentguards

2023-10-23 12:44 UTC, decko commented on pulpcore/app/models/publication.py
> +            raise PermissionError("Access denied.")
@bmbouter good point.

@ipanova We had gone on that path but then decided to log the details and present only a generic error on the message [here](https://github.com/pulp/pulpcore/pull/4534#discussion_r1361587433)

2023-10-23 12:48 UTC, decko commented on pulpcore/app/viewsets/publication.py
> +    endpoint_name = "header"
All the other ContentGuards use the `endpoint_name` in singular and don't have the `_contentguards` sufix. I believe that the complete URL make that sufix redundant.

2023-10-23 15:34 UTC, merged