More export optimizations and a bugfix
pulp/pulpcore pull request #4540
Opened 2023-10-11 01:34 UTC by dralley

2023-10-11 01:39 UTC, dralley commented on pulpcore/plugin/importexport.py
> +    def dehydrate_pulp_domain(self, content):
@ggainey Would it be better, to define this on the `QueryModelResource` above, which is inherited by both `BaseContentResource` and `ArtifactResource`?

2023-10-11 01:59 UTC, dralley commented
Combined with https://github.com/pulp/pulp_rpm/pull/3278, an export dropped from 466 seconds to 335 seconds, or about 28%.

This is the solution to the mystery of the field fetches mentioned on Matrix.

2023-10-11 05:09 UTC, dralley commented
One interesting thing is that at this point, the progress reporting is seemingly taking up 18% of the time despite only saving once every 5 seconds (and I checked that it works as expected, and it is)

![Screenshot from 2023-10-11 01-01-58](https://github.com/pulp/pulpcore/assets/2751996/c22db54e-1da8-47dc-8d62-7b7d47083ac2)

That really quite strange.  And all that time is just spent waiting on the database to commit.  Maybe all the disk read traffic is preventing timely writes?  The load is enough to visibly slow operations like `git log`.

 Anyway, it claims only about 142 seconds out of 289 were spent scheduled on the CPU, so we're essentially IO bound for exports at this point.

2023-10-11 18:25 UTC, ggainey requested changes

2023-10-11 18:25 UTC, ggainey commented on pulpcore/app/modelresource.py
> +    def dehydrate_pulp_domain(self, content):
Let's move this to QueryModelResource, then it's available to everyone (ie both Content and Artifact resources). We can then remove from https://github.com/pulp/pulp_rpm/pull/3278

2023-10-11 18:25 UTC, ggainey commented on pulpcore/app/modelresource.py
> +            "timestamp_of_interest",
:+1:

2023-10-11 18:25 UTC, ggainey commented on pulpcore/app/viewsets/importer.py
> +            description="Import of {path}".format(path=path or toc)
:+1:

2023-10-11 18:25 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +    def dehydrate_pulp_domain(self, content):
Having it in QMR seems the better choice - I'm a big fan of DRY :)

2023-10-11 19:01 UTC, dralley commented on pulpcore/app/modelresource.py
> +        )
Special attention might be warranted on this query.  I'm pretty sure it's identical but...

2023-10-11 19:16 UTC, ggainey commented on pulpcore/app/modelresource.py
> +        )
I did walk through this "in my head" a number of times. I'm *pretty* confident one ends up with a query that will select the same set of ContentArtifacts as a result. Existing code unions "content from repoversion" and "all ids from mapping-file" and filters by that. Your change gets *the set of all content-IDs from repoversion-content* , and ors-in the content-ids from the mapping-file. At the end of the day, the QS is filtering by "all the IDs in this collection", and the collection is built from the same pieces.

"100% sure" would require tests that run both ways and then specifically compares the output, I guess.

2023-10-11 20:43 UTC, ggainey approved these changes

2023-10-11 20:43 UTC, ggainey commented on pulpcore/plugin/importexport.py
> +    def dehydrate_pulp_domain(self, content):
:+1:

2023-10-12 12:23 UTC, ipanova commented on pulpcore/app/modelresource.py
> +            .select_related("artifact")
are you saying we need to prefetch artifact( and generally any other related model) when the FKwidget is using other field than pk?

2023-10-12 13:06 UTC, dralley commented on pulpcore/app/modelresource.py
> +            .select_related("artifact")
Yes, to avoid N+1 issues.  Because FKWidget would otherwise trigger a request for that artifact

2023-10-13 05:40 UTC, dralley commented on docs/plugin_dev/plugin-writer/concepts/subclassing/import-export.rst
> +an N+1 query scenario is likely.
@ipanova here's the docs we discussed.  If you're fine with this phrasing, feel free to merge.

2023-10-13 06:45 UTC, mdellweg commented
I see backport labels and 4 commits. This is not going to work (a technical limitation in patchback).
I think you either need to merge the commits or split the PR.

2023-10-13 14:10 UTC, dralley commented
@mdellweg I'd rather the commits stay separate, so given that the other options is 4 separate PRs with like 24 backport PRs, I think I would prefer to just manually cherrypick to 6 PRs.

2023-10-13 15:16 UTC, merged

2023-10-15 16:11 UTC, lubosmj commented on docs/plugin_dev/plugin-writer/concepts/subclassing/import-export.rst
> +an N+1 query scenario is likely.
@ipanova, do you think we should adhere to these recommendations in pulp-container? https://github.com/pulp/pulp_container/blob/4df9e2ebb20f4a48f6441fe2f11f7f98284c8a1c/pulp_container/app/modelresource.py#L84-L93

2023-10-16 11:23 UTC, ipanova commented on docs/plugin_dev/plugin-writer/concepts/subclassing/import-export.rst
> +an N+1 query scenario is likely.
yes, we will need to dehydrate pulp-domain for the basecontent subclasses and use select_related in the queryset. To avoid importing large models we should apply .only() on the needed fields.