WIP
pulp/pulpcore pull request #4547
Opened 2023-10-12 12:06 UTC by mdellweg

Do not merge before 3.40!

fixes #4546

2023-10-30 15:40 UTC, gerrod3 requested changes

2023-10-30 15:40 UTC, gerrod3 commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +            Task.bulk_update(batch, fields=["enc_args", "enc_kwargs", "versions"])
You forgot to clear the batch list here.

2023-10-30 15:40 UTC, gerrod3 commented on pulpcore/app/models/task.py
> -    # running at least <version this landed> then copies their values to enc_(kw)args and adds
Did you forgot this check in the migration, or is it not needed?

2023-10-30 16:25 UTC, mdellweg commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +            Task.bulk_update(batch, fields=["enc_args", "enc_kwargs", "versions"])
Right. Good find!

2023-10-30 16:26 UTC, mdellweg commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +        RequireVersion("core", "3.34.0"),
The check you were searching for is here.

2023-10-30 20:09 UTC, gerrod3 commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +    for task in Task.objects.filter(Q(args__is_null=False) | Q(kwargs__is_null=False)):
Do we need to use an `iterator` or `only` clause here? I assume some machines could have a large task database.

2023-10-31 08:50 UTC, mdellweg commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +    for task in Task.objects.filter(Q(args__is_null=False) | Q(kwargs__is_null=False)):
Are you saying, this queryset will be cached completely in memory once we access the first task? Will I ever fully understand this?

2023-10-31 08:58 UTC, mdellweg commented on pulpcore/app/migrations/0114_remove_task_args_remove_task_kwargs.py
> +    for task in Task.objects.filter(Q(args__is_null=False) | Q(kwargs__is_null=False)):
Reading https://docs.djangoproject.com/en/4.2/ref/models/querysets/#iterator , i now think that using `iterator()` will skip the caching altogether, which seems desirable here. I added it.

2023-10-31 13:29 UTC, mdellweg commented on pulpcore/app/models/task.py
> -    # running at least <version this landed> then copies their values to enc_(kw)args and adds
See comment below.

2023-10-31 14:30 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
> +pytestmark = pytest.mark.skipif(settings.DOMAIN_ENABLED, reason="Domains do not support export.")
`pytest.skip(allow_module_level=True)` somehow started to fail with pytest-xdist...

2023-10-31 15:53 UTC, ggainey approved these changes

2023-10-31 16:03 UTC, gerrod3 approved these changes

2023-10-31 16:05 UTC, merged