Added CompositeCOntentGuard to manage set of guards for a Dist.
pulp/pulpcore pull request #4605
Opened 2023-10-22 21:30 UTC by ggainey

closes #4583.

2023-10-23 00:33 UTC, ggainey commented
POC for a content-guard that calls the permit() of a list-of-content-guards. Current state is "allows OR, only". Incoming are docs, tests, and possibly allowing AND-or-OR.

Current error-msg on all-guards-fail looks like so:
```
(oci-env) (main) ~/github/Pulp3/oci_env $ http :5001/pulp/content/ccg/
HTTP/1.1 403 Access not authenticated. Refusals: [
  "Guard 'redirect', HREF '/pulp/api/v3/contentguards/core/content_redirect/018b4cf7-35c2-77a5-b8cc-dfbf2df0a96b/', class '<class 'pulpcore.app.models.publication.ContentRedirectContentGuard'>', refused access due to [Access not authenticated].", 
  "Guard 'redirect_2', HREF '/pulp/api/v3/contentguards/core/content_redirect/018b57fa-42e5-79c2-a72b-5efdd5a77461/', class '<class 'pulpcore.app.models.publication.ContentRedirectContentGuard'>', refused access due to [Access not authenticated]."]
(oci-env)
```

Eyes plizkthxbai

2023-10-26 17:02 UTC, ggainey commented on pulpcore/app/models/publication.py
> +            return
If a Distribution has no content-guard, content-access is allowed. Current implementation maintains that behavior.

2023-10-26 17:05 UTC, ggainey commented on pulpcore/app/models/publication.py
> +                return  # success on first-pass
Not including this one, pulpcore currently has three content guards (ContentRedirect, Header, and RBAC). **NONE** of them are documented, at all. They generally have minimal (or zero) tests. I  don't know **where** to "add in docs", and I certainly don't know how to write about the performance implications here, when there is no way to know what the performance implications are for any of the things you might add to this list.

2023-10-26 17:06 UTC, ggainey commented on pulpcore/app/serializers/publication.py
> +        queryset=models.ContentGuard.objects.all(),
I have no idea. Is there a reason why that might not be accounted for?

2023-10-27 08:44 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +            return
Well, it's an edge case. Either way is fine. Even not allowing it to be empty would suite me.

2023-10-27 08:50 UTC, mdellweg commented on pulpcore/app/serializers/publication.py
> +        queryset=models.ContentGuard.objects.all(),
There is probably no use to add a `ContentRedirectContentGuard`, but it is also not really "hidden" in any api. Disregard my comment please.

2023-10-27 12:11 UTC, ggainey commented on pulpcore/app/models/publication.py
> +            return
I thought about that, but allowing it to be empty allows the workflow "create and attach one (which doesn't change the Distribution's behavior), and *then* figure out which guards and in what order you want to have". Felt like a gentler process for the admin.

2023-10-27 12:31 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +            return
I think i still lean towards adding the empty one as a complete lock-down that you can then gradually open up by adding guards.
But I'll accept anything you come up with.

2023-10-31 16:01 UTC, decko commented on pulpcore/app/models/publication.py
> +                return  # success on first-pass
https://github.com/pulp/pulpcore/issues/4629

2023-11-20 14:31 UTC, bmbouter commented
@pulp/core would it be possible for this to be prioritized?  The services deployment of Pulp is going to need this likely very soon. Would it be possible to pick it up on the week of the 27th? We can talk that over any way you all would like. Thank you!

2023-11-30 17:37 UTC, mdellweg requested changes

2023-11-30 17:37 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +    guards = models.ManyToManyField(ContentGuard, related_name="+", symmetrical=False)
```
When Django processes this model, it identifies that it has a [ManyToManyField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.ManyToManyField) on itself, and as a result, it doesn’t add a person_set attribute to the Person class. Instead, the [ManyToManyField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.ManyToManyField) is assumed to be symmetrical – that is, if I am your friend, then you are my friend.
```
So `symmetrical=False` is exactly what we want, because this is defining a hierarchy.
And not wanting a related name sounds ok to me, too.

2023-11-30 17:37 UTC, mdellweg commented on pulpcore/app/viewsets/publication.py
> +        "core._viewer": ["core.view_compositecontentguard"],
```suggestion
        "core.compositcontentguard_viewer": ["core.view_compositecontentguard"],
```

2023-11-30 19:13 UTC, ggainey commented on pulpcore/app/models/publication.py
> +    guards = models.ManyToManyField(ContentGuard, related_name="+", symmetrical=False)
That was my reading as well - I feel better that we both arrived at the same place independently!

2023-11-30 19:19 UTC, ggainey commented on pulpcore/app/models/publication.py
> +    guards (django.contrib.postgres.fields.ArrayField): List of ContentGuards to examine.
Hm, while this may be correct under-the-hood, I need to decide if this is the correct way to document it. It's actually a QuerySet that is finding a list-of, let me correct this.

2023-12-01 07:53 UTC, mdellweg commented on pulpcore/app/models/publication.py
> +    guards = models.ManyToManyField(ContentGuard, related_name="+", symmetrical=False)
`symmetrical=True` would lead to infinite recursion, once you had a ccg reference another. Not that anyone would ever do that.

2023-12-01 07:56 UTC, mdellweg approved these changes

2023-12-01 11:04 UTC, dkliban approved these changes

2023-12-01 11:49 UTC, decko approved these changes

2023-12-01 12:28 UTC, merged