Protect distributed repo versions from cleanup
pulp/pulpcore pull request #4750
Opened 2023-11-21 15:12 UTC by daviddavis

This change protects repo versions from being cleaned up if they have publications that are being served by distributions.

fixes #2705

2023-11-27 13:17 UTC, mdellweg approved these changes

2023-11-27 13:17 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +
Circular Imports?

2023-11-27 13:45 UTC, daviddavis commented on pulpcore/app/models/repository.py
> +
Yes, exactly.

```
  File "/home/vagrant/devel/pulpcore/pulpcore/app/models/repository.py", line 20, in <module>
    from .publication import Distribution, Publication
  File "/home/vagrant/devel/pulpcore/pulpcore/app/models/publication.py", line 25, in <module>
    from .repository import Remote, Repository, RepositoryVersion
ImportError: cannot import name 'Remote' from partially initialized module 'pulpcore.app.models.repository' (most likely due to a circular import) (/home/vagrant/devel/pulpcore/pulpcore/app/models/repository.py)
```

2023-11-27 16:02 UTC, ipanova requested changes
This code does not work with plugins that do not have publications and repository/version can be served directly from distribution. Please update the code so it accounts for such plugins.
```
$ http DELETE https://puffy.example.com/pulp/api/v3/repositories/container/container/018bfb9a-ffa4-72e3-a9f4-f884f8719305/versions/1/ --auth admin:password
HTTP/1.1 500 Internal Server Error
Access-Control-Expose-Headers: Correlation-ID
Connection: keep-alive
Content-Length: 145
Content-Type: text/html; charset=utf-8
Correlation-ID: 0d33ccdcae8e431fbb34871ae3436d05
Cross-Origin-Opener-Policy: same-origin
Date: Mon, 27 Nov 2023 15:59:02 GMT
Referrer-Policy: same-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>

pulpcore-api[92257]:     if version in version.repository.protected_versions():
pulpcore-api[92257]:   File "/pulpcore/pulpcore/app/models/repository.py", line 333, in protected_versions
pulpcore-api[92257]:     latest_publication = publications.select_related("repository_version").latest(
pulpcore-api[92257]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 1045, in latest
pulpcore-api[92257]:     return self.reverse()._earliest(*fields)
pulpcore-api[92257]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 1028, in _earliest
pulpcore-api[92257]:     return obj.get()
pulpcore-api[92257]:   File "/usr/local/lib/pulp/lib64/python3.10/site-packages/django/db/models/query.py", line 637, in get
pulpcore-api[92257]:     raise self.model.DoesNotExist(
pulpcore-api[92257]: pulpcore.app.models.publication.Publication.DoesNotExist: Publication matching query does not exist.
^C
```

2023-11-27 16:34 UTC, daviddavis commented
@ipanova done.

2023-11-27 22:10 UTC, gerrod3 commented on pulpcore/app/models/repository.py
> +            versions = self.versions.complete().exclude(pk__in=self.cast().protected_versions())
Do you plan to allow plugins to customize the `protected_versions` method with this `cast` call?

2023-11-27 22:14 UTC, daviddavis commented on pulpcore/app/models/repository.py
> +            versions = self.versions.complete().exclude(pk__in=self.cast().protected_versions())
That was my thinking: if plugins want to protect repo versions for some reason they could define protected_versions.

2023-12-01 11:03 UTC, ipanova commented on docs/workflows/repo-versioning.rst
> +Cleanup will ignore any repo versions with publications that are being served by a distribution.
Cleanup will ignore any repo versions that are being served directly via a distribution or via a publication.

2023-12-01 11:04 UTC, ipanova commented on pulpcore/app/models/repository.py
> +        A protected version is one with a publication that is being served by a distro.
A protected version is one that is being served by a distro directly or via publication

2023-12-01 11:06 UTC, ipanova commented on pulpcore/app/models/repository.py
> +        qs = self.versions.filter(pk__in=Distribution.objects.values_list("repository_version__pk"))
please use repository_version_id

2023-12-01 11:06 UTC, ipanova commented on pulpcore/app/models/repository.py
> +            publication__pk__in=Distribution.objects.values_list("publication__pk")
same here

2023-12-01 11:16 UTC, ipanova commented on pulpcore/app/models/repository.py
> +            publication__pk__in=Distribution.objects.values_list("publication__pk")
there are few other instances down the road, better to use _id then .pk to not access another table

2023-12-01 11:18 UTC, ipanova commented on pulpcore/app/models/repository.py
> +                latest_publication = publications.select_related("repository_version").latest(
you probably do not need the select_related here if you stick to repo-version-id

2023-12-05 14:10 UTC, daviddavis commented
@ipanova @dralley thanks for the review. I think I've addressed everything.

2023-12-06 16:25 UTC, ipanova commented on pulpcore/app/models/repository.py
> +        if Distribution.objects.filter(repository=self.pk).exists():
@daviddavis sorry for not noticing this earlier. You are still missing the case when plugin distributes the repositry directly. In that case latest repo version is distributed.
So here you need to look for not only publication but also it's latest repo-version for the case when:
repository is distributed.

2023-12-06 18:13 UTC, ipanova approved these changes

2023-12-07 16:29 UTC, ipanova submitted a review, later dismissed

2023-12-07 16:52 UTC, mdellweg commented on pulpcore/app/models/repository.py
> +            if distro.cast().SERVE_FROM_PUBLICATION:
```suggestion
            if distro.detail_model().SERVE_FROM_PUBLICATION:
```

2023-12-07 17:01 UTC, mdellweg approved these changes

2023-12-07 17:06 UTC, daviddavis commented on pulpcore/app/models/repository.py
> +            for version in versions.order_by("-number")[self.retain_repo_versions :]:
Exactly, as I would say, protected repo versions are excluded from`retain_repo_versions`. 

And I think this makes sense. Suppose `retain_repo_versions` was 1 and you already had 1 protected version. Then if you created another version, it would immediately get cleaned up.

2023-12-07 17:26 UTC, ipanova approved these changes

2023-12-07 17:27 UTC, merged