Fix a race condition in distribution filtering
pulp/pulpcore pull request #4767
Opened 2023-11-23 12:28 UTC by mdellweg

This change adds a `detail_model` property to the master-detail concept and removes a race condition by replacing calls to `cast` with it in `DistributionWithContentFilter`.

fixes #4766

2023-11-27 22:01 UTC, gerrod3 reviewed
Was `cast` really causing a DB call? I thought you changed it a while back to use the lookup table?

2023-11-28 08:03 UTC, mdellweg commented
I changed it from recursive to using the lookup table, but it still needs look at the detail db-table.
And is this case we really only want to know about a class attribute.

2023-11-28 15:04 UTC, gerrod3 approved these changes
I think the race condition window is still present, just much smaller without all the extra `cast` db calls.

2023-11-28 16:25 UTC, mdellweg commented
> I think the race condition window is still present, just much smaller without all the extra `cast` db calls.

Where do you see that race?

2023-11-29 04:15 UTC, gerrod3 requested changes

2023-11-29 04:15 UTC, gerrod3 commented on pulpcore/app/viewsets/custom_filters.py
>          for dist in qs.exclude(repository_version=None).values("repository_version", "pk"):
```suggestion
        for dist in qs.exclude(repository_version=None).values("repository_version", "pulp_type"):
```
We need to pull in the `pulp_type` or else the `detail_model` call will trigger a db lookup. `pk` is always pulled in, so no need to list it.

2023-11-29 04:15 UTC, gerrod3 commented on pulpcore/app/viewsets/custom_filters.py
>          for dist in qs.exclude(repository=None).prefetch_related("repository__versions"):
> > I think the race condition window is still present, just much smaller without all the extra `cast` db calls.
> 
> Where do you see that race?

I'm not sure, but I have a feeling that there might be race condition in this loop. There are so many queries being performed here, that it just seems likely we would encounter one here. Also, this `prefetch_related` is probably doing nothing but adding an extra query. This loop probably needs to be refactored somehow.

2023-11-29 10:32 UTC, mdellweg commented on pulpcore/app/viewsets/custom_filters.py
>          for dist in qs.exclude(repository=None).prefetch_related("repository__versions"):
I believe the race was that the query with `.exclude(repository=None)` returned a distribution that after casting actually had `dist.repository == None`. And I don't see that this can happen again. But, there may be more such windows for sure.

2023-12-01 21:07 UTC, ggainey approved these changes

2023-12-01 21:07 UTC, merged