Convert pulp-certguard and pulp-file to new docs stack.
pulp/pulpcore pull request #5070
Opened 2024-02-19 16:34 UTC by ggainey

2024-02-19 19:53 UTC, pedro-psb requested changes
I've suggested some changes in content types, according to what I understand is the main purpose of each page. Feel free to present another point of view!

Also, you've included both pulp_certguard and pulp_file here, so I think you can close https://github.com/pulp/pulpcore/pull/5069/files and let it be merged here.

2024-02-19 19:53 UTC, pedro-psb commented on pulp_certguard/staging_docs/user/tutorials/overview.md
I think thats a Learn content, as it explains some aspects of the plugin and do not provide steps to achieve a specific goal (theoretical knowledge in learning time).

2024-02-19 19:53 UTC, pedro-psb commented on pulp_certguard/staging_docs/user/tutorials/usage.md
This could be what I'm calling a plugin "quickstart", which is the first and essential contact someone must have with the plugin. I think it doesn't yet have a very "tutorial style", but it seems the purpose (to teach basic pulp_file stuff through a workflow example).

Also, renaming it to `quickstart.md` and the title to Quickstart will make it appear as the first page in the plugin submenu, giving it some highlight.

2024-02-19 19:53 UTC, pedro-psb commented on pulp_file/staging_docs/user/tutorials/00-overview.md
Would add this as overview of `guides`, or to `learn` as something like `About File Repositories`.

2024-02-19 19:53 UTC, pedro-psb commented on pulp_file/staging_docs/user/tutorials/01-sync.md
Looks a how-to guide, as it provided straightforward steps to achieve a goal (practical knowledge in working time)

2024-02-19 19:53 UTC, pedro-psb commented on pulp_file/staging_docs/user/tutorials/02-publish-host.md
Looks a how-to guide, as it provided straightforward steps to achieve a goal (practical knowledge in working time)

2024-02-19 19:53 UTC, pedro-psb commented on pulp_certguard/staging_docs/admin/learn/reverse_proxy_config.md
Looks a how-to guide, as it provided straightforward steps to achieve a goal which is to "Configure a Reverse Proxy" (practical knowledge in working time)

2024-02-27 17:47 UTC, pedro-psb approved these changes

2024-02-28 16:54 UTC, gerrod3 submitted a review, later dismissed

2024-02-28 18:34 UTC, pedro-psb approved these changes

2024-02-28 19:16 UTC, lubosmj reviewed
I left a couple of suggestions. Great job so far!

2024-02-28 19:16 UTC, lubosmj commented on pulp_certguard/staging_docs/user/tutorials/quickstart.md
> +`$ http --cert ~/client.pem --cert-key ~/key.pem https://localhost/pulp/content/somepath/test.iso`
```
$ http --cert ~/client.pem --cert-key ~/key.pem https://localhost/pulp/content/somepath/test.iso
```

I like the code block more. Can we change it?

2024-02-28 19:16 UTC, lubosmj commented on pulp_file/staging_docs/user/guides/02-publish-host.md
> +
```suggestion
this, see the [sync](site:/pulp_file/docs/user/guides/01-sync.md) or [upload](site:/pulp_file/docs/user/guides/02-upload.md) documentation.

```

2024-02-28 19:16 UTC, lubosmj commented on pulp_certguard/staging_docs/user/tutorials/yum-howto.md
> +<https://docs.pulpproject.org/pulp_rpm/workflows/create_sync_publish.html>
A reference to the old documentation should be eliminated. Do you agree?

2024-02-28 19:16 UTC, lubosmj commented on pulp_file/staging_docs/user/guides/02-publish-host.md
> +    ```
This is rendered as:
![image](https://github.com/pulp/pulpcore/assets/8740962/e82c5991-aad8-47d5-b0b4-f2722623aa3b)

Perhaps, because of the indentation.

2024-02-29 20:19 UTC, lubosmj commented on pulp_file/staging_docs/user/learn/00-overview.md
> +`filename,sha256-checksum,size-in-bytes` . Pulp creates a PULP_MANIFEST when you [publish](site:/pulp_file/user/tutorials/02-publish-host.md)
```suggestion
`filename,sha256-checksum,size-in-bytes` . Pulp creates a PULP_MANIFEST when you [publish](site:/pulp_file/docs/user/tutorials/02-publish-host.md)
```

2024-02-29 20:34 UTC, ggainey commented on pulp_file/staging_docs/user/learn/00-overview.md
> +`filename,sha256-checksum,size-in-bytes` . Pulp creates a PULP_MANIFEST when you [publish](site:/pulp_file/user/tutorials/02-publish-host.md)
Worse than that - the file moved, *and* we don't specify the .md anymore!

Wants to be `site:/pulp_file/docs/user/guides/02-publish-host/`

2024-02-29 21:52 UTC, lubosmj approved these changes

2024-03-01 17:53 UTC, pedro-psb approved these changes

2024-03-03 06:32 UTC, gerrod3 approved these changes

2024-03-03 12:02 UTC, merged