Fix replicate for a distribution with publication
pulp/pulpcore pull request #5140
Opened 2024-03-19 16:21 UTC by mdellweg

In case a distribution that is supposed to be subject to replication is referring to a publication (because it was created by someone else) we need to unset the publication field for the replicate task to succeed.

fixes #4637

2024-03-19 16:24 UTC, mdellweg commented on pulpcore/app/replica.py
> +        }
Do we need to defer this to another method so it can easily be overwritten by a Replicator subclass?

Also why do distributions have names. They can perfectly be identified by their base_path, why do publications not have names? They are sooo hard to identify.

2024-03-19 20:26 UTC, mdellweg commented
I do not understand the test failure. It runs fine on my box. And i guess the green runs are the ones where domains are unavailable and the test is skipped.

2024-03-20 14:17 UTC, mdellweg commented on pulpcore/app/replica.py
> +                shared_resources=[repository],
I think this is what was missing. We need to wait for the sync to complete before we can assign the repository to the distribution.

But anyway, share-locking the repository should have been here all the way.

2024-03-21 14:42 UTC, gerrod3 requested changes

2024-03-21 14:42 UTC, gerrod3 commented on pulpcore/app/replica.py
> +                general_multi_delete,
Nice use of multi-delete.

2024-03-21 14:42 UTC, gerrod3 commented on pulpcore/tests/functional/__init__.py
> +def domain_factory(domains_api_client, pulp_settings, gen_object_with_cleanup):
Did you change anything by moving this fixture up the file? Also, do you want to change this to use `pulpcore_bindings`?

2024-03-21 14:42 UTC, gerrod3 commented on pulpcore/tests/functional/api/test_replication.py
> +
Should there be any other actions here on the source domain or replica domain, like a new repository, new distribution, new content?

2024-03-21 14:42 UTC, gerrod3 commented on pulpcore/app/replica.py
> +        # TODO check and compare this to distribution locking on the distribution viewset.
Distribution viewset lock should be updated to match this.

2024-03-21 14:42 UTC, gerrod3 commented on pulpcore/app/replica.py
> +        }
> Do we need to defer this to another method so it can easily be overwritten by a Replicator subclass?

I would say so since plugins can have extra fields on their distribution models.

2024-03-21 16:33 UTC, mdellweg commented on pulpcore/tests/functional/__init__.py
> +def domain_factory(domains_api_client, pulp_settings, gen_object_with_cleanup):
No change just moved it to the factories section.
Some people seem to follow an always add to the end of the file policy.
But yes, good call there.

2024-03-21 16:54 UTC, mdellweg commented on pulpcore/app/replica.py
> +        # TODO check and compare this to distribution locking on the distribution viewset.
This is another issue that may need more thinking to get it upgrade safe.
https://github.com/pulp/pulpcore/issues/5143

2024-03-21 16:57 UTC, mdellweg commented
@gerrod3 Does this address all your requests now?

2024-03-21 19:03 UTC, gerrod3 approved these changes

2024-03-22 14:23 UTC, dkliban approved these changes

2024-03-22 14:23 UTC, merged