Include a new SecurityScheme for external authentication
pulp/pulpcore pull request #5193
Opened 2024-03-27 20:05 UTC by decko

Closes #5179

2024-04-02 11:35 UTC, mdellweg reviewed
I'm increasingly confused.
How come that the HeaderTokenAuthentication is not described as a token bearer, but OAuth2? Are we reimplementing half of the OAuth2 protocol here?

2024-04-02 11:35 UTC, mdellweg commented on pulpcore/openapi/__init__.py
> +    name = settings.REMOTE_AUTHENTICATION_DISCOVERY_PAYLOAD.pop("name", None)
Did you know that `pop` had a side effect?

Also why consulting the settings anyway? Is there a reason not to link it to the HeaderAuth class directly?

2024-04-02 11:35 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +@pytest.mark.from_pulpcore_for_all_plugins
I don't think this is useful?

2024-04-02 12:53 UTC, dkliban commented
> I'm increasingly confused. How come that the HeaderTokenAuthentication is not described as a token bearer, but OAuth2? Are we reimplementing half of the OAuth2 protocol here?

The new setting[0] is supposed to allow the user to add an additional `securityScheme`[1] when an external authentication method is used. The possible `type` values for a `securityScheme` are `"apiKey", "http", "mutualTLS", "oauth2", "openIdConnect"`. 

[0] https://github.com/pulp/pulpcore/issues/5179
[1] https://spec.openapis.org/oas/latest.html#security-scheme-object

2024-04-02 17:37 UTC, decko commented on pulpcore/openapi/__init__.py
> +    name = settings.REMOTE_AUTHENTICATION_DISCOVERY_PAYLOAD.pop("name", None)
> Did you know that `pop` had a side effect?

Like, remove the attribute from the dict?

2024-04-02 17:45 UTC, decko commented on pulpcore/openapi/__init__.py
> +    name = settings.REMOTE_AUTHENTICATION_DISCOVERY_PAYLOAD.pop("name", None)
> Also why consulting the settings anyway? Is there a reason not to link it to the HeaderAuth class directly?

Different gateways have different behaviors. I don't think we want the schema to be triggered every time we use the `JSONHeaderRemoteAuthentication` class.

2024-04-02 17:47 UTC, decko commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +@pytest.mark.from_pulpcore_for_all_plugins
Removed.

2024-04-03 06:02 UTC, mdellweg requested changes

2024-04-03 06:02 UTC, mdellweg commented on template_config.yml
> +      }
Who said, this needs to be a string?

2024-04-03 13:49 UTC, decko commented on template_config.yml
> +      }
tried with the `|` operator without success.

2024-04-03 13:50 UTC, decko commented on pulpcore/openapi/__init__.py
> +    name = "oauth2"
Do you have a suggestion?

2024-04-03 13:51 UTC, mdellweg commented on template_config.yml
> +      }
This is templated with a tojson filter.

2024-04-03 13:58 UTC, dkliban commented on docs/authentication/json_header.rst
>    REMOTE_AUTHENTICATION_DISCOVERY_PAYLOAD = {
How about `AUTHENTICATION_JSON_HEADER_OPENAPI_SECURITY_SCHEME` or `AUTHENTICATION_JSON_HEADER_OPENAPI` ?

2024-04-03 19:10 UTC, decko commented on template_config.yml
> +      }
When I use something like this:
```yaml
  remote_authentication_discovery_payload: |
    {
      "type": "oauth2",
      "description": "External OAuth integration",
      "flows": {
          "clientCredentials": {
              "tokenUrl": "https://your-identity-provider/token/issuer",
              "scopes": {"api.console":"grant_access_to_pulp"}
          }
      }
    }
```
then I receive an error like this https://github.com/pulp/pulpcore/actions/runs/8544072240/job/23409355496?pr=5193#step:10:231

2024-04-03 19:11 UTC, decko commented on template_config.yml
> +      }
Also we had this conversation here https://matrix.to/#/!aVApiNMtnstWbwDcVU:matrix.org/$7Nnw_2SeKM-znGqmP4MNQsiaapY36bemYZtkIhKwAYs?via=matrix.org&via=ctrl-c.liu.se&via=x9c4.spdns.org

2024-04-04 09:26 UTC, mdellweg commented on template_config.yml
> +      }
"|" makes it a multiline string. It should not be a string though. You want the full dict here.

2024-04-04 09:53 UTC, mdellweg requested changes

2024-04-04 09:53 UTC, mdellweg commented on docs/authentication/json_header.rst
> +it and obtain the correct data. The user is created in the database if one is not found.
```suggestion
it and obtain the relevant data. The user is created in the database if one is not found.
```

2024-04-04 09:53 UTC, mdellweg commented on docs/authentication/json_header.rst
> +It's a common scenario where Pulp is behind an API Gateway which handles the authenatication process.
I would not call this common.
More like "In case, Pulp is deployed..., you need to adjust the OpenAPI security schema definitions."

2024-04-04 09:53 UTC, mdellweg commented on docs/authentication/json_header.rst
> +  AUTHENTICATION_JSON_HEADER_OPENAPI_SECURITY_SCHEME = {
Maybe use the tabs feature and provide a bearer and an oauth2 stanza.

2024-04-04 09:53 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    assert "clientCredentials" in oauth_security_scheme["flows"]
This is assuming things only defined in the CI setup.
Can't we just compare with the setting? Because that is what we want to code to do: Present what is configured.

2024-04-04 09:53 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +## Enabling the ThirdParty Authentication Schema
Obviously this is the place where my comments should go.
I don't think we are supposed to write rst docs anymore.

2024-04-04 09:53 UTC, mdellweg commented on template_config.yml
> +      }
... yaml syntax.

2024-04-04 13:52 UTC, decko commented on template_config.yml
> +      }
THanks man. It worked

2024-04-04 17:10 UTC, decko commented on staging_docs/admin/guides/authentication/05-json_header.md
> +## Enabling the ThirdParty Authentication Schema
I think we will stop when the moving is done.

2024-04-04 18:24 UTC, dkliban commented on docs/authentication/json_header.rst
> +`Security Scheme Object definition <https://swagger.io/specification/#security-scheme-object>`_. Here is an example describing
Let's link to the openapis.org site instead. https://spec.openapis.org/oas/latest.html#security-scheme-object
Swagger.io is a private company that is now separate from OpenAPI Initiative.

2024-04-04 18:31 UTC, dkliban reviewed
This looks good overall. Just asked for one change in the docs. 

Btw, you don't have to update the rst docs. The new docs are the main focus now.

2024-04-04 20:02 UTC, dkliban submitted a review, later dismissed

2024-04-05 14:55 UTC, mdellweg commented on pulpcore/app/settings.py
> +
???

2024-04-05 15:20 UTC, mdellweg requested changes

2024-04-05 15:20 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    )
This redefinition does not help readability of the test in my opinion.

2024-04-05 15:20 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    is located at the template_config.yml file under
This is not true for any other then gh ci way of running tests. Just don't mention it.

2024-04-05 15:20 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    assert {*authentication_json_header_openapi_security_scheme} <= {*security_scheme}
Can you explain what this test is supposed to do and especially why a simple `==` would not work? I thought we configured the exact thing we expect the api docs to provide.

2024-04-05 15:20 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +=== HTTP Basic Authentication
You could have taken the api_key or the JWT bearer example. But it's unclear to me how basic auth could be setup as external authentication.

2024-04-05 15:20 UTC, mdellweg commented on template_config.yml
> +                api.console: "grant_access_to_pulp"
Ahh, it works in the easiest way imaginable.
Only that the CI update will reformat this file eventually.

2024-04-05 15:20 UTC, mdellweg commented on pulpcore/app/settings.py
> +
This looks like a noop.

2024-04-08 12:59 UTC, decko commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    assert {*authentication_json_header_openapi_security_scheme} <= {*security_scheme}
It tests if it renders the same body found on the config, at least the keys on the first level.

2024-04-08 13:03 UTC, decko commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    )
Changed to a simpler name.

2024-04-08 13:05 UTC, decko commented on staging_docs/admin/guides/authentication/05-json_header.md
> +=== HTTP Basic Authentication
The API Gateway could require any authentication mechanism to protect the desired endpoint. Even HTTP Basic Auth.
But I will add another method here to make things clear.

2024-04-08 18:00 UTC, decko commented on pulpcore/app/settings.py
> +
Refactored to make it more clear.

2024-04-10 14:40 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +=== HTTP Basic Authentication
So the api gateway is transparently translating the basic auth header into the json header with the username? OK.
But if the user needs to talk to another server to obtain a token, that is called 'token bearer'.

2024-04-10 14:43 UTC, mdellweg commented on pulpcore/tests/functional/api/test_openapi_schema.py
> +    assert {*authentication_json_header_openapi_security_scheme} <= {*security_scheme}
I see that, but why? Do we expect there to be more? Don't the values count too?
Why the extra hoops to make the assertion fuzzy?

2024-04-12 10:50 UTC, decko commented on staging_docs/admin/guides/authentication/05-json_header.md
> +=== HTTP Basic Authentication
If that token is obtained using `oauth2` or `openidconnect` this will not be an issue. It's part of the spec.
Using other methods require that the service being accessed be the issuer of the credential itself. Basic Auth as ex.

2024-04-12 13:06 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +In a case where Pulp is deployed behind an API Gateway, it may be necessary to indicate to the clients where and which authorization process to use.
```suggestion
In a case where Pulp is deployed behind an API Gateway, it may be necessary to indicate to the clients which authorization process to use.
```

2024-04-12 14:20 UTC, mdellweg reviewed
Please also merge the commits.

2024-04-12 14:20 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +OpenAPI security schema describing it to be used by clients or Pulp-CLI itself.
```suggestion
In a case where Pulp is deployed behind an API Gateway which could require a specific authentication schema, it may be necessary to indicate to the clients which authorization process to use.
For this scenario, you may be able to provide an OpenAPI security schema describing it to be interpreted by clients.
```

2024-04-12 14:20 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +an OAuth2 and a HTTP Basic authentication system:
```suggestion
To enable that, you have to configure the `AUTHENTICATION_JSON_HEADER_OPENAPI_SECURITY_SCHEME` setting with a payload following the [Security Scheme Object definition](https://spec.openapis.org/oas/latest.html#security-scheme-object).
Here are some examples describing a HTTP basic auth, a simple bearer server and an OAuth2 authentication scheme:
```

2024-04-15 14:16 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +an OAuth2 and a HTTP Basic authentication system:
I don't see this resolved.
My suggestion was to add the bearer scenario to the description, because we have the example below.

2024-04-15 14:17 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +OpenAPI security schema describing it to be used by clients or Pulp-CLI itself.
Suggestion was: "clients." Don't mention a specific one.

2024-04-15 14:18 UTC, mdellweg commented on staging_docs/admin/guides/authentication/05-json_header.md
> +an OAuth2 and a HTTP Basic authentication system:
Maybe you resolved, but did forget to push?

2024-04-15 17:51 UTC, dkliban approved these changes

2024-04-15 22:16 UTC, mdellweg approved these changes

2024-04-16 13:20 UTC, merged