Add Worker metrics.
pulp/pulpcore pull request #5234
Opened 2024-04-08 22:38 UTC by decko

- [X] Report the number of workers online
- [] Report the number of tasks
- [] Report the number of tasks blocked
- [] Report the number of workers busy
- [] Report the Avg time of a task to be executed after join a queue
- [] Report the number of tasks canceled

Close #3821

2024-04-19 20:26 UTC, decko commented on pulpcore/app/models/telemetry.py
> +    # @pg_lock
WIP. Ideas on how to abstract this are welcome.

2024-04-19 20:26 UTC, decko commented on pulpcore/app/models/telemetry.py
> +    def emmit_unblocked_waiting_tasks_metric(self, model):
Receiving the model object to avoid circular imports

2024-04-19 20:27 UTC, decko commented on pulpcore/tasking/worker.py
> +        # self.worker_counter.add(-1, attributes={"name": self.name})
Remove in a future iteration

2024-04-19 20:28 UTC, decko commented on pulpcore/tests/functional/__init__.py
> +    def _received_otel_metric(data, retries=3):
Looking to find a way to avoid all this code duplication here

2024-04-19 20:29 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    metrics = json.loads(response.content)
Hey @lubosmj, wdyt about removing the server side assertion we have today for a local one? Like, on test/client side?

2024-04-19 20:29 UTC, decko commented on pulpcore/tests/functional/assets/otel_server.py
> +                    translated_metric["unit"] = metric.unit
We wanna test metric attributes? For sure.

2024-04-22 22:00 UTC, decko commented on pulpcore/app/models/telemetry.py
> +    # @pg_lock
Gonna use the PGAdvisoryLock context manager.

2024-04-23 07:53 UTC, lubosmj commented on pulpcore/tests/functional/api/test_tasking.py
> +    metrics = json.loads(response.content)
We can try working on this. Though, we would need to download all data from the server to perform the comparison on the client's side. Maybe, you are thinking about taking a different approach?

2024-04-23 12:15 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +            self.record_unblocked_waiting_tasks_metric()
Please run this from the worker heartbeat routine only.

2024-04-24 17:58 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    metrics = json.loads(response.content)
Nope. I was thinking on download things and test directly on our side.

2024-04-24 17:59 UTC, decko commented on pulpcore/tasking/worker.py
> +            self.record_unblocked_waiting_tasks_metric()
You say on `def beat` definition?

2024-04-25 18:02 UTC, decko commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_trigger, '{time_trigger}'")
Trigger the record ;)

2024-04-25 18:03 UTC, decko commented on pulpcore/tasking/worker.py
> +        for task in tasks_incomplete_states:
Sorry, gonna undo that. It was an idea to extract the first metric draft from this query itself.

2024-04-25 18:12 UTC, decko commented on pulpcore/tasking/worker.py
> +    TASK_METRIC_TRIGGER_LOCK,
Done

2024-04-25 18:12 UTC, decko commented on pulpcore/tasking/worker.py
> +        elif notification.channel == "pulp_worker_metrics_trigger":
Done

2024-04-26 09:30 UTC, mdellweg commented on pulpcore/constants.py
> +TASK_METRICS_HEARTBEAT_LOCK = 74
That's your favorite number then?

2024-04-26 09:30 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +        self.last_metric_heartbeat = timezone.now()
:+1: So this is never None.

2024-04-26 09:30 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{time_heartbeat}'")
No triggering here.

2024-04-26 09:30 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +        if self.last_metric_heartbeat:
unneeded if.

2024-04-26 09:30 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +            worker_ttl_delta = timedelta(seconds=(settings.WORKER_TTL / 3))
Don't recalculate stuff in the hot code paths.

2024-04-26 11:59 UTC, lubosmj commented on pulpcore/tasking/worker.py
> +                                longest_age=Coalesce(Max("unblocked_for"), timezone.timedelta(0)),
```suggestion
                                longest_age=Max("unblocked_for", default=timezone.timedelta(0),
```
Is this one possible?

2024-04-26 12:10 UTC, lubosmj commented on pulpcore/tests/functional/assets/otel_server.py
> +                    _logger.info("Received a {} metric meter".format(translated_metric["name"]))
We are logging metrics every time we receive them during the testing. This might clutter our logs a bit.

2024-04-26 12:13 UTC, lubosmj commented on pulpcore/tests/functional/assets/otel_server.py
> +                    translated_metric["unit"] = metric.unit
I would go even further and would try to test the value of the gauge if it is is possible with the current implementation. Do we test one of the following somewhere now?
```
1. Number of unblocked waiting tasks waiting more than 5 seconds
2. the longest waiting task time
```

2024-04-26 12:29 UTC, ipanova commented on pulpcore/exceptions/__init__.py
> +    AdvisoryAcquireLockError,
These do not seem to be used anywhere.

2024-04-26 12:33 UTC, decko commented on pulpcore/tasking/worker.py
> +                                longest_age=Coalesce(Max("unblocked_for"), timezone.timedelta(0)),
I think it is. Gonna test it before committing your suggestion.

2024-04-26 12:33 UTC, decko commented on pulpcore/tests/functional/assets/otel_server.py
> +                    _logger.info("Received a {} metric meter".format(translated_metric["name"]))
Check on line 87. We drop the ones we don't need right now

2024-04-26 12:33 UTC, decko commented on pulpcore/tests/functional/assets/otel_server.py
> +                    translated_metric["unit"] = metric.unit
Still trying to understand how to convert it properly to a python dict.
Maybe it would be better if we just retrieve the protobuf data and test over it.

2024-04-26 13:02 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                    with PGAdvisoryLock(TASK_METRICS_HEARTBEAT_LOCK):
And perstering the database for it.

2024-04-26 13:52 UTC, decko commented on pulpcore/exceptions/__init__.py
> +    AdvisoryAcquireLockError,
Thanks Ina! Forgot to remove them.

2024-04-26 13:55 UTC, mdellweg commented on pulpcore/tasking/worker.py
>                  except AdvisoryLockError:
I prefer suppress.

2024-04-26 13:55 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +
We should send this while still holding the lock.
Also we can reuse the time we we gathered at the beginning of the locked part.

2024-04-26 13:59 UTC, decko commented on pulpcore/tasking/worker.py
> +                                longest_age=Max("unblocked_for", default=timezone.timedelta(0)),
Thanks @lubosmj

2024-04-26 14:42 UTC, decko commented on pulpcore/tasking/worker.py
> +
Done

2024-04-28 07:08 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                )
Can we have a more consistent naming schema? Like "{name}_meter" for the variable?

Also is it worth keeping these objects on the class instead of recreating them?

2024-04-28 07:08 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                    name="tasks_longest_waiting_task",
Try to find a name that reflects the contents. This name suggests we report a task.

2024-04-28 07:08 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                )
I am not convinced, that breaking up the query into multiple statements makes it any more readable.
This is about unblocked tasks. I got that after the second occurrence of unblocked.
Instead, make sure the annotation variables match the names of your meters.

2024-04-29 11:19 UTC, decko commented on pulpcore/tasking/worker.py
> +                )
> Also is it worth keeping these objects on the class instead of recreating them?

The way we're doing now it creates/recover just one instance each time we're about to send the metric. If I set this directly on the class we'll create the same number of instances but just one will send the metrics.

2024-04-29 11:27 UTC, decko commented on pulpcore/tasking/worker.py
> +                )
I think it makes easier for another person to quickly understand each step of the query. Since this is not increasing the cost of the query itself, I think it's  good to keep it as it is now.
Also, I changed the names. Thanks for the suggestion.

2024-04-29 13:00 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +from datetime import datetime, timedelta
does it provede timedelta too?

2024-04-30 06:57 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                self.changes_on_queue = True
Move it up one frame.
Also a queue changes when you remove one element from the front too.

2024-04-30 06:57 UTC, mdellweg commented on template_config.yml
> +  otel_metric_export_interval: 800
Is this used anywhere?

2024-04-30 06:57 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                [self.sentinel, connection.connection], [], [], self.heartbeat_period.seconds
Ahh, that explains why we didn't have it as timedelta before.

2024-04-30 07:03 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                )
It doubles the space taken up on my screen and also doubles the reading time. And a variable name like `some_query_annotated` does not convey any new information at all.
If you want to help people in the future to understand what's going on, then instead, make the code succinct and add a comment, about why the hell this is compiled into a single query.

2024-04-30 10:21 UTC, decko commented on template_config.yml
> +  otel_metric_export_interval: 800
Yes. we need it for the tests since the default timeout is 60 seconds.

2024-04-30 10:22 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    sleep(worker_heartbeat)
I know, but got no other solution than "wait for the metrics to be flushed"

2024-04-30 20:36 UTC, decko commented on pulpcore/tasking/worker.py
> +from datetime import datetime, timedelta
Nope. And also the Django's timezone doesn't provide the `fromisostring` method. So I had to return the datetime module here.

2024-05-02 17:03 UTC, ggainey requested changes
Wordsmithing pass w/ some suggestions.

2024-05-02 17:03 UTC, ggainey commented on pulpcore/tasking/worker.py
> +# Until we understand they aren't settings properly they gonna live as constants
Unless/until we can provide reasonable ways to decide to change their values, the will live as constants instead of "proper" settings.

2024-05-02 17:03 UTC, ggainey commented on pulpcore/tasking/worker.py
> +# Threshold time in seconds of an unblocked task to consider a queue stalled
```suggestion
# Threshold time in seconds of an unblocked task before we consider a queue stalled
```

2024-05-02 17:03 UTC, ggainey commented on pulpcore/tasking/worker.py
> +                # Don't consider this tasks resources as held.
```suggestion
                # Don't consider this task's resources as held.
```

2024-05-02 17:56 UTC, decko commented
> Wordsmithing pass w/ some suggestions.

Without works to thank you enough. 🙏🏽

2024-05-02 17:58 UTC, ggainey submitted a review, later dismissed

2024-05-02 18:01 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        dispatch_task("pulpcore.app.tasks.test.sleep", args=(0,), exclusive_resources=[resource])
By making these tasks require the same resource we do not generate unblocked tasks.
Instead we should start one long running task per worker and then we can add further tasks (all without rousources probably) to have something to report on.

2024-05-03 07:38 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        dispatch_task("pulpcore.app.tasks.test.sleep", args=(0,), exclusive_resources=[resource])
And don't forget to cancel the tasks after receiving the desired stats.

2024-05-03 14:36 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    for dummy in range(workers_count * 5):
You are still just creating a bunch of blocked tasks.
Also why 5 extra tasks per worker. And where do we extract the number and age of blocked tasks now?
In it's current form, this test tells us very little about the feature it's supposed to test.

2024-05-03 19:39 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    for dummy in range(workers_count * 5):
You're right. I've fixed that in the latest changes.
But, some how, the unblocked tasks got executed before the long-running ones. 
https://github.com/pulp/pulpcore/actions/runs/8943880878/job/24569587920#step:14:956

Am I missing something here?

2024-05-03 23:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        )
```suggestion
    resident_task_hrefs = [dispatch_task("pulpcore.app.tasks.test.sleep", args=(30,)) for worker in range(workers_online)]
```

2024-05-03 23:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    )
```suggestion
    )
    
    [pulpcore_bindings.TasksApi.cancel(href) for href in resident_task_hrefs]
```

2024-05-03 23:58 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    )
What about the value of the metric?

2024-05-06 09:06 UTC, lubosmj commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{str(now)}'")
I would think we do not need to re-notify the worker, do we?

2024-05-06 09:06 UTC, lubosmj commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
Is there any safeguard that prohibits the execution of this method if the telemetry is disabled?

2024-05-06 09:09 UTC, lubosmj commented on CHANGES/3821.feature
> +And `pulp_tasks_longest_unblocked_waiting_time` has the time in seconds of the longest waiting time for a task in the queue.
Added two new metrics for Tasks: ``pulp_tasks_unblocked_waiting_queue`` now tracks the number of unblocked tasks waiting for over five (5) seconds, while ``pulp_tasks_longest_unblocked_waiting_time`` records the longest wait time, in seconds, for a task in the queue.

2024-05-06 09:12 UTC, lubosmj reviewed
At this stage of the implementation, I think we can squash all the commits into a single one. What do you think?

2024-05-06 14:06 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{str(now)}'")
We notify all workers, that the work was done. So they hold off of doing it for another cooldown time.

2024-05-06 14:07 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{str(now)}'")
But since you asked, a comment to that end may help.

2024-05-06 16:01 UTC, decko commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{str(now)}'")
Thanks man. In the end I removed since it doesn't make sense to be used anymore.

2024-05-06 16:15 UTC, mdellweg commented on pulpcore/tasking/worker.py
> -            self.cursor.execute("UNLISTEN pulp_worker_metrics_heartbeat")
Don't remove this logic. It is there to establish a cluster wide cooldown sending the metric.

2024-05-06 16:31 UTC, decko commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
Nope. It simply will not be emitted if the agent is not used.

2024-05-06 16:34 UTC, decko commented on pulpcore/tasking/worker.py
> -            self.cursor.execute("UNLISTEN pulp_worker_metrics_heartbeat")
Thanks man. My head is not working properly today.

2024-05-06 16:35 UTC, decko commented on pulpcore/tasking/worker.py
> +                self.cursor.execute(f"NOTIFY pulp_worker_metrics_heartbeat, '{str(now)}'")
Sorry @lubosmj. @mdellweg reminded me why we're using this. https://github.com/pulp/pulpcore/pull/5234#pullrequestreview-2041172514

2024-05-06 16:39 UTC, decko commented on CHANGES/3821.feature
> +And `pulp_tasks_longest_unblocked_waiting_time` has the time in seconds of the longest waiting time for a task in the queue.
Used some of your suggestions man.

2024-05-06 16:44 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    )
As we talked before, this involves some changes to the test machinery, and yet we probably won't be able to catch the right value for the metric during the tests.
Talking with @lubosmj and @dkliban we understood that changing to use the OpenTelemetry Collector and test the metrics as it's exported to be consumed by Prometheus could generate better results. Yet, it's a considerable effort that is out of the scope of this task.

2024-05-07 09:56 UTC, mdellweg commented on pulpcore/app/models/task.py
Try to avoid changing unrelated files.

2024-05-07 09:56 UTC, mdellweg commented on pulpcore/tests/functional/assets/otel_server.py
> +c_handler = logging.StreamHandler()
```suggestion
```

2024-05-08 15:09 UTC, mdellweg commented on pulpcore/app/models/task.py
This file is still in the diff for unnecessary whitespace changes.

2024-05-13 09:53 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    workers_online = pulpcore_bindings.WorkersApi.list(last_heartbeat__gte=age_threshold).count
AFAIK: There's "online" filter in the api. We should not repeat to implement that logic here.

2024-05-13 09:53 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
The question is valid. In the current state, we still run the query even if we send nothing.

2024-05-13 14:02 UTC, decko commented on pulpcore/tests/functional/api/test_tasking.py
> +    workers_online = pulpcore_bindings.WorkersApi.list(last_heartbeat__gte=age_threshold).count
Thanks!

2024-05-13 14:25 UTC, mdellweg reviewed
There's the last question remaining, how to avoid the costly db queries on systems that do not run with otel.

2024-05-13 14:25 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    workers_online = pulpcore_bindings.WorkersApi.list(online="true").count
:+1:

2024-05-14 11:37 UTC, ipanova commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
don't we have an otel_enabled setting we can look at?

2024-05-21 16:38 UTC, lubosmj commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
Not yet, we have just an environment variable that can be used for a lookup (https://github.com/pulp/pulpcore/blob/455ce9a8442c380d6e0d6a2853152e6c0be77d34/docs/components.rst?plain=1#L168).

I can imagine doing something similar to [DomainMetricsEmitter.build()](https://github.com/pulp/pulpcore/blob/455ce9a8442c380d6e0d6a2853152e6c0be77d34/pulpcore/app/util.py#L564) here.

2024-05-21 17:40 UTC, decko commented on pulpcore/tasking/worker.py
> +    def record_unblocked_waiting_tasks_metric(self):
I did it in the tests. Gonna work on the same thing here.

2024-05-22 12:10 UTC, decko commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
it works when we set a `PULP_OTEL_ENABLED` to `true`.

2024-05-22 12:52 UTC, ipanova commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
So you have introduced a new setting here, and by this created a potential discrepancy in how otel can be enabled. Now we have an env var  and setting that enables otel. In the test you check whether env var is set but not the setting. There might combination of env var not set but setting enabled and viceversa.My suggestion is to stick to env var an in the code  by simply checking for `os.getenv("PULP_OTEL_ENABLED")`

2024-05-22 15:32 UTC, decko commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
Nope, I changed in the tests @ipanova. The thing is that the `PULP_OTEL_ENABLED` is used by the container code to run the otel agent when it's needed, and also it populates the `OTEL_ENABLED` setting by dynaconf configuration.

2024-05-22 15:34 UTC, decko commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
> So you have introduced a new setting here, and by this created a potential discrepancy in how otel can be enabled. Now we have an env var and setting that enables otel. In the test you check whether env var is set but not the setting. There might combination of env var not set but setting enabled and viceversa.My suggestion is to stick to env var an in the code by simply checking for `os.getenv("PULP_OTEL_ENABLED")`

Got your point.

2024-05-22 15:51 UTC, lubosmj approved these changes

2024-05-22 16:57 UTC, ipanova commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
you forgot to remove this from settings

2024-05-22 16:57 UTC, ipanova approved these changes

2024-05-22 17:19 UTC, decko commented on pulpcore/app/settings.py
> +OTEL_ENABLED = False
Thanks @ipanova

2024-05-22 17:21 UTC, ipanova approved these changes

2024-05-23 09:00 UTC, mdellweg approved these changes

2024-05-23 09:00 UTC, merged