EXPERIMENT
pulp/pulpcore pull request #5466
Opened 2024-06-11 09:08 UTC by mdellweg

2024-06-11 17:01 UTC, ggainey requested changes

2024-06-11 17:01 UTC, ggainey commented on requirements.txt
> +requests!=2.32.3,<2.32
```suggestion
requests!=2.32.3,<2.33
```

2024-06-11 18:20 UTC, ggainey commented on requirements.txt
> +requests!=2.32.3,<2.32
nm, missed that this was a dliberate experiment in the second force-push.

2024-06-11 18:23 UTC, ggainey commented
So what this teaches us is, we don't have to (and prob should not) use https: to talk to backend-storage, *and* (more importantly) it's the requests=2.32 changes in the SSLContext arena that are breaking us.

2024-06-13 08:06 UTC, mdellweg commented
Closing. There's really not much that can be done from here.

2024-06-13 08:06 UTC, closed without merging