Fix upload for existing on-demand content
pulp/pulpcore pull request #5502
Opened 2024-06-21 22:33 UTC by gerrod3

fixes: #5501

2024-06-24 09:11 UTC, mdellweg requested changes
This issue gets me thinking:
What do we do, if someone uploads a file into another content that magically happend to match this content_artifact?
Don't we need to check that the artifacts we attach here match the expectations of the remote_artifacts for the content_artifact, like size and checksums?

2024-06-24 09:11 UTC, mdellweg commented on pulpcore/app/serializers/content.py
> +                content = self.Meta.model.objects.create(**validated_data)
I think, this was actually correct. If we had created the content, we need to create the content_artifacts also. And we need to do so in a transaction for the content to never be incomplete.

2024-06-24 09:11 UTC, mdellweg commented on pulpcore/app/serializers/content.py
> +            )
What if you moved this block into the except branch? That should be the only codepath where the content could have unresolved remote artifacts.

2024-06-24 13:39 UTC, gerrod3 commented on pulpcore/app/serializers/content.py
> +            )
No, that's wrong. The except part will only be reached if the result of the first `retrieve` is `None`.

2024-06-24 13:54 UTC, mdellweg commented
> > This issue gets me thinking: What do we do, if someone uploads a file into another content that magically happend to match this content_artifact? Don't we need to check that the artifacts we attach here match the expectations of the remote_artifacts for the content_artifact, like size and checksums?
> 
> I don't understand what you are trying to say. `ContentArtifact` is unique on `content` and `relative_path`. When you call `retrieve` you have the **validated** data of the artifact the user uploaded and their supplied metadata that the plugin's create api requires. This is meant so that you are guaranteed to pull the correct content unit if it already exists in Pulp by supplying the correct bits. This is only wrong if your implementation of `validate` is wrong and doesn't check that the user is supplying what they say they are supplying.

OK, I think I'm saying two loosely related things:
Let's ignore the first (upload of an artifact for a remote artifact of another content unit not know to the user).
But the second one is: If there is on demand content, it has content artifacts and hopefully remote artifacts attached. And as far as i know, these can contain checksums the actual artifact should meet. Now the user uploads artifacts that presumably create that content and we take it for that what if the checksums mismatch?
The thing is with on-demand content we kind of rely on the upstream to never lie to us. I start to think this is a really bad idea. Maybe remote content and content should not be mixed that way.

2024-06-24 14:06 UTC, gerrod3 commented
> OK, I think I'm saying two loosely related things: Let's ignore the first (upload of an artifact for a remote artifact of another content unit not know to the user). But the second one is: If there is on demand content, it has content artifacts and hopefully remote artifacts attached. And as far as i know, these can contain checksums the actual artifact should meet. Now the user uploads artifacts that presumably create that content and we take it for that what if the checksums mismatch? The thing is with on-demand content we kind of rely on the upstream to never lie to us. I start to think this is a really bad idea. Maybe remote content and content should not be mixed that way.

Yes, that is correct. Your content unit if it supports on-demand syncing should understand how to differentiate between content units from its metadata, either from the upstream or from an uploaded artifact. If the upstream lies about it's metadata then on upload you should create a different content unit, not re-use the bad content. This is a contract we expect our plugins to follow (which is why pulp_ansible is a mess since it doesn't follow it), so I am still not seeing your problem.

2024-06-24 20:59 UTC, dralley commented on pulpcore/app/serializers/content.py
> +                content = self.Meta.model.objects.create(**validated_data)
Agree with this

2024-06-24 21:15 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_content_access.py
> +    monitor_task(file_bindings.RepositoriesFileApi.sync(file_repo.pulp_href, body).task)
Just reminding myself here - this doesn't pollute the shared fixture, does it?

2024-06-24 21:18 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_content_access.py
> +    monitor_task(file_bindings.RepositoriesFileApi.sync(file_repo.pulp_href, body).task)
No, all the pulp_file fixtures are unique per test. Each one is generated during the test, I don't think any test uses a shared fixtures.

2024-06-24 21:29 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_content_access.py
> +    monitor_task(file_bindings.RepositoriesFileApi.sync(file_repo.pulp_href, body).task)
Cool, the way pytest fixtures work is a bit unintuitive sometimes

2024-06-25 10:38 UTC, mdellweg commented
Well, the one thing I am going to require is, that when we create a new content, we need to create the content artifacts in the same transaction.

Otherwise we open up a window for race conditions, where we have incorrect content in the database.

2024-07-10 15:27 UTC, gerrod3 commented
> Well, the one thing I am going to require is, that when we create a new content, we need to create the content artifacts in the same transaction.
> 
> Otherwise we open up a window for race conditions, where we have incorrect content in the database.

Ok, I reverted the create logic so now this is only a new check we perform when the content already existed in Pulp.

2024-07-11 06:35 UTC, mdellweg approved these changes

2024-07-16 14:49 UTC, mdellweg approved these changes

2024-07-16 14:49 UTC, mdellweg commented on pulpcore/app/serializers/content.py
> +                    update_conflicts=True,
Is this the thing that basically turns this into an update for all the not yet associated artifacts?

2024-07-22 19:20 UTC, ggainey approved these changes

2024-07-22 19:20 UTC, merged