Update pulpcore index page
pulp/pulpcore pull request #5544
Opened 2024-07-05 21:18 UTC by pedro-psb

This index page is not the website index page (that lives in pulp-docs).

This is the presentation page that is opened when you click on a plugins name.
See https://pulpproject.org/pulp-docs/docs/dev/guides/create-plugin-overviews/

I've used the content from the legacy website with slight modifications and link updates.

[noissue]

2024-07-08 06:41 UTC, mdellweg submitted a review, later dismissed

2024-07-10 14:45 UTC, ggainey requested changes

2024-07-10 14:45 UTC, ggainey commented on staging_docs/index.md
> +# Welcome do Pulp Core
```suggestion
# Welcome to Pulp Core
```

2024-07-10 14:45 UTC, ggainey commented on staging_docs/index.md
> +[Installation Introduction](site:pulp-oci-images/docs/admin/tutorials/quickstart/)
I would put this bullet after "Main concepts..." - so the flow is overview/concepts/install/workflows/plugin-auth

2024-07-10 18:33 UTC, pedro-psb commented
@ggainey Done, thanks for noticing.

2024-07-10 19:11 UTC, ggainey approved these changes

2024-07-11 06:36 UTC, mdellweg approved these changes

2024-07-11 06:36 UTC, merged