Restrict non-admin users from uploading artifacts
pulp/pulpcore pull request #5669
Opened 2024-08-06 19:00 UTC by git-hyagi

fixes: #5525

2024-08-07 06:56 UTC, mdellweg commented on pulpcore/app/viewsets/content.py
> +                "function": "add_roles_for_object_creator",
Oh, please don't do that. Artifacts are shared. No one owns them.

2024-08-07 11:32 UTC, mdellweg commented on pulpcore/app/viewsets/content.py
> +                "action": ["create", "destroy"],
Sorry, but I think I cannot just let go here:
Deleting artifacts is a dangerous operation. It should not only be not allowed, but actually not possible at all.

2024-08-07 12:25 UTC, lubosmj commented on pulpcore/app/viewsets/content.py
> +            },
I think the idea is to completely lock this endpoint to admin users. Maybe, in the future, to even make this (and other admin endpoints) domain-enabled.

2024-08-08 08:44 UTC, mdellweg commented on pulp_file/tests/functional/api/test_domains.py
> +    monitor_task(task)
Future idea (not this PR): Can we run orphan cleanup as part of the domain deletion task?

2024-08-08 08:50 UTC, mdellweg commented on pulpcore/tests/functional/api/test_upload.py
> +    monitor_task(pulpcore_bindings.OrphansCleanupApi.cleanup({"orphan_protection_time": 0}).task)
This can break other tests running in parallel. Why do we even care? Just remove all of this.

2024-08-08 08:50 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +    def upload_valid_attrs(monitor_task, pulpcore_bindings):
This sounds wrong. Is this function actually _used_ somewhere?

2024-08-08 11:26 UTC, ipanova commented on pulp_file/tests/functional/api/test_domains.py
> +    monitor_task(task)
you can explicitly mention in this ticket to include content deletion as well https://github.com/pulp/pulpcore/issues/3362

2024-08-09 12:33 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +    def _upload_valid_attrs(artifact_api, file, data):
Now that this is a fixture, we can ask for the `pulpcore-binding` fixture:
```suggestion
@pytest.fixture
def upload_valid_attrs(pulpcore_bindings, allow_admin_destroy_artifact):
    def _upload_valid_attrs(file, data):
```

2024-08-13 17:54 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
>      assert not file_exists
Instead of not running in parallel, why not just remove this piece from the test.
It's not testing the artifact api. It's testing orphan cleanup, which should really be done elsewhere.
I understand where you are coming from, but `pulpcore_bindings.ArtifactsApi.delete(artifact.pulp_href)` is exactly what we don't support so there is no use trying to keep the test for it.

2024-08-14 10:47 UTC, ipanova commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +        # assumes ALLOWED_CONTENT_CHECKSUMS does NOT contain "md5"
What Matthias meant here is that you can rely on settings by accessing them and based on what they contain you can check for the absence of certain checksum algorithms rather than relying on an assumption comment.

2024-08-14 10:52 UTC, ipanova commented on pulpcore/tests/functional/api/test_crd_artifacts.py
>      """Delete an artifact, it is removed from the filesystem."""
you need to update docstrings in multiple places

2024-08-16 09:01 UTC, ipanova commented on pulpcore/tests/functional/api/test_crd_artifacts.py
>          for keys in itertools.combinations(file_attrs, i):
is there any value to test upload with different attribute combinations? I would just upload the artifact once with the provided file_attrs, this way there won't be any need to orphan delete the artifact in between.

2024-08-16 09:24 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +            )
I would not care about cleaning anything up here. The Artifact api is meant to be handling duplicate artifacts transparently. And specifically "empty file" could lead to a collision with content, that cannot be cleaned up at this point, way to easily.
(I think desperately needing to start clean is a left over from when reuploading artifacts lead to errors.)

2024-08-16 09:29 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
>          for keys in itertools.combinations(file_attrs, i):
Well i think it is testing that you can upload the artifact with e.g. only providing the size, or only sha128 and sha244 or so.
And for exactly that reason we should not run cleanup inbetween, because Pulp _is_ supposed to find the existing artifact at least starting from the second attempt.

2024-08-16 09:33 UTC, mdellweg commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +        # assumes ALLOWED_CONTENT_CHECKSUMS does NOT contain "md5"
Also on a machine configured with MD5 this test will fail as a false positive.

2024-08-16 12:45 UTC, ipanova approved these changes

2024-08-19 08:01 UTC, lubosmj commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +def test_upload_empty_file(pulpcore_bindings, tmp_path, monitor_task):
What is the rationale behind this change? Could we revert it along with the `pulpcore_bindings.OrphansCleanupApi.cleanup({"orphan_protection_time": 0})` call?

2024-08-20 17:36 UTC, lubosmj requested changes
Please, address my last comment before merging.

2024-08-22 11:09 UTC, git-hyagi commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +def test_upload_empty_file(pulpcore_bindings, tmp_path, monitor_task):
hum... this test is failing without the orphan cleanup:
```
E           HTTP response body: {"non_field_errors":["Artifact with sha256 checksum of 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' already exists."]}
```
Should we still address this error (when removing the orphan cleanup) in this PR or as [mdellweg mentioned](https://github.com/pulp/pulpcore/pull/5669#pullrequestreview-2242339791) "[..] _merge this now and rethink the testing in a second PR._"?

2024-08-22 12:56 UTC, lubosmj commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +def test_upload_empty_file(pulpcore_bindings, tmp_path, monitor_task):
Is it failing with `delete_orphans_pre` too?

2024-08-22 14:09 UTC, lubosmj commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +def test_upload_empty_file(pulpcore_bindings, tmp_path, monitor_task):
I see. Okay. Let's merge this!w

2024-08-22 14:09 UTC, lubosmj approved these changes

2024-08-22 14:09 UTC, merged