Fix memory spike on repository delete
pulp/pulpcore pull request #5765
Opened 2024-09-03 09:55 UTC by dralley

Django handles cascade deletes itself (as opposed to letting the database handle it) and in doing so it pulls a lot of data out, resulting in a memory spike on repository deletion.

The only solution is to write a custom cascade delete that deletes the objects at the bottom of the cascade tree more incrementally.

closes https://github.com/pulp/pulpcore/pull/2280

2024-09-03 14:19 UTC, dkliban commented
@dralley what do you think about improving this test? https://github.com/pulp/pulpcore/blob/main/pulpcore/tests/functional/api/using_plugin/test_crud_repos.py#L17

I was thinking we could create a publication in the test. Then assert that it got deleted. Maybe also make some assertions on RepositoryVersions? The assertions for repository versions would have to use the RepositoryVersion model from pulpcore and not the REST API.

2024-09-04 09:21 UTC, dralley commented
@dkliban Instead of implementing a new task type, perhaps we should be overriding the base `.delete()` functions?

Should I be doing the same for repository version delete (which already does override `.delete()` for squashing functionality)?

2024-09-04 09:26 UTC, dkliban commented
@dralley I agree that it would be better to change the implementation of repository.delete() instead of introducing a new task.

2024-09-04 13:40 UTC, dkliban approved these changes

2024-09-05 10:03 UTC, dralley commented
@dkliban Do you think we ought to do any large-scale testing before enabling the option by default?  e.g. the COPR testing box or services staging

2024-09-06 08:53 UTC, dkliban requested changes
Let's get rid of the setting and just always delete with the new implementation.

2024-09-16 13:14 UTC, dralley commented
@dkliban TBH I'm still partial to leaving the setting around for a release or two personally.  I'm not totally against removing it, just risk averse.

2024-09-16 15:25 UTC, dkliban approved these changes
Thank you!

2024-09-16 15:25 UTC, dralley commented on pulpcore/app/models/publication.py
> +        with transaction.atomic():
The goal of this is just to minimize the scope of the transaction to the part that is making modifications.  All of the above is just queries, there's no need to hold the transaction open.

2024-09-16 17:59 UTC, merged