Add pulp_labels to Content.
pulp/pulpcore pull request #5787
Opened 2024-09-11 14:03 UTC by ggainey

2024-09-13 09:03 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +            "are added."
OK, I can see, that this is still unambiguous. But should we maybe go for a new `remove_q` field?
You may for example remove all files from a repository by their `relative_path__startswith`...
So the logic could start with `remove_q="pulp_label='foo'"` and later we add support for  `remove_q="pulp_label='foo' OR relative_path__startswith='/bar/'`.

2024-09-13 09:06 UTC, mdellweg commented on pulpcore/app/serializers/repository.py
> +            "are added."
Having said that, should we factor this part (advanced modify) into it's own PR? It would give us time to think this high level api design over.

Given that a user can filter content by labels, they can already compile the set of content hrefs locally to call modify with them.

2024-09-13 17:32 UTC, ggainey commented on pulpcore/app/serializers/repository.py
> +            "are added."
> Given that a user can filter content by labels, they can already compile the set of content hrefs locally to call modify with them.

Yes - but the user-experience of calling an API with a list of possibly thousands of HREFs, for one label, is...suboptimal. And "remove all the units with a given build id" is the actual requirement we're being asked to respond to, it's the point for doing this at all.

I can see benefits to a more-general Q filter - but I'm not sure the extra flexibility is worth the extra complication?

2024-09-16 17:44 UTC, gerrod3 commented on pulpcore/app/serializers/repository.py
> +        labels_specified = [s for s in value if "=" in s]
Technically you can have a label that is just a key, with no value. So we probably should assume anything that doesn't begin with a slash to be a proper label.

2024-09-16 18:10 UTC, ggainey commented on pulpcore/app/serializers/repository.py
> +        labels_specified = [s for s in value if "=" in s]
Ooof, good point. Pushes us towards @mdellweg 's comment above, to have a `remove_q=...` construct.

2025-02-25 02:58 UTC, ggainey commented on pulpcore/app/serializers/repository.py
> +            "are added."
Removing the label-support for remove-content for "future development"

2025-02-25 08:46 UTC, mdellweg approved these changes

2025-02-25 14:07 UTC, dkliban requested changes
Thank you for this wonderful feature! Please add a test that uses the generic Content API to perform filtering my pulp_label.

2025-02-25 16:57 UTC, merged