Add PRN support
pulp/pulpcore pull request #5813
Opened 2024-09-18 18:23 UTC by gerrod3

fixes: #5766

2024-09-24 13:59 UTC, mdellweg commented on pulpcore/app/viewsets/repository.py
> +                model, pk = resolve_prn(uri)
So a repository version PRN is not `prn:file.repository:<uuid>:<version>` ?

2024-09-24 14:01 UTC, gerrod3 commented on pulpcore/app/viewsets/repository.py
> +                model, pk = resolve_prn(uri)
Nope, it is always `prn:<app_label>.<model_label>:<uuid>`, even for repository versions.

2024-09-24 14:04 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_tasks.py
> +    assert ctx.value.status == 400
It kind of makes sense, you couldn't find a badly named resource so 404 not found. But it's an improper input so it should probably return 400, which it now does since I changed the filter code.

2024-09-24 14:09 UTC, mdellweg submitted a review, later dismissed

2024-09-24 14:23 UTC, ggainey requested changes
It would be good to document, for plugin-authors, something along the lines of "if you subclass from ModelSerializer directly" (which plugins do) "you'll want to add 'prn' to your exposed-fields"

2024-09-24 14:31 UTC, gerrod3 commented on pulpcore/app/util.py
> +            _("PRN must be of the form 'prn:app_label.model_label:pk': {}").format(prn)
No, they run `isidentifier()` on the label, so it is a slug: https://github.com/django/django/blob/39de2e97a06d0317973b280bc159ca6f89fc64e3/django/apps/config.py#L33-L38


https://docs.python.org/3/reference/lexical_analysis.html#identifiers

2024-09-24 15:39 UTC, ggainey requested changes
Some docs-wordsmithing - otherwise, looking very good!

2024-09-24 15:39 UTC, ggainey commented on docs/dev/learn/subclassing/serializers.md
> +    you should include the fields of that serializer in your own. Important fields it provides include
```suggestion
    you should include the fields of that serializer in your own. Important fields it provides include `pulp_created`, `pulp_last_updated`, and `prn`.
    
    See the `pulpcore.plugin.serializers.ContentGuardSerializer` for an example of how to accomplish this:
    ```
    class Meta:
        model = models.ContentGuard
        fields = ModelSerializer.Meta.fields + ("name", "description")
   ```
```


Picked a suggested-example basically at random - feel free to point to something "more canonical". But I thought having a specific good-practices how-to would be helpful.

2024-09-24 15:39 UTC, ggainey commented on docs/dev/learn/subclassing/serializers.md
> +    `pulp_created`, `pulp_last_updated`, and `prn`.
Can remove if previous-comment is acceptable.

2024-09-24 16:57 UTC, gerrod3 commented on docs/dev/learn/subclassing/serializers.md
> +    you should include the fields of that serializer in your own. Important fields it provides include
Added an example to the note.

2024-09-24 17:59 UTC, ggainey requested changes

2024-09-24 17:59 UTC, ggainey commented on docs/dev/learn/subclassing/serializers.md
> +    See `pulpcore.plugin.serializers.ContentGuardSerializer` for an example:
:+1:

2024-09-24 17:59 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
This fails, right now, if you have pulp_rpm installed with "rpm.DistributionTreeResponse". I'm sure there are more. Can we set this up to collect/log *all* the failures, and *then* fail the test?

2024-09-24 18:02 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
Ahh, I didn't test with other plugins installed.

2024-09-24 18:13 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
A quick "manual" scan shows pulp_rpm is missing the base fields in `DistributionTreeSerializer` and `UpdateCollectionSerializer`, fwiw. Would be good to have the test give us a complete list for a given install, so a run with many-plugins would ferret out the list of serializers that need to be fixed.

2024-09-24 18:19 UTC, gerrod3 commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
Ok, I've updated the test to group them together. Can you try it out and see if it is correct?

2024-09-24 18:39 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
Ha! OK, it works - but it still only finds `DistributionTreeSerializer` - because `UpdateCollectionSerializer` doesn't expose `pulp_href`! 

```python
>       assert len(failed) == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = len(['rpm.DistributionTreeResponse'])
```

Let me reset my env to include container and deb and let's see what we get, give me a bit.

2024-09-24 19:03 UTC, ggainey commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
OK cool, this looks like it does pick up all the ones it finds:
```
E       AssertionError: assert 5 == 0
E        +  where 5 = len(['CollectionSummaryResponse', 'ansible.AnsibleDistributionResponse', 'ansible.AnsibleNamespaceMetadataResponse', 'ansible.CollectionVersionMarkResponse', 'rpm.DistributionTreeResponse'])
```

(That's from an env with `DEV_SOURCE_PATH=pulpcore:pulp_rpm:pulp_container:pulp_python:pulp_deb:pulp_ansible` , btw)

2024-09-25 06:47 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_prn.py
> +                assert schema["properties"]["prn"]["type"] == "string", name
We used to have a set of tests in pulpcore that will run on the plugins ci. I'm not sure this is still a *thing*. But this sounds like a good candidate.

2024-09-25 19:23 UTC, dralley approved these changes

2024-09-25 19:24 UTC, merged