Re-enable Storage Metrics emiter and refactor it.
pulp/pulpcore pull request #5891
Opened 2024-10-09 16:19 UTC by decko

Closes #5762

2024-10-09 16:31 UTC, lubosmj commented on CHANGES/5762.feature
> +This is an experimental feature and can change without prior notice.
```suggestion
Re-enabled and refactored the Domain Storage metric emiter.
```

2024-10-09 18:05 UTC, decko commented on CHANGES/5762.feature
> +This is an experimental feature and can change without prior notice.
Are you suggesting to remove the experimental disclaimer?

2024-10-09 19:11 UTC, lubosmj commented on CHANGES/5762.feature
> +This is an experimental feature and can change without prior notice.
Yes, because it is in tech preview, looking at the doc. And the empty new line should be removed too.

2024-10-09 19:49 UTC, bmbouter commented
@mdellweg @decko the task usage here really is a nice design. It's so little code.

2024-10-10 06:34 UTC, lubosmj submitted a review, later dismissed

2024-10-10 09:16 UTC, mdellweg requested changes

2024-10-10 14:47 UTC, decko commented on pulpcore/app/tasks/telemetry.py
> +def emit_domain_space_usage_metric():
> This name appears in the database. There is no way we can change it later. The current name is specific to it's first batch of work, yes. But it's not future proof. Also it suffers from homeopathic naming. "emit" and "usage" don't actually add reasonable information. And still this is the one recurring task to collect and send all the measures that need updates frequently (currently five minutes, but i'm not sold on that interval, so don't put it in the name).
We may think about adding a "otel_metrics_daily" later. You get the idea?

I got the idea, but the thing is that this function here will only emit this metric, no other. If we need to emit another metric on periodic basis then we need to add another function and so on. With this we can trace back which metric could be causing issues for example.

Also, we could have another periodic metric that would demand a different time schedule. With the `configure_periodic_telemetry` we can schedule different metrics emitter with different time schedules without issues.

Yet, the complete name of the function that will appear on the Tasks database will be `pulpcore.app.telemetry.emit_domain_space_usage_metric`, which makes sense to me. There's another term that could be more explicit than `space_usage`? I'm all ears.

2024-10-11 07:45 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +def emit_domain_space_usage_metric():
That's fine. You can have as many functions as you wish. But you get one periodic task to call them. And this is nothing we can fix later. Task names are there for all eternity.

2024-10-11 09:14 UTC, lubosmj commented on pulpcore/app/tasks/telemetry.py
> +def emit_domain_space_usage_metric():
Let me clear up some misunderstandings here.

@decko's idea is to have separate periodic tasks for different metrics (that might come in the future), making them more isolated. Currently, he finds the task's name self-explanatory -- it emits exactly one metric related to current disk space usage. In contrast, `otel_metrics_N` is too vague. Is it initializing metrics, or emitting them? I agree with him.

However, I got @mdellweg's point of hiding as many details as possible inside the task's implementation and not trying to make any assumptions too early. The change he proposes could offer better opportunities if something backfires. To mitigate potential problems in the future, we should use as generic name as possible, because the tasks' names stay in the DB for eternity. This is a limitation we have to deal with. I agree with him.

After considering all the aspects, I am now leaning towards having a more generic task name, like: "emit_otel_metrics". We should not specify the interval in the name because it should be known from `dispatch_interval` defined at the task level.

2024-10-11 09:47 UTC, decko commented on pulpcore/app/tasks/telemetry.py
> +def emit_domain_space_usage_metric():
Folks, I've changed it following @mdellweg ideas.

2024-10-11 10:31 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +def emit_domain_space_usage_metric():
> The change he proposes could offer better opportunities if something backfires.

That's a new aspect.
All right. Let's talk about failure scenarios. I love that.
So what can go wrong?
* Bad code: We don't plan for that, right?
* Failed to gather some information: Put a proper try-except block around every individual function and all the others still run.
* Failed to push the data to the collector: Is it really worth gathering more data at this point? The others will probably fail too. It will retry one interval later anyway. Also a failed task is a good thing at this time to report about the telemetry stack being down.

2024-10-11 11:56 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +provider = MeterProvider(metric_readers=[metric_reader], resource=resource)
I think, all of this setup should happen inside of the task.
There's no need to have that overhead when this file is imported somewhere else.

2024-10-11 11:56 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +    meter = provider.get_meter(__name__)
This is where you get the name of the function that will appear as the label of the data?
That's a good indicator to have this run from within a function called by the task.

2024-10-11 11:56 UTC, mdellweg commented on pulpcore/app/tasks/telemetry.py
> +    space_utilization_per_domain = Artifact.objects.values("pulp_domain__name").annotate(
why calling it utilization in one place and usage in another?

2024-10-12 10:17 UTC, mdellweg approved these changes

2024-10-14 11:41 UTC, merged