Experiment with uvloop in the Gunicorn worker
pulp/pulpcore pull request #6023
Opened 2024-11-14 06:55 UTC by pedro-psb

Just checking if nothing breaks.

https://github.com/pulp/pulpcore/issues/6021

2024-11-14 07:27 UTC, pedro-psb commented
Just a note, maybe we should watch out for [this](https://docs.aiohttp.org/en/stable/faq.html#why-is-creating-a-clientsession-outside-of-an-event-loop-dangerous). We've done something about it, but: https://github.com/pulp/pulpcore/pull/5666#issuecomment-2275274707

2024-11-14 16:08 UTC, bmbouter commented
I'm +1 on this!

2024-11-20 17:06 UTC, dralley commented
Are we intending to actually merge this now or does it remain just a test?  Do we have any idea for example how much of a difference it makes in practice?

2024-11-20 17:46 UTC, bmbouter commented
I think we should merge it. This only considers the overhead of the loop itself (whereas, in reality the overwhelming majority of the time is in our application code), but if we're comparing asyncio (what we use) versus uvloop, uvloop seems over twice as fast. https://magic.io/blog/uvloop-blazing-fast-python-networking/

2024-11-21 14:19 UTC, decko commented
Do we also need to set the asyncio event loop to use uvloop?
```asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())```

Also, setting this in the entrypoint, is this gonna work to all the application itself?

2024-11-21 14:51 UTC, mdellweg requested changes

2024-11-21 14:51 UTC, mdellweg commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
Can we consider adding this as an optional dependency?

2024-11-21 14:59 UTC, pedro-psb commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
Yes. Personally I would prefer to merge this as an optional feature.
Maybe do some discourse post to invite people give it a try and provide feedback.

2024-11-21 15:01 UTC, pedro-psb commented
> @decko Do we also need to set the asyncio event loop to use uvloop?

That's literally the only thing that new worker do! :smile: 
https://github.com/aio-libs/aiohttp/blob/4adb0616a6de8351c45779048610081e000f7c6a/aiohttp/worker.py#L230

> Also, setting this in the entrypoint, is this gonna work to all the application itself?

Not sure I understand what you mean. What I understand is that specifically all new content-app workers will use it.

2024-11-21 15:41 UTC, pedro-psb commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
@bmbouter Can we start with that? ^

2024-11-22 18:08 UTC, bmbouter commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
Optional dependencies seem complicated. To me, the containers we build for the community would still have it installed because I don't think we want to ship options that then require users to rebuild containers. Pulp (imo) should Just Work™

At that point if it's optional in pulpcore, but still in 100% of the officially supported install method we'd do better just to keep it simple.

I'm fine with whatever you all decide.

2024-11-22 19:19 UTC, pedro-psb commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
My problem is not having strong evidence. I believe it will be fine (not break things) and improve performance, but I would like a bit more than that before shipping it widely. And also to justify to the build team why we are adding more deps.

I have a proposal which I prefer (over adding as optional and hoping someone will opt-in and provide feedback):
1) We ship this as a patch on services for a fixed amount of time (1-3 months? on the agenda) with the purpose of gaining more trust (against breaks or regressions).
2) We conduct some benchmarking (on services or not) and write a report. I would be happy to do/participate on that.

2024-11-22 19:23 UTC, dralley commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
I agree with all of that ^ FWIW.

2024-11-22 19:30 UTC, bmbouter commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
I like this idea because it'll produce some real-world analysis. We can evaluate it first in the staging environment.

To do this we'll need the patch to be applied to [this repo](https://github.com/pulp/pulp-service/). Also have the usage of it enabled/disabled on the presence of an environment variable. If the env var is set use it, if the env var is non-existant don't. That will be the safest because then we can apply the patch and anywhere it goes it'll not break anything.

Then @dkliban or @decko can set the env var in the deployment repo (another repo with other contributors perms that are kind of hard to adjust). Also they can add uvloop to the container build file.

@pedro-psb could you open a patch like that? Feel free to message with us more about it, we'd like to help make it easy.

2024-11-25 12:55 UTC, pedro-psb commented on pyproject.toml
> +  "uvloop>=0.21.0,<0.22",
Yes, I can submit the patch.

2025-03-30 17:25 UTC, closed without merging