Add timeout to immediate tasks
pulp/pulpcore pull request #6155
Opened 2024-12-16 20:38 UTC by pedro-psb

2024-12-17 13:43 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +    signal.alarm(IMMEDIATE_TASK_TIMEOUT)
Oh, interesting.
This is quite close to low level process handling. I wonder if this might interfere with other uses of the signal handler.

Do you think we can instead require that all immediate tasks are async functions? We could then implement the timeout on the asyncio level with much more confidence.

2024-12-17 15:03 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> +    signal.alarm(IMMEDIATE_TASK_TIMEOUT)
> Do you think we can instead require that all immediate tasks are async functions? We could then implement the timeout on the asyncio level with much more confidence.

Yes. I dont have a good idea of how much friction this imposes, but that's definitely more safe.

2025-02-12 13:34 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> +    signal.alarm(IMMEDIATE_TASK_TIMEOUT)
@mdellweg Hey! Can you provide an early review for the api worker part?

2025-02-13 09:08 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                    loop.run_until_complete(asyncio.wait_for(result, timeout=IMMEDIATE_TIMEOUT))
Looks like a good first cut. But we still stop the heartbeat loop for up to 5 seconds here.

We should definitely plan on rewriting the workers in async.

2025-02-13 15:13 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> +                    loop.run_until_complete(asyncio.wait_for(result, timeout=IMMEDIATE_TIMEOUT))
> We should definitely plan on rewriting the workers in async.

Would you say that's a blocker (for running on foreground)?

I was trying to find a way to integrate the coroutine control yielding with the select-loop, but I'm reaching dark corners.

If that's a blocker this PR could be really about the timeout (as originally intented). The commit "wip: add timeout to supervise immediate tasks" adds a timeout to the regular task process. Maybe we could stop there.

2025-02-14 10:35 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                    loop.run_until_complete(asyncio.wait_for(result, timeout=IMMEDIATE_TIMEOUT))
Not necessarily. It's a certain risk. But it's nothing we cannot revert when things go bad.

2025-02-14 10:41 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                    loop.run_until_complete(asyncio.wait_for(result, timeout=IMMEDIATE_TIMEOUT))
Maybe after all it's wise to split the work into smaller chunks to reduce that risk.
Ensuring that immediate tasks don't run too long is still an incremental improvement.

2025-02-14 17:20 UTC, pedro-psb commented
No idea why this fails only on s3:
https://github.com/pulp/pulpcore/actions/runs/13333279626/job/37242548757?pr=6155#step:14:18219

An exception does get caught...

2025-03-18 10:54 UTC, mdellweg requested changes
Not sure if you wanted a review at this stage...

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/constants.py
> +#: Timeout for immediate tasks
Is that seconds?

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> -    # This extra stack is needed to isolate the current_task ContextVar
Why drop this comment?

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +        is_coroutine = asyncio.iscoroutine(result)
Has this ever been true? Should we no check if `func` is a coroutine even before executing it?

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +        time_limit = time.monotonic() + IMMEDIATE_TIMEOUT
Why do we not use `timezone.now` here?

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    # Case 1
Each case should be a separate test. If you want to share resources, you can group them in a class.

2025-03-18 10:54 UTC, mdellweg commented on pulpcore/tasking/worker.py
> +        time_limit = time.monotonic() + IMMEDIATE_TIMEOUT
Also didn't we want to let the timeout tick in the async loop?
That will help us maybe run even more than one immediate tasks per worker eventually.
Also the timeout will be in effect even on the api worker.

2025-03-18 17:02 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> +        is_coroutine = asyncio.iscoroutine(result)
Gerrod showed that this is valid [here](https://github.com/pulp/pulpcore/issues/5929#issuecomment-2634836859). But I can look up a more intuitive form to check it.

2025-03-18 17:11 UTC, pedro-psb commented on pulpcore/tasking/worker.py
> +        time_limit = time.monotonic() + IMMEDIATE_TIMEOUT
Oh, that's true :facepalm: 
The worker ends up calling execute_task, so we only need it there with the async loop...

2025-03-18 17:11 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> -    # This extra stack is needed to isolate the current_task ContextVar
I guess that was an accident

2025-03-18 17:12 UTC, pedro-psb commented on pulpcore/constants.py
> +#: Timeout for immediate tasks
Yes, I'll add that on the description

2025-03-19 09:57 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> -    # This extra stack is needed to isolate the current_task ContextVar
Absolutely not. But then it doesn't seem to be telling its story.

2025-03-19 10:09 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +        is_coroutine = asyncio.iscoroutine(result)
The big problem is that we run the task function first and then we check if it returned something awaitable.
(That is what coroutine functions are: They are functions returning an awaitable generator object.)

While in the old code this may be working properly (unless some task accidentally returned a generator of any sort), here we don't want to run the task function in case it is immediate and not async.

So what should happen, i think, is we should check for `asyncio.iscoroutinefunction(func)` and then decide whether or how to execute it.

2025-03-19 10:12 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +        is_coroutine = asyncio.iscoroutine(result)
Sadly the python documentation itself uses the term "coroutine" a bit inconsistently.
Sometimes as the function declared with async, and sometimes as the awaitable object that is the result of calling the former.

2025-03-19 12:56 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> -    # This extra stack is needed to isolate the current_task ContextVar
I mean dropping the comment was an accident.
The comment is fine. I didnt know what a ContextVar was when I first read it, but then I read about it an it made sense.

2025-03-19 22:19 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        COMMON_RESOURCE = "PPP"
I'd make the resource a random string to avoid any collisions.
Also why not mark this as parallel too?

2025-03-19 22:23 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        dispatch_long_task(required_resources=[COMMON_RESOURCE])
You could cancel the long task after dispatching the regular one in order to speed up the tests dramatically.

2025-03-19 22:25 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +class TestImmediateTaskNoLocking:
TestImmediateTaskWithNoResource?

2025-03-19 22:25 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    def test_succeed_on_api_worker(self, pulpcore_bindings, dispatch_task, monitor_task):
This is really nit picky...
test_succeeds_on_api_worker

2025-03-19 22:28 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        task = monitor_task(task_href)
Should we monitor that task? Should it not return as completed already from dispatch_task? Also we should be able to catch the deprecation warning here and assert on it.
Also we don't want it to bubble into the collected deprecation warnings for the ci.

2025-03-19 22:33 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +            coro = func(*args, **kwargs)
Not sure if it's wise to call this thing coro given the confusion with that name throughout the python docs.
The only idea i can come up with is "awaitable".

2025-03-19 22:33 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +            assert asyncio.iscoroutine(coro), coro
Extra safety? (I'm almost certain we can be sure of that now...)

2025-03-24 09:49 UTC, mdellweg commented on pulpcore/pytest_plugin.py
> +    streamed from the pulpcore-manager call.
ohhhh!

Now I'm wondering if we could just use the capsys or capfd fixture instead? (If you _want_ to try that.)

2025-03-24 10:09 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    def test_throws_when_non_deferrable(
This is not a newly defined behaviour. Can you do me a favor and see whether we already have a test for this?

(Ideally we combine them or pick the nicer one...)

2025-03-24 10:10 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +    def test_timeouts_on_task_worker(
Nitpick mode: `test_times_out_on_task_worker` reads more English to me.

2025-03-24 13:35 UTC, pedro-psb commented on pulpcore/tasking/tasks.py
> +                )
Yes, this was supposed to add more info.
But it'll be handled by the outer try/catch-all at L107 (from changed code) and receive all the context info.
Or am I missing something?

2025-03-24 15:41 UTC, pedro-psb commented on pulpcore/tests/functional/api/test_tasking.py
> +    def test_throws_when_non_deferrable(
Looks like we don't test it elsewhere: 

```
> git grep -I -n defer -- pulpcore/tests/
pulpcore/tests/functional/api/test_tasking.py:564:    def test_throws_when_non_deferrable(
pulpcore/tests/functional/api/test_tasking.py:569:        WHEN dispatching as immediate and not deferrable
pulpcore/tests/functional/api/test_tasking.py:578:                deferred=False,
```

2025-03-25 09:03 UTC, mdellweg commented on pulpcore/tasking/tasks.py
> +                )
Right. But i think we can still add something like:
`logger.warn("Immediate task {task.pk} timed out after ...")` So we see it in the worker and api worker logs too.

2025-03-25 09:10 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        assert "Support for non-coroutine immediate tasks will be dropped" in stderr_content
Thank you! Not adding a new fixture for this makes me happier.

2025-03-25 09:10 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        wait_until("running", task_href)
No, that's not true. A task blocks a resource even in waiting state.

2025-03-25 23:41 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        wait_until(TASK_INCOMPLETE_STATES, task_href)
```suggestion
```
What do you want to wait for here?

2025-03-26 00:12 UTC, pedro-psb commented on pulpcore/tests/functional/api/test_tasking.py
> +        wait_until(TASK_INCOMPLETE_STATES, task_href)
Yeah, the wait doesnt make sense anymore. Removing...

But I wanted to share some thoughts I had on this (not wanting to change anything in this PR):

The long task will always be unblocked first because [it has lower `pulp_created`](https://github.com/pulp/pulpcore/blob/25085248e5289e9713a20926440f37d32ca79c6f/pulpcore/tasking/worker.py#L259-L263), and the short is assured to be blocked as we intend in the test, right?

I was thinking if we shouldnt sort by immediate task there too (in the `unblock_task`). This is a violation of the event order, but so is our immediate task prioritization in `iter_tasks`. I can see there is a diffrence, and feels like it would be worse to violate that in unblocking-time than it is in picking-time, but that's not crystal clear to me.

2025-03-26 09:09 UTC, mdellweg commented on pulpcore/tests/functional/api/test_tasking.py
> +        wait_until(TASK_INCOMPLETE_STATES, task_href)
Well the thing is the immediate task will not be unblocked before the other task is in a final state. And that's the only thing needed to assure resource usage is serialized. It does not matter whether the prior task is identified unblocked or in a waiting, running or canceling state.

2025-03-26 17:41 UTC, merged