Use PulpTemporaryFile instead of Artifact when passing temporary data
pulp/pulpcore pull request #835
Opened 2020-08-10 17:18 UTC by lubosmj

closes #7270

2020-08-10 17:24 UTC, lubosmj commented
This change was tested on the pulp_rpm plugin because UpdateRecordSerializer benefits from NoArtifactContentUploadSerializer (https://github.com/pulp/pulp_rpm/blob/bbf70f539d9524d53b777ebdd63d4e445e6120f3/pulp_rpm/app/serializers/advisory.py#L203).

2020-08-11 03:28 UTC, dralley commented on pulpcore/app/tasks/base.py
> +    A caller should always pass the dictionary "data", as a keyword argument, containing
If it should always be present, I kinda think it should be an explicit keyword argument, although I'm interested in what others think and if there's any good reasons not to do that.

2020-08-11 03:36 UTC, dralley commented on pulpcore/app/tasks/base.py
> +    A caller should always pass the dictionary "data", as a keyword argument, containing
Otherwise, everything looks good

2020-08-11 14:59 UTC, bmbouter commented on CHANGES/7270.misc
> +Replaced an Artifact object, which was used for storing temporary data in
Can this become CHANGES/plugin_api/7270.misc

2020-08-11 15:03 UTC, bmbouter commented on pulpcore/app/tasks/base.py
> +    A caller should always pass the dictionary "data", as a keyword argument, containing
If it's always required then I think it should be an arg even instead of a keyword arg since it can't have a reasonable default.

2020-08-12 10:19 UTC, lubosmj commented on pulpcore/app/tasks/base.py
> +    A caller should always pass the dictionary "data", as a keyword argument, containing
There is such a statement because I wanted to explicitly note that this parameter is mandatory. I could write a similar docstring like we did for the function `general_create()`, but I decided to do write it more precisely.

Also, in the function `general_create()` we have the field `artifact` that is stored within `data` too. I wonder why this should not be done in exactly the same way.
https://github.com/pulp/pulpcore/blob/d78416238190111ff2cc5f53e8542d949b7aff0d/pulpcore/plugin/viewsets/content.py#L56-L65
Do you still want to make that change?

2020-08-19 20:16 UTC, dralley commented on pulpcore/app/tasks/base.py
> +    A caller should always pass the dictionary "data", as a keyword argument, containing
I think I lean towards "yes" but I'm not familiar with this part of the codebase.  Curious if there's any reasons why not to.

2020-08-27 14:57 UTC, daviddavis commented
@lubosmj what's the status of this work?

2020-09-08 14:40 UTC, mdellweg requested changes

2020-09-08 14:40 UTC, mdellweg commented on pulpcore/app/tasks/base.py
> +    A caller should always pass a reference to the temporary file. This function
`temp_file_pk` is a mandatory arg, so it should be a "must".
More important, we should mention that the task takes ownership of that temporary file and deletes it afterwards.

2020-09-08 14:40 UTC, mdellweg commented on pulpcore/plugin/viewsets/content.py
> -        self._task_function_type = tasks.base.general_create
This makes the base class an abstract base class, right?

2020-09-08 14:40 UTC, mdellweg commented on pulpcore/plugin/viewsets/content.py
> -    def init_content_data(self, serializer, request):
Was it impossible to prepare the tempfile in this polymorphic manner?

2020-09-09 10:57 UTC, lubosmj commented on pulpcore/plugin/viewsets/content.py
> -        self._task_function_type = tasks.base.general_create
Kind of. I am going to update the docstring. The classes which inherit from this ViewSet have in common one thing, that is the method `get_deffered_context()`.

2020-09-09 11:06 UTC, lubosmj commented on pulpcore/plugin/viewsets/content.py
> -    def init_content_data(self, serializer, request):
I was requested to change the task's function parameters. Therefore, if I would stick to the current pattern, I would be required to add an additional method that would deal with the function parameters.

I am not sure how polymorphism could serve better in this case. Because the ViewSets do not have many things in common at the moment. I opted to move backwards and just added a new class that works with temporary files.

2020-09-09 12:01 UTC, mdellweg commented on pulpcore/plugin/viewsets/content.py
> -    def init_content_data(self, serializer, request):
Thanks for the explanation.

2020-09-09 18:41 UTC, bmbouter approved these changes
This all looks ok to me. Thanks @lubosmj !

2020-09-09 18:43 UTC, bmbouter commented
I'm LGTM on this, @mdellweg are you?

2020-09-10 08:12 UTC, mdellweg commented
I think, every comment has been addressed. :+1:

2020-09-10 10:14 UTC, merged