Fixing groups API validation
pulp/pulpcore pull request #864
Opened 2020-08-25 21:20 UTC by fao89

https://pulp.plan.io/issues/7329
closes #7329

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2020-08-26 05:54 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
I do not believe, gettext works in this situation. How is it supposed to extract the translatable string here?

2020-08-26 05:59 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +        User = get_user_model()
Would it be OK do make this call at the top level? Or is django insufficiently initialized at that point?

2020-08-26 06:01 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +        except (User.MultipleObjectsReturned, User.DoesNotExist, FieldError) as exc:
How can `MultipleObjectsReturned` happen, if we require to provide `pk`, `id` or `username`?
Is this overly cautious?

2020-08-26 14:34 UTC, fao89 commented on pulpcore/app/viewsets/user.py
> +        except (User.MultipleObjectsReturned, User.DoesNotExist, FieldError) as exc:
it was a bad copy/paste

2020-08-26 14:37 UTC, fao89 commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
I do not know how gettext works, `str(exc)` returns a string I imagined it would work

2020-08-26 15:47 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
Well, I thought it must be able to extract the strings without calling the code. So it probably looks for calls to ’_("...")’.

2020-08-27 14:54 UTC, dkliban commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
The exception text should already be translated if a translation is available. Please remove the _() around str(exc).

2020-08-28 15:51 UTC, mdellweg requested changes
Not sure if i'm the right one to review.
But at least with the gettext stuff i am pretty confident now.

2020-08-28 15:51 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(f"Invalid value for 'obj': {request.data['obj']}"))
Stackoverflow says nope:
https://stackoverflow.com/questions/49797658/how-to-use-gettext-with-python-3-6-f-strings

```suggestion
            raise ValidationError(_("Invalid value for 'obj': " + str(request.data['obj'])))
```
Or the good old "format" of course (Usually this helps people translating if they see the whole string template).
```suggestion
            raise ValidationError(_("Invalid value for 'obj': {obj}").format(request.data['obj']))
```

2020-08-28 15:51 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
```suggestion
            raise ValidationError(str(exc))
```
Won't work at all, but the exception should only use translatable strings anyway.

2020-08-28 15:51 UTC, mdellweg commented on pulpcore/app/viewsets/user.py
> +            raise ValidationError(_(str(exc)))
same here
```suggestion
            raise ValidationError(str(exc))
```

2020-08-31 08:46 UTC, mdellweg approved these changes

2020-08-31 14:24 UTC, dkliban commented on pulpcore/app/viewsets/user.py
> +        user = get_object_or_404(User, pk=pk)
Is this going to be a problem for galaxy_ng?

2020-08-31 14:27 UTC, fao89 commented on pulpcore/app/viewsets/user.py
> +        user = get_object_or_404(User, pk=pk)
nope, at the beginning of this file (line 22) I declared:
```python 
User = get_user_model()
```

2020-08-31 14:31 UTC, merged