Added support for specifying/limiting content-checksums used by Pulp.
pulp/pulpcore pull request #894
Opened 2020-09-08 21:04 UTC by ggainey

settings.ALLOWED_CONTENT_CHECKSUMS now drives the other checksum-related
fields of Artifact (DIGEST_FIELDS, COMMON_DIGEST_FIELDS, RELIABLE_DIGEST_FIELDS)

closes #5216

2020-09-09 12:34 UTC, mdellweg requested changes
Thank you for letting me get a very early look on this **brill** PR.

Running it in the FIPS environment exposed at least one more location where a not allowed hash algorithm is used: pulpcore/app/files.py

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/app/settings.py
> +ALLOWED_CONTENT_CHECKSUMS = set(("md5", "sha1", "sha224", "sha256", "sha384", "sha512"))
I thought this kind of information should be in the "other" `settings.py` finally located at `/etc/pulp/settings.py`.

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/app/settings.py
> +if "sha256" not in ALLOWED_CONTENT_CHECKSUMS:
And this test is probably slated for after including dynaconf.

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_content.py
> +            self.assertEqual(new_data[csum], "asdf")
Can you add a second loop to test that all excluded algorithms saved "None"?

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/app/models/content.py
> +        for digest_name in Artifact.DIGEST_FIELDS:
You should not need this change. Class specifiers are avaliable in the instances unless overwritten.

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    return checksum_cache["reliable_checksums"]
You asked for comments about the memoization.
Well, first of all i see you calling those functions exactly once at importing the module for the first time. So, what is the memoization for?
Having realized that, it should be sufficient to write a corresponding list comprehension at definition of those constants.
See suggestion there.

2020-09-09 12:34 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = checksums_by_frequency()
```suggestion
    COMMON_DIGEST_FIELDS = [ algo for algo in ("sha256", "sha512", "sha384", "sha224", "sha1", "md5") if algo in settings.ALLOWED_CONTENT_CHECKSUMS ]
```

2020-09-09 13:59 UTC, ggainey commented on docs/settings.rst
> +    ``ALLOWED_CONTENT_CHECKSUMS = set(("sha1", "sha224", "sha256", "sha384", "sha512"))``
Indeed - I was following the existing code, but I agree we can simplify.

2020-09-09 14:00 UTC, ggainey commented on pulpcore/app/models/content.py
> +        for digest_name in Artifact.DIGEST_FIELDS:
Heh, fair - personally, I prefer the explicit namespace.

2020-09-09 14:02 UTC, ggainey commented on pulpcore/app/models/content.py
> +    return checksum_cache["reliable_checksums"]
Ah great - that crystallizes the murky "there is something not right about this" I was feeling last night, thanks.

2020-09-09 15:51 UTC, mdellweg commented on pulpcore/app/settings.py
> +if "sha256" not in ALLOWED_CONTENT_CHECKSUMS:
... as dynaconf is loading the on-site-config from whatever specific location (commonly /etc/pulp/settings.py)

2020-09-09 15:54 UTC, mdellweg commented on pulpcore/app/models/content.py
> +        for digest_name in Artifact.DIGEST_FIELDS:
I know, it's academic, but you could subclass the Artifact and define a different value there. Then only self does
*the-right-thing (tm)*.

2020-09-09 16:57 UTC, ggainey commented on pulpcore/app/models/content.py
> +        for digest_name in Artifact.DIGEST_FIELDS:
Fair enough - plus, 'consistency' is more important than 'personal quirk' anyway :)

2020-09-09 17:54 UTC, ggainey commented
> Thank you for letting me get a very early look on this **brill** PR.
> 
> Running it in the FIPS environment exposed at least one more location where a not allowed hash algorithm is used: pulpcore/app/files.py

Concur - see changes in files.py with latest repush

2020-09-09 17:55 UTC, ggainey commented on docs/settings.rst
> +    ``ALLOWED_CONTENT_CHECKSUMS = set(("sha1", "sha224", "sha256", "sha384", "sha512"))``
Updated to use the simpler/more-direct syntax

2020-09-09 17:55 UTC, ggainey commented on pulpcore/app/settings.py
> +ALLOWED_CONTENT_CHECKSUMS = set(("md5", "sha1", "sha224", "sha256", "sha384", "sha512"))
Moved to post-dynaconf to allow site-settings to override

2020-09-09 17:55 UTC, ggainey commented on pulpcore/tests/unit/serializers/test_content.py
> +            self.assertEqual(new_data[csum], "asdf")
Concur, moved

2020-09-09 17:56 UTC, ggainey commented on pulpcore/app/models/content.py
> +    return checksum_cache["reliable_checksums"]
Removed the overly-complicated mess to follow suggestion below

2020-09-09 17:57 UTC, ggainey commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = checksums_by_frequency()
Concur, applied to each of these attributes

2020-09-09 17:57 UTC, ggainey commented on docs/settings.rst
> +    proper subset of the checksums defined by the Artifact model.
Concur, clarified thie whole section (I think)

2020-09-09 17:58 UTC, ggainey commented on pulpcore/tests/unit/serializers/test_content.py
> +            self.assertEqual(new_data[csum], "asdf")
Done

2020-09-09 17:59 UTC, ggainey commented on pulpcore/app/settings.py
> +if "sha256" not in ALLOWED_CONTENT_CHECKSUMS:
Concur, moved post-dynaconf

2020-09-09 19:05 UTC, bmbouter commented on docs/settings.rst
> +   ``ALLOWED_CONTENT_CHECKSUMS = {"sha1", "sha224", "sha256", "sha384", "sha512"}``
I think we should disinclude sha1 also given that is has been shown to be shattered. https://shattered.io/

2020-09-09 19:05 UTC, daviddavis commented
This code looks great to me. Impressive turnaround time on this.

Question: would it be possible to test this out by defining `ALLOWED_CONTENT_CHECKSUMS` in https://github.com/pulp/pulpcore/blob/master/.travis/settings.py.j2?

2020-09-09 19:06 UTC, bmbouter commented on pulpcore/app/settings.py
> +ALL_KNOWN_CONTENT_CHECKSUMS = {"md5", "sha1", "sha224", "sha256", "sha384", "sha512"}
I think we need to move this out of settings.py because it's not safe for users to override this. Instead can this become a constant somewhere, maybe on the Artifact object itself, or perhaps https://github.com/pulp/pulpcore/blob/master/pulpcore/constants.py

2020-09-09 19:07 UTC, bmbouter commented on docs/settings.rst
> +      Specifying checksums that are not listed under ``ALL_KNOWN_CONTENT_CHECKSUMS`` will cause
Can we list the explicit entire set here instead of referring to `ALL_KNOWN_CONTENT_CHECKSUMS`. If we move `ALL_KNOWN_CONTENT_CHECKSUMS` to a constant (I think we need to) user's won't know the values it provides.

2020-09-09 19:10 UTC, bmbouter commented on pulpcore/app/models/content.py
>      # All digest fields ordered by algorithm strength.
```suggestion
    # All available digest fields ordered by algorithm strength.
```

2020-09-09 19:10 UTC, bmbouter commented on pulpcore/app/models/content.py
>      # All digest fields ordered by relative frequency
```suggestion
    # All available digest fields ordered by relative frequency
```

2020-09-09 19:19 UTC, bmbouter commented on pulpcore/app/settings.py
> +#       in your on-site configuration (commonly /etc/pulp/settings.py)
There are various ways to set this, I recommend not naming just one and instead removing the "how to set" recommendation.

2020-09-09 19:20 UTC, bmbouter commented on docs/settings.rst
> +   in your on-site configuration (commonly /etc/pulp/settings.py)
There are various ways to set this, I recommend not naming just one and instead removing the "how to set" recommendation.

You could refer users to the docs on it tho https://docs.pulpproject.org/pulpcore/installation/configuration.html

2020-09-09 19:21 UTC, bmbouter commented on pulpcore/app/settings.py
> +#           ALLOWED_CONTENT_CHECKSUMS = {"sha1", "sha224", "sha256", "sha384", "sha512"}
Can we remove the FIPS related recommendation L#240 and 241. The available "FIPS" algorithms are different depending on if a user is government or not. I think the safe thing is for us to remain silent on this.

2020-09-09 19:24 UTC, bmbouter commented on pulpcore/app/settings.py
> +    )
Ok this comment is an idea I'm just now having, so it's not in the original story. Let me know if this is too much to request. What if an additional check was made that would:

1) Pick a random Artifact from the db
2) Check that all the checksums present in `ALLOWED_CONTENT_CHECKSUMS` are set and only those are set. If not, the user is changing this variable post-content-being-saved and should be instructed via `ImproperlyConfigured` that they should set it to: {name the set of set attributes} on the tested Artifact.

2020-09-09 19:54 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
I think these would be nicer with a property and moved to the module level. I'm read python every day and I'm even a bit unsure of what this is providing. This could become:

It could roughly be:

```
_COMMON_DIGEST_FIELDS = []
for algo in ("sha256", "sha512", "sha384", "sha224", "sha1", "md5")
    if algo in settings.ALLOWED_CONTENT_CHECKSUMS:
        _COMMON_DIGEST_FIELDS.append(algo)

class Artifact(HandleTempFilesMixin, BaseModel):
    <fields>

    @property
    def COMMON_DIGEST_FIELDS(self):
        return _COMMON_DIGEST_FIELDS    
```

Similarly for the other ones.

2020-09-09 19:57 UTC, ggainey commented on docs/settings.rst
> +   ``ALLOWED_CONTENT_CHECKSUMS = {"sha1", "sha224", "sha256", "sha384", "sha512"}``
Per following comments and some pondering, I'm just removing my 'helpful' suggestions - security-conscious users know what they need, they don't it from us/here!

2020-09-09 19:57 UTC, ggainey commented on pulpcore/app/settings.py
> +ALL_KNOWN_CONTENT_CHECKSUMS = {"md5", "sha1", "sha224", "sha256", "sha384", "sha512"}
Concur, moving to constants.py

2020-09-09 19:58 UTC, bmbouter commented on pulpcore/app/models/content.py
> +                    raise UnsupportedDigestValidationError()
We can continue to do this here, but I think we need this same `raise UnsupportedDigestValidationError` in a new `Artifact.__init__(*args, **kwargs)` call. The reason is that plugin writers are not required to use `init_and_validate` and while they should they don't have to. Also by not having it on the Artifact() instantiation itself when `DeclarativeArtifact` creates in-memory Artifacts in FirstStage of a Stages pipeline the error won't be raised until much later in the pipeline.

If we did it in `Artifact.__init__(...)` itself, we probably wouldn't need it in either of these places then because underneath they both call `Artifact.__init__(...) at some point.

2020-09-09 19:58 UTC, ggainey commented on pulpcore/app/models/content.py
>      # All digest fields ordered by algorithm strength.
Oh, good suggestion - changing all three instances

2020-09-09 19:58 UTC, ggainey commented on pulpcore/app/models/content.py
>      # All digest fields ordered by relative frequency
concur

2020-09-09 19:58 UTC, ggainey commented on pulpcore/app/settings.py
> +#       in your on-site configuration (commonly /etc/pulp/settings.py)
See prev "removing helpful suggestions"

2020-09-09 19:58 UTC, ggainey commented on docs/settings.rst
> +   in your on-site configuration (commonly /etc/pulp/settings.py)
Good suggestion, adding pointer and removing suggestions

2020-09-09 19:59 UTC, ggainey commented on pulpcore/app/settings.py
> +#           ALLOWED_CONTENT_CHECKSUMS = {"sha1", "sha224", "sha256", "sha384", "sha512"}
See prev RE removing :)

2020-09-09 20:00 UTC, ggainey commented on pulpcore/app/settings.py
> +    )
I think this is a reasonable idea - but I think I'd like to see it as a refinement. Can we get an issue opened for it, and if we can fit it into the current crunch it'll be in the next release, and if not, we'll have FIPS-compliance available and won't forget to add that when we can.

2020-09-09 20:06 UTC, ggainey commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
Lots of ways to do this. Part of the issue here (imnsho) is that Black's decision about how list-comprehensions 'should' look is...kind of painful.

In any event - perfectly happy to change for readability.

2020-09-09 20:09 UTC, bmbouter commented on pulpcore/app/settings.py
> +    )
That works for me, I added it here: https://pulp.plan.io/issues/7487

Since we can't change settings during functional tests run I don't believe we can reasonably test for https://pulp.plan.io/issues/7487

2020-09-09 20:23 UTC, mdellweg commented on pulpcore/app/settings.py
> +    )
That test would give a false sense of security. Consider pulp being started with [a,b,c] and an artifact A1 was created. Then a turned bad and it is reconfigured [b,c]. A second artifact A2 is created. Now someone configures [a,b,c] again (which is wrong). This test would only report the error in about half the cases (and you can tweak this ration in every direction).

2020-09-09 20:26 UTC, mdellweg commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
doesn't need to be a property here. You can just assign the value.
Read-onlyness of constants is more of a convention in python anyway.

2020-09-09 20:28 UTC, ggainey commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
So, @property defines instance-level not class-level - and this change as-is results in a lot of "TypeError: argument of type 'property' is not iterable" errors in the several/many places that take advantage of these entities.

Note that none of these are new - where they exist in Artifact is where they've been for...quite some time, and there is code that relies on them. I can make creating the list be more explicit, but I think further change is more invasive than I'm confortable with, and doesn't actually gain us much. What do you think?

2020-09-09 20:38 UTC, ggainey commented on docs/settings.rst
> +      Specifying checksums that are not listed under ``ALL_KNOWN_CONTENT_CHECKSUMS`` will cause
Concur

2020-09-09 20:40 UTC, daviddavis commented on pulpcore/app/settings.py
> +    )
Yup, we could perhaps do a select like `SELECT * FROM artifacts WHERE a IS NULL or b IS NULL ...`.

2020-09-09 20:41 UTC, ggainey commented on pulpcore/app/settings.py
> +    )
@mdellweg ah, good point. What we're really going for here is, "once you're up and running for a while, deciding to suddenly limit the available checksums is....Fraught With Peril." This feels like something that we def need to think on more - let's discuss under 7487, if we come up with an answer great, if not oh well - but either way, it's a 'future enhancement' :)

2020-09-09 20:42 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
If it's causing problems it's not worth it. But can we try what @mdellweg is suggesting as the only other thing we'd try to gain the readability? Basically have it:

```
_COMMON_DIGEST_FIELDS = []
for algo in ("sha256", "sha512", "sha384", "sha224", "sha1", "md5")
    if algo in settings.ALLOWED_CONTENT_CHECKSUMS:
        _COMMON_DIGEST_FIELDS.append(algo)

class Artifact(HandleTempFilesMixin, BaseModel):
    <fields>

    COMMON_DIGEST_FIELDS = _COMMON_DIGEST_FIELDS  
```

2020-09-09 20:52 UTC, ggainey commented on pulpcore/app/models/content.py
> +    COMMON_DIGEST_FIELDS = [
Was in the process of making this exact change :)  Looks to work, we'll go w/ @mdellweg 's suggestion here

2020-09-09 21:00 UTC, bmbouter commented on pulpcore/app/settings.py
> +    )
Excellent points. I revised https://pulp.plan.io/issues/7487 as such w/ attribution

2020-09-10 11:27 UTC, mdellweg commented
I can confirm, this peachy PR is passing the `pulp_file` test suite (unit & functional) on a the centos8-fips box.

2020-09-10 16:24 UTC, ggainey commented on pulpcore/app/models/content.py
> +                    raise UnsupportedDigestValidationError()
Added __init__ to Artifact - left this code in place as well

2020-09-10 16:25 UTC, ggainey commented on pulpcore/app/models/content.py
> +    def __init__(self, *args, **kwargs):
@bmbouter @mdellweg More eyes please - is this what we want for Artifact.__init__?

2020-09-10 16:26 UTC, ggainey commented on pulpcore/tests/unit/models/test_content.py
> +    def test_set_forbidden(self):
This test will fail, on a box that has denied md5, only if the remaining code in tyhis PR is broken. How useful is this? (I mean, it helped me find/fix problems in the code, but those fixes are all in place now...)

2020-09-10 16:27 UTC, ggainey commented on pulpcore/tests/unit/serializers/test_content.py
> +        # This part of the test will only fire if the system-under-test has forbidden
SImilar comment to models/test_content

2020-09-10 17:08 UTC, ggainey commented
> This code looks great to me. Impressive turnaround time on this.
> 
> Question: would it be possible to test this out by defining `ALLOWED_CONTENT_CHECKSUMS` in https://github.com/pulp/pulpcore/blob/master/.travis/settings.py.j2?

@daviddavis , I have...no insight here. I've done a lot of local testing by setting in /etc/pulp/settings.py.

2020-09-10 17:34 UTC, mdellweg commented
> > This code looks great to me. Impressive turnaround time on this.
> > Question: would it be possible to test this out by defining `ALLOWED_CONTENT_CHECKSUMS` in https://github.com/pulp/pulpcore/blob/master/.travis/settings.py.j2?
> 
> @daviddavis , I have...no insight here. I've done a lot of local testing by setting in /etc/pulp/settings.py.

You would add that to the plugins template_config and regenerate the travis directory.

2020-09-10 17:37 UTC, mdellweg commented on pulpcore/app/models/content.py
> +            :class:`~pulpcore.exceptions.UnexpectedDigestValidationError`: When the
```suggestion
            :class:`~pulpcore.exceptions.UnsupportedDigestValidationError`: When the
```

2020-09-10 17:38 UTC, mdellweg commented on pulpcore/app/models/content.py
> +            :class:`~pulpcore.exceptions.UnexpectedDigestValidationError`: When the
also "...when any of the expected_digests..."

2020-09-10 19:23 UTC, ggainey commented on pulpcore/app/models/content.py
> +            :class:`~pulpcore.exceptions.UnexpectedDigestValidationError`: When the
Nice catch, updated both init_and_validate methods

2020-09-10 20:51 UTC, bmbouter commented on pulpcore/app/models/content.py
> +)
ty for all this.

2020-09-10 20:58 UTC, bmbouter commented on pulpcore/constants.py
> +ALL_KNOWN_CONTENT_CHECKSUMS = {"md5", "sha1", "sha224", "sha256", "sha384", "sha512"}
:+1:

2020-09-10 21:08 UTC, bmbouter commented on pulpcore/tests/unit/serializers/test_content.py
> +from pulpcore.app import models
The test suite is expected to be run from a third party box and may not have pulpcore packages installed on it, or if they are, they may not be configured the same way. In those environments this import will fail or return incorrect data.

To resolve this, I think do two things:
1) Have the test suite expect that `ALLOWED_CONTENT_CHECKSUMS = {"sha1", "sha224", "sha256", "sha384", "sha512"}`. This is the same approach [used by the import/export tests](https://github.com/pulp/pulpcore/blob/40f7cc3bb28830d9944a9908f971ea7002702b16/pulpcore/tests/functional/api/using_plugin/test_pulpimport.py#L4) which require the user to set settings to specific values for the test suite to pass.
2) Have travis fulfill that requirement by adding in the var here: https://github.com/pulp/pulpcore/blob/ab3e4ebbf4fafa93576dc03b8940752ecc56ca1e/.travis/install.sh#L78

2020-09-11 09:08 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_content.py
> +from pulpcore.app import models
This last thing would need to go into the plugins template_config.yaml to survive regenerating the ci files.

2020-09-11 09:12 UTC, mdellweg commented on pulpcore/tests/unit/serializers/test_content.py
> +from pulpcore.app import models
Also i just realize that this is a unit test. And i fail to see why it should be ok to import `ArtifactSerializer` but not `Artifact`.
Is there any context missing?

2020-09-11 19:55 UTC, ggainey commented on pulpcore/tests/unit/serializers/test_content.py
> +from pulpcore.app import models
Updated template_config.yml and regen'd. Turns out you cannot use sets and dynaconf together; tweaked ALLOWED_CONTENT_CHECKSUMS to be a list, explicitly used a set() around it wherever I needed to use difference/intersection.

2020-09-11 19:56 UTC, ggainey commented on pulpcore/tests/unit/serializers/test_content.py
> +from pulpcore.app import models
Also, yes, as noted by @mdellweg , these are unit-tests not functional-tests, so it's ok to rely on being able to import directly (as they all do)

2020-09-11 19:57 UTC, ggainey commented on pulpcore/tests/unit/models/test_content.py
> +    def test_set_forbidden(self):
Addressed by setting ALLOWED_ template_config.yml to not-include md5 by default.

2020-09-11 19:58 UTC, ggainey commented
> > > This code looks great to me. Impressive turnaround time on this.
> > > Question: would it be possible to test this out by defining `ALLOWED_CONTENT_CHECKSUMS` in https://github.com/pulp/pulpcore/blob/master/.travis/settings.py.j2?
> > 
> > 
> > @daviddavis , I have...no insight here. I've done a lot of local testing by setting in /etc/pulp/settings.py.
> 
> You would add that to the plugins template_config and regenerate the travis directory.
> 
> Like here: https://github.com/pulp/pulpcore/blob/master/template_config.yml#L30

And done!

2020-09-14 10:51 UTC, mdellweg commented
I was finally (sort of) able to pass the functional testsuite of pulpcore (pagination fails due to remaining repos from earlier tests of the same run) in fips environment.

2020-09-14 12:47 UTC, daviddavis approved these changes

2020-09-14 13:25 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    def __init__(self, *args, **kwargs):
This could use a docstring that especially calls out the `:raises` parts. Also maybe the main docstring should get an update too?

2020-09-14 14:49 UTC, bmbouter commented
@ggainey is there a functional test that can assert that a sync'd content unit does not have 'md5' set?

2020-09-14 14:55 UTC, ggainey commented
> @ggainey is there a functional test that can assert that a sync'd content unit does not have 'md5' set?

I only have unit-tests in this commit. Hm.

2020-09-14 18:50 UTC, bmbouter commented
> > @ggainey is there a functional test that can assert that a sync'd content unit does not have 'md5' set?
> 
> I only have unit-tests in this commit. Hm.

I think you could likely extend this test to check on the md5 aspects of things pretty easily.  https://github.com/pulp/pulpcore/blob/master/pulpcore/tests/functional/api/test_crd_artifacts.py#L52-L57  wdyt?

2020-09-15 19:02 UTC, ggainey commented
> > > @ggainey is there a functional test that can assert that a sync'd content unit does not have 'md5' set?
> > 
> > 
> > I only have unit-tests in this commit. Hm.
> 
> I think you could likely extend this test to check on the md5 aspects of things pretty easily. https://github.com/pulp/pulpcore/blob/master/pulpcore/tests/functional/api/test_crd_artifacts.py#L52-L57 wdyt?

Fine idea - added testing for "did you get md5 back from a valid upload?" and a new test for "trying to upload while specifying md5 as the checksum should fail" (both assuming md5 is not present in ALLOWED_CONTENT_CHECKSUMS"

2020-09-15 19:51 UTC, bmbouter commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +        self.assertTrue(read_artifact["md5"] is None)
All these tests look greattttt! :+1:

2020-09-15 19:54 UTC, bmbouter commented
I'm LGTM once the `Artifact.__init__` docstring is added. Thank you @ggainey !

2020-09-15 20:04 UTC, bmbouter commented on pulpcore/app/models/content.py
> +    def __init__(self, *args, **kwargs):
Thank you!

2020-09-15 20:04 UTC, ggainey commented on pulpcore/app/models/content.py
> +    def __init__(self, *args, **kwargs):
Pushed!

2020-09-15 20:04 UTC, bmbouter approved these changes
Thank you for this very excellent piece of work. I really appreciate how you brought this together so quickly. :+1: :1st_place_medal: :rocket:

2020-09-15 20:05 UTC, ggainey commented on pulpcore/tests/functional/api/test_crd_artifacts.py
> +        self.assertTrue(read_artifact["md5"] is None)
awesome!

2020-09-15 21:18 UTC, merged