Raise an error when a user tries to update a signing service
pulp/pulpcore pull request #983
Opened 2020-10-23 21:35 UTC by lubosmj

closes #7701

2020-10-23 21:39 UTC, lubosmj commented
When a user performs a single update, the error is correctly raised. However, this approach has a limitation when executing bulk operations (such as SigningService.objects.filter(name="s").update(name="b")):

> Be aware that the update() method is converted directly to an SQL statement. It is a bulk operation for direct updates. It doesn’t run any save() methods on your models, or emit the pre_save or post_save signals (which are a consequence of calling save()), or honor the auto_now field option. If you want to save every item in a QuerySet and make sure that the save() method is called on each instance [https://docs.djangoproject.com/en/2.2/topics/db/queries/#updating-multiple-objects-at-once].

2020-10-26 14:09 UTC, bmbouter commented on pulpcore/app/models/content.py
> +            "The signing service is immutable. It is advised to create a new signing service "
Can this be i8ln with gettext please?

2020-10-26 14:16 UTC, bmbouter requested changes
This looks good once the i8ln is fixed. Thank you!

2020-10-30 12:40 UTC, mdellweg approved these changes
The requested change has been made.

2020-11-03 19:09 UTC, bmbouter approved these changes
Thank you!

2020-11-03 19:09 UTC, merged