Several documentation errors
pulp/pulpcore pull request #988
Opened 2020-10-27 15:01 UTC by lboclboc

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

2020-10-27 15:09 UTC, mdellweg requested changes

2020-10-27 15:09 UTC, mdellweg commented on docs/workflows/exposing-content.rst
> +    export REMOTE_HREF=$(http :24817/pulp/api/v3/remotes/ansible/collection/ | jq -r '.results[] | select(.name == "bar") | .pulp_href')
I don't think you want to use a collection remote to sync a role here.

2020-10-27 15:09 UTC, mdellweg commented on docs/workflows/exposing-content.rst
> +    export REPO_VERSION_HREF=$(http GET ':24817'$REPO_HREF'versions/0/' | jq -r '.pulp_href')
After synching, version 1 sounds right to me.

2020-10-27 15:19 UTC, lboclboc commented on docs/workflows/exposing-content.rst
> +    export REPO_VERSION_HREF=$(http GET ':24817'$REPO_HREF'versions/0/' | jq -r '.pulp_href')
I agree, but when I ran the example the first version was a 0.

2020-10-27 15:25 UTC, lboclboc commented on docs/workflows/exposing-content.rst
> +    export REMOTE_HREF=$(http :24817/pulp/api/v3/remotes/ansible/collection/ | jq -r '.results[] | select(.name == "bar") | .pulp_href')
Sorry, wrong row changed. Pushing new commit

2020-10-27 16:08 UTC, mdellweg commented on docs/workflows/exposing-content.rst
> +    export REPO_VERSION_HREF=$(http GET ':24817'$REPO_HREF'versions/0/' | jq -r '.pulp_href')
The zeroth version must always exist and always be empty.

2020-10-27 16:16 UTC, lboclboc commented on docs/workflows/exposing-content.rst
> +    export REPO_VERSION_HREF=$(http GET ':24817'$REPO_HREF'versions/0/' | jq -r '.pulp_href')
Ok, strange. That was what I got, and I did not get any errors earlier. I have changed it back to 1 and I will test this more later.

2020-10-29 11:24 UTC, ipanova commented on docs/workflows/exposing-content.rst
> +    http POST :24817/pulp/api/v3/remotes/ansible/collection/ name=bar url='https://galaxy.ansible.com/api/v1/roles/?namespace__name=elastic'
it should not be collection but roles, at least if looking at the docs https://pulp-ansible.readthedocs.io/en/latest/workflows/roles.html#create-a-remote

2020-10-29 11:26 UTC, ipanova commented on docs/workflows/exposing-content.rst
> +    http POST :24817/pulp/api/v3/distributions/ansible/collection/ name='baz' base_path='dev' repository_version=$REPO_VERSION_HREF
ansible/ansible/ 
https://pulp-ansible.readthedocs.io/en/latest/workflows/roles.html#create-a-distribution-for-repository-foo

2020-10-29 11:29 UTC, ipanova commented on CHANGES/7760.doc
> +Several documentation errors
how about - Fixed several documentation errors

2020-10-29 11:36 UTC, ipanova commented on docs/workflows/exposing-content.rst
> +    http POST :24817/pulp/api/v3/repositories/file/file/ name=foo2
i don;t think these 3 separate workflows were meant to be executed one after each other, hence same repo , remote and distribution name was used.
But i can see how this can block users from trying out those workflows since repo name is unique across all plugins. 
Since in these examples there have been used 3 plugins - container, ansible and file I suggest you then creating repos,remotes and distributions with different names so they do not collide :)

2020-10-30 15:00 UTC, dralley commented
In the commit message, you have

```
fixes #7760
closes #7760
```

These are the same, but actually neither is in the exact format that is needed to trigger the automation.  Just use

```closes: #7760```

2020-10-30 16:04 UTC, lboclboc commented
> In the commit message, you have
> 
> ```
> fixes #7760
> closes #7760
> ```
> 
> These are the same, but actually neither is in the exact format that is needed to trigger the automation (missing colon). Just use
> 
> `closes: #7760`

Ah, sorry. I was following the examples at https://docs.pulpproject.org/pulpcore/contributing/git.html . Ill fix it

2020-10-30 18:03 UTC, daviddavis commented
Technically you don't need a colon. From the [redmine docs](https://www.redmine.org/projects/redmine/wiki/RedmineSettings#Referencing-issues-in-commit-messages): "The keywords are caseinsensitive and at least one blankspace or colon is needed between the keyword and the first hash to produce
a match." But yea, just use `fixes` or `closes` and not both.

2020-10-30 18:40 UTC, dralley commented
@daviddavis That's what the docs say, but that's not how it seems to work.  On multiple occasions I've seen it just not work without the colon, and same applies here - it's not detecting the commit.  https://pulp.plan.io/issues/7760

2020-10-30 19:36 UTC, daviddavis commented
It should work without the colon. In this case it didn't work because the PR processor doesn't revisit a PR (see https://pulp.plan.io/issues/6720).

2020-12-01 19:46 UTC, dralley commented
@lboclboc Could you rebase?

2020-12-02 14:18 UTC, ipanova requested changes
@lboclboc can you address the comments? Thank you.

2021-01-05 14:31 UTC, daviddavis commented
@lboclboc hey happy new year. any chance you could address the feedback?

2021-01-06 22:45 UTC, lboclboc commented
> @lboclboc hey happy new year. any chance you could address the feedback?

Sorry, I have not had any time for this. I'm just beginning to learn pulp so I am not sure what a correct change should be, perhaps I should cancel this pr and instead just write a ticket..

2021-01-11 13:36 UTC, daviddavis commented
@lboclboc we're [on IRC to help](https://pulpproject.org/help/#irc) if you need it. Filing an issue though is ok too. Our tracker is at https://pulp.plan.io/issues/new.

2021-01-11 13:38 UTC, daviddavis commented
Actually, I guess there's already an issue. If you want to update it with more specifics, that would work. 

Thanks again for your help.

2021-02-02 14:56 UTC, daviddavis commented
Closing due to inactivity. Feel free to reopen when you have time. We'd love to help you.

2021-02-02 14:56 UTC, closed without merging