Add a univeral Pulp repair endpoint
pulp/pulpcore pull request #991
Opened 2020-10-28 04:44 UTC by dralley

Create a new endpoint /pulp/api/v3/repair/ which can attempt to fix corruption
across all of Pulp.

closes: #7755
https://pulp.plan.io/issues/7755

2020-10-28 04:55 UTC, dralley commented
TODO:

* Smash test
* Expose the ```check_hashes``` option to the user?
    * Allowing the user to disable checksum verification and only check for *missing* files would be much faster (orders of magnitude), and if that user already has a fancy corruption-detecting filesystem such as ZFS or Btrfs, might be a better value proposition the majority of the time.

2020-10-28 05:03 UTC, dralley commented
@dkliban @mdellweg Before I start on the smash tests, could you please sanity check the code and give feedback on whether we should expose ```check_hashes```?

2020-10-28 09:40 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +                    valid = _verify_artifact(artifact)
This command is calculating a checksum from a file on disk, which takes some time. At the same time the event loop might be downloading content (async code) that is blocked by this. To avoid this, `_verify_artifact` should be offloaded to another thread by `loop.run_in_executor` (until the django storage framework allows `chunks` to be used as an async iterator).

2020-10-28 17:06 UTC, dralley commented on pulpcore/app/views/repair.py
> +        default=True,
I think there's actually a solid argument to make this default to ```False```, since the gulf in performance is so large, and the use case for detecting bitrot more limited.

2020-10-28 17:22 UTC, dralley commented on pulpcore/app/views/repair.py
> +        default=False,
I think ```False``` is a better default than ```True``` for a couple of reasons.

* Reading every byte of every artifact out from disk and then computing the hashes will likely degrade the performance of the entire system since we're talking about potentially hundreds of gigabytes (or more) of data.
* Depending on the underlying storage technology (RAID, filesystem checksumming), error detection and correction could possibly be handled without our intervention.
* From recent experience, it seems like "whoops, files are gone" incidents could be more likely than random corruptions.

2020-10-28 21:26 UTC, dralley commented on pulpcore/app/tasks/repository.py
> +            _("Artifact {} is unrepairable - no remote source".format(content_artifact.artifact))
i.e. ```PublishedMetadata```, which we store via the ```Artifact``` machinery as well [0].  Should we print a more meaningful message here or is this ok?

[0] https://github.com/pulp/pulpcore/blob/master/pulpcore/app/models/publication.py#L185

2020-10-28 21:31 UTC, dralley commented on pulpcore/app/tasks/repository.py
> +                artifact = content_artifact.artifact
In the case where ```verify_checksums=True```, we're now checking for the existence of each file first, separately.  This is a little slower, but probably insignificant, and it gives us better reporting.  This way missing files aren't reported as digest mismatches.

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +    remotes = content_artifact.remoteartifact_set.all()
sounds like this variable should be named `remote_artifacts`.
Especially when i read it i thought "Remotes".

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +            _("Artifact {} is unrepairable - no remote source".format(content_artifact.artifact))
I guess it's ok.
We can easily grep for `unrepairable` if a user ever hit's this.

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +def _verify_artifact(artifact):
Maybe add a comment why this should run in the executor.
(I know, i should have done that in the first place.)

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +    ) as repaired:
Yay for less indentation!

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +    loop.run_until_complete(_repair_artifacts_for_content(subset=version.content))
shouldn't this allow the `verify_checksums` too?
for compatibility reasons probably with True as default.

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/app/views/repair.py
> +        async_result = enqueue_with_reservation(repair_all_artifacts, [], args=[verify_checksums])
Have you thought about locking?
I think, the only dangerous operation is the redownloading of the artifact. Does that interfer with any other workflows?

Should we limit the number of concurrent repair actions to 1?

I'm fine, if "No action required" is the answer.

2020-10-29 09:23 UTC, mdellweg commented on pulpcore/tests/functional/api/using_plugin/test_repair.py
> +    settings.DEFAULT_FILE_STORAGE not in SUPPORTED_STORAGE_FRAMEWORKS,
@dkliban didn't you change the way how settings can be accessed recently?

2020-10-29 13:23 UTC, dralley commented on pulpcore/app/views/repair.py
> +        async_result = enqueue_with_reservation(repair_all_artifacts, [], args=[verify_checksums])
I don't think we can realistically lock on every single artifact, especially since we won't know which ones it's operating on without duplicating some of the logic outside of the function.  I'm not sure how dangerous it really is considering that any affected artifacts are already broken.

I don't *think* it should interfere with anything else.

2020-10-29 13:36 UTC, mdellweg commented on pulpcore/app/views/repair.py
> +        async_result = enqueue_with_reservation(repair_all_artifacts, [], args=[verify_checksums])
I agree. Thanks for sharing a thought about it. I had the same feeling and now it's much more comfortable.

2020-10-29 13:37 UTC, dralley commented on pulpcore/app/tasks/repository.py
> +def _verify_artifact(artifact):
Can I add it to the comment in the location where it's called?

2020-10-29 13:56 UTC, dralley commented on pulpcore/app/tasks/repository.py
> +    loop.run_until_complete(_repair_artifacts_for_content(subset=version.content))
Added

2020-10-29 13:57 UTC, dralley commented on pulpcore/tests/functional/api/using_plugin/test_repair.py
> +    settings.DEFAULT_FILE_STORAGE not in SUPPORTED_STORAGE_FRAMEWORKS,
We must have missed a spot, but I updated it to use "the new way"

2020-10-29 15:02 UTC, mdellweg commented on pulpcore/app/tasks/repository.py
> +def _verify_artifact(artifact):
Sure

2020-11-02 10:04 UTC, mdellweg approved these changes

2020-11-03 17:44 UTC, ipanova commented on pulpcore/app/serializers/repository.py
> +class RepositoryVersionRepairSerializer(serializers.Serializer):
can we use ValidateFieldsMixin so we check on unknown fields? same for the RepairViewset.

2020-11-03 17:57 UTC, ipanova commented on pulpcore/app/serializers/repository.py
> +            "If enabled, will verify that the checksum of all stored files matches what saved in "
the help_text is not accurate. the checksum verification is enabled by default.

2020-11-03 18:13 UTC, ipanova commented on pulpcore/app/tasks/repository.py
> +async def _repair_artifacts_for_content(subset=None, verify_checksums=True):
i believe verify_checksums does not need to be set to True by default, it is always set through the serializer

2020-11-03 18:15 UTC, ipanova commented on pulpcore/app/views/repair.py
> +class RepairSerializer(serializers.Serializer):
can we move this to /serializers/repair.py

2020-11-03 18:30 UTC, ipanova commented on CHANGES/7755.feature
> +Added support for repairing Pulp by detecting and redownloading missing or corrupted artifact files. Sending a POST request to ``/pulp/api/v3/repair/`` will trigger a task that scans all artifacts fo
@dralley I suggest adding docs about this feature

2020-11-03 18:32 UTC, dralley commented on pulpcore/app/tasks/repository.py
> +async def _repair_artifacts_for_content(subset=None, verify_checksums=True):
That's true but I wanted it to be a keyword argument, and keyword arguments need a default.  It doesn't actually hurt anything.

2020-11-03 18:39 UTC, ipanova approved these changes

2020-11-03 18:41 UTC, ipanova commented
@dralley maybe also fix in the commit the typo s/univeral/universal/ :laughing:

2020-11-03 18:57 UTC, ipanova commented on pulpcore/app/views/repair.py
> +        required=False,
@dralley let's make this consistent repo version repair endpoint and have this enabled by default

2020-11-03 23:25 UTC, dralley commented
@ipanova See documentation and feel free to merge if it looks good since I'll be out tomorrow.

After some discussion with Brian we went the "other way" and decided to default to including checksum verification.

2020-11-04 11:40 UTC, ipanova commented on docs/workflows/repairing-pulp.rst
> +            "/pulp/api/v3/repositories/file/file/47a3f651-aaa6-4026-b649-130c45ab38ea/"
i assume it was copy/paste, because we are not locking on the repos when repairing all artifacts.

2020-11-04 11:40 UTC, ipanova commented on pulpcore/app/serializers/repair.py
> +        default=False,
default=True

2020-11-04 11:41 UTC, ipanova commented on pulpcore/app/serializers/repair.py
> +            "If enabled, will verify that the checksum of all stored files matches what saved in "
"Will verify that the checksum of all stored files matches what saved in the database. Otherwise only the existence of the files will be checked. Enabled by default"

2020-11-04 11:46 UTC, ipanova commented on pulpcore/app/viewsets/repository.py
> +        serializer = RepairSerializer(data=request.data)
:+1:

2020-11-04 11:49 UTC, ipanova commented on docs/workflows/repairing-pulp.rst
> +    internal storage. It attempts a redownload of these files from known upstream urls.
s/the internal storage/ the storage/

2020-11-04 11:50 UTC, ipanova commented on docs/workflows/repairing-pulp.rst
> +    directly into Pulp or were created by Pulp itself (i.e. generated metadata), Pulp is
s/Pulp/ Pulp repair feature/

2020-11-04 11:56 UTC, ipanova requested changes
small things but needs to be fixed.

2020-11-04 21:58 UTC, dralley commented
Updated

2020-11-04 22:28 UTC, ipanova approved these changes
:100:

2020-11-04 22:29 UTC, merged