Remove SELinux from installer note
pulp/pulpcore pull request #997
Opened 2020-10-28 16:03 UTC by melcorr

[noissue]

Discussed this with @mikedep333 last week. 

Let me know if any changes are needed.

2020-10-29 17:50 UTC, mikedep333 approved these changes

2020-11-03 19:15 UTC, bmbouter requested changes
@melcorr I'm thinking this is significantly enough for it to show up in the changelog. If you agree, add a file to the CHANGES/xxxx.doc entry with a changelog. The XXXX would be a yet-to-be-filed issue in Redmine , which also should have the 'documentation' tag. The Redmine issue can be sparse, with maybe just a title that says "Remove references claiming Pulp does not have an SELinux policy."

Would you be willing to jump through these extra hoops for the changelog entry?

2020-11-04 20:00 UTC, bmbouter approved these changes
Thanks!

2020-11-04 20:08 UTC, daviddavis approved these changes

2020-11-04 20:24 UTC, merged